### ISSUE TITLE
rename package entry from `azure` to something else. 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-python-worker#100]
If I understand correctly (and I might be wrong), the package is installed with `azure` as a name. we probably shouldn't take that namespace.

**Comment by elprans** [comment]
@ahmelsayed We use a pure namespace package here (no ``__init__``), so we are not "taking" the root namespace.  The actual namespaces that we take are ``azure.worker`` and ``azure.functions``.

**Comment by asavaritayal** [comment]
Agree with @elprans . Since we're not taking the root `azure` anmespace, we should be okay. I will verify with the azure sdk team as well, before we publish the  package.
