### ISSUE TITLE
Incompatibility between linux python azure function and azure ML 

### ISSUE THREAD

**Issue by sudoPete** [Azure/azure-functions-python-worker#1007]
#### Is your question related to a specific version? If so, please specify:
Core Tools V4~
Linux Functions
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
Http trigger
#### Question
I am experiencing some issues trying to call Azure machine learning functions from a function. Functions apps appear to be incompatible with Azure machine learning, due to a dotnet error. Is there a way to specify a Linux distro for the function that supports .NetCore 2.1 to allow azure machine learning SDK to function and the Core Tools 4~?
`
Result: Failure Exception: NotImplementedError: Linux distribution debian 11. does not have automatic support. .NET Core 2.1 can still be used via dotnetcore2 if the required dependencies are installed. Visit https://aka.ms/dotnet-install-linux for Linux distro specific .NET Core install instructions. Follow your distro specific instructions to install `dotnet-runtime-*` and replace `*` with `2.1`. Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 398, in _handle__invocation_request call_result = await self._run_async_func( File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 617, in _run_async_func return await ExtensionManager.get_async_invocation_wrapper( File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 147, in get_async_invocation_wrapper result = await function(**args) File "...

..., in create_dataset Dataset.Tabular.register_pandas_dataframe( File "/home/site/wwwroot/.python_packages/lib/site-packages/azureml/data/_loggerfactory.py", line 132, in wrapper return func(*args, **kwargs) File "/home/site/wwwroot/.python_packages/lib/site-packages/azureml/data/dataset_factory.py", line 653, in register_pandas_dataframe dflow = dataprep().read_pandas_dataframe(df=sanitized_df, in_memory=True) File "/home/site/wwwroot/.python_packages/lib/site-packages/azureml/dataprep/api/readers.py", line 537, in read_pandas_dataframe return _read_in_memory_pandas_dataframe(df) File "/home/site/wwwroot/.python_packages/lib/site-packages/azureml/dataprep/api/readers.py", line 588, in _read_in_memory_pandas_dataframe read_df_step = Step('Microsoft.DPrep.ReadDataFrameFromSocketBlock', { File "/home/site/wwwroot/.python_packages/lib/site-packages/azureml/dataprep/api/step.py", line 118, in __init__ self.arguments = arguments if isinstance(arguments, PropertyValues) else PropertyValues.from_pod(arguments, _get_prop_descriptions(step_type)) File "/home/site/wwwroot/.python_packages/lib/site-packages/azureml/dataprep/api/engineapi/typedefinitions.py", line 72, in _get_prop_descriptions descriptions = get_engine_api().get_block_descriptions() File "/home/site/wwwroot/.python_packages/lib/site-packages/azureml/dataprep/api/engineapi/api.py", line 19, in get_engine_api _engine_api = EngineAPI() File "/home/site/wwwroot/.python_packages/lib/site-packages/azureml/dataprep/api/engineapi/api.py", line 102, in __init__ self._message_channel = launch_engine() File "/home/site/wwwroot/.python_packages/lib/site-packages/azureml/dataprep/api/engineapi/engine.py", line 333, in launch_engine dependencies_path = runtime.ensure_dependencies() File "/home/site/wwwroot/.python_packages/lib/site-packages/dotnetcore2/runtime.py", line 285, in ensure_dependencies if not attempt_get_deps(): File "/home/site/wwwroot/.python_packages/lib/site-packages/dotnetcore2/runtime.py", line 279, in attempt_get_deps raise NotImplementedError(err_msg + '\n' + _unsupported_help_msg) `

**Comment by pdthummar** [comment]
Hi SudoPete, 
I would suggest you create a Custom container deployment on this scenario. Please refer following link for more info: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=in-process%2Cbash%2Cazure-cli&pivots=programming-language-python

Thanks

**Comment by pdthummar** [comment]
Hope this resolved your issue, please create a new issue if you face any concerns. Thanks

**Comment by waltherg** [comment]
Creating a custom container doesn't resolve the issue @pdthummar as this just opens another can of worms.
When will this issue be resolved? It's disheartening investing time in the Azure Function V4 stack just to be told that a very common use case won't be doable with it and to just invest in some other stack.

If this issue won't be resolved a clear top-level disclaimer as to the shortcomings of this particular technology is necessary.
