### ISSUE TITLE
[BUG] azure-functions-python-library version 1.11.0 is classified as production release in PyPI and other package managers

### ISSUE THREAD

**Issue by katz** [Azure/azure-functions-python-worker#1018]
###### Please provide the following:

In GitHub, azure-functions-python-library 1.11.0 is categorized as Pre-release.
https://github.com/Azure/azure-functions-python-library/releases/tag/1.11.0

But, according to [PEP 440](https://peps.python.org/pep-0440/), the version name `1.11.0` doesn't contain [Pre-release separators](https://peps.python.org/pep-0440/#pre-release-separators) notation. Because of this, `1.11.0` is considered as production release in package managers like [Poetry](https://python-poetry.org/) and [PyPI](https://pypi.org/project/azure-functions/#history).

If the version `1.11.0` is alpha, beta or release candidate release, the version notation should be `1.11.0a1`, `1.11.0b1` or `1.11.0rc1` respectively.

**Comment by YunchuWang** [comment]
marking lib nonbeta released and all worker versions released
