### ISSUE TITLE
Microsoft Azure SDK for Python modules conflict with azure.functions module

### ISSUE THREAD

**Issue by cliveg** [Azure/azure-functions-python-worker#102]
Unable to use Azure SDK modules by referencing them as part of an import in the python code, or specifying the module to install as part of REQUIREMENTS.txt.

Adding 'azure-servicebus' or 'azure' (bundle) into REQUIREMENTS.TXT shows an error when the container is RUN: ModuleNotFoundError: No module named 'azure.functions'.
- When you specify azure==3.0.0 you also see an uninstall for azure:0.01 indicating it is already present, however it's not clear how to reference modules.

Trying to reference modules (without adding to REQUIREMENTS.TXT) from your python code e.g. 'from azure.servicebus import ServiceBusService' produces an error e.g. ModuleNotFoundError. Do you have any guidance on this?

**Comment by elprans** [comment]
@asavaritayal We need to tweak `setup.py` to omit the top-level namespace in the package descriptor.  I'll submit a PR shortly.

**Comment by asavaritayal** [comment]
Great, thanks for explaining :)
