### ISSUE TITLE
Unable to Reference IoTHub Modules

### ISSUE THREAD

**Issue by cliveg** [Azure/azure-functions-python-worker#103]
Unable to use IoTHub Modules from Python
- Adding "azure-iothub-service-client" and "azure-iothub-device-client" to REQUIREMENTS.TXT
- Specifying in python code 'from iothub_client import IoTHubClient'

Function App when called gives error:
"Failure Exception: ImportError: libboost_python-py35.so.1.58.0: cannot open shared object file: No such file or directory"

**Comment by elprans** [comment]
This seems like a package bug.  Properly packaged Linux wheels should include all their shared library dependencies: https://www.python.org/dev/peps/pep-0513/#bundled-wheels-on-linux
