### ISSUE TITLE
Important delay between invocation post and function execution

### ISSUE THREAD

**Issue by MarcGiannuzzi** [Azure/azure-functions-python-worker#1042]
**Stack: Python 3.7
Runtime: 4.0
Service Plan: B3:3**

FUNCTIONS_WORKER_PROCESS_COUNT=3
PYTHON_THREADPOOL_THREAD_COUNT=32

Hi,

I am encountering an issue with a HTTP triggered function.

Azure log appearing at time T (just after log telling that "Request successfully matched the route..."):
**_Verbose log at time T is: Posting invocation id:xyz... on workerId:zyx..._**

Personal python function log (first line of the function when triggered) appears in the logs at T + someTime.
Here, someTime is random, but often  is greater than 1 minute.

For that specific transaction/operation, there isn't anything between the two logs mentioned above.

That issue happens a lot (relatively), and **randomly**, resulting in many requests that take more than 1 minute, whereas it is supposed to be run in some ms.

Not any failure has been recorded inside the metrics. 
Furthermore, memory and CPU usage are OK for the three workers. No need to scale up/down.
No other function is running on the function App, and no other app is running on the plan.

The function is often called and works well when that issue does not appear. Function is running asynchronously.

Please help. 
Thank you in advance.

**Comment by Ved2806** [comment]
Hi @vrdmr Could you please look into this issue?

**Comment by vrdmr** [comment]
Hi @MarcGiannuzzi - Apologies for the delay - Can you please share an invocation id for us to internally get your function name?

Please follow these instructions - https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by fpousserot** [comment]
I see the same behavior. What was the resolution at the time?
