### ISSUE TITLE
Populate WorkerMetadata in WorkerInitResponse message

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-python-worker#1057]
The protobuf has been updated to include a `WorkerMetadata` property within the `WorkerInitResponse` message. The worker should include `WorkerMetadata` when sending the `WorkerInitResponse` to the host.

[PR](https://github.com/Azure/azure-functions-language-worker-protobuf/pull/76) for reference on how to fill in the fields.

You will need to pull in the latest protobuf version first (this [doc](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/EngineeringProcesses/ReleaseProcesses/ProtobufReleaseProcess.md&version=GBmaster&_a=preview) may help).

```proto
message WorkerMetadata {
  // The runtime/stack name
  string runtime_name = 1;

  // The version of the runtime/stack
  string runtime_version = 2;

  // The version of the worker or worker SDK
  string worker_version = 3;

  // The worker bitness/architecture
  string worker_bitness = 4;

  // Optional additional custom properties
  map<string, string> custom_properties = 5;
}
```

**Comment by liliankasem** [comment]
Latest proto version is now [v1.5.8](https://github.com/Azure/azure-functions-language-worker-protobuf/releases/tag/v1.5.8-protofile)

**Comment by liliankasem** [comment]
@vrdmr can we prioritize this for the next sprint?

**Comment by liliankasem** [comment]
Documentation to help with implementation: https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/Design/OOPWorkers/WorkerMetadata.md&version=GBmaster&_a=preview

**Comment by YunchuWang** [comment]
@liliankasem Hi Lilian, sure a task to added to our backlog and we will prioritize it next sprint.
