### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#107]
Opening issue to track release process
- Merge dev to master
- Add Tag with the build number from master branch
- Add release notes specifically mentioning the version of the functions runtime host the release depends on
- Add documentation in wiki on how to release python worker

**Comment by pragnagopa** [comment]
/cc: @asavaritayal 
@elprans / @1st1  - We missed doing this before we started private preview.  Can you please tag the master branch with latest green buildnumber-alpha and also add release notes. Python worker preview depends on Function host V2.0.11651

**Comment by pragnagopa** [comment]
@elprans / @1st1 - I tried merging dev into master, but there are merged conflicts. Could one you move the bits master?

**Comment by elprans** [comment]
@pragnagopa The `dev` branch lost sync with master for some reason.  I had to rebase it onto `master` to straighten the history.  It might have been because of a force push.  Would it be possible to protect the master and the dev branch?

**Comment by pragnagopa** [comment]
Any reason why you would want to preserve history on master? As we haven't officially tagged a release, let's push to master and going forward we need to follow a process to move bits from dev to master and not push directly to master.

**Comment by pragnagopa** [comment]
Please note that we need this as prerequite to issue #101 to maintain a working combination of python worker and functions host in the functions dockerfile

**Comment by elprans** [comment]
@pragnagopa We already are not pushing directly to master.  What I meant is that at some point `dev` and `master` diverged in a way that was causing conflicts.  I force-pushed into `dev` to fix that, but let's "protect" both dev and master to prevent future force pushes and ensure that we can always merge dev into master cleanly.

**Comment by pragnagopa** [comment]
Great. I will add a tag: 1.0.0-alpha and release notes

**Comment by asavaritayal** [comment]
5/17 - This is done.
