### ISSUE TITLE
Get Request Context in Asgi worker

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-functions-python-worker#1082]
I've been using this [ASGI worker] and it works really nice.

I have a problem now that i need to capture the context from que function (to get context.function_directory so i can make it work with a file share).

Any hint on how to make it work in this?

```python
def main(req: func.HttpRequest, context: func.Context) -> func.HttpResponse:
    return AsgiMiddleware(app).handle(req, context)
```

Original issue by @hcs-bernardo-rufino

**Comment by gavin-aguiar** [comment]
ASGI does have context support now. Here is a quick test I did to check

![image](https://user-images.githubusercontent.com/80794152/184032090-b5f81f55-3350-48a1-874b-85cbee9773b8.png)
