### ISSUE TITLE
Increase grpc max message size

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#109]
Functions Host is updated to send command line argument: [--grpcMaxMessageLength ](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/ProcessManagement/DefaultWorkerProcessFactory.cs#L35)
Python worker needs to be updated to set this value for grpc.max_send_message_length and grpc.max_receive_message_length on the channel

**Comment by pragnagopa** [comment]
@1st1 / @elprans  - We are rolling out functions runtime soon.  It would be good to have the change on the worker sooner to support working with large blobs

**Comment by elprans** [comment]
@pragnagopa Can you point me to the Host artifact that contains this please?

**Comment by elprans** [comment]
Just to confirm, does 11709 also contain the `enable_content_negotiation` (#101) bit?

**Comment by pragnagopa** [comment]
Yes. You can use these for proto changes as well!
