### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#11]
In order to write traces during an execution, we'll use Python's **logging** module. The runtime will instantiate ```logger``` as a keyword-only required argument of type **logging.Logger**. 

The module provides various convenience methods that let you write to the console at more than one trace level. 

Method | Description
--------|------------
**debug**(message)|Detailed information, typically of interest only when diagnosing problems.
**info**(message)| Confirmation that things are working as expected.
**warning**(message)| An indication that something unexpected happened, or indicative of some problem in the near future (e.g. ‘disk space low’). The software is still working as expected.
**error**(message)| Due to a more serious problem, the software has not been able to perform some function.
**critical**(message)| A serious error, indicating that the program itself may be unable to continue running.

The logger object will be accessible in two ways: 

1. Via the reserved keyword ```logger```
```python
# main.py
def main(logger):
	logger.warning('Something has happened!')
```
2. By declaring ```Logger``` type for a method argument
```python
# main.py
def main(foo: Logger):
	foo.error('Type mismatch')
```

By default, the effective level for logger will be set to INFO. To modify this level, use the ```setLevel()``` method provided by the logging module. Example - 
```python
# main.py
def main(logger):
	logger.setLevel(logging.ERROR)
        logger.debug('Effective trace level changed to error.') # not logged
        logger.error('Something has happened.') # logged
```

**Note:** Since we use a single Python process per function app, using the inbuilt **print** utility will output to our system logs. These are not available to the user and hard to distinguish on a per function basis.

**Comment by 1st1** [comment]
I'm looking at our GRPC schema:

```protobuf
message RpcLog {
  // Matching ILogger semantics
  // https://github.com/aspnet/Logging/blob/9506ccc3f3491488fe88010ef8b9eb64594abf95/src/Microsoft.Extensions.Logging/Logger.cs
  enum Level {
    Trace = 0;
    Debug = 1;
    Information = 2;
    Warning = 3;
    Error = 4;
    Critical = 5;
    None = 6;
  }

  string invocation_id = 1;
  string category = 2;
  Level level = 3;
  string message = 4;
  string event_id = 5;
  RpcException exception = 6;

  // json serialized property bag, or could use a type scheme like map<string, TypedData>
  string properties = 7;
}
```

And it seems like Azure Functions logging is a bit different from the standard Python `logging` module:

* Python doesn't have a `Trace` debug level.
* Python doesn't have `event_id` and `category`. What are these two used for, by the way?
* Python doesn't have support for attaching arbitrary `properties`.

All in all, it seems that it would be easier to design an azure-functions-specific (and independent from the `logging` module) `Logger` object. 

Now, do we need `logger.set_level` method?  The `WorkerInitRequest` has a `log_categories` field to indicate what logging level are supported for this worker, so maybe we can handle the logging level based on that?

It also looks like `RpcLog` can be streamed back from client to server at any time, so we probably need two different Logger objects implementations -- one synchronous and one asynchronous.

**Comment by 1st1** [comment]
> All in all, it seems that it would be easier to design an azure-functions-specific (and independent from the logging module) Logger object.

After a chat with @elprans we concluded that this would be a bad idea. Lots of existing Python packages use the standard `logging` module, so instead of developing a new system we should adapt the existing one.

So we'll add a new `logging.Handler` implementation that will stream all logging messages back to the WebHost (via `RpcLog` messages).  I'll update this issue with a mapping of Python Log object's attributes to RpcLog fields later.

-------

**The open question** now is whether we should have a "logger" argument for Functions (or `context.logger` attribute).  IMO we don't really need it, as it's easy for users to simply create a new logger object with `import logging; logging.getLogger('my function')`.

**Comment by 1st1** [comment]
Logging has been implemented in the `dev` branch; the exception bit is commented out until https://github.com/Azure/azure-functions-host/issues/2433 is resolved.
