### ISSUE TITLE
Pin version of grpc

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#110]
Is it possible to include a specific version of grpc in Setup script [setup.py#L151](https://github.com/Azure/azure-functions-python-worker/blob/dev/setup.py#L151)? We would like to control when we take dependency on grpc updates

**Comment by pragnagopa** [comment]
Sorry missed concluding on the version. We do want to stick to 1.0.x to be consistent worth other language workers. Tying the host and language workers version numbers might easier to track but does not make sense and they are version independently

**Comment by elprans** [comment]
Fixed in dev.
