### ISSUE TITLE
Python language worker (for integration testing) build for the v3.x-dev branch fails

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-python-worker#1101]
The pipeline that builds the Python language worker for the `v3.x-dev` branch has been falling since mid-August 2022. Building this component is a prerequisite to build the Core Tools for integration testing. As a result, integration testing for V3 is blocked. For the time being, I will remove the Python language worker from integration testing to unblock the test pass. Once the build is working again, I will add it back.

**Comment by gavin-aguiar** [comment]
This error is fixed with the above PR and builds are succeeding now.
