### ISSUE TITLE
[BUG] AzureML on Azure Functions Consumption Plan Linux

### ISSUE THREAD

**Issue by waltherg** [Azure/azure-functions-python-worker#1124]
###### Please provide the following:

- Function App name: happy to provide privately
- Core Tools version: V4

### Repro steps

Using the `azureml` package in Python in an Azure Function on a consumption plan (linux) breaks for basic operations such as

```python
Dataset.to_pandas_dataframe()
```

with the following error message:

```text
Exception: NotImplementedError: Linux distribution debian 11. does not have automatic support.
Missing packages: {'liblttng-ust.so.0'}
.NET Core 3.1 can still be used via `dotnetcore2` if the required dependencies are installed.
Visit https://aka.ms/dotnet-install-linux for Linux distro specific .NET Core install instructions.
Follow your distro specific instructions to install `dotnet-runtime-*` and replace `*` with `3.1.23`.
```

### Expected behavior

I expect a Microsoft stack such as Azure Functions + azureml + .NET to be fully integrated and to "just work".

My requirements as they relate to Azure packages:

```txt
azure-functions==1.9.0
azure-functions-durable==1.1.3
azure-storage-blob==12.9.0
azureml-core==1.43.0
azureml-dataset-runtime==1.43.0
```

The same bug has already been raised and unfortunately closed (#1007) but the solution proposed therein doesn't seem helpful: I'm trying to use a tech stack that is fully MS / Azure (Azure Functions + azureml) so I don't expect the solution here is to build my own Docker image. I would expect that the base Docker image underlying Azure Functions consumption plan includes the MS technology .NET if it's necessary.

**Comment by ramya894** [comment]
@waltherg We will discuss this issue with our next level team and update you.

**Comment by pdthummar** [comment]
Hi @waltherg,
Thanks for creating the issue.
Would you be able to provide code snippet for replicating the issue? Thanks

**Comment by waltherg** [comment]
Thanks for taking care of this issue @pdthummar!

With the requirements I posted in my bug report, the following should reproduce the issue when run in a consumption plan function deployed from a zipped package (I use Azure DevOps release jobs):

```python
from azureml.core import Dataset

forecast = Dataset.get_by_name(workspace=workspace, name=forecast_name)
forecast_df = forecast.to_pandas_dataframe()
```

**Comment by waltherg** [comment]
@vrdmr @pdthummar thank you very much for looking into this issue.
If possible, can you please share any initial insights or rough estimates if and when this issue may be resolved?

We need to be able to use the `azureml` package in an ETL pipeline of ours and need to decide how to proceed.
Building a custom Docker image to achieve this would also mean switching to a Premium subscription from our current consumption plan thus incurring additional cost.

**Comment by pdthummar** [comment]
hi @waltherg, we are trying to reproduce the issue and investing it. Unfortunately, at this time, we cannot provide any timelines without completely investing the issue. Thanks

**Comment by pdthummar** [comment]
Sorry for delayed response. We have created [PR](https://github.com/Azure/azure-functions-docker/pull/834) for missing dependency. It will be available for consumption plan after release. Thanks

**Comment by pdthummar** [comment]
Closing this issue as [https://github.com/Azure/azure-functions-docker/pull/834](PR) is merged. If you are still facing issue, please create an issue with including replication steps. Thanks
