### ISSUE TITLE
Feature: Default functionapp python file `__init__.py` should be feel more like main file and pythonic

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-functions-python-worker#1125]
core tools version: 4.0.4829 (x64 on rosetta to use python)
OS: MacOs Montery 12.6 (Mac M1 Pro)

This might be broader than python, but I really notice it with Python in the user experience.  

Typically I'm used to the main code file in Python or any language either being something domain specific (e.g. `calculate_rates.py`)., or something more generic and pleasing like `app.py` or `index.py` or `functionmain.py`.  It's even more confusing because the functions.json file "pops" a lot more as the main file I want to click, where as `__init__.py` feels like a generated code I should ignore.  a few examples to look at might be github.com/dapr/quickstarts, or for less bias this is one of the top google search ranked repos with python: https://github.com/milaan9/90_Python_Examples

Recommend we change name to `app.py`, or alternatively `functionapp.py` or `functionmain.py` (see what community likes).  Since the "domain" of the trigger type is already in the folder name above, i think we can get away with app.py personally.

```console
 paulyuk@Pauls-MBP-2  ~/src/functions/templates/TimerTrigger  ls -la
total 24
drwxr-xr-x   5 paulyuk  staff  160 Oct 19 16:12 .
drwxr-xr-x  10 paulyuk  staff  320 Oct 19 16:16 ..
-rw-r--r--   1 paulyuk  staff  380 Oct 19 16:12 __init__.py
-rw-r--r--   1 paulyuk  staff  180 Oct 19 16:12 function.json
-rw-r--r--   1 paulyuk  staff  762 Oct 19 16:12 readme.md
```

Notice how function.json looks so much more interesting than the main code file.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/1968137/196825969-87e75893-f4ee-4398-b068-88a1f9201a55.png">

**Comment by ejizba** [comment]
@paulyuk transferred this to the Python repo, but suffice to say this has already been completely revamped as a part of the new programming model. I'll let the Python folks give more detail

**Comment by YunchuWang** [comment]
thanks for bringing this up, as mentioned by Eric, python new programming model is out in public preview, for ref https://techcommunity.microsoft.com/t5/azure-compute-blog/azure-functions-v2-python-programming-model/ba-p/3665168. As suggested, there is no more __init__.py in every function folder but one function_app.py file to write all function codes in.
