### ISSUE TITLE
No module named 'confluent_kafka.cimpl' - Python 3.7 and confluent-kafka

### ISSUE THREAD

**Issue by asgallu** [Azure/azure-functions-python-worker#1129]
#### Is your question related to a specific version? If so, please specify: 

python3.7/3.9/3.9 and confluence-kafka 1.7.0

#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 

function azure

#### Question

Hi I have to upgrade the version of a funcion App on Azure from python 3.6 to 3.7 or 3.8 or 3.9 (I don't mind what version but I vhave to do it because python 3.6 doesn't exist any longer). What's more, we use confluence-kafka on the script.

To solve the issue I've upgraded the module confluence-kafka to the version 1.7.0, but I still have an error when I debug or run the function on Azure. I also tried to run the function with several versions of  pyhon, 3.7, 3.8, 3.9 but nothing. I also changed the version of the module confluence-kafka, version 1.7.0, 1.8.2, 1.9.2 and the same error. 

That's the error:

"_Result: Failure Exception: ModuleNotFoundError: No module named 'confluent_kafka.cimpl'. Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 359, in _handle__function_load_request func_request.metadata.entry_point) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 42, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/loader.py", line 127, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/CopyTransactionHttpTrigger/__init__.py", line 8, in <module> from confluent_kafka import avro File "/home/site/wwwroot/.python_packages/lib/site-packages/confluent_kafka/__init__.py", line 19, in <module> from .deserializing_consumer import DeserializingConsumer File "/home/site/wwwroot/.python_packages/lib/site-packages/confluent_kafka/deserializing_consumer.py", line 19, in <module> from confluent_kafka.cimpl import Consumer as _ConsumerImpl_"

I was searching on the internet for a solution but I just founded for AWS. I don't know If I have to install the module manually and where or what I have to do to sort it out.

Thanks

**Comment by ramya894** [comment]
@chandrod / @shrohilla Can anyone you help me on this issue

**Comment by ramya894** [comment]
@jgadelevopment thanks for reporting, have you tried the trouble shootings steps provided below.
https://aka.ms/functions-modulenotfound
.

**Comment by shrohilla** [comment]
I think @jgadelevopment, Can you try this with -- confluent-kafka[avro]==1.7.0 ?

**Comment by jgadelevopment** [comment]
Sorry, I've made I mistake when I wrote 'confluent_kafka[avro]==1.7.0', I've got confluent-kafka[avro]==1.7.0 in my requirements.txt. @shrohilla you meant? => -- confluent-kafka[avro]==1.7.0 o confluent-kafka[avro]==1.7.0

**Comment by ramya894** [comment]
@shrohilla Can you provide your inputs on above. Thanks.

**Comment by asgallu** [comment]
Finally, I could pass the error "ModuleNotFoundError: No module named 'confluent_kafka.cimpl'." What I did was to install the modules inside the .pythn_packages\lib\site-packages. However I've got another error:

Result: Failure Exception: ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/local/lib/python3.7/ctypes/__init__.py). Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 359, in _handle__function_load_request func_request.metadata.entry_point) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 42, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/loader.py", line 127, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1006, in _gcd_import File "<frozen importlib._bootstrap>", line 983, in _find_and_load File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 677, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 728, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/home/site/wwwroot/CopyTransactionHttpTrigger/__init__.py", line 8, in <module> from confluent_kafka import avro File "/home/site/wwwroot/.python_packages/lib/site-packages/confluent_kafka/__init__.py", line 18, in <module> _delvewheel_init_patch_76882796227() File "/home/site/wwwroot/.python_packages/lib/site-packages/confluent_kafka/__init__.py", line 11, in _delvewheel_init_patch_76882796227 from ctypes import WinDLL

It's quite similar to the another one, it requires a module, I think

**Comment by ramya894** [comment]
Closing as resolved
