### ISSUE TITLE
[FeatureRequest] Python 3.11 support in Azure Functions

### ISSUE THREAD

**Issue by thiezn** [Azure/azure-functions-python-worker#1133]
Hi,

Python 3.11 was just released and comes with a lot of great improvements.  The potential 10-60% speedup over 3.10  (which also provided speedups over 3.9) will make a lot of people happy when used in serverless setups as it will directly affect the duration.

[Python 3.11 release notes](https://www.python.org/downloads/release/python-3110/)
[Details on speed improvements](https://docs.python.org/3.11/whatsnew/3.11.html#faster-startup)

Python is on a yearly release cycle and would be great if the Azure Functions Python worker could more closely follow this if at all possible.

Kind regards,
Thiezn

**Comment by ramya894** [comment]
@thiezn Thanks for reporting, Yes we are working on that the target it to do it by mid Jan, Feb early months of next year i.e2023.

**Comment by shreyabatra4** [comment]
Reopening this issue to track the work for support for Python 3.11

**Comment by stevesimmons** [comment]
Hi guys. It's now mid-Feb. When will Azure Functions have support for Py3.11?

**Comment by vrdmr** [comment]
[Available now!](https://github.com/Azure/azure-functions-python-worker/issues/1256)
