### ISSUE TITLE
[BUG] warmupTrigger doesn't work as documented

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [Azure/azure-functions-python-worker#1135]
###### Please provide the following:

- Timestamp: 2022-10-26
- Function App name: 
- Function name(s) (as appropriate):
- Core Tools version: 3.0.4727

###### Provide the steps required to reproduce the problem:

1. Create a very basic function with a `httpTrigger `and a `warmupTrigger `following the official guide https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=in-process&pivots=programming-language-python:

```json
## httptrigger/function.json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}

```
```python
## httptrigger/__init__.py
import logging
import azure.functions as func

async def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info("Succes!")
    return func.HttpResponse("Succes", status_code=200)
```

```json
## warmup/function.json
{
    "bindings": [
        {
            "type": "warmupTrigger",
            "direction": "in",
            "name": "warmupContext"
        }
    ]
}

```
```python
## warmup/__init__.py
import logging
import azure.functions as func

def main(warmupContext : func.Context) -> None:
    logging.warning('Function App instance is warm 🌞🌞🌞')

```
2. Run the function.
3. Get the following error:
 ```
For detailed output, run func with --verbose flag.
[2022-10-26T09:21:14.653Z] Worker process started and initialized.
[2022-10-26T09:21:17.301Z] Host lock lease acquired by instance ID '0000000000000000000000002C1B88F1'.
[2022-10-26T09:21:18.829Z] Worker failed to function id 65568825-e196-4213-9fc3-b55a123c4b89.
[2022-10-26T09:21:18.831Z] Result: Failure
Exception: FunctionLoadError: cannot load the warmup function: type of warmupContext binding in function.json "warmupTrigger" does not match its Python annotation "Context"
Stack:   File "C:\Users\tfh\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.8/WINDOWS/X64\azure_functions_worker\dispatcher.py", line 320, in _handle__function_load_request   
    self._functions.add_function(
  File "C:\Users\tfh\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.8/WINDOWS/X64\azure_functions_worker\functions.py", line 217, in add_function
    raise FunctionLoadError(
```

If I try and remove the type it is never run which can be seen as this Exception is never hit
```python
import azure.functions as func

def main(warmupContext) -> None:
    raise Exception('Function App instance is warm 🌞🌞🌞')
```

###### Provide a description of the expected behavior.
It should locally when I run it as according to the guide

> Support for the warmup trigger is provided by default in all development environments. You don't have to manually install the package or register the extension.

https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=in-process&pivots=programming-language-python

###### Provide a description of the actual behavior observed.

Raises the error:

```
For detailed output, run func with --verbose flag.
[2022-10-26T09:21:14.653Z] Worker process started and initialized.
[2022-10-26T09:21:17.301Z] Host lock lease acquired by instance ID '0000000000000000000000002C1B88F1'.
[2022-10-26T09:21:18.829Z] Worker failed to function id 65568825-e196-4213-9fc3-b55a123c4b89.
[2022-10-26T09:21:18.831Z] Result: Failure
Exception: FunctionLoadError: cannot load the warmup function: type of warmupContext binding in function.json "warmupTrigger" does not match its Python annotation "Context"
Stack:   File "C:\Users\tfh\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.8/WINDOWS/X64\azure_functions_worker\dispatcher.py", line 320, in _handle__function_load_request   
    self._functions.add_function(
  File "C:\Users\tfh\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.8/WINDOWS/X64\azure_functions_worker\functions.py", line 217, in add_function
    raise FunctionLoadError(
```

###### Provide the requirements.txt file to help us find out module related issues.

```
azure-functions==1.8.0 
```

###### Provide any related information

* Links to source
* Bindings used

**Comment by thomasfrederikhoeck** [comment]
Hi @gavin-aguiar . I can see @vrdmr assigned you to this. Have you been able to replicate?

**Comment by thomasfrederikhoeck** [comment]
@gavin-aguiar @vrdmr is this actively worked on? :-)

**Comment by ramya894** [comment]
@thomasfrederikhoeck We are investigating on this will update you the findings soon.

**Comment by thomasfrederikhoeck** [comment]
@ramya894 sounds good!

**Comment by ramya894** [comment]
@thomasfrederikhoeck We are able to reproduce the problem and working on the solution to fix it. Thanks.

**Comment by gavin-aguiar** [comment]
Hi @thomasfrederikhoeck , apologies for the late response. 
We are looking into this error. In the mean time for mitigation, remove the type in the definition as you mentioned. 
Locally, you can invoke the warmup trigger by calling http://localhost:7071/admin/warmup. 
In Azure, the warmup trigger will be called only during scale out operations.

**Comment by thomasfrederikhoeck** [comment]
@gavin-aguiar  Thank you. I have tried the work around and that works. However it still requires me to call the endpoint. Will the fix you have merged automatically call the warmup trigger when starting a local debug?

**Comment by YunchuWang** [comment]
@thomasfrederikhoeck Hi Thomas, in local the warmup trigger wont be automatically called. its only invoked by runtime in scaling scenarios, i.e in dedicated or elastic premium plans.
