### ISSUE TITLE
Question: delay before function executes code

### ISSUE THREAD

**Issue by Nuqlear** [Azure/azure-functions-python-worker#1150]
#### Is your question related to a specific version? If so, please specify:
Python Version: 3.8
Runtime Version: 4.14.0.0
FUNCTIONS_WORKER_PROCESS_COUNT: 4
PYTHON_THREADPOOL_THREAD_COUNT: 1

#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
HTTP

#### Question
I've discovered in App Insights that sometimes there is a large time gap between a message about the function being executed and the first logging call in its handler.
For example the following log displays  a delay of more than a minute:
```
12/2/2022, 1:47:24.926 PM Executing 'Functions.sheet_entry_create' (Reason='This function was programmatically called via the host APIs.', Id=1eb08925-0df8-4e36-8f01-40b3fca9f0aa)
12/2/2022, 1:48:28.284 PM Starting executing function... <- coming from handler's logging.info call
```
 I would like to understand what is causing that delay. Does it relate to a cold start?

**Comment by vrdmr** [comment]
Hi @Nuqlear - Thanks for the question, and apologies for the late reply. I've been meaning to write a doc for this as well - I'll work on that as well.

> I would like to understand what is causing that delay. Does it relate to a cold start?

No - this isn't related to cold-start. It is related to how execution is sent from Host to PythonWorker. Below is the internal architecture of the Functions runtime (Host and the Python worker). In sync case, we (Python worker) receive the execution request and submit it to the [ThreadPoolExecutor](https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/dispatcher.py#L465).

<img width="842" alt="image" src="https://user-images.githubusercontent.com/1047040/216216801-2b23bf9b-1a00-42e1-81d9-0ca7ef8c3253.png">

With the `PYTHON_THREADPOOL_THREAD_COUNT` set to 1 in your application; it'll queue up the request in the ThreadPoolExecutor as it only has one thread to work with and cannot schedule other executions. If the [PYTHON_THREADPOOL_THREAD_COUNT] is set, it changes the value of max_worker used by the [ThreadPoolExecutor (doc link)](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) - It'll use the pool of at most _max_workers_ (set by `PYTHON_THREADPOOL_THREAD_COUNT`) threads to execute calls asynchronously.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/1047040/216216186-18410133-8d5e-4e69-abdb-4d07419196f1.png">

Log from the host
```log

12/2/2022, 1:47:24.926 PM Executing 'Functions.sheet_entry_create' (Reason='This function was programmatically called via the host APIs.', Id=1eb08925-0df8-4e36-8f01-40b3fca9f0aa)
```

This log is from the Python worker.
```log
12/2/2022, 1:48:28.284 PM Starting executing function... <- coming from handler's logging.info call 
```

**Comment by vrdmr** [comment]
Looking at your application usage patterns, your duration patterns range from 1 second to 90+ seconds. You would benefit significantly from using `PYTHON_THREADPOOL_THREAD_COUNT` to get more threads used in parallel - if you have enough CPU and Memory to allow it. I would recommend reducing the `FUNCTIONS_WORKER_PROCESS_COUNT` to 1 (# cores) and increasing `PYTHON_THREADPOOL_THREAD_COUNT` to around 2 * #cores + 1.

```
durationInS | count_
-- | --
1 | 91
2 | 256
3 | 155
4 | 105
5 | 65
6 | 55
7 | 54
8 | 56
9 | 44
10 | 32
11 | 19
12 | 20
13 | 9
14 | 8
15 | 4
16 | 8
17 | 8
18 | 10
19 | 1
20 | 4
21 | 4
22 | 1
23 | 6
24 | 4
25 | 4
26 | 3
27 | 2
29 | 3
30 | 2
32 | 3
33 | 2
36 | 3
39 | 1
44 | 1
47 | 1
48 | 1
62 | 3
68 | 1
69 | 2
70 | 1
73 | 1
74 | 4
76 | 1
79 | 1
93 | 1
```

**Comment by vrdmr** [comment]
Please re-open the issue if you need more information or are facing some other issue.

**Comment by Nuqlear** [comment]
Thank you @vrdmr for such a detailed response.
I will look into the way to make adjustments to match your recommendations.
