### ISSUE TITLE
Python function request to Table storage throttles

### ISSUE THREAD

**Issue by edgarhuichen** [Azure/azure-functions-python-worker#1155]
I deployed my Python function (V2, HTTP trigger) on the Linux consumption plan but noticed significant performance slowness. Locally the request only takes 20 seconds. However, via Azure endpoint, it takes 2 minutes.

By analyzing the log, I see the connection to Azure Table API is throttling. After each request to the table, it waits for around 7 seconds. Because my function needs to request the same table few times during each execution, it takes way longer than running it locally.

Any ideas why and how to improve the request response time?

**Comment by YunchuWang** [comment]
@edgarhuichen thanks for reporting on this! can you share the function app name via https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately ?

**Comment by edgarhuichen** [comment]
@YunchuWang sure, is this what you need: 2022-12-14 18:00:34.747 Executed 'Functions.HourlyAggregator' (Succeeded, Id=eada73e2-ff6a-4de7-8b4b-2b59b600bd0c, Duration=96407ms)

**Comment by YunchuWang** [comment]
@edgarhuichen sorry for delayed response, thats the function name, can you also share the function app name?
