### ISSUE TITLE
[FeatureRequest] Add binding at runtime

### ISSUE THREAD

**Issue by flvndh** [Azure/azure-functions-python-worker#1156]
Input and output bindings are great abstractions for those who want to avoid using clients. Unfortunately, there are still cases where you are forced to use a client. Take for example this one:

> Whenever a blob appear at `/abc/{date}/{filename}.{ext}` copy it to `/xyz/year={year}/month={month}/day={day}/{filename}.{ext}`

It requires the binding to be set at runtime which is currently not possible in Python.

An option could be to set the output path on the `Out` class like this:

```python
@app.blob_trigger(
    arg_name="input_blob",
    path="abc/{date}/{filename}.{ext}",
    connection="abc",
)
@app.blob_output(
    arg_name="output_blob",
    connection="xyz",
)
def copy_blob(input_blob: func.InputStream, output_blob: func.Out[str]):
    # Logic
    output_blob.set(output, path=f"xyz/year={year}/month={month}/day={day}/{filename}.{ext}")
```

**Comment by ramya894** [comment]
@flvndh Thanks for reporting we will discuss this feature internally and update you on the inputs soon.

**Comment by bhagyshricompany** [comment]
@vrdmr pls validate and comment

**Comment by flvndh** [comment]
@bhagyshricompany @vrdmr any news on this?

**Comment by hallvictoria** [comment]
This can be addressed by using SDK type bindings for blob. The BlobTrigger can define a client type, and the client type can be used to rename and upload the blob.

Please see this documentation for more information:
- [Python Developer Reference - SDK Type Bindings](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=get-started%2Casgi%2Capplication-level&pivots=python-mode-decorators#sdk-type-bindings-preview)
- [SDK type bindings for Azure Blob Storage](https://techcommunity.microsoft.com/t5/azure-compute-blog/azure-functions-sdk-type-bindings-for-azure-blob-storage-with/ba-p/4146744)
