### ISSUE TITLE
[BUG] .venv not in sys.path (?)

### ISSUE THREAD

**Issue by Clam-** [Azure/azure-functions-python-worker#1159]
###### Please provide the following:

- Timestamp: 2022-12-31T04:56:29.748Z
- Function App name: newazurefunc
- Function name(s) (as appropriate): mytimer
- Core Tools Version:       4.0.4915 Commit hash: N/A  (64-bit)
- Function Runtime Version: 4.14.0.19631
- Python 3.9.13

###### Provide the steps required to reproduce the problem:

1. Open VSCode
2. Click Azure button
3. Click Create Function button
4. Create new folder C:\test\NewFunc2
5. Select folder created above
6. at "Select a language" prompt select: "python (Programming Model V2)"
7. Select a Python interpreter to create a virtual environment: "python3 3.9.13"
(also tried "python 3.9.4")
9. Select "Open in current window"
10. Edit "requirements.txt" add new line "requests"
11. Change body of "function_app.py" to be:
```python
import azure.functions as func
import logging
import datetime
import requests 
app = func.FunctionApp()
@app.function_name(name="mytimer")
@app.schedule(schedule="0 */5 * * * *", arg_name="mytimer", run_on_startup=True,
              use_monitor=False) 
def test_function(mytimer: func.TimerRequest) -> None:
    utc_timestamp = datetime.datetime.utcnow().replace(
        tzinfo=datetime.timezone.utc).isoformat()
    if mytimer.past_due:
        logging.info('The timer is past due!')
    logging.info('Python timer trigger function ran at %s', utc_timestamp)
```
12. press F5
13. "Exception: ModuleNotFoundError: No module named 'requests'."

###### Provide a description of the expected behavior.
Expected the function to run without import error

###### Provide a description of the actual behavior observed.
```
Error in index_function_app. Sys Path: ['C:\\Users\\<>\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\bin\\workers\\python\\3.9\\WINDOWS\\X64', 
'C:\\Users\\<>\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\bin\\workers\\python\\3.9\\WINDOWS\\X64', 
'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\python39.zip', 
'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\DLLs', 
'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib', 
'C:\\Users\\<>\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0', 
'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0', 
'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\site-packages', 
'C:\\test\\NewAzureFunc'],
```

###### Provide a description of any known workarounds.
I've tried a lot of things short of manually injecting into sys.path to no avail.

###### Provide the requirements.txt file to help us find out module related issues.
```
azure-functions
requests
```

###### Provide any related information
n/a

**Comment by Clam-** [comment]
I can perform the following in terminal:
```.\.venv\Scripts\Activate.ps1
(.venv) PS C:\test\NewAzureFunc> python --version
Python 3.9.13
(.venv) PS C:\test\NewAzureFunc> python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\python39.zip', 
'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\DLLs', 
'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib', 
'C:\\Users\\lee\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0', 
'C:\\test\\NewAzureFunc\\.venv', 
'C:\\test\\NewAzureFunc\\.venv\\lib\\site-packages']
>>>
```

as you can see above the .venv site-packages is in the path.
Not sure why it's not there when ```func host start``` runs.

**Comment by Clam-** [comment]
I thought this may have been a problem with the Programming Model V2, but it also happens when I select normal "Python", too. Now I'm confused and concerned that I cannot make any functions run locally with modules in the requirements.txt.
I'm not even sure where to start trying to diagnose/fix this.

**Comment by bhagyshricompany** [comment]
Thanks for updating will update you soon on this issue

**Comment by YunchuWang** [comment]
@Clam- have you installed requests in the venv? i tried v2 model and it works for me
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/12449837/210889952-2d6d44d4-def0-4c95-9fe5-0e2781c26555.png">

**Comment by Clam-** [comment]
I used requirements.txt which installs the required packages for you when you run/setup the package for the first time.
Oh, one thing I forgot to mention is that if I manually activate the venv, run python and import requests the package loads fine:
```python
PS C:\test\newfunc3>
PS C:\test\newfunc3> .\.venv\Scripts\Activate.ps1
(.venv) PS C:\test\newfunc3> python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> 
```

If I manually try to install requests it says it is already installed as one would expect:
```python
(.venv) PS C:\test\newfunc3> pip install requests
Requirement already satisfied: requests in c:\test\newfunc3\.venv\lib\site-packages (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\test\newfunc3\.venv\lib\site-packages (from requests) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\test\newfunc3\.venv\lib\site-packages (from requests) (2022.12.7) 
Requirement already satisfied: idna<4,>=2.5 in c:\test\newfunc3\.venv\lib\site-packages (from requests) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\test\newfunc3\.venv\lib\site-packages (from requests) (2.1.1)
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the 'c:\test\newfunc3\.venv\Scripts\python.exe -m pip install --upgrade pip' command.
(.venv) PS C:\test\newfunc3> 
```

**Comment by Clam-** [comment]
I mean the underlying issue is that when running the actual function the runtime environment isn't correct for some reason. sys.path doesn't have the venv site-packages in it.
I'm not sure why or even how to diagnose it or even what to try to fix it. For example, would removing and re-adding the azure functions extension fix that? uninstalling/reinstalling Visual Studio Code?

Thanks for your time.

**Comment by YunchuWang** [comment]
@Clam- i followed your steps using vscode extension to create the app but still cant repro it. the sys.path has .venv site-packages in it. 
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/12449837/211048434-98f569fc-ce65-4323-8046-5c8187fee247.png">

my azure functions extension is v1.9.0, core tool version is 4.0.4915.
Can you try reinstalling azure functions extension/vscode and core tool and create a new project to test again? thanks

**Comment by Clam-** [comment]
Here is a [gist](https://gist.github.com/Clam-/bb589b7efbaaf25f7dbafdf186f34591) of the full output of the terminal along with a screenshot:
![image](https://user-images.githubusercontent.com/985835/211447636-d8201f5f-d677-435c-b6c7-4bf2d5678e28.png)

**Comment by YunchuWang** [comment]
@Clam- Hi thanks for the update. Sorry for confusion. We are looking into it. By the way, does deploying this function to azure remotely works?

**Comment by pdthummar** [comment]
FYI, @YunchuWang @Clam- Replicated the issue using Core Tools Version: 4.0.4915 and 4.0.4765 and works fine, No issues. Thanks

**Comment by Clam-** [comment]
@YunchuWang I haven't tried deploying yet since I wanted to locally develop first. Deploying blind makes me a bit nervous however later this week I could attempt a simple deploy of the test timer thing, probably.

**Comment by bhagyshricompany** [comment]
@clam Hope you got the solution by above comment please update .

**Comment by Clam-** [comment]
@bhagyshricompany what solution? There didn't seem to be anything written that I could try.

**Comment by bhagyshricompany** [comment]
@clam have you tried with the option given by @pdthummar ?

**Comment by Clam-** [comment]
I don't understand what that text means. I am using Core Tools 4.0.4915. Is that text saying to use 4.0.4765 ?
The text you quoted sounds like "both 4.0.4915 and 4.0.4765 work fine".
I will try 4.0.4765 if that is what the text is suggesting.
Thank you.

**Comment by bhagyshricompany** [comment]
try one of the version mentioned

**Comment by Clam-** [comment]
I already have 4.0.4915 installed.

I do not see 4.0.4765 in npm view azure-functions-core-tools version.
It shows:
```
'4.0.3594',
  '4.0.3687',       '4.0.3743',       '4.0.3780',      '4.0.3928',
  '4.0.3971',       '4.0.4426',       '4.0.4483',      '4.0.4544',
  '4.0.4590',       '4.0.4629',       '4.0.4653',      '4.0.4670',
  '4.0.4704',       '4.0.4736',       '4.0.4785',      '4.0.4829',
  '4.0.4865',       '4.0.4895',       '4.0.4915'
```

I installed the closest match which was 4.0.4785.

Same problem. Tried creating a new function using the steps in the opening post to no avail.

Why isn't my debugging environment using the correct sys path? How do I debug this?

Thanks.

**Comment by YunchuWang** [comment]
@Clam- sorry for delayed response, have you installed python from Microsoft windows store? if so, can you try uninstall it? there is likely a bug using vscode function extension with windows store python

**Comment by Clam-** [comment]
@YunchuWang Yes, I was using Windows Store Python. Understood. I will try normal python installer in the coming days.

**Comment by JinjaFog** [comment]
For future reference: uninstalling the Microsoft store Python (3.11), installing it from python.org and recreating the venv fixed the issue.
