### ISSUE TITLE
Exception: TypeError: TriggerApi.route() got an unexpected keyword argument 'http_auth_level'

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-functions-python-worker#1160]
Getting error below when specify auth level when using new programming model for Python. Error is gone if I don't specify `http_auth_level` inside `@app.route()`. Not sure if this is a bug. 

![image](https://user-images.githubusercontent.com/25314976/211105319-7e6dbc84-48a4-4b5b-b661-da15cc36c06a.png)

Version info: 
![image](https://user-images.githubusercontent.com/25314976/211105412-8df03d1f-7c5f-468d-8cc2-6a08b6655a02.png)
- Functions extension v1.9.0
- Python extension v2022.16.1
- VSCode Version: 1.68.1 on Mac

**Comment by YunchuWang** [comment]
Hi @lilyjma, thanks for reporting this. the arg name for setting function level auth level is "auth_level", you can see from pydoc in vscode.
<img width="795" alt="image" src="https://user-images.githubusercontent.com/12449837/212189079-56590979-1e9d-4f9b-9349-9f03ff054f9e.png">

<img width="1600" alt="image" src="https://user-images.githubusercontent.com/12449837/212188902-1d9da227-fc73-470d-bee4-320f59d449e6.png">
changing to auth_level will work. thanks plz let us know if it works.
