### ISSUE TITLE
Python program is not being executed after the Function App is triggered

### ISSUE THREAD

**Issue by J04N4** [Azure/azure-functions-python-worker#1163]
I've built a python blob trigger function using VS code that is triggered when a file is added to a storage and then transforms the data of that file and inserts its content on a database . The function works fine locally and is deployed successfully on the Azure portal. However, when I insert files in storage, the function is triggered, but nothing happens (its file contents aren't added to the db).
![triggers](https://user-images.githubusercontent.com/44548285/212050644-26195a3a-aa83-467a-b2fa-cd1a2bb00141.png)

Requirements.txt
<img width="122" alt="requirements" src="https://user-images.githubusercontent.com/44548285/212050968-4ea208bb-2dbd-43f1-9705-2709ca770b21.png">

I already configured the variables manually in the azure portal in the settings of the Function App to match my json files. 
<img width="110" alt="application_settings" src="https://user-images.githubusercontent.com/44548285/212051696-a7b95e06-13c4-4efc-b06e-bb7673584bd1.png">

I use python 3.9, a linux consumption plan and a runtime ~4. I configured everything accordingly to the documentation. I don't understand why the function is not being executed

UPDATE: 
This seems to be the error I'm getting 
<img width="736" alt="error" src="https://user-images.githubusercontent.com/44548285/212068292-87807d58-d555-4968-8243-d0f38cf024b3.png">
That is how i configured the connection to the db in my code:
<img width="325" alt="connectDB" src="https://user-images.githubusercontent.com/44548285/212072444-9c7e5d58-c500-4b07-bf67-0cd17fac846f.png">
The driver i use is "SQL server"

**Comment by adamwhitneysoftwire** [comment]
This has also just happened on one of my projects after upgrading package versions. Currently trying things out to see which package fixes it.

It runs locally without issue, same as the original post.

**Comment by J04N4** [comment]
I was going to report an incident to Azure, but i found in the "Help + Support > <My-Function-App> | Configuration and Management" what it seems to be my issue.....

<img width="736" alt="error" src="https://user-images.githubusercontent.com/44548285/212067614-0fb7388b-7e34-49f9-812a-6215f2c9ae1f.png">

**Comment by YunchuWang** [comment]
@J04N4 thanks for sharing this and glad help support troubleshooting page pin out the issue for you, is the issue resolved？

**Comment by J04N4** [comment]
@YunchuWang No. I tried switching the SQL server to ODBC Driver 13 for SQL Server like it is represented in my db connection string, but now I can't seem to run it locally nor on the portal

**Comment by bhagyshricompany** [comment]
will check  and update you soon

**Comment by J04N4** [comment]
@bhagyshricompany It seems that the containers used for the Consumption (serverless) Function Apps has by default odbc driver 17 for sql server installed..... So I had to swap to it.

**Comment by bhagyshricompany** [comment]
@J04N4 yes closing it.
