### ISSUE TITLE
Converge azure.functions.ServiceBusMessage with azure.servicebus.ServiceBusMessage

### ISSUE THREAD

**Issue by metamoof** [Azure/azure-functions-python-worker#1172]
This is copied over from https://github.com/Azure/azure-sdk-for-python/issues/26827 as it was suggested I should post it in here.

I deal with a lot of code in azure functions that requires me to process messages in a ServiceBus queue, and then pass that message on untouched. However, despite the fact that an Azure Functions ServiceBus Queue Trigger passes in an `azure.functions.ServiceBusMessage`,  `azure.servicebus.ServiceBusSender` does not accept that kind of message, preferring to throw the rather cryptic error: `Exception: TypeError: Only AmqpAnnotatedMessage, ServiceBusMessage instances or Mappings representing messages are supported. Received instead: ServiceBusMessage`.

And as such, my code is peppered with this boilerplate:

```python
# msg is my azure.functions.ServiceBusMessage passed in at the start
with azure.servicebus.ServiceBusClient.from_connection_string(
    os.environ["SERVICEBUS"]
) as sb:
    sender = sb.get_queue_sender("next-step")
    message = azure.servicebus.ServiceBusMessage(
        body=msg.get_body(),
        application_properties=msg.user_properties,
        message_id=msg.message_id,
        content_type=msg.content_type,
    )
    sender.send_messages(message)
```

Also, knowing when to use `application_properties` or `user_properties` drives me a little crazy, and means I can't just do something like `message = azure.servicebus.ServiceBusMessage(**msg.__dict__)` or somesuch.

**Describe the solution you'd like**
Ideally, some sort of convergence, in which `azure.functions.ServiceBusMessage` is a subclass of `azure.servicebus.ServiceBusMessage`, but implementing the old API as backwards-compatible aliases, and eventually deprecating the APIs that are not in  `azure.servicebus.ServiceBusMessage`. I can see no reason why they need to be separate classes.

**Describe alternatives you've considered**
Somewhat messier alternatives:
 * Allow `azure.servicebus.ServiceBusSender.send_messages()` to accept `azure.functions.ServiceBusMessage` instances
 * Make an `azure.servicebus.ServiceBusMessage.from_azure_functions_message()` constructor that creates one from the other

**Comment by bhagyshricompany** [comment]
@metamoof  pls share the all repro steps.
Thanks

**Comment by metamoof** [comment]
In a function with a servicebus trigger that has a servicebus configured in the `SERVICEBUS` environment variable, and there is a `next-step` queue in that servicebus.

```python
import azure.functions as func
import azure.servicebus
import os 

def main(msg: func.ServiceBusMessage):
    with azure.servicebus.ServiceBusClient.from_connection_string(
        os.environ["SERVICEBUS"]
    ) as sb:
        sender = sb.get_queue_sender("next-step")
        sender.send_messages(msg) # Exception: TypeError: Only AmqpAnnotatedMessage, ServiceBusMessage instances or Mappings representing messages are supported. Received instead: ServiceBusMessage
```

**Comment by bhagyshricompany** [comment]
thanks will check update asap

**Comment by bhagyshricompany** [comment]
@gavin-aguiar  pls comment and validate

**Comment by gavin-aguiar** [comment]
Currently this is not supported in python functions. We are working on a feature where the sdk client will be passed as a binding which should help in this case. But the feature is still in progress and will be coming out within a few months.

**Comment by alecglen** [comment]
@gavin-aguiar @bhagyshricompany, any updates for either metamoof's proposal or the SDK client binding Gavin mentioned?

As far as I can tell there is still no solution provided - not sure why it was marked completed.

**Comment by alecglen** [comment]
@gavin-aguiar I think [this](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=get-started%2Casgi%2Capplication-level&pivots=python-mode-decorators#sdk-type-bindings-preview) is the feature you were referring to?

It seems it still does not support the Service Bus SDK. Even if it did, that would not solve this issue as the provided SDK client still wouldn't accept an `azure.functions.ServiceBusMessage` type object.
