### ISSUE TITLE
[BUG] Underscore is not supported in the argument names in V2

### ISSUE THREAD

**Issue by paldaniel** [Azure/azure-functions-python-worker#1174]
Functions with underscore in the argument names are not mapped in V2
```
"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.15.0, 4.0.0)"
  }
```

**Not working:**
```
@app.function_name(name="django_backend")
@app.route(route="{*route}", trigger_arg_name='a_req', methods=['GET', 'POST'], auth_level=func.AuthLevel.ANONYMOUS)
def django_backend(a_req: func.HttpRequest, context) -> func.HttpResponse:
    return func.WsgiMiddleware(application).handle(a_req, context)


@app.function_name(name="a_timer")
@app.schedule(schedule="0/3 * * * * *", arg_name="a_timer", run_on_startup=True, use_monitor=True)
def test_function(a_timer: func.TimerRequest) -> None:
    logging.info("This is a scheduled function")

    if a_timer.past_due:
        logging.info("The timer is past due!")
```

**Working:**
```
@app.function_name(name="django_backend")
@app.route(route="{*route}", trigger_arg_name='aReq', methods=['GET', 'POST'], auth_level=func.AuthLevel.ANONYMOUS)
def django_backend(aReq: func.HttpRequest, context) -> func.HttpResponse:
    return func.WsgiMiddleware(application).handle(aReq, context)


@app.function_name(name="aTimer")
@app.schedule(schedule="0/3 * * * * *", arg_name="aTimer", run_on_startup=True, use_monitor=True)
def test_function(aTimer: func.TimerRequest) -> None:
    logging.info("This is a scheduled function")

    if aTimer.past_due:
        logging.info("The timer is past due!")
```

**Comment by bhagyshricompany** [comment]
Thanks for update.
As I can see with your code you not followed the generic azure function rules for creating argument.
This is likely because the underscores can cause issues with serialization or with mapping the arguments to other components in the Azure ecosystem.

If you're encountering an issue with using underscores in argument names in Azure Functions, you may want to consider using CamelCase instead. For example, instead of def my_function(arg_1, arg_2), you could use def myFunction(arg1, arg2).

**Comment by paldaniel** [comment]
Thanks for the fast response!
Could you please send me url to the rules?

**Comment by bhagyshricompany** [comment]
https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python?pivots=python-mode-decorators
https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level&pivots=python-mode-decorators

Here's a list of guidelines and restrictions on naming conventions for arguments in Azure Functions:

Function arguments must follow the naming rules of Python variables, which means they can only contain letters, numbers, and underscores, and must start with a letter or an underscore.

Argument names must not contain any spaces or special characters, as this can cause issues when mapping the arguments to other components in the Azure ecosystem.

Function arguments can have default values, but they must be specified using the standard syntax for default arguments in Python, such as def myFunction(arg1, arg2=None).

When defining multiple arguments, it is best practice to separate them with a comma, like so: def myFunction(arg1, arg2).

It's recommended to avoid using Python keywords as argument names, as this can cause conflicts when the arguments are mapped to other components in the Azure ecosystem.

Some tools such as the Azure Functions bindings may have specific restrictions on argument names. For example, in the case of HTTP triggered functions, argument names must match the names of the query string or route parameters in the URL.

You can use __ (double underscore) to indicate a private variable, however, it's not enforced and the variable can still be accessed normally.

**Comment by paldaniel** [comment]
Thanks!

**Comment by gpiantoni** [comment]
Sorry to reopen this issue. As it is now, it's not possible to use underscores in `arg_name` in v2 (as the above example shows), so this sentence is not correct: "Function arguments must follow the naming rules of Python variables, which means they can only contain letters, numbers, and underscores, and must start with a letter or an underscore." camelCase is unpythonic and underscores are preferred (PEP8)

Could you please document this bug / unexpected behavior in the official documentation?

**Comment by williamhbell** [comment]
In case it is helpful, the PEP8 style guidelines on variable names are found at https://peps.python.org/pep-0008/#function-and-variable-names
