### ISSUE TITLE
Publish azure.functions package to PyPI

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#118]
## Requirements
- Library should have released a stable version (1.0 +)  on pypi(1) 
- Cross platform (windows, linux, osx) (1) 
- Library should follow below guidelines (1) 
      - Library should be on par with service side features  
      - Library should use industry standard libraries/implementations where applicable 
      - Lists with iterators instead of lists 
      - Should have Async pattern 
      - too reliant on duck-typing (if method exists checks) 
      - exception over pre-check

**Comment by asavaritayal** [comment]
@asavaritayal to add list of fundamentals

**Comment by aluong** [comment]
Is the current recommended release tag for installing the Python worker?

**Comment by asavaritayal** [comment]
Closing issue as this is now available - https://pypi.org/project/azure-functions/
