### ISSUE TITLE
[BUG]  AsgiRequest hard codes scheme as 'https' in scope

### ISSUE THREAD

**Issue by jasonchester** [Azure/azure-functions-python-worker#1185]
### Expected behavior

Scheme should either be http or https depending on the request being handled.

### Actual behavior

Scheme is hard coded as https
 
### Related information

https://asgi.readthedocs.io/en/latest/specs/www.html

* Links to source

https://github.com/Azure/azure-functions-python-library/blob/cc3fd5d13770244bdcc1030be608c81d50df1ad2/azure/functions/_http_asgi.py#L32-L62

* Bindings used

**Comment by bhagyshricompany** [comment]
Thanks for  update will inform

**Comment by jasonchester** [comment]
@bhagyshricompany, **WsgiRequest** appears to handle scheme correctly with **urllib.parse.urlparse**

https://github.com/Azure/azure-functions-python-library/blob/cc3fd5d13770244bdcc1030be608c81d50df1ad2/azure/functions/_http_wsgi.py

```py
#...
from urllib.parse import ParseResult, urlparse, unquote_to_bytes
#...
class WsgiRequest:
#...
    def __init__(self,
                 func_req: HttpRequest,
                 func_ctx: Optional[Context] = None):
        url: ParseResult = urlparse(func_req.url)
#...
        self.wsgi_url_scheme = url.scheme
 
#...
```

**Comment by bhagyshricompany** [comment]
@gavin-aguiar  pls comment and update
