### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#12]
To retrieve information about the current process or user environment, use the ```os.environ``` method of the ```os``` module in Python. For example -

```python
# main.py

import os
def main(logger):
	logger.info('Python process has begun!')
	
	for name in ('HOME', 'USERPROFILE', 'USERNAME'):
		info = os.environ.get(name)
		logger.info(f'{name} : {info}')	

```

**Comment by 1st1** [comment]
Yeah, this is a standard way of accessing environment variables, so I believe we don't need to do anything special on our end.
