### ISSUE TITLE
Is then an exemple of defining and registering per-function FuncExtensionBase custom extension?

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-functions-python-worker#1204]
#### Question

I would like to define a custom extension that is per function.
This extension would capture the HttpTrigger request and perform some custom processing.

I could not find any sample for that.
Is there any sample?

**Comment by bhagyshricompany** [comment]
Thanks for reaching out.
There is already doc available for this.you can refer this below doc.
https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-the-http-request

**Comment by springcomp** [comment]
> Thanks for reaching out. There is already doc available for this.you can refer this below doc. https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-the-http-request

Thanks for the feedback.
My question however relates to Python and not .Net.

Is there any example for creating a custom class inheriting from Fun extension base?

**Comment by bhagyshricompany** [comment]
you can try for sample below.
import azure.functions as func

class MyCustomFunction(func.Function):
    def __init__(self):
        super().__init__()

    def __call__(self, req: func.HttpRequest) -> func.HttpResponse:
        
        return func.HttpResponse("Hello, World!")

**Comment by springcomp** [comment]
@bhagyshricompany thanks for the feedback.

Can you please share a more complete sample?
I fail to see where you are showing a FuncExtensionBase-derived class ?

**Comment by bhagyshricompany** [comment]
# extensions/my_extension/__init__.py

from .my_extension import MyExtension

def main(req, context):
    my_extension = MyExtension()
    result = my_extension.func_name(req)
    return result


# extensions/my_extension/my_extension.py

from azure.functions import FunctionExtensionBase

class MyExtension(FunctionExtensionBase):

    def func_name(self, input):
        # Implementation of your function here
        return result

**Comment by bhagyshricompany** [comment]
# extensions/my_extension/__init__.py
from .my_extension import MyExtension

def main(req, context):
    my_extension = MyExtension()
    result = my_extension.func_name(req)
    return result
# extensions/my_extension/my_extension.py
from azure.functions import FunctionExtensionBase

class MyExtension(FunctionExtensionBase):

    def func_name(self, input):
        # Implementation of your function here
        return result

**Comment by springcomp** [comment]
@bhagyshricompany thanks a lot.

This demonstrate how one would go in consuming a custom extension.

However, I’m specifically looking for an example of _how to create such a custom extension_.

For instance, the [official document](https://learn.microsoft.com/en-us/azure/azure-functions/develop-python-worker-extensions?tabs=windows%2Cpypi#create-the-python-worker-extension) shows how to create a custom extension using an **AppFunctionExtension** base class.

```python
import typing
from logging import Logger
from time import time
from azure.functions import AppExtensionBase, Context, HttpResponse
class TimerExtension(AppExtensionBase):
    """A Python worker extension to record elapsed time in a function invocation
    """

…
```

The document then has this text:

> This code inherits from [AppExtensionBase](https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/extension/app_extension_base.py) so that the extension applies to every function in the app. You could have also implemented the extension on a function-level scope by inheriting from [FuncExtensionBase](https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/extension/func_extension_base.py).

However, I cannot find any example of creating such a custom extension from an **FuncExtensionBase** class.

**Comment by bhagyshricompany** [comment]
ok will update for this asap.

**Comment by bhagyshricompany** [comment]
You can refer below Link for good sample:
Tutorial: https://learn.microsoft.com/azure/azure-functions/develop-python-worker-extensions

 

Example extension: https://github.com/census-ecosystem/opencensus-python-extensions-azure/tree/main/extensions/functions

 

[Hazhzeng/python-worker-extension-timer (github.com)](https://github.com/Hazhzeng/python-worker-extension-timer)

**Comment by springcomp** [comment]
I think the answer gives me a lot of information for going further. Thanks a lot.
