### ISSUE TITLE
Blob Output Binding: Setting file name within the function

### ISSUE THREAD

**Issue by pietz** [Azure/azure-functions-python-worker#1205]
#### Is your question related to a specific version? If so, please specify:
I believe the issue (or missing feature) is related to the V1 and V2 python programming model.

#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
Blob Output Binding

#### Question
How can I set the name of the blob output file within the function?

Setting the name of the blob output file seems to be able in two ways:

1. static name in the path -> why does this even exist?
2. dynamic name in the path, which needs to reference a name from the trigger or input

But how can I define the name of the output file within the function?

I'm using this endpoint as a HTTP upload endpoint. I want to choose the file name based on the md5 hash of the file to avoid collisions and check if a file already exists. How can I do that?

**Comment by bhagyshricompany** [comment]
Thanks for informing.
You can try this.
import hashlib
import base64
import azure.functions as func

def main(req: func.HttpRequest, outputBlob: func.Out[bytes]) -> func.HttpResponse:
    # Retrieve the file content from the HTTP request body
    file_content = req.get_body()
    
    # Generate the MD5 hash of the file content
    md5_hash = hashlib.md5(file_content).digest()
    
    # Encode the MD5 hash as base64 and use it as the blob name
    blob_name = base64.b64encode(md5_hash).decode('utf-8')
    
    # Set the blob name as the dynamic binding parameter
    outputBlob.set(file_content, blob_name=blob_name)
    
    # Return an HTTP response
    return func.HttpResponse(f"File uploaded as {blob_name}")
if its not works pls let me know.
Thanks

**Comment by bhagyshricompany** [comment]
Hope you got the answer other wise you can raise the new req.

**Comment by miztiik** [comment]
@pietz - Did you manage to get it working?

**Comment by pietz** [comment]
After reading a bit more into the topic, I came to the conclusion that the bindings are basically useless if you want to do serious interaction with other resources. Except for trigger bindings, don't use binding. Just use the cosmos or blob clients.

Honestly, the bindings are a good idea for the first 10s but afterwards they are both worth your time. I wish it was different.

**Comment by miztiik** [comment]
@pietz  Thanks for taking to respond. You have pretty much confirmed my findings. I am refactoring to using SDK to interact with the resources and retain the triggers.
