### ISSUE TITLE
Deleting objects with bindings?

### ISSUE THREAD

**Issue by pietz** [Azure/azure-functions-python-worker#1206]
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 

Basically all of them

#### Question

How can I delete objects in a blob storage or from a Cosmos DB with bindings?

**Comment by bhagyshricompany** [comment]
Thanks for informing.
you can refer this document to delete method.
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-delete#delete-a-blob
