### ISSUE TITLE
[FeatureRequest] Azure SQL binding

### ISSUE THREAD

**Issue by joedevgee** [Azure/azure-functions-python-worker#1212]
## Support for azure sql in/out binding

I've already seen people raise similar issue before: #365 

At this time, looks like the only db binding supported is cosmos, the doc is [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?pivots=python-mode-decorators&tabs=asgi%2Capplication-level#triggers-and-inputs:~:text=At%20this%20time%2C%20only%20specific%20triggers%20and%20bindings%20are%20supported%20by%20the%20Python%20v2%20programming%20model.%20Supported%20triggers%20and%20bindings%20are%20as%20follows)

Considering 
1. programming model 1 already supported sql in/out biding, [doc](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-output?tabs=in-process&pivots=programming-language-python#configuration:~:text=a%20JSON%20body.-,The%20following%20is%20binding%20data%20in%20the%20function.json%20file%3A,-JSON), can we expect same feature to exist for model 2
2. RDBMS like azure sql has a huge user base, Having these bindings would really benefit the sql users

Sample v1 binding for sql
```json
{
    "name": "todoItems",
    "type": "sql",
    "direction": "out",
    "commandText": "dbo.ToDo",
    "connectionStringSetting": "SqlConnectionString"
}
```

**Comment by bhagyshricompany** [comment]
Thanks for Feedback will confirm for the same.

**Comment by joedevgee** [comment]
Similar topic, I see in the v2 [doc](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level&pivots=python-mode-decorators#triggers-and-inputs:~:text=account%20guidance.-,At%20this%20time%2C,-only%20specific%20triggers) below is ss for supported triggers. Is there a timeline/roadmap where we can see the progress of supporting each of these?

<img width="897" alt="image" src="https://user-images.githubusercontent.com/11239869/231225054-2ab4176d-8917-4f7f-bfee-2b07c1cfb525.png">
