### ISSUE TITLE
CosmosDB  V4 extension update

### ISSUE THREAD

**Issue by gavin-aguiar** [Azure/azure-functions-python-worker#1222]
Versions 4.x+ of the Cosmos DB extension for Azure Functions includes different several [changes](https://learn.microsoft.com/azure/azure-functions/functions-bindings-cosmosdb-v2?tabs=in-process%2Cextensionv4&pivots=programming-language-csharp) in parameter names. We are updating the v2 programming model for Functions in Python to provide first class support for the new version of Cosmos DB.

If you are currently using the Cosmos DB extension with the v2 programing model for Python, **this may mean a breaking change for you**. Once support for the latest Cosmos DB extension is live, the existing decorator names will refer to the new extension.

The new decorator names will be as follows:

Extension 2.x and 3.x

- cosmos_db_trigger_v3
- cosmos_db_input_v3
- cosmos_db_output_v3

Extension 4.x and above

- cosmos_db_trigger
- cosmos_db_input
- cosmos_db_output

We recommend using version 4.x and above of the Cosmos DB extension, as the older extensions will soon be unsupported due to the underlying SDK being deprecated.

**Comment by yourmaingotoguy** [comment]
Hi @gavin-aguiar

**Comment by gavin-aguiar** [comment]
Hi @yourmaingotoguy , you won't be able to pin the azure-functions-python-worker but if you're still using the older extensions, you can pin the azure-functions version to 1.13.3.
