### ISSUE TITLE
Getting HTTP 500 and no module in requirement,txt file, already requests modules in the requirement.txt, but still showing but error

### ISSUE THREAD

**Issue by Umamahesh888** [Azure/azure-functions-python-worker#1238]
<img width="640" alt="module not found" src="https://user-images.githubusercontent.com/131890600/238279320-826be712-7bae-4ab8-b2c7-039ca25329ba.PNG">
  i tried the above proccess, we are using pip 3.9 build and release succuusefully the function app, but when access through portal getting HTTP 500 error, and as per above message chains used the above command in the build pipeline, pip install --target="$(workingDirectory)/.python_packages/lib/site-packages" -r requirements.txt, but still getting the same  HTTP response code
500 Internal Server Error could you please help me the resoling the issue.

**Comment by Umamahesh888** [comment]
locally developers using the python 3.10 , but in azure pipeline build using the 3.9 version , this is for causing the issue?

**Comment by bhagyshricompany** [comment]
Thanks fo reaching out. we are investigating once done update you

**Comment by Umamahesh888** [comment]
ok, but now redeployed the code thru vs code in to azure function app, now getting the azure app function not reachable and 502 bad gatway in azure funtion app ,could you please help me

**Comment by bhagyshricompany** [comment]
we are investigating the issue .
Could you please share the invocation id,fun name region etc
