### ISSUE TITLE
Unable to load a model file to Azure blob storage

### ISSUE THREAD

**Issue by varunvrcloudtech** [Azure/azure-functions-python-worker#1246]
Unable to load a model file to Azure blob storage.

from azure.storage.blob import BlobClient

sas_url = "https://account.blob.core.windows.net/container/blob-name?<sas-token>"
blob_client = BlobClient.from_blob_url(sas_url)

# Upload the created file
with io_open(file=model, mode="rb") as data:
    blob_client.upload_blob(data)

I keep getting error while trying to upload the model file to blob storage

**Comment by bhagyshricompany** [comment]
Thanks for reporting issue pls provide the repro steps.or u can share here in privately:https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately
