### ISSUE TITLE
How to defer messages within a Service Bus Trigger?

### ISSUE THREAD

**Issue by 05vald0** [Azure/azure-functions-python-worker#1249]
Binding: Service Bus Trigger, programming model V2

I want to defer the input message of a Service Bus Trigger, since the message should only be marked as complete when another Service Bus Trigger finishes. However, the only [example](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/sync_samples/receive_deferred_message_queue.py) of message deferral in Python I've found uses a queue receiver. If I understand correctly, I cannot get the message via such receiver within the trigger, since the input message is locked by the trigger.

I tried setting the autoCompleteMessage attribute to false in host.json, and then settling the message outside of the trigger, but it did not make any difference, since the message was removed from the queue as soon as the trigger finished.

Is there a way to do this?

**Comment by bhagyshricompany** [comment]
I hope you got the answer if not pls raise new request will work on that .Hence Closing.
Thanks
