### ISSUE TITLE
Retry Policy support for V2

### ISSUE THREAD

**Issue by gavin-aguiar** [Azure/azure-functions-python-worker#1253]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-functions-python-worker/pull/1268
- [ ] https://github.com/Azure/azure-functions-python-library/pull/182
```

**Comment by ogiel** [comment]
Could any example be given on how to use retry policies on V2 functions? Everything I try results in no functions shown in the function app:
```
@app.retry(strategy="fixedDelay", max_retry_count="3", delay_interval="00:00:30")
@app.schedule(
    schedule="* 0 * * * *", arg_name="myTimer", run_on_startup=True, use_monitor=False
)
def AzureMapsWeatherToADT(myTimer: func.TimerRequest) -> None:
```
If i comment out the @app.retry() it works.

Unfortunately I am unable to find any examples or documentation, or even references to possible options for the strategy in the python package. E.g. should strategy be fixedDelay or fixed_delay?

**Comment by gavin-aguiar** [comment]
Hi @ogiel, Thanks for the feedback and apologies for the confusion. As you mentioned, all names are snake cased. We'll definitely add some examples for retries with the v2 programming model.
