### ISSUE TITLE
[FeatureRequest] Add special checks whenever __init__.py of functions library is changed

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-python-worker#1260]
[Task 21232166](https://msazure.visualstudio.com/Antares/_workitems/edit/21232166): Add CI to have more strict checks whenever __init__.py files are updated

We want to add labels to the PR if it changes `__init__.py` and use actions such as [enforce-label-action](https://github.com/yogevbd/enforce-label-action) or others such that unless the label is removed, we don't merge it.

**Comment by pdthummar** [comment]
Merged https://github.com/Azure/azure-functions-python-library/pull/183
