### ISSUE TITLE
Module not found error when upgrading from Consumption to Elastic Premium Plan

### ISSUE THREAD

**Issue by bepa92** [Azure/azure-functions-python-worker#1269]
After changing the Service Plan from Consumption to Elastic Premium, there is the following error message:

![failed](https://github.com/Azure/azure-functions-python-worker/assets/137293215/6a0ce761-2d0b-45a7-952f-4b355fa89d89)

The init.py file as well as the requirements.txt remained the same. 
The deployment process still works fine, however the http-request produces the error.

I'm using Python 3.9 , an http-trigger and mcr.microsoft.com/azure-functions/python:4-python3.9-appservice-stage5.

Unfortunately, it is not possible to include pango via pip and the requirements.txt.
How it is possible, that the code works fine on Consumption and then is faulty via Premium Plan?

**Comment by bhagyshricompany** [comment]
@bepa92  Thanks for reporting the issue pls share the function app name ,invocation id,region,timestamp etc.

**Comment by bepa92** [comment]
Timestamp: 2023-06-21T11:50:43.046+00:00
    Function App name: app-Vorkontierung-prem
    Function name: func-Vorkontierung
    Core Tools version: 4.0.5198
    Execution Id: 77226517-8791-40da-88ee-ba5c62be1062
    Region: West Europe
