### ISSUE TITLE
Investigation : Test Python Functions E2E on Anatares on Windows

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#127]

**Comment by pragnagopa** [comment]
@asavaritayal  -  I have a working sample with python functions running in Azure.
Setup (please fix python installation steps if I missed any)
- Create function app
- Go to Kudu
- Install Python 3.6 following instructions at [/running-python-code-on-azure-functions-app](https://ourwayoflyf.com/running-python-code-on-azure-functions-app/)
- Git clone https://github.com/Azure/azure-functions-python-worker
- cd to azure-functions-python-worker
- python pip install
- Add application setting name: FUNCTIONS_WORKER_RUNTIME  value: python
- Add application setting name: workers:config:path  value: {path to azure-functions-python-worker directory}
- Copy python function under: D:\home\site\wwwroot

**Comment by asavaritayal** [comment]
Work required to productionize Python on Windows - 
- We will have to preinstall python3.6 on the workers. 
- Dependency / package management: On Windows workers, we can leverage Kudu as a build server. Maybe it just builds the package, uploads it to storage, and return the sas url to the CLI that then updates app settings. Or we can get some work done to have kudu be able to set the WEBSITE_USE_ZIP setting through the auth mechanism we now have with the front end.
