### ISSUE TITLE
Can't use pyodbc

### ISSUE THREAD

**Issue by svickers** [Azure/azure-functions-python-worker#1272]
Starting from a fresh function app with the v2 model it will stop working when you import pyodbc.  

### Investigative information
- Core Tools version: 4.0.5198
- Platform: Windows
- Python Version: 3.9.13

### Repro steps

1. `func init python_test_func --python -m V2`
2. `pip install pyodbc`
3.  Create file function_app.py:
```py
import azure.functions as func

app = func.FunctionApp()

@app.function_name(name="HttpTrigger1")
@app.route(route="hello")
def test_function(req: func.HttpRequest) -> func.HttpResponse:
    return func.HttpResponse("HttpTrigger1 function processed a request!")
```
4. run `func start` to verify it works.
5. add `import pyodbc` to top of function_app.py
6. run `func start`

### Expected behavior
Should continue to work and serve requests.

### Actual behavior
```
Result: Failure
Exception: ModuleNotFoundError: No module named 'pyodbc'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound
Stack:   File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.10\WINDOWS\X64\azure_functions_worker\dispatcher.py", line 338, in _handle__functions_metadata_request
    fx_metadata_results = self.index_functions(function_path)
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.10\WINDOWS\X64\azure_functions_worker\dispatcher.py", line 607, in index_functions
    indexed_functions = loader.index_function_app(function_path)
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.10\WINDOWS\X64\azure_functions_worker\utils\wrappers.py", line 48, in call
    raise extend_exception_message(e, message)
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.10\WINDOWS\X64\azure_functions_worker\utils\wrappers.py", line 44, in call
    return func(*args, **kwargs)
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.10\WINDOWS\X64\azure_functions_worker\loader.py", line 151, in index_function_app
    imported_module = importlib.import_module(module_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\me\dev\python_test_func\function_app.py", line 2, in <module>
    import pyodbc
```

### Known workarounds

None

### Contents of the requirements.txt file:
azure-functions
pyodbc

**Comment by bhagyshricompany** [comment]
Hi @svickers  pls try again its working fine as I tested the step you provided.
<img width="591" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/cc14aae3-1a1a-430f-aeb5-17b7a0a17fb1">
<img width="877" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/db705f33-99b3-4117-9c8c-9c4d50a20c14">
<img width="743" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/b51449b2-7f6f-49fe-9beb-03168a7d9dff">

**Comment by svickers** [comment]
@bhagyshricompany Did you add `import pyodbc` to the top of the function_app.py file?

**Comment by bhagyshricompany** [comment]
yes as you can see here.
<img width="868" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/df74c64a-85bb-4529-b46e-89f60c73e83c">

**Comment by svickers** [comment]
Interesting... I pushed a basic test repo up here: https://github.com/svickers/python_test_func

Here is my environment information:
```
func start
Found Python version 3.10.11 (python3).

Azure Functions Core Tools
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667
```

**Comment by bhagyshricompany** [comment]
pls check your file format  have and directory structure
<img width="831" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/a6ac00a7-090f-4b79-96bc-b21c5c073f53">

**Comment by svickers** [comment]
Also one other thing to note is I can deploy to a function app just fine until I add the pyodbc reference and then it also fails to start and fails to index any functions.... which makes me think it is more than just my local environment.

![Screenshot_550](https://github.com/Azure/azure-functions-python-worker/assets/105884/4f615c5a-3a5d-4eb7-af7d-7cb5b463711a)
![Screenshot_551](https://github.com/Azure/azure-functions-python-worker/assets/105884/05339f7d-ece8-4b78-9726-e2df1403bf2d)

If I remove the single import pyodbc line then everything works fine in azure:

![Screenshot_552](https://github.com/Azure/azure-functions-python-worker/assets/105884/656d6d21-55f8-48ce-9f13-51a1233599f4)

**Comment by bhagyshricompany** [comment]
I deplyed code with pyodbc its working fine.

**Comment by svickers** [comment]
Can you post your repo somewhere so I can try it?

**Comment by bhagyshricompany** [comment]
you downloaded python from msstore or python.org

**Comment by svickers** [comment]
Installed from python.org.

**Comment by bhagyshricompany** [comment]
still not working ?

**Comment by svickers** [comment]
Yes still not working.

**Comment by bhagyshricompany** [comment]
@vrdmr pls comment and validate

**Comment by YunchuWang** [comment]
Tried the test repo and working for me too. Here is my func info:
Found Python version 3.10.11 (py).

Azure Functions Core Tools
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667

<img width="735" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/12449837/65a49eaa-5cbf-4449-b005-1306bf190233">

Here is my local.settings.json file:
<img width="346" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/12449837/68244868-1b40-4ea3-b20c-3d7af1aadcc1">

@svickers Wonder whats your local.settings.file look like and can you try the core tool version i have with a new virtual environment created?

**Comment by svickers** [comment]
Still seeing the same issue with a fresh venv, really unsure what is going on because the same code also doesn't work in azure, which shouldn't have anything to do with my local setup.

![Screenshot_609](https://github.com/Azure/azure-functions-python-worker/assets/105884/bdc76e3f-b2d0-40fa-b8da-02048418b992)

My local.settings.json file is:
```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "AzureWebJobsFeatureFlags": "EnableWorkerIndexing",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true"
  }
}

```

**Comment by yorek** [comment]
Hi, I'm having the same issue. It seems it happens only when I'm trying to run `func start` and I have an active virtual enviroments=, and the package are only installed in the virtual enviroments.

**Comment by KKiriri** [comment]
Same issue here. Only difference is that I am using v1 python model, running with __init__.py. Both local environment and Azure function environment have trouble importing pyodbc.

**Comment by hallvictoria** [comment]
Hi, just to follow up on this.

I tested this with this setup:
	- Function app repo: https://github.com/svickers/python_test_func
	- Python: 3.10
	- Core Tools: 4.0.5455

![image](https://github.com/Azure/azure-functions-python-worker/assets/59299039/259e5f3c-c4b4-43d5-9d87-665100210360)

I was able to replicate the error by doing this:
	1. `python -m venv .venv`
	2. `.venv/Scripts/activate`
	3. `func start`

![image](https://github.com/Azure/azure-functions-python-worker/assets/59299039/354e66f2-04ea-4200-be8e-f9162813e3e7)
![image](https://github.com/Azure/azure-functions-python-worker/assets/59299039/a13e7fce-6ff1-47ab-9f24-03fa2e03d658)

From this, it looks like pyodbc has not been installed correctly.

I then tried running `pip install -r requirements.txt` and it started correctly:
	1. `python -m venv .venv`
	2. `.venv/Scripts/activate`
	3. `pip install -r requirements.txt` 
	5. `func start`

![image](https://github.com/Azure/azure-functions-python-worker/assets/59299039/46ff8072-da77-4e26-9b1d-6cb20b58efae)

I also tested deploying the app from VSCode (with pyodc added in requirements.txt and imported) and that was successful.

![image](https://github.com/Azure/azure-functions-python-worker/assets/59299039/72cdac0b-53ab-4806-82d2-7e475f6dc87a)
![image](https://github.com/Azure/azure-functions-python-worker/assets/59299039/d8103a8a-b0ad-4b0f-b926-f54c98c4653e)
![image](https://github.com/Azure/azure-functions-python-worker/assets/59299039/b1aed2bd-72ce-48db-93a4-c6a13c31efc4)

Is this still not working correctly on your end?

**Comment by GengisGutierrez** [comment]
I have been looking for a solution to my deployment error, and I found the error .... So, the pyodbc library works with an ODBC SQL driver. So make sure you know which driver your Azure function environment works with. If you are using Python 10, it seems to me that by default it enables a driver of the type DRIVER={ODBC Driver 17 for SQL Server} . And searching through several forums, I stopped to check the driver for my environment... and it turned out that for the version of Python 11 as the environment language, the driver is DRIVER={ODBC Driver 18 for SQL Server}. 

My advice will be. **First make sure you know what ODBC drivers your app has** with the code 
drivers = pyodbc.drivers() 

For local tests it works the same, the driver I used was DRIVER={SQL Server} ... My connection code was 
conn = pyodbc.connect(
         "DRIVER={ODBC Driver 18 for SQL Server};"
         f"SERVER=tcp:{server};"
         f"DATABASE={database};UID={user};"
         f"PWD={password};"
         "Encrypt=yes;"
         "TrustServerCertificate=no;"
         "Connection Timeout=30;"
     )

**Comment by Winkielek** [comment]
In case anyone has still problem with it. For me it turned out that I forgot to install an ODBC driver manager on my Linux (dev container) prior to installing `pyodbc`.

According to the `pydobc` documentation:

```
You should make sure you have an ODBC driver manager installed before installing pyodbc. See the [docs](https://github.com/mkleehammer/pyodbc/wiki/Install) for more information about how to do this on different Unix flavors. (On Windows, the ODBC driver manager is built-in.)
```

**Comment by jacksorjacksor** [comment]
Hi - I'm having this same issue.
Windows 11
Azure Functions CLI v4.0.5455
Python 3.11.9

**Steps to reproduce:**
Create a new folder
Using Powershell 7
`func new --template "Http Trigger" --name MyHttpTrigger --worker-runtime Python`
`python -m venv .venv`
`.\.venv\scripts\Activate.ps1`
`pip install -r requirements.txt`
`pip install pyodbc`
`pip freeze > requirements.py`

In `function_app.py` add line `import pyodbc`
(we literally just need to import the library, we don't even do any code!)

`func start`

This leads to two different errors:
1. `Error in index_function_app. Sys Path: [....loads of locations....] ,python-packages Path exists: False `

2. `Worker failed to index functions`
`Result: Failure Exception: ModuleNotFoundError: No module named 'pyodbc'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound`

Any help would be GREATLY appreciated.

I've made a YT video showing this: https://youtu.be/dR4i41d5E8Q

Thanks!

Rich

**Comment by jacksorjacksor** [comment]
FIXED: installed Python from Python.org. 
Version downloaded from Microsoft Store resulted in these issues.

https://github.com/Azure/azure-functions-core-tools/issues/3042#issuecomment-1113848949
