### ISSUE TITLE
Missing tag error while deploying functions with core tools

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#128]
Followed instructions from:

and when executing func azure functionapp publish pypreviewapp, got the following error.

Running docker exec -t c042b8fecca82e433ecf220fff4794de4cca89d918e2c09d026d2e9b8ebdc7ba /python_docker_build.sh
Obtaining azure_functions_python from git+https://github.com/Azure/azure-functions-python-worker.git@549f40b8be07388fedbc5b706db6d14e5179bc6e#egg=azure_functions_python (from -r requirements.txt (line 1))
  Cloning https://github.com/Azure/azure-functions-python-worker.git (to "549f40b8be07388fedbc5b706db6d14e5179bc6e") to ./worker_venv/src/azure-functions-python
  **Could not find a tag or branch "549f40b8be07388fedbc5b706db6d14e5179bc6e", assuming commit.**

and it doesn't move forward from here.

Workaround: Change the tag from "549f40b8be07388fedbc5b706db6d14e5179bc6e" to "dev" in requirements.txt.

**Comment by aluong** [comment]
This looks like this issue that I filed: https://github.com/Azure/azure-functions-core-tools/issues/476

**Comment by asavaritayal** [comment]
Is this a warning or an error?

**Comment by priyaananthasankar** [comment]
This seems like an error and it doesn't proceed after this. As Andy says, if the requirements.txt is frozen, then it automatically adds this label to the pip install. So I suspect the func core tools that adds the venv.

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-core-tools#484
