### ISSUE TITLE
Azure Functions in VS Code but cannot seem to create Python V2 model project

### ISSUE THREAD

**Issue by shawnchapla-8451** [Azure/azure-functions-python-worker#1281]
I'm using VS Code v1.79.2 on macOS v13.4.1, and am trying to create an Azure Function using the Python programming model v2 as described [here](https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python?pivots=python-mode-decorators#create-an-azure-functions-project). The article indicates that after selecting the folder for the new project, it will prompt for the programming language for the Function, which is where you choose Python V2 model. However, in my case, it skips right to selecting the Python environment, and creates the stubbed out code in the older V1 style. I've installed the Azure Functions extension (v1.11.0) and had tried installing the Azure Tools extension which seems to be a bundle of Azure-related extensions including the one for Functions, but I still seem to be stuck with only the V1 model as an option.

Another difference I noted is that while the screenshot in the Microsoft docs looks like this:

![create-new-project](https://github.com/Azure/azure-functions-python-worker/assets/114088734/1ac78901-ee38-46e8-8922-a9dd2ea9bcc1)

... mine looks like this (no '+' sign and only option is to add a new Azure Function):

![Untitled](https://github.com/Azure/azure-functions-python-worker/assets/114088734/0397b32e-ff5d-49be-ba19-52d0200d8f97)

Wondering if I missed something in the setup or if I don't have the correct version of something?

**Comment by bhagyshricompany** [comment]
Hi @shawnchapla-8451  after click on the function there option coming select your language then choose python v2 model.
<img width="817" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/88379fea-7dfc-477b-91fd-4f2255afd23c">

**Comment by shawnchapla-8451** [comment]
That's the issue ... I don't see the same options in the UI as in your screenshots.

I think I've worked around this by using the ```func``` CLI as described [here](https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-python#create-a-local-function-project):

```
func new -t "Timer Trigger" -n MyFunc --language python -m V2
```

**Comment by bhagyshricompany** [comment]
yes  you can go with that option.install latest version azure core tools
