### ISSUE TITLE
[BUG] Azure function works locally but not when deployed

### ISSUE THREAD

**Issue by levalencia** [Azure/azure-functions-python-worker#1290]
###### Please provide the following:

- Timestamp: 2023-07-20T14:31:57Z 
- Function App name: mooregrantsrestapi 
- Function name(s) (as appropriate):
- Core Tools version:C
- Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667

###### Provide the steps required to reproduce the problem:

I developed an Azure Function iN VS code and it works locally, I can test it in Postman or in the browser.

Just a small example of one of the functions:

```
@app.route(route="CreatePineConeIndex")
def CreatePineConeIndex(req: func.HttpRequest) -> func.HttpResponse:
    """Create a Pinecone index.

    Args:
        req (func.HttpRequest): The HTTP request object.

    Returns:
        func.HttpResponse: The HTTP response object.
    """
    try:
        req_body = req.get_json()
        api_key = req_body.get('api_key')
        environment = req_body.get('environment')
        index_name = req_body.get('indexName')
        dimensions = req_body.get('dimensions', 1536)
        metric = req_body.get('metric', 'dotproduct')

        client = PineconeClient(api_key=api_key, environment=environment)
        client.CreateIndex(index_name, dimension=dimensions, metric=metric)

        return func.HttpResponse("Index Created", status_code=200)
    except Exception as e:
        return func.HttpResponse(f"Could not create Pinecone Index. {str(e)}", status_code=500)

```

I have tested the deploy from VS Code or via Azure Devops pipelines, deployment works without any errors

However the ```Azure Function url /api/CreatePineConeIndex``` shows as 404 however ```localhost/api/CreatePineConeIndex works```

I already did this:
https://learn.microsoft.com/en-us/azure/azure-functions/recover-python-functions?tabs=vscode%2Cbash&pivots=python-mode-decorators#issue-with-deployment

![image](https://github.com/Azure/azure-functions-python-worker/assets/6962857/04b38bb5-ae93-4327-98b8-70dc39808b61)

**Comment by bhagyshricompany** [comment]
thanks for reporting will check and update

**Comment by holger-waschke** [comment]
I have the same problem, I had to redoply a function which always worked because we switched to a app service plan from consumption and it runs locally just fine but on azure side I see in the Application Insight Logs

![image](https://github.com/Azure/azure-functions-python-worker/assets/85643002/1adc2a8c-4983-4c8e-83ab-9b447739ca32)

On the local side it just works fine
![image](https://github.com/Azure/azure-functions-python-worker/assets/85643002/738d5ad1-b1ee-4dac-9185-e867804f8518)

I already set the AzureWebJobsFeatureFlags=EnableWorkerIndexing App setting to enable v2 programming model

**Comment by levalencia** [comment]
any updates here?

**Comment by bhagyshricompany** [comment]
pls share your requirement .txt file

**Comment by levalencia** [comment]
Perhaps I should give more context as I think its related to a local library.

I have created my own custom python library which WHL is published in an Azure Devops artifacts repository.
When publishing I think this library is not available from Azure Functions, so the pip install wont find the package feed.

I am trying the following documentation:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level&pivots=python-mode-decorators#install-local-packages

**Comment by levalencia** [comment]
I am really struggling with this no build option, sometimes it recognizes the functions, sometimes it doesnt!

Sometimes it recognizes functions that were deleted 10 minutes ago.

![image](https://github.com/Azure/azure-functions-python-worker/assets/6962857/fc95345c-db7a-4cd8-a505-a48f0c4462ca)

**Comment by holger-waschke** [comment]
> pls share your requirement .txt file

heres my req.txt

```
tabulate
requests
certifi
pytz
charset-normalizer
datetime
idna
numpy
dataclasses
pandas
python-dateutil
six
zope.interface
azure-functions==1.15.1b1
azure-storage-blob
pybase64
regex
azure-identity
azure-keyvault-secrets
azure-core
prometheus_client
azure-mgmt-subscription
```

**Comment by levalencia** [comment]
> 

is any of those a local python library developed by yourself? or all of them are in pypi repository?

**Comment by holger-waschke** [comment]
> > 
> 
> is any of those a local python library developed by yourself? or all of them are in pypi repository?

we have a custom python package which we install via github. packages pat is a GH action PAT.
shared-libs @ git+https://${PACKAGES_PAT}@github.com/exampel/shared-libs-exampel#egg=shared-libs


We usually use the remote build which works better in most cases if you have to use the nobuild this should work

```
pip3 install --target=".python_packages/lib/site-packages" --upgrade -r requirements.txt
func azure functionapp publish $functionAppName --verbose --python --no-build
```

Or just create a pypi Account and upload your package with twine
twine upload dist/*

**Comment by levalencia** [comment]
I am doing the same commands, but I dont get consistent results, sometimes I can see the functions, sometimes I dont, without changing any code. there is something buggy on the tooling or azure fn..

**Comment by holger-waschke** [comment]
You are running on consumption plan? Theres alot of delay involved, if youre using zip deployment you should check app setting WEBSITE_RUN_FROM_PACKAGE too, this could cause the problem were you see an "old or new" function if this setting gets updated for whatever reason.

But for now let´s focus on the initial issue as it seems to be a real reproducible bug and we´re not able to deploy any python functions in a running state right now.

**Comment by levalencia** [comment]
@bhagyshricompany 

I started from scratch a new Azure Functions project

Requirements.txt file:
```
azure-functions
e61indexingclient
```

on the .venv folder I created a pip.ini file with my feed 

```
[global]
extra-index-url=https://pkgs.dev.azure.com/aaa/bbb/_packaging/ccc/pypi/simple
```

then I did:
```
func azure functionapp publish moorerestapi --no-build
```
I get this result:

```
Getting site publishing info...
Creating archive for current directory...
Skipping build event for functions project (--no-build).
Uploading 6,73 MB [###############################################################################]
Upload completed successfully.
Deployment completed successfully.
Functions in xxxrestapi:
```

No functions found!!!


However, if I press F5 in VS CODE, I get this:
```
 *  Executing task: .venv\Scripts\activate && func host start 

Found Python version 3.10.11 (py).

Azure Functions Core Tools
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667

[2023-07-24T12:13:21.069Z] Worker process started and initialized.

Functions:

        CreatePineConeIndex:  http://localhost:7071/api/CreatePineConeIndex

        DeletePineConeIndex:  http://localhost:7071/api/DeletePineConeIndex

        DeletePineConeVectorsFromIndex:  http://localhost:7071/api/DeletePineConeVectorsFromIndex

        IndexContainer:  http://localhost:7071/api/IndexContainer

        KeywordSearchWithCognitiveSearch:  http://localhost:7071/api/KeywordSearchWithCognitiveSearch

        SimilaritySearch:  http://localhost:7071/api/SimilaritySearch

For detailed output, run func with --verbose flag.

```

And the settings are correct according to the documentation:
![image](https://github.com/Azure/azure-functions-python-worker/assets/6962857/e4d9478b-9dcd-4387-8cdc-9bb91cb4de4e)


On another project I also tried creating new functions without any external or local package dependency, just a bunch of Hello World http triggers, and I noticed that sometimes the deployment works and you can see the triggers on the portal, sometimes the triggers are lost.

**Comment by holger-waschke** [comment]
I did some troubleshooting and the problem was related to incorrect dependencies our custom python package pyproject.toml. In our case we remove dataclasses and changed DateTime to datetime and miraculously the function started showing up. Some meaningful traces in application insights log would have been helpful though..

**Comment by levalencia** [comment]
oh sorry, I misread :(

**Comment by holger-waschke** [comment]
> oh sorry, I misread :(

I had to set the log level to debug in the host.json

```
{
  "version": "2.0",
     "logging": {
        "fileLoggingMode": "debugOnly",
        "logLevel": {
          "default": "Trace",
          "Host.Results": "Trace",
          "Function": "Trace",
          "Host.Aggregator": "Trace"
        },
        "applicationInsights": {
            "samplingSettings": {
              "isEnabled": true,
              "maxTelemetryItemsPerSecond" : 20,
              "evaluationInterval": "01:00:00",
              "initialSamplingPercentage": 100.0,
              "samplingPercentageIncreaseTimeout" : "00:00:01",
              "samplingPercentageDecreaseTimeout" : "00:00:01",
              "minSamplingPercentage": 0.1,
              "maxSamplingPercentage": 100.0,
              "movingAverageRatio": 1.0,
              "excludedTypes" : "Dependency;Event",
              "includedTypes" : "PageView;Trace"
            },
            "enableLiveMetrics": true,
            "enableDependencyTracking": true,
            "enablePerformanceCountersCollection": true,
            "httpAutoCollectionOptions": {
                "enableHttpTriggerExtendedInfoCollection": true,
                "enableW3CDistributedTracing": true,
                "enableResponseHeaderInjection": true
            },
            "snapshotConfiguration": {
                "agentEndpoint": null,
                "captureSnapshotMemoryWeight": 0.5,
                "failedRequestLimit": 3,
                "handleUntrackedExceptions": true,
                "isEnabled": true,
                "isEnabledInDeveloperMode": false,
                "isEnabledWhenProfiling": true,
                "isExceptionSnappointsEnabled": false,
                "isLowPrioritySnapshotUploader": true,
                "maximumCollectionPlanSize": 50,
                "maximumSnapshotsRequired": 3,
                "problemCounterResetInterval": "24:00:00",
                "provideAnonymousTelemetry": true,
                "reconnectInterval": "00:15:00",
                "shadowCopyFolder": null,
                "shareUploaderProcess": true,
                "snapshotInLowPriorityThread": true,
                "snapshotsPerDayLimit": 30,
                "snapshotsPerTenMinutesLimit": 1,
                "tempFolder": null,
                "thresholdForSnapshotting": 1,
                "uploaderProxy": null
            }
        }
    },
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[3.3.0, 4.0.0)"
    }
}

```

and then in the application insights a simple

```
traces
| where cloud_RoleName contains "<insertfunctionappname>"
```

**Comment by levalencia** [comment]
I added some logging and couldnt find any exception, however in the traces I can see:

No job functions found. Try making your job classes and methods public.

**Comment by levalencia** [comment]
> seems issue in pine core client lib will update you on this as soon as possible. Thanks

Can you give us an update please?

**Comment by pdthummar** [comment]
Hi @levalencia,

For custom packages, i would suggest try out following options with remote build,

1) One way is to add the extra-index-url option directly in your requirements.txt file, followed by the packages you want to install from that URL. For example:
```
azure-functions
--extra-index-url=https://pkgs.dev.azure.com/aaa/bbb/_packaging/ccc/pypi/simple
e61indexingclient
```
  This will tell pip to install azure-functions from the default index (PyPI) and e61indexingclient from your custom index.

2) Second way is to set an environment variable in your Azure Function app configuration that specifies the extra-index-url option. For example, you can add a new application setting with the key **PIP_EXTRA_INDEX_URL** and the value. This will tell pip to use your custom index as an additional source for all packages when you publish your function app. You can then keep your requirements.txt file simple, like this:
```
azure-functions
e61indexingclient
```
Ref: [Remote build with extra index URL](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level&pivots=python-mode-configuration#remote-build-with-extra-index-url)

If you are deploying using VScode, try deploying using func azure functionapp publish <APP_NAME> . Thanks

**Comment by levalencia** [comment]
I already gave the information requested what else do you need, and why the ticket was marked as stale

**Comment by bhagyshricompany** [comment]
pls check above comment already commented soln .
