### ISSUE TITLE
remote build VS code issue - ModuleNotFoundError: No module named 'teradatasqlalchemy.dialect

### ISSUE THREAD

**Issue by Sagarthore11** [Azure/azure-functions-python-worker#1299]
Error : Result: Failure Exception: ModuleNotFoundError: No module named 'teradatasqlalchemy.dialect' 

Hello Team,

Please refer the requirement.txt and init.py for reference and to reproduce issue

**init.py**

import logging
from sqlalchemy import create_engine
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
     
    teradata_client = create_engine("teradatasql://username:passwd@server_name")
    logging.info('after teradata')

    name = req.params.get('name')
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get('name')

    if name:
        return func.HttpResponse(f"Hello, {name}. This HTTP triggered function executed successfully.")
    else:
        return func.HttpResponse(
             "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.",
             status_code=200
        )

**requirement.txt**

azure-functions
teradatasqlalchemy

Deployed the above code using vs code in python function app version ~4 and receiving an Failure Exception: ModuleNotFoundError: No module named 'teradatasqlalchemy.dialect' . even though same code is working fine on local

=> Also noticed that adding there is an issue with remote build only I believe
=> Even tried to do the pip install explicitly on kudu site but no luck

Can you please help me with this? You can simply create the test function app, create the sample http trigger, add the code, and reproduce.

Thanks

**Comment by Sagarthore11** [comment]
Hello Team any help would be appreciated

**Comment by bhagyshricompany** [comment]
Thanks for reporting  will check and update you.

**Comment by Sagarthore11** [comment]
@bhagyshricompany Thank you for looking into it. Please feel free to let me know if you need any information from me.

**Comment by Sagarthore11** [comment]
Any update on it please ?

**Comment by bhagyshricompany** [comment]
investigating on it will update once done

**Comment by Sagarthore11** [comment]
@bhagyshricompany are you able to reproduce the issue ?

**Comment by YunchuWang** [comment]
tried repro the code and i got this error both running in a simple python file or function app in local:
<img width="647" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/12449837/1bb59378-a818-40d3-a499-49710af2877b">
<img width="1036" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/12449837/4e26d932-cc05-4d42-9ca5-aacae7ec87a9">

in my .venv, teradatasql is installed
<img width="229" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/12449837/61f8d044-a7df-4e07-97f1-0c6174a4f340">

Look like a sqlalchemy issue

**Comment by Sagarthore11** [comment]
Hello @YunchuWang  for looking into it. But we are not seeing any issue in vs code local. Please refer the below screen shot for the same

![image](https://github.com/Azure/azure-functions-python-worker/assets/118530325/29266c1b-6940-4a12-9010-364faef63799)

**Comment by Sagarthore11** [comment]
@YunchuWang  could you please try once by doing pip intsall in vs code 

pip3 install -r requirements.txt

**Comment by YunchuWang** [comment]
@Sagarthore11 thanks for clarification, i am able to repro this error. As you mentioned right seem an issue with remote build, I downloaded the deployed code and i found it seems an issue with remote build not building this package teradatasqlalchemy properly. In my screenshot you can see all the package module files are missing. 
<img width="543" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/12449837/883c0c37-26c0-45cf-a318-c21999d1f86c">

while building with local dependencies works, (func azure functionapp publish <appname> --build-native-deps)
<img width="632" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/12449837/1b39faec-e9a0-4cba-95bb-f253689df900">

<img width="1247" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/12449837/07da455e-ebd5-4301-ab23-b25997998d34">

Will try if i can check the remote build logs and let you know, meantime you can try local build

**Comment by Sagarthore11** [comment]
Hello @YunchuWang ,

Thank you so much for looking into it and helping.

Yes I tried with the local build and after adding the ENABLE_ORYX_BUILD = false and SCM_DO_BUILD_DURING_DEPLOYMENT = 0 in the configuration setting of function app explicitly when I am deploying using github workflow action and it's working 

**Ask:** we would like to know is there only issue with the remote build ?  

Thank you so much for your help

**Comment by Sagarthore11** [comment]
Hello @YunchuWang 

Thanks for helping into it.

Did you get chance to check the remote build logs?

Thanks

**Comment by Sagarthore11** [comment]
Hello @YunchuWang ,

Do you have any update on it please ?

Thanks

**Comment by Sagarthore11** [comment]
Hello @YunchuWang and Team,

Greetings!!!

Thank you so much for helping us. Do you have any update on it please?

**Comment by YunchuWang** [comment]
@Sagarthore11 Hi Sagarthore, sorry for delay. I was busy with other work past few days and just got a chance. I checked the oxry build log but cant find any err logs related https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html. Will try build with oryx locally to see why this package is not installed properly and let you know soon.

**Comment by Sagarthore11** [comment]
@YunchuWang Thank you for the response and help.

I will wait for your update. Thanks

**Comment by Sagarthore11** [comment]
Hello @YunchuWang ,

Any luck on it please ?

Thanks

**Comment by Sagarthore11** [comment]
Hello @YunchuWang ,

Thanks for helping on it

Any help on it please?

**Comment by YunchuWang** [comment]
@Sagarthore11 Hi Saga, sorry. I tried oyrx build(the same way how remote build builds the packages) and see the same err 
<img width="1703" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/12449837/8582a9c9-0747-415f-bd08-17a8e35341a9">
. This is first time we observe issue like this, thanks for bringing it up. I contacted oyrx team internally for further investigation on this matter and will let you know once they give an update.

**Comment by Sagarthore11** [comment]
Thanks a lot @YunchuWang for helping us on it 👍

**Comment by YunchuWang** [comment]
@Sagarthore11 No problem, a heads up, oyrx team identified this is a known issue which got fixed in https://github.com/microsoft/Oryx/releases/tag/20230403.1 by setting app setting ORYX_DISABLE_PIP_UPGRADE to true then publish with remote build.
![image](https://github.com/Azure/azure-functions-python-worker/assets/12449837/cf0e9652-e23c-4d2b-bd0e-c4ff197e01f1)

Remote build right now uses Oryx Version: 0.2.20230210.1. I will let you know when remote build will release with oyrx 20230403.1

**Comment by Sagarthore11** [comment]
Thanks a lot once again @YunchuWang  for your help.

**Comment by bhagyshricompany** [comment]
hope now  resolved query hence its closing

**Comment by Mikeflames** [comment]
I am facing the same issue , Everything works fine on local but on deployment it throws this error :-
`2025-03-07T09:51:43Z   [Error]   Failed to create engine: No module named 'teradatasqlalchemy.dialect'
2025-03-07T09:51:43Z   [Error]   Teradata data fetch/store error: No module named 'teradatasqlalchemy.dialect'`

I tried changing the enviornment variables as recommended above but that didn't helped :-

![Image](https://github.com/user-attachments/assets/623a81b2-ff0e-4657-80d5-27b140466567)

 @YunchuWang  Can you please see this

**Comment by Sagarthore11** [comment]
Hello @Mikeflames ,

Could you please by adding SCM_DO_BUILD_DURING_DEPLOYMENT and ENABLE_ORYX_BUILD are set to true and see if still it's same problem ?

I am happy to check with on it. if facing the same issue

**Comment by Mikeflames** [comment]
Would Continue the Conversation on Open Issue .
Link :- https://github.com/Azure/azure-functions-python-worker/issues/1648

Yes still the same issue :-

![Image](https://github.com/user-attachments/assets/a298a938-f9e2-445e-8044-4d510c2d01b6)

Env variables :-

![Image](https://github.com/user-attachments/assets/98a8977b-5199-4da7-ad30-71483e030302)

**Comment by Sagarthore11** [comment]
@Mikeflames  I will check the details and will keep you posted on it

**Comment by Mikeflames** [comment]
Hi are there any updates / resolution ? Please let me know 
@YunchuWang
