### ISSUE TITLE
Please provide clear instructions on how to change the port the debugger listens to

### ISSUE THREAD

**Issue by danielniccoli** [Azure/azure-functions-python-worker#1301]
The worker listens on port 9091 by default. How can I change this to a different port?

**Comment by bhagyshricompany** [comment]
{
  "version": "2.0",
  "http": {
    "routePrefix": "api",
    "port": 8080 // Change this to the desired port
  }
}

**Comment by danielniccoli** [comment]
Hi @bhagyshricompany, this is the http port. I was asking about the port to connect the debugger to.

**Comment by bhagyshricompany** [comment]
plz refer this link:
https://github.com/Azure/azure-functions-core-tools/issues/1016

**Comment by danielniccoli** [comment]
@bhagyshricompany I changed the title of this issue. Iit would be helpful if both, this repository and the docs would offer a clear explanation on how to change the port the debug server listens to, from the default 9091 to a custom one. At the moment it is not possible to run multiple azure functions locally side by side. This is required if you have an azure function running FastAPI and a durable function.

**Comment by bhagyshricompany** [comment]
If you are using Visual Studio Code, the process is here:

Open your Azure Functions project in Visual Studio Code.
Open the debug configuration settings. You can do this by clicking on the gear icon in the Debug sidebar and selecting "Add Configuration..."
This will open a launch.json file. Find the configuration for your Azure Functions project.
Add the following entry to the configuration to specify the debugging port:
json
Copy code
"runtimeArgs": [
  "--language-worker",
  "--inspect=6009"
]
Replace 6009 with your desired debugging port.
Save the launch.json file.

if above not works then open a support request on azure portal.

**Comment by danielniccoli** [comment]
@vrdmr if you take the time to respond, why don't you take the time to read the actual question?

That is the port the debugger connects to. If you change that, you also must change the port the local azure functions worker listens to. And that is not VS Code specific. But I already said this earlier...

**Comment by vrdmr** [comment]
@danielniccoli - I recommend this is a Python and VSCode extension-specific issue.

From my understanding, the worker doesn't listen to that port. I changed the port to and it still worked

<img width="560" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/1047040/62c8d13f-4619-4653-bd0a-e52197f1a9e4">
 
<img width="959" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/1047040/584458c4-fc21-48ad-9b92-93e2c552f815">

> That is the port the debugger connects to. If you change that, you also must change the port the local azure functions worker listens to. And that is not VS Code specific. But I already said this earlier... And that's not documented anywhere.

The Python process (azure_functions_worker) starts up, and debugpy (or earlier ptvsd would listen to this process) listens to it. This is set in the [Functions VSCode Extension](https://github.com/microsoft/vscode-azurefunctions/blob/98a968ff1105155b3fbcbb240b191de447a6f11e/src/debug/PythonDebugProvider.ts#L11). The Python extension is then passed this info:
<img width="1400" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/1047040/5f0025b5-73bb-4014-8434-d08d149198d1">

**Comment by danielniccoli** [comment]
@vrdmr Granted, I did not know that the extension does some hidden magic (which is both, good and bad) and it does work, when you use the debugger (<kbd>F5</kbd>) to launch the azure function core tools host. However, technically you're changing the port you're connecting to and the extensions does the rest to automagically make the language worker listen to that port.

But, this does not work if you do not use the VS code debugger. For example, if you run func host start manually, there is no magic that changes the port. And if you use VS code tasks (<kbd>F1</kbd> > Tasks: Run Task > func: host start) this also does not work, and the language worker is started on the default port 9091. I'm using a multi-root workspace with several azure function projects and I'm relying on running the `func: host start` task from each project. Hence, it still is important to know, how to change the **listen** port manually. I'm not the only one with that problem, as you can perhaps see from the other issues linked in this thread. And none of them have a concise explanation how to do that. Everybody is suggesting different solutions, which work differently for different people. That's not helpful.

![image](https://github.com/Azure/azure-functions-python-worker/assets/2971735/59fee3d2-722a-488c-af02-f5f9ef81b2f7)


In both cases, I believe it should be properly documented at https://learn.microsoft.com/en-us/azure/azure-functions/durable/ and https://learn.microsoft.com/en-us/azure/azure-functions/ how to configure the debug server.

**Comment by dannyopts** [comment]
Hi @danielniccoli, 

Hopefully the following is useful :) 

You can run azure functions locally selecting the debug port without vscode using the following:

```
func host start --language-worker -- "-m debugpy --listen 127.0.0.1:5678" --verbose
```

You need to make sure that debugpy is installed in the worker runtime (I ran pip install debugpy). This will start your debugger on port 5678. 

If you are using vscode you can then specify the port in your launch.json to connect the port you specified above (5678)

This removes the magic vscode extension coupling between the task config and the launch config.

my vscode config is below
``` launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Python Functions",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "preLaunchTask": "func: host start"
        }
    ]
}
```

``` tasks.json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "func",
			"label": "func: host start",
			"command": "host start --language-worker -- \"-m debugpy --listen 127.0.0.1:5678\"",
			"problemMatcher": "$func-python-watch",
			"isBackground": true,
			"options": {
				"cwd": "${workspaceFolder}/az_function"
			}
		}
	]
}
```

I I'm not mistaken, Azure function python worker and azure function core tools dont actually do anything explicitly to support debugging, it is the `-m debugpy --listen 127.0.0.1:5678` which runs the debugger. 

Note you can instead add the following to your local.settings.json

```
    "languageWorkers:python:arguments": "-m debugpy --listen 127.0.0.1:5678"
```

You can also specify the language worker args as an env var picked up by the vscode az functions extension:

``` tasks.json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "func: host start",
			"command": "poetry run func host start",
			"problemMatcher": "$func-python-watch",
			"isBackground": true,
			"options": {
				"cwd": "${workspaceFolder}/az_function",
				"env": {"languageWorkers__python__arguments": "-m debugpy --listen 127.0.0.1:5678"}
			}
		}
	]
}
```
("type": "shell" not nessecary here, I was just using this as a way to get debugging azure funcitons while using poetry as build system)

https://github.com/Azure/azure-functions-python-worker/wiki/Debug-Python-Worker-with-Azure-Functions-Host
https://github.com/Azure/azure-functions-host/wiki/Language-Extensibility

**Comment by bhagyshricompany** [comment]
closed

**Comment by danielniccoli** [comment]
@dannyopts, thanks for that.

Is there any way to change the port without installing additional packages? Using the extension that works, so there must be a way to do that.

@bhagyshricompany Why are you so eager to close this? I have not had the time to confirm if Danny's solution worked, and the automation was not going to close it for another 3 days. And my issue was about clear documentation, so everybody benefits. An issue is not documentation. You've done nothing but actively pushing back on improvement, which is baffling.

**Comment by dannyopts** [comment]
If you are running from the vscode debugger then it is my understanding that debugpy is added to your python path by the extension, so the tasks example i have doesn’t require you to install anything additional.
    On Tuesday, 5 September 2023, 08:55:54 BST, Daniel Niccoli ***@***.***> wrote:  
 
 


@dannyopts, thanks for that.

Is there any way to change the port without installing additional packages? Using the extension that works, so there must be a way to do that.

@bhagyshricompany Why are you so eager to close this? I have not had the time to confirm if Danny's solution worked, and the automation was not going to close it for another 3 days. And my issue was about clear documentation, so everybody benefits. An issue is not documentation. You've done nothing but actively pushing back on improvement, which is baffling.

**Comment by victorgolda** [comment]
For me sometimes it does work, and sometimes it doesn't:
![image](https://github.com/Azure/azure-functions-python-worker/assets/7671373/46192bb4-fba5-4a1e-842d-95e833688a2f)

Few seconds later:
![image](https://github.com/Azure/azure-functions-python-worker/assets/7671373/782a134b-891a-4881-9a7e-19f6d9d72876)

Also, because the hot reload doesn't work, the function just dies and leads to the case of not working just like I show in the images.



Here is my current config:


`{
    "version": "0.2.0",
    "configurations": [
        {
          "name": "PYTHON: Attach to Python Functions",
          "type": "python",
          "request": "attach",
          "port": 5679,
          "preLaunchTask": "func: host start"
      }
    ]
}`

`{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "func",
			"label": "func: host start",
			"command": "host start --language-worker -- \"-m debugpy --listen 127.0.0.1:5679\"",
			"problemMatcher": "$func-python-watch",
			"isBackground": true,
			"dependsOn": "pip install (functions)"
		},
		{
			"label": "pip install (functions)",
			"type": "shell",
			"osx": {
				"command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
			},
			"windows": {
				"command": "${config:azureFunctions.pythonVenv}\\Scripts\\python -m pip install -r requirements.txt"
			},
			"linux": {
				"command": "${config:azureFunctions.pythonVenv}/bin/python -m pip install -r requirements.txt"
			},
			"problemMatcher": []
		}
	]
}`

**Comment by Falven** [comment]
It says it switches the port when you do:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "func",
			"label": "func: host start",
			"command": "host start -p 7072 --language-worker -- \"-m debugpy --listen 127.0.0.1:9092\"",
			"problemMatcher": "$func-python-watch",
			"isBackground": true
		}
	]
}
```

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Python Functions",
            "type": "python",
            "request": "attach",
            "port": 9092,
            "preLaunchTask": "func: host start"
        }
    ]
}
```

And while I am able to send requests in the new port, the debugger doesn't actually attach. Also, you still get address in use errors if you try to run another azure function on another port.
