### ISSUE TITLE
Aiohttp requests timing out in coroutines

### ISSUE THREAD

**Issue by kmtechsupport** [Azure/azure-functions-python-worker#1311]
Hi team, 

I am experiencing an issue where I am using asyncio.gather to await roughly 100 coroutines. These co routines do a simple api and then return a data frame. My code runs perfectly fine on my local environment but in my azure function about 10% of my coroutines return timeout errors (which I am using the default ClientSession() timeout of 5 minutes). These co routines are quick and only take about 10 seconds each. 

The code for my function performing the actual https request is something like the following (this function is used in the coroutines)
```
async def GetData(input, session):

    requestPayload = {
        'name': input
    }

    requestData = json.dumps(requestPayload)
    async with session.post(ENDPOINT, data=requestData) as resp:
        return await resp.json()  
```
Any advice or links to useful resources would be much appreciated.

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls share all the repro steps and req.txt file

**Comment by YunchuWang** [comment]
@kmtechsupport Hi, please share your app name and invocation id, sku type, etc. This could be worker memory overloaded or network congestion, etc. With more details, we can take a closer look.

**Comment by kmtechsupport** [comment]
> @kmtechsupport Hi, please share your app name and invocation id, sku type, etc. This could be worker memory overloaded or network congestion, etc. With more details, we can take a closer look.

App name : https://getsentinelthreats.azurewebsites.net (this is the sandbox app being used for testing)
Invocation Id of one of the failed instances: 4446776e217755dfcb12b5943c9bd841

Let me know if you need more info

**Comment by kmtechsupport** [comment]
> Thanks for reporting pls share all the repro steps and req.txt file

Requirements: 

```
azure-functions
azure-functions-durable
pandas
requests
numpy
aiohttp
asyncio
xmltodict
```

Steps to reproduce is something like the following:

```
async def GetData(input, session):

    requestPayload = {
        'name': input
    }

    requestData = json.dumps(requestPayload)
    async with session.post(ENDPOINT, data=requestData) as resp:
        return await resp.json()

async def main(mytimer: func.TimerRequest, starter: str) -> None:
    async with ClientSession() as session:
            try:
                backupData = await asyncio.gather(
                *[
                        GetData(input, session)
                        for item in items
                    ],
                    return_exceptions=True
                )
            except Exception as e:
                logging.info(repr(e))

```

**Comment by kmtechsupport** [comment]
> > @kmtechsupport Hi, please share your app name and invocation id, sku type, etc. This could be worker memory overloaded or network congestion, etc. With more details, we can take a closer look.
> 
> App name : https://getsentinelthreats.azurewebsites.net (this is the sandbox app being used for testing) Invocation Id of one of the failed instances: 4446776e217755dfcb12b5943c9bd841
> 
> Let me know if you need more info

Not sure if it's worth mentioning but the issue appears pretty much as soon as the coroutines exceeds 5. But is inconsistent so sometimes I'll get 50 successes back sometimes 10. 

Another thing maybe worth mentioning is I have also tried changing this to a durable function with the orchestrator spawning these coroutines as activity and functions and it exhibits the exact same behavior. At a certain point the activity functions simply start timing out.

I have also tried chunking the input by not spawning all 100 coroutines at once but rather processing the array in chunks of 5. I have tried this method in both the single script and the durable function methods and they both do not fix the issue.

**Comment by kmtechsupport** [comment]
@bhagyshricompany  any luck with this one?

**Comment by kmtechsupport** [comment]
@bhagyshricompany will this be looked into or do I need to explore other solutions?

**Comment by bhagyshricompany** [comment]
@vrdmr  pls comment.

**Comment by YunchuWang** [comment]
sorry for late reply. Taking a look now.
