### ISSUE TITLE
[BUG] Custom dimensions not showing in App Insights

### ISSUE THREAD

**Issue by wiseskus** [Azure/azure-functions-python-worker#1327]
Trying to log custom dimensions from an http trigger functions.

import logging

logging.basicConfig(level=logging.DEBUG)

@app.route(route="test", methods=['GET'])
def test(req: func.HttpRequest, context: func.Context) -> func.HttpResponse:

    properties = {'custom_dimensions': {
        'key_1': 'value_1', 'key_2': 'value_2'}
}

    logging.info(
        'test',
        extra=properties
    )

    return func.HttpResponse(
        "All good",
        mimetype="application/json",
        status_code=200
    )

Here are the custom dimensions shown in App Insight for this code:

customDimensions {"HostInstanceId":"e5121470-c5a1-4596-84fb-72879f1e9185","InvocationId":"25e10fbc-0683-480e-b32c-717815d3a9ab","LogLevel":"Information","ProcessId":"61","Category":"Function.test.User"}

Using

properties = {'key_1': 'value_1', 'key_2': 'value_2'}

doesn't work either.

Thanks

**Comment by pdthummar** [comment]
@wiseskus. Thanks for creating issue. To activate debug logging, set PYTHON_ENABLE_DEBUG_LOGGING=1, which triggers debug-level logging. If this setting is absent or set to 0, the Python worker will transmit only information and higher-level logs to the Functions host. Utilize this configuration for debugging or tracing your Python function executions. For additional information, please refer the documentation below.

Ref doc: [python_enable_debug_logging](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#python_enable_debug_logging), [configure-log-levels](https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-log-levels)

**Comment by wiseskus** [comment]
Hi,
Where/how do I "activate debug logging, set PYTHON_ENABLE_DEBUG_LOGGING=1"?
Thanks,
JD
________________________________

**Comment by pdthummar** [comment]
@wiseskus This [Doc](https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings?source=recommendations&tabs=portal) will help you for setting up the App setting. Thanks
