### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by kowalczyk-p** [Azure/azure-functions-python-worker#1347]
python version: >=3.7, <= 3.11
function version: 4
`Starting Host (HostId=redacted, InstanceId=18e5b7f9-c832-4b7f-abe4-8c27109f3c84, Version=4.27.5.5, ProcessId=1937, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=~4)`

### Contents of the requirements.txt file:
```
azure-functions
msal
```

On my computer function runs fine but after deployment there are errors:

```
Host initialized (201ms)
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/err/mod.rs:790:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have no clue what I'm doing wrong, it looks like some dependencies are missing.

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls share the all repro steps with your  sample code.invocation id,timestamp,region etc.
