### ISSUE TITLE
Do not expose protobuf to the bindings

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#135]
Tracking issue to investigate decoupling azure.functions and azure.functions.worker.

Use type annotations if the function expects a custom type such as 
singnalRConnectionInfo which is not a basic type like: string or byte[] or rich binding type defined in azure-functions-python-library

```
def main(req: func.HttpRequest, connectionInfo: signalRConnectionInfo) -> func.HttpResponse:
    return func.HttpResponse(connectionInfo)
```

Python worker needs to convert the input data sent by the functions host to the type requested by the function. This is the goal of issue https://github.com/Azure/azure-functions-python-worker/issues/135 as well.

Here is the flow for the above example:
- User function includes reference to the library where `signalRConnectionInfo`  is defined
- On function invocation, host sends input data as String/Json
- Python worker examines the type annotation and converts input data to type `signalRConnectionInfo`
- If type conversion fails, throw error

**Comment by asavaritayal** [comment]
Brainstorming item, not currently scheduled. @pragnagopa to update objective and problem statement.

**Comment by pragnagopa** [comment]
https://github.com/Azure/azure-functions-host/issues/3140

**Comment by maiqbal11** [comment]
@pragnagopa, @asavaritayal, reviving this old thread because I've got some time on my hands. Work on exposing generic data types is almost finished (https://github.com/Azure/azure-functions-python-worker/issues/66). Once that is checked in, we can potentially get rid of `azure.functions` altogether + the binding specific code in the language worker. Wanted to lay out some top-of-mind benefits and drawbacks.

Benefits:

1. Having some rich data types helps with getting users started instead of them having to deal with raw data in the form of bytes, strings etc.
2. This would be a big breaking change and would require re-education about how to use these types. 
3. It should also help with intellisense but that's a work in progress. 

Drawbacks:

1. I see the comments at Azure/azure-functions-host#3140 and it makes sense that we might not want to be in the business of owning these libraries and maintaining them. We've been bitten by this before: https://github.com/Azure/azure-functions-python-worker/issues/269. Arguably, if this had been handled by the appropriate SDK, we wouldn't have to worry about it. This adds engineering complexity as we need to maintain/service a different code base - aspects of which are not in our control if something about the format of the messages changes, for example.

A middle way might be just to leave things as they are right now and not expand the set of rich data types that we provide. We'd still maintain the ones we have but that's been okay so far. 

Lemme know what you think!

**Comment by pragnagopa** [comment]
Removing azure.functions reference from the worker and loading them as out-out-tree bindings following the guidance #398 will allow users to update azure.functions without requiring a python worker release.

@elprans - Can you please look into this?

@asavaritayal  - This will establish the right pattern where loading bindings is not tied to the worker. Please triage and assign appropriate priority.

**Comment by pragnagopa** [comment]
@elprans - can you give an estimate how large/small this workitem is?

**Comment by elprans** [comment]
@pragnagopa With the new binding plugin support we can move the concrete binding implementation out of the worker to `azure.functions`

**Comment by elprans** [comment]
That said, we need to figure out the dependency on protobuf definitions.  Especially in the HTTP case.

**Comment by pragnagopa** [comment]
Minor version updates to azure-functions-python-library will not have breaking changes. Python worker is the layer that is exposed to protobuf. I do not anticipate any breaking changes in the current version of protobuf. Even if protobuf introduces breaking changes, worker will be able to handle  them.

**Comment by elprans** [comment]
Bindings are also exposed to the protobuf.  Primarily because of how the HTTP binding works.  Are you saying we should create an abstraction over the protobuf and have the binding implementations use that instead?  I'm a bit confused by this, to be honest.

**Comment by pragnagopa** [comment]
> Are you saying we should create an abstraction over the protobuf and have the binding implementations use that instead?

That is correct. Protobuf should not be exposed to the user. This is an internal implementation details. azure.functions should have an abstraction for http bindings

**Comment by elprans** [comment]
OK, then I think we need to discuss the "Binding API" interface as the way to describe the data sent by the Functions Host in all cases.

**Comment by pragnagopa** [comment]
Apologies if that was not clear earlier. Types defined in azure.functions package should not rely on proto messages. Only worker needs to be aware of protobuf. For any breaking changes, only worker needs to be updated.

Given this context, can you please give an estimate on this work item?

**Comment by elprans** [comment]
I think we need to discuss this a bit more.  Let's put this on the agenda for the next meeting. \cc @asavaritayal

**Comment by pragnagopa** [comment]
@maiqbal11 - Let me know if you need any clarifications for this issue. We need to investigate and make sure addressing this issue does not have any breaking changes.

**Comment by pragnagopa** [comment]
continuing the discussion from #409 
This issue is a GA requirement because, we need to ensure that static reference of current version of azure.functions does not interfere with loading future versions of the same package.

@elprans - Please let me know what further clarifications you need to make progress on this issue.

**Comment by pragnagopa** [comment]
cc: @maiqbal11 
Also, updated the title to reflect the change this issue is driving. Removing azure.functions reference from the worker completely will break existing apps.  Worker needs to be updated to load azure.functions from a well known location to fall back to a default version if the package is not found in [ExtensionBundle](https://github.com/Azure/azure-functions-extension-bundles/tree/master/src/Microsoft.Azure.Functions.ExtensionBundle)
well known location

**Comment by pragnagopa** [comment]
@elprans - ping!

**Comment by elprans** [comment]
@pragnagopa I'm afraid I don't fully understand what "loading from a well known location" means in this case.  If you mean setting `PYTHONPATH` to an appropriate setting, then this does not require any code changes on the worker side, only core-tools adjustments.

**Comment by pragnagopa** [comment]
There are two parts to this issue:
1. Remove any direct dependency on protobuf for any types defined in azure.functions
2. Load azure.functions similar to any other custom binding library. 

   a.  Removing dependency from the worker will be breaking change

   b.  Removing reference from python worker and updating core tools to add azure.functions to pythonpath is also breaking change as this would force republishing existing apps and only fixes the apps that are published via core tools.

Expanding on 2.b (cc @soninaren)
-  [Extension Bundles](https://github.com/Azure/azure-functions-extension-bundles) is a new feature that we just released. This feature will be bridging the gap between C# extension libraries that users bring in using `func extentsions install` and python bindings such as the one defined in `azure.functions`

- Next planned work item for extension bundles will package each extension with all the supported languages. For example, current extension bundle version `[1.*, 2.0.0)` see here for [sample host.json with bundles configuration](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python#reference-bindings)  will include python package: `azure.functions`.  This will ensure supported versions for bindings in each language for a given extension bundle version.

- The ask for this issue is to update the worker so that we can configure the path where to load azure.functions.

**Comment by elprans** [comment]
> The ask for this issue is to update the worker so that we can configure the path where to load azure.functions.

So, `PYTHONPATH`?

**Comment by pragnagopa** [comment]
> So, PYTHONPATH?

Yes, if you recommend updating python path from within the worker and not the tooling.

**Comment by elprans** [comment]
Generally, updating `PYTHONPATH` from within a running Python app is considered bad style.  The path should be set in the tooling.

**Comment by pragnagopa** [comment]
So what are the options? As I explained earlier, going forward extension bundles will include bindings for each language and they will be present in Azure. We need the worker to be able to discover libraries from the extension bundle path.

**Comment by elprans** [comment]
Well, the CLI already sets `PYTHONPATH`.  Why can't we update code in `StartHostAction.cs` to do the bundle path discovery as well?

**Comment by pragnagopa** [comment]
@maiqbal11 / @ankitkumarr  -  Is it possible to update PYTHONPATH to load azure.functions withtout breaking existing apps?

@elprans  - while we discuss the approach where to load azure.functions from,  can you start looking into removing any direct dependency on protobuf for any types defined in azure.functions? Feel free to open a separate issues if needed.

**Comment by pragnagopa** [comment]
Opened new issue https://github.com/Azure/azure-functions-python-worker/issues/434 to track best approach to load azure.functions.

**Comment by pragnagopa** [comment]
From @elprans 
> The crux of the issue here is how to replace the RpcHttp protobuf.

Can you explain what is the dependency for the types defined in : [_http.py](https://github.com/Azure/azure-functions-python-library/blob/master/azure/functions/_http.py) on protobuf?

**Comment by elprans** [comment]
@pragnagopa HTTP request is a structured type that contains headers and other metadata, *and* a possibly binary blob of data as the body.  The protobuf encodes that typed information nicely.  If we are hiding the protobuf, then what is the replacement here?  We cannot use JSON since the body data can be binary (and base64-encoding it is inefficient).

**Comment by pragnagopa** [comment]
oK. I understand now.  [_http.py](https://github.com/Azure/azure-functions-python-library/blob/master/azure/functions/_http.py) is abstraction that is needed and we have that already.

Protobuf is still python worker dependency. Worker converts RpcHttp to types defined in _http.py.  Protobuf is a contract between host and the worker.  Minor version updates of the protobuf will not be breaking.  

There is no action item for this issue. I will go ahead and close it. If you disagree  or you need further clarification please reopen.
