### ISSUE TITLE
[BUG] Az Function python library doesnt create eventhub function: `Object reference not set to an instance of an object.`

### ISSUE THREAD

**Issue by BillmanH** [Azure/azure-functions-python-worker#1351]
###### Please provide the following:

- Timestamp: 11.11.2023
- Function App name: Azure Event Hub trigger
- new VSC, Conda updated, fresh downloads all around.

- Core Tools version: 4.0.5455

### Repro steps
1. `func init az-functions`
2. `func new --template "Azure Event Hub" --name myFunction`

To verify that everything else is configured correctly: 
1. `func new --template "Timer trigger" --name myFunction`
2. function creates successfully. No issue. 

The `func` tools is able to create the HTTP function but not the EventHub function. Making it impossible to work with Azure EventHub Triggers. 
 
### Expected behavior
Function is created. 

### Actual behavior
`Object reference not set to an instance of an object.`
No function is created

### Known workarounds
If you can find an example of the eventhub function, you can copy and paste it manually.

**Comment by bhagyshricompany** [comment]
Thanks for  reporting .Will check and update.Thanks

**Comment by hallvictoria** [comment]
Hi @BillmanH, could you please provide a screenshot of your app code and the full error logs that show up?
Thanks

**Comment by pyrabbit** [comment]
I am also seeing this issue with Durable Functions orchestrator. Verbose logging doesn't return any additional information outside of what was originally reported. 

Func CLI Version: 4.0.5455

**Comment by BillmanH** [comment]
@hallvictoria , sure. Here you go:
![image](https://github.com/Azure/azure-functions-python-worker/assets/10108711/c4d2b6a9-83fa-4c07-98a1-e7ff2d38e5ad)

**Comment by BillmanH** [comment]
Not really any logs to call out.

**Comment by BillmanH** [comment]
I'm wondering if the core tools supports the event hub template. It says that it does. 

Running the command: 
`func templates list`

Returns: 
```
Python Templates:
  Azure Blob Storage trigger
  Azure Cosmos DB trigger
  Durable Functions activity
  Durable Functions entity
  Durable Functions HTTP starter
  Durable Functions orchestrator
  Azure Event Grid trigger
  **Azure Event Hub trigger**
  HTTP trigger
  Kafka output
  Kafka trigger
  Azure Queue Storage trigger
  RabbitMQ trigger
  Azure Service Bus Queue trigger
  Azure Service Bus Topic trigger
  SQL Input Binding
  SQL Output Binding
  Timer trigger
```

However, this could just be a static list somewhere, not a list of template folders. `Object reference not set to an instance of an object`  could mean that it's looking for the EventHub template, but it doesn't exist in the tool. This would be bad. Hopefully MSFT can confirm. It could also mean that MSFT has removed support for the Python Event Hub Trigger, but didn't update this static list. I'm speculating here. 

@hallvictoria , can you confirm that this trigger is supported?

**Comment by hallvictoria** [comment]
Hi @BillmanH, yes, the Event Hub trigger is supported, and the template name is `Azure Event Hub trigger`. Please try running `func new --template "Azure Event Hub trigger" --name myFunction` and let me know if the same issue occurs.

Thanks

**Comment by BillmanH** [comment]
![image](https://github.com/Azure/azure-functions-python-worker/assets/10108711/753a4711-3b1c-4a4e-9ff9-6542434f94c7)

Same issue.

**Comment by hallvictoria** [comment]
Thanks for your patience. One last thing -- does `func new --template "EventHub trigger" --name myFunction` work for you?

**Comment by BillmanH** [comment]
It did, 
![image](https://github.com/Azure/azure-functions-python-worker/assets/10108711/3ee2fe41-c104-4eb7-91d7-77a16f4c39ad)

Can you confirm for the Durable function as well? Is there some way to know the proper text string that generates the function? Or can you update the list so that a user can know what the expected text field will be? There may be other cases where the list in `func templates list` differs from the string expected by the `--template` argument.

**Comment by hallvictoria** [comment]
Templates for Durable functions aren't supported at this moment. I agree, the list provided from `func templates list` is outdated and confusing. We'll look into a fix that will make this clearer and easier to use.

**Comment by hallvictoria** [comment]
Linking relevant Core Tools issues
Unsupported templates: Azure/azure-functions-core-tools#3529
Inconsistent naming: Azure/azure-functions-core-tools#3530

**Comment by BillmanH** [comment]
As there are other issues opened, I can close this one. Thanks @hallvictoria for the fix and the workaround. I'm unblocked.
