### ISSUE TITLE
Support for Anaconda environment

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#136]
Existing Anaconda environment with Python version 3.5/3.6
BYOC/BYOF instructions fail unless Anaconda path is removed.

While using the BYOF functions tools, the tools does not support a conda environment by itself. Supports only virtual environments. Conda support is useful for machine learning scenarios and in general python environment support.

(minor) This solution requires the user to use virtualenv and does not support Conda (from Andy's notes)

**Comment by asavaritayal** [comment]
@1st1 @elprans Is this a limitation of the language worker or core tools?

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-core-tools#509
