### ISSUE TITLE
HttpTrigger local func start keys issue

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#137]
HttpTrigger local func start gives the following error - anonymous function vs function keys – there was issue in the Kudu console. 

Tried to use anonymous functions without keys and deployed using BYOF - the trigger did not work in azure.
Worked locally. Interchanging with and without keys caused errors in Kudu. - This was reproducible during serverless openhack.

**Comment by asavaritayal** [comment]
@priyaananthasankar can you provide the repro steps? Also, what version of the CLI were you using?

**Comment by asavaritayal** [comment]
I can't repro this on the latest. I'll close this but let me know if you are still seeing issues.

**Comment by priyaananthasankar** [comment]
Reopening this issue as it is observed even today. A simple get method with func new works locally, but gives 401 unauthorized after func core tools deploy.

**Comment by mcollier** [comment]
I followed the instructions at https://github.com/Azure/azure-functions-python-worker/wiki/Create-Function-(CLI).  I could get the function to work locally at http://localhost:7071/api/HelloCherry.  After publishing it to Azure, I could not get the function to work.  I initially received an HTTP 401 response.  I changed the 'authLevel' in function.json to 'anonymous' and republished.  That resulted in an HTTP 500 error.

I'm using Python version 3.6.5 and Azure Function Core Tools version 2.0.1-beta.28.

**Comment by asavaritayal** [comment]
@mcollier  Can you share your `function.json` file, app name and the endpoint you're calling to invoke your function?

**Comment by mcollier** [comment]
App name: https://mcollier-func-py.azurewebsites.net/
Function name: HelloCherry

I've tried calling via https://mcollier-func-py.azurewebsites.net/api/HelloCherry and https://mcollier-func-py.azurewebsites.net/HelloCherry.

The function.json file I used is as follows:
```
{
  "scriptFile": "__init__.py",
  "disabled": false,
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

I've tried changing the authLevel to 'anonymous'.  That resulted in an HTTP 500 error.

**Comment by asavaritayal** [comment]
Have you tried the below? 

![funckey](https://user-images.githubusercontent.com/8435148/42238323-5118529e-7eb5-11e8-9cfe-b247ca69d08e.gif)

**Comment by asavaritayal** [comment]
Quick update - @mcollier and I synced offline. The issue is not a `404` but a `500`. 

There is no repro on our end but I'll investigate and come back here.

**Comment by asavaritayal** [comment]
@pragnagopa can you investigate this?

**Comment by asavaritayal** [comment]
The issue is caused due to a breaking change in the v2 runtime (preview). Deployments are in progress. We'll send an update to this thread once the release is done.

**Comment by asavaritayal** [comment]
This should now be resolved. @priyaananthasankar and @mcollier  go ahead and try again. 

Please make sure that you upgrade the Azure Functions Core Tools to version `2.0.1-beta.33`

If you're not starting over from scratch, check that the `requirements.txt` file contains the following list of dependencies:

```
azure-functions==1.0.0a1
azure-functions-worker==1.0.0a3
grpcio==1.12.1
grpcio-tools==1.12.1
protobuf==3.6.0
six==1.11.0
```
