### ISSUE TITLE
[BUG] cosmos trigger v2 decorative model without functions.json

### ISSUE THREAD

**Issue by vijaystroup** [Azure/azure-functions-python-worker#1386]
### Investigative information

- Timestamp: 2024-01-01T22:56:18.107Z
- Function App name: local
- Function name(s) (as appropriate): cosmos_db_trigger
- Core Tools version: 4.0.5455

### Repro steps

```py
import logging
import os
import azure.functions as func

bp = func.Blueprint()

@bp.cosmos_db_trigger(
    arg_name='documents',
    connection='COSMOS_CONNECTION_STRING',
    database_name=os.environ['DB_NAME'],
    container_name=os.environ['DB_CONTAINER']
)
def cosmos_trigger(documents: func.DocumentList) -> str:
    if documents:
        logging.info('Document id: %s', documents[0]['id'])
```

### Expected behavior

Upon insertion of a new document into the container:
```
Document id: xxxxxxxxxxxxxxxx
```

### Actual behavior

Error on startup:
```
The 'cosmos_trigger' function is in error: Unable to configure binding 'documents' of type 'cosmosDBTrigger'. This may indicate invalid function.json properties. Can't figure out which ctor to call.
```

### Known workarounds

Not tested but from looking at other issues, perhaps adding the binding connection information in a `functions.json` file for the specific function would yield the correct results, but other documentation suggests functions.json is for the v1 programming model, not v2.

### Contents of the requirements.txt file:

```
azure-functions
requests
azure-storage-blob
pyjwt[crypto]
azure-servicebus
azure-cosmos
```

**Comment by bhagyshricompany** [comment]
Thanks for reporting will check and update.share the  func invocationid,timestamp ,region etc.

**Comment by VijayStroup** [comment]
The error was not caused by an invocation of the function.
Upon starting the dev server: `func start`, all my functions are listed except this cosmos_trigger.
Then shortly after the list without any invocations to any of the functions it logs an error as indicated in the Actual behavior section.

**Comment by bhagyshricompany** [comment]
can you share which doc you use..

**Comment by VijayStroup** [comment]
> can you share which doc you use..

https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-trigger?tabs=python-v2%2Cisolated-process%2Cextensionv4%2Cnodejs-v4&pivots=programming-language-python

**Comment by bhagyshricompany** [comment]
Hi @vijaystroup  please use the blueprint for your function app.
I  checked and its working   fine.
<img width="439" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/7d2a9fd7-cfbd-4100-978f-cf002b85bd9c">
please see the below code.
<img width="737" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/7c47e88d-6caf-4d92-82b3-3cb23d896498">
<img width="891" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/8de29641-fe81-4f88-8730-fc72c91d91b5">
.

**Comment by vijaystroup** [comment]
Still getting the same error:
```py
import logging
import os
import azure.functions as func

bp = func.Blueprint()


@bp.cosmos_db_trigger(
    arg_name='documents',
    connection='COSMOS_CONNECTION_STRING',
    database_name=os.environ['COSMOS_DATABASE'],
    container_name=os.environ['COSMOS_CONTAINER'],
    create_lease_container_if_not_exists=True,
    lease_container_name='lease',
)
def cosmos_trigger(documents: func.DocumentList) -> str:
    if documents:
        logging.info('Document id: %s', documents[0]['id'])
```

The documentation for lase containers located [here](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-functions) do not show an example of "the lease container automatically with the Azure Functions trigger".
I'm not 100% sure how the lease container works besides keeping the db in sync with multiple instances of functions, so perhaps I am not setting something up correctly.
It should be noted, the code above is the only thing that I changed, I did not manually create a lease container as from the docs it said it would automatically create one.

**Comment by bhagyshricompany** [comment]
please follow the doc as in local setting file also have to be maintain   "LeaseContainerName":"leases",
"CreateLeaseContainerIfNotExists" :true
 this two props.
Try to add the missing details in your local.settings.json file like cosmos DB connection string and the database name and the collection name which you are referring.then it works.

**Comment by vijaystroup** [comment]
Still same error on start up: `The 'cosmos_trigger' function is in error: Unable to configure binding 'documents' of type 'cosmosDBTrigger'. This may indicate invalid function.json properties. Can't figure out which ctor to call.`

I do not have to have manually created a lease container correct?
![image](https://github.com/Azure/azure-functions-python-worker/assets/38572582/7d309ee3-6527-4e8e-bef3-3ed2d64fa72b)
Here I make sure the db, container, and lease names are actually filled in and I do have COSMOS_CONNECTION_STRING set in my local.settings.json file.

The docs indicate that only the `connection` argument needs the key name whereas the other arguments need the actual value rather than the key name.

**Comment by hallvictoria** [comment]
Hi @vijaystroup  

No, you don't have to manually create a lease container. `create_lease_container_if_not_exists=True` will handle that for you. You can verify that the container exists by checking your CosmosDB database. Also, if one of your resources doesn't exist a 404 error will be thrown at start up.

In your host.json file, what `version` for `extensionBundle` are you using? I was able to replicate the issue using `[3.*, 4.0.0)`, but the function worked properly with `[4.*, 5.0.0)`. If you aren't using `[4.*, 5.0.0)`, can you try changing to that and see if the issue still occurs? 
<img width="554" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/59299039/8bdb61b3-2c77-4611-ab17-7c3dd9123f27">

**Comment by vijaystroup** [comment]
> Hi @vijaystroup
> 
> No, you don't have to manually create a lease container. `create_lease_container_if_not_exists=True` will handle that for you. You can verify that the container exists by checking your CosmosDB database. Also, if one of your resources doesn't exist a 404 error will be thrown at start up.
> 
> In your host.json file, what `version` for `extensionBundle` are you using? I was able to replicate the issue using `[3.*, 4.0.0)`, but the function worked properly with `[4.*, 5.0.0)`. If you aren't using `[4.*, 5.0.0)`, can you try changing to that and see if the issue still occurs? <img alt="image" width="554" src="https://private-user-images.githubusercontent.com/59299039/298697093-8bdb61b3-2c77-4611-ab17-7c3dd9123f27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjY1ODgsIm5iZiI6MTcwNjAyNjI4OCwicGF0aCI6Ii81OTI5OTAzOS8yOTg2OTcwOTMtOGJkYjYxYjMtMmM3Ny00NjExLWFiMTctN2MzZGQ5MTIzZjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE2MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNjJkY2M5ODU1NmI5NDE0NmZhZWMxZGMxZjU4MGE2ZTRlMWFiYmRiYTU0MzdjN2E3ZjI0MmE1MTBmMWVhNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uQKco3qTowXMfwqIFO5UrJsCSGuW6QgLZOJQUaMtHjY">

That was it! Thank you.
