### ISSUE TITLE
BYOC - No support with ACS. Have to push image to public docker hub (if using custom docker image approach for deployment) 

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#139]
This was the case during April last week. There was no support to upload own container into ACS and get the functions app to refer. If this is not the case today, it can be closed. Raised issue for tracking.

**Comment by asavaritayal** [comment]
@Jen7714 @dariagrigoriu

**Comment by asavaritayal** [comment]
Closing as this was identified as not a Python issue.
