### ISSUE TITLE
Setup DevOps to publish to PyPI

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#141]
When generating azure.functions and azure.functions.worker packages, the version needs to match the release tag. We need something similar to [this](https://github.com/Azure/azure-functions-java-worker/blob/dev/appveyor.yml#L28) when generating packages.

**Comment by elprans** [comment]
If the goal is to have git serve as a version tag source, then the recommended way in Python is to use `setuptools_scm`.

**Comment by pragnagopa** [comment]
We do want to control package versions from the code. Here is the flow for nodejs worker updates.
- Version for the pacakge is defined in [package.json](https://github.com/Azure/azure-functions-nodejs-worker/blob/dev/package.json)
- Once we are ready to release, 
  - Update version on package.json
  - Merge dev to master
  - Create a tag with the same name as version in package.json
  - Publish nuget package from the tagged build. This will look like Microsoft.Azure.Functions.NodeJsWorker 1.0.0-beta1

What is the equivalent for package.json for PyPI?

**Comment by elprans** [comment]
> What is the equivalent for package.json for PyPI?

``setup.py``

**Comment by pragnagopa** [comment]
Assuming the similar flow works here too. We would update package versions in setup.py and create tags for each release that match the package version

**Comment by elprans** [comment]
Sounds good.

**Comment by pragnagopa** [comment]
Moving this to next milestone. We need to address this as part of repos split

**Comment by asavaritayal** [comment]
Need instructions on how to publish to PyPI. @elprans

**Comment by paulbatum** [comment]
@pragnagopa is this work item still relevant?

**Comment by elprans** [comment]
@pragnagopa Can you describe the staging/production scenario please?

**Comment by pragnagopa** [comment]
Functions V2 is GA, but language worker extensibility model is still in preview. If there are breaking changes in RPC layer, we need to be able to test end to end with staged packages in PyPI before moving them to production

**Comment by pragnagopa** [comment]
Ahh !  Right.
- For production, adding a release tag should push to pypi
- For staging, can we make this publish step manual? Build should produce artifacts on every commit to the master but publishing to test.pypi is a manual action via Deploy

**Comment by Hazhzeng** [comment]
This issue is fixed by a recent PR
https://github.com/Azure/azure-functions-python-worker/pull/663

From now on, we first push a tag related to the worker version (e.g. 1.2.1).
Then when a host release, we can push a new release branch `release/2.0.xxxxx` or `release/3.0.xxxxx` which will generate a Python Worker NuGet package matching the version of the host.

The updated **Release Instruction** wiki is [here](https://github.com/Azure/azure-functions-python-worker/wiki/Release-Instructions).
