### ISSUE TITLE
[BUG] Azure-Docker is not finding any Functions

### ISSUE THREAD

**Issue by yovelcohen** [Azure/azure-functions-python-worker#1424]
###### Please provide the following:

- Timestamp: February 2nd, 2024, 08:00
- Function App name: 
- Function name(s) (as appropriate): ping, translate, parse_video_trigger
- Core Tools version: 4.0.5455

###### Provide the steps required to reproduce the problem:
1. func init
2. add new HTTP/blob triggers
3. build a docker image and run it with `docker run -it --rm -e  -p 8080:80  <imgtag>`
4. no functions detected in output logs.

###### Provide a description of the expected behavior.
all functions should be discovered

### Actual behavior

No Job-Functions found, but when I ran the function using `func start` all of the functions were recognized and working when I called them locally.

###### Provide the requirements.txt file to help us find out module-related issues.
```
azure-functions==1.18.0
azure-functions-durable==1.2.8
```

###### Provide any related information

My docker file:
```Docker
FROM mcr.microsoft.com/azure-functions/python:4-python3.11-slim

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    AzureWebJobsFeatureFlags=EnableWorkerIndexing
    
RUN apt-get update && apt-get install -y ffmpeg gcc portaudio19-dev python-all-dev libmagic-dev ca-certificates sox && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt
RUN pip install --global-option='build_ext' --global-option='-I/usr/local/include' --global-option='-L/usr/local/lib' pyaudio==0.2.14

COPY . /home/site/wwwroot
```

I also tried following the suggestions such as adding different combinations of environment variables in other similar issues such as:
https://github.com/Azure/azure-functions-python-worker/issues/1384 
https://stackoverflow.com/questions/75519932/azure-function-python-model-2-in-docker-container

The only difference for me from those is that I'm using Python 3.11 I guess?

**Comment by hallvictoria** [comment]
Hi @yovelcohen 
	
I followed the repro steps listed using the provided requirements.txt and dockerfile content, but didn't have the same issue. I tried with HTTP triggers and using a Durable Functions app.
	
I did need to add the `AzureWebJobsStorage` environment variable to my Dockerfile. Can you try adding that and see if that fixes the issue?

```
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    AzureWebJobsFeatureFlags=EnableWorkerIndexing  \
    AzureWebJobsStorage=...
```
