### ISSUE TITLE
how to stream json outputs via Azure function

### ISSUE THREAD

**Issue by AInisha** [Azure/azure-functions-python-worker#1426]

**Comment by hallvictoria** [comment]
Hi @AInisha 

You can use the Azure Blob Storage client library to stream blob content.

Here are some docs for reference:
- [Quickstart: Azure Blob Storage client library for Python](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python?tabs=managed-identity%2Croles-azure-portal%2Csign-in-azure-cli)
- [Azure Storage Blobs client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/storage-blob-readme?view=azure-python)
- [download_blob method for BlobClients](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-download-blob)

Python will also be implementing support for SDK type bindings soon, which will enable streaming through Blob Trigger or Blob Input scenarios as well.
