### ISSUE TITLE
Easier way of accessing environment variables

### ISSUE THREAD

**Issue by Jsans** [Azure/azure-functions-python-worker#143]
hey,
it will be good to see "applications settings" incorporated bit more seamlessly.

Currently it is:

`
import os 
name=os.environ.get('name')

`

**Comment by kapilt** [comment]
not sure what could be easier, that is the standard python way of getting env variables, anything else would be non idiomatic.

**Comment by priyaananthasankar** [comment]
Agree with @kapilt . I just used those to retrieve app settings. This is line with how we get app settings using C# interfaces as well that is idiomatic to C#.

**Comment by benc-uk** [comment]
The current approach is also in-step with Node.js Functions too, it's clean and platform/framework independent
It's also the same in App Service Web Apps

**Comment by asavaritayal** [comment]
The current experience is in line with the standard Python approach for env variables. Closing the issue since we have don't have enough feedback to enforce the need for a different experience.
