### ISSUE TITLE
Using microsoft event grid output binding python v2 doesnt show the service on azure portal

### ISSUE THREAD

**Issue by natashadonana** [Azure/azure-functions-python-worker#1444]

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls share the repro steps.
Is there any error  in application insight  pls share the log error msg.
Need to check on function app,invocation id,time stamp region etc
share your app name privately.
[Sharing Your Function App name privately · Azure/azure-functions-host Wiki (github.com)](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)
