### ISSUE TITLE
[BUG] Blob triggers log "Blob Size: None" when triggered

### ISSUE THREAD

**Issue by hossam-nasr** [Azure/azure-functions-python-worker#1453]
### Investigative information
Func version: 4.0.5390
Python version: 3.10.11
Extension bundle: v4
Repros with both programming model V1 & V2

### Repro steps
1. Create a Python Functions project
2. Create a blob trigger function (use default template), listening to blobs on the `samples-workitems` container in the local emulator
4. Execute your function using F5 on VSCode or running `func start`
5. Trigger your function by uploading any blob to the `samples-workitems` container in the emulator
6. Check output log

### Expected behavior
Show the correct blob size in the output log:
![image](https://github.com/Azure/azure-functions-python-worker/assets/31644556/0f95902f-cc75-433c-a4e8-2c11c8af9ad1)

### Actual behavior
The blob size is "None bytes" in the output log:

![image](https://github.com/Azure/azure-functions-python-worker/assets/31644556/2ce0b09f-b8d2-4ba9-9451-da2774755e3a)

### Known workarounds
The default template for blob triggers logs the size of the blob using `myblob.length`. I tried manually debugging the function, and saw that in my one example, using instead `myblob.blob_properties['ContentLength']` to log the blob length worked. I'm not sure if that's always set or a reliable property though. Also not sure if this is a Python worker issue that it doesn't properly set the `myblob.length` property, or a templates issue that it shouldn't rely on the `myblob.length` property to begin with.

### Contents of the requirements.txt file:

```
azure-functions
```

### Related information
From https://github.com/microsoft/vscode-azurefunctions/issues/4051

**Comment by bhagyshricompany** [comment]
Hi @hossam-nasr  thanks for reporting will check and update.

**Comment by YunchuWang** [comment]
![{5CA404F6-56D5-4274-B8C5-720FB2B13183}](https://github.com/user-attachments/assets/0d6c6fcd-5c28-4d61-823c-0f3dadebc826)

**Comment by hallvictoria** [comment]
This has been fixed! Please make sure to update to `azure-functions >= 1.22.0b4` and add `"PYTHON_ISOLATE_WORKER_DEPENDENCIES": "1"`.
