### ISSUE TITLE
Resolve conflicts and merge dev to master

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#147]
@elprans - Can you send a PR for this?

**Comment by elprans** [comment]
Done.

**Comment by pragnagopa** [comment]
@elprans - Can you please look at the test failures at https://ci.appveyor.com/project/appsvc/azure-functions-python-worker/build/1.0.289

**Comment by elprans** [comment]
Eventhub failed to call the trigger within the timeout.  I can increase it, but it seems like a host issue. Travis is OK.

**Comment by pragnagopa** [comment]
To avoid race conditions, can you use dedicated resources for CI?

**Comment by elprans** [comment]
They are dedicated already.
