### ISSUE TITLE
Can you make a blob triggered azure function app that only binds the filename, not the whole blob? 

### ISSUE THREAD

**Issue by ajay-sk-finarb** [Azure/azure-functions-python-worker#1486]
#### Is your question related to a specific version? If so, please specify: 
No

#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) : 
Blob Tigger

#### Question
Can you suggest me way such that, irrespective of size of blob size that triggered the function, I can get the blob name?
Currently, whenever I upload a file, say of size 600MB, It fails silently without ever showing up in logs. Please Advise.

**Comment by bhagyshricompany** [comment]
will check and update.

**Comment by bhagyshricompany** [comment]
@gavin-aguiar  pls comment and validate.Thanks

**Comment by hallvictoria** [comment]
This can be addressed by using SDK type bindings for blob. The BlobTrigger can define a client type, and the client type can be used to access the blob name even if the blob is large.

Please see this documentation for more information:
- [Python Developer Reference - SDK Type Bindings](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=get-started%2Casgi%2Capplication-level&pivots=python-mode-decorators#sdk-type-bindings-preview)
- [SDK type bindings for Azure Blob Storage](https://techcommunity.microsoft.com/t5/azure-compute-blog/azure-functions-sdk-type-bindings-for-azure-blob-storage-with/ba-p/4146744)
