### ISSUE TITLE
[BUG] Module not found error when deploying function from Azure Functions extension in VSCODE

### ISSUE THREAD

**Issue by samin-batra** [Azure/azure-functions-python-worker#1497]
###### Please provide the following:

- Timestamp: 15th May, 2024 
- Function App name: 
- Function name(s) (as appropriate): data_populate
- Core Tools version:4.0.5700 Commit hash: N/A +71cc84964a60bfb07d95839b7c666bd239507bdd (64-bit)

###### Provide the steps required to reproduce the problem:
Deploy to function app using the task: deploy to existing app in Azure functions extension for VSCode

###### Provide a description of the expected behavior.
Function app should show the deployed function in azure portal.

###### Provide a description of the actual behavior observed.
The deployed function does not show up and an error message is displayed; We were not able to load some functions in the list due to errors. Refresh the page to try again. See details

When I check the logs, it mentions that an error occurred while importing the numpy module.

### Known workarounds
https://learn.microsoft.com/en-us/azure/azure-functions/recover-python-functions?tabs=vscode%2Cbash&pivots=python-mode-decorators#troubleshoot-modulenotfounderror

###### Provide the requirements.txt file to help us find out module related issues.
azure-functions
pandas==2.0.3
numpy==1.22.3
pyodbc==5.1.0
SQLAlchemy==2.0.30
statsmodels==0.14.1

###### Provide any related information
Python version 3.8 and also 3.9.
Till yesterday, it was working fine and deploying correctly. However, since then this issue has been coming. Earlier it was with the scikit-learn package that I then removed because I had a workaround for not using it. Now the issue is coming with numpy package. Any help would be greatly appreciated!

**Comment by bhagyshricompany** [comment]
Thanks for informing will check and confirm the same.

**Comment by bhagyshricompany** [comment]
Can you try again it seems working fine.please try again if have anything please update  with full code 
<img width="947" alt="image" src="https://github.com/Azure/azure-functions-python-worker/assets/116645353/1b1e900c-e0e3-4345-848a-5e28919d36d6">
