### ISSUE TITLE
no module named 'azure.functions'

### ISSUE THREAD

**Issue by jiata** [Azure/azure-functions-python-worker#151]
https://github.com/Azure/batch-scoring-for-dl-models/issues/2

**Comment by jiata** [comment]
@asavaritayal @pragnagopa

**Comment by pragnagopa** [comment]
can you give us more details? link you provided gives 404

**Comment by jiata** [comment]
Keeps getting a message like "cannot find azure.functions module" even though I walked through the install instructions

![image](https://user-images.githubusercontent.com/16616215/41626386-1ea654b2-73ea-11e8-9b5e-265a37dd9553.png)

**Comment by asavaritayal** [comment]
Can you manually install - 

```
pip install azure-functions
pip install azure-functions-worker
```

**Comment by asavaritayal** [comment]
Closing due to no repro.
