### ISSUE TITLE
Queue trigger connection isn't being used by retry decorator

### ISSUE THREAD

**Issue by matt256** [Azure/azure-functions-python-worker#1536]
#### Is your question related to a specific version? If so, please specify:

azure-functions:1.20
azure-core:1.30.2

#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 

Queue Trigger/ retry

#### Question

TLDR: *queue_trigger* decorator connection string isn't used for *requeuing* by the retry decorator.

Detailed:

```
@func_name.queue_trigger(
    arg_name="message",
    queue_name=<from_config>,
    connection=<from_config>,
)
@func_name.retry(strategy=<from_config>, 
     max_retry_count=<from_config>,
     delay_interval=<from_config>)
def function_name(message: func.QueueMessage):
     .....
```

We have a custom connection string that is working fine for triggers, but when deployed the function cannot requeue the messages because it appears to be going back to the default queue server url and not our custom one.  It says adjust the retrypolicy settings, but they dont including anything regarding connections. 

ERROR:

```
Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a 
custom retry policy in ClientOptions.RetryPolicy. (Name or service not known
```
So in the documentation, a function will be retried up to 5 times before being requeued (for a retry). So I'm a bit unclear on whether this is referring to it's requeuing attempt, or to create/push to the poison queue after a full failure. 

Am I missing a configuration somewhere that allows us to define the connection paths for retries? Is this a bug?

**Comment by bhagyshricompany** [comment]
Thanks for reporting.please config your setting  please ref  this https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue?tabs=isolated-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-python#host-json
