### ISSUE TITLE
Run with WEBSITE_RUN_FROM_PACKAGE=<URL> + FastAPI get 404?

### ISSUE THREAD

**Issue by eddison-shyi** [Azure/azure-functions-python-worker#1550]
Hello everyone,

I've tested to run my Azure Functions with FastAPI good in both local & Azure, but when I tried to use Managed Identity for all connection authentication, the Functions gone and left just 404. 

**Can someone helps me to figure out how to do right deployment with FastAPI Azure Functions & WEBSITE_RUN_FROM_PACKAGE=URL? big thanks~** 

## Scenario & Step I've done
> Python v2 model, FUNCTIONS_EXTENSION_VERSION: ~4
> Runtime: Python 3.11 | Linux
> App Service Plan: Y1(Consumption), Dynamic
> Using Bicep to build: Storage Account, App Service Plan(ServerFarm), Azure Functions (with environment variables & Managed Identity role assignment)
> Manually upload .zip to storage container

1. In order to (let Functions) connect to Storage Account with Managed Identity, I've changed environment variables from AzureWebJobsStorage to AzureWebJobsStorage__accountName. (I've assigned role: Storage Blob Data Contributor to this Azure Functions before this step) 
2. [According to this documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial#edit-the-azurewebjobsstorage-configuration), I noticed this in the blue 'Important area': 
    > When you enable identity-based connections for AzureWebJobsStorage in Linux Consumption, you will need to deploy via [an external deployment package](https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package).
3. I've added environment variables: WEBSITE_RUN_FROM_PACKAGE with URL value, because it asked me to deploy via external deployment package.
4. After .zip uploaded, I restarted Functions from Azure Portal (because it asked me to sync triggers mannually, I chose 'restart Functions from portal'), and the Functions disappeared.
5. Then I tried to make sure whether good or not while using python sample code below and uploaded again. The endpoint in sample code appear! (so both "WEBSITE_RUN_FROM_PACKAGE with URL" & "AzureWebJobsStorage__accountName with accountName" seem working, and something wrong in deployment of Functions with ASGIFunctionApp)

### Using same environment variables for these code below
Bicep snippet for environment variables
![image](https://github.com/user-attachments/assets/01cb72e0-a40e-47b7-b786-c8030c87796b)

``` python
# sample code snippet and this runs well in both local & Azure Functions
import azure.functions as func

app = func.FunctionApp()

@app.function_name(name="HttpTrigger1")
@app.route(route="req")
def main(req: func.HttpRequest) -> str:
    user = req.params.get("user")
    return f"Hello, {user}!"
```

``` python
# another code snippet using FastAPI, only runs well in local and get 404 in Azure Functions
import azure.functions as func
from fastapi import FastAPI

fast_api = FastAPI()

@fast_api.get("/")
async def test():
    return {"Hello, human!"}

app = func.AsgiFunctionApp(app=fast_api, http_auth_level=func.AuthLevel.ANONYMOUS)
```

**Comment by gavin-aguiar** [comment]
@eddison-shyi If you're using managed identities you will have to add WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID to the app settings. If you're using the system assigned identity then the value of this app setting will be `SystemAssigned` or if you're using user assigned identity the value will be the resource id of the user assigned identity

For more info refer to https://learn.microsoft.com/en-us/azure/app-service/deploy-run-package#access-a-package-in-azure-blob-storage-using-a-managed-identity

**Comment by eddison-shyi** [comment]
> @eddison-shyi If you're using managed identities you will have to add WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID to the app settings. If you're using the system assigned identity then the value of this app setting will be `SystemAssigned` or if you're using user assigned identity the value will be the resource id of the user assigned identity
> 
> For more info refer to https://learn.microsoft.com/en-us/azure/app-service/deploy-run-package#access-a-package-in-azure-blob-storage-using-a-managed-identity

Dear gavin-aguiar,

I've tried to add env: `WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID=SystemAssigned` , it still failed with error code: 404
![image](https://github.com/user-attachments/assets/addf77ce-b0a5-486b-aedd-1bcd7abea9da)
![image](https://github.com/user-attachments/assets/e03d310e-749e-422f-9691-c60207f637eb)
