### ISSUE TITLE
Run async code during function initialization

### ISSUE THREAD

**Issue by konstantinmiller** [Azure/azure-functions-python-worker#1565]
What is the proper way to run async initialization code during function initialization?

The code that registers functions runs synchronously

```
app = azure.functions.FunctionApp()
app.register_functions(function_blueprint)
```

How do I perform initialization that requires async? For example, setting up a shared `aiohttp.ClientSession`, or other shared services that have async initialization.

Should I use `asyncio.run()`?

**Comment by bhagyshricompany** [comment]
Hi @konstantinmiller   thanks for reporting will check and update.Thanks

**Comment by hallvictoria** [comment]
Hi @konstantinmiller, thanks for reporting.

To clarify my understanding, are you wanting to do something like set up an `aiohttp.ClientSession` while the function app is starting up? Thus, the session would already be initialized and running even before any function executions?

We currently don't support creating a new loop, so `asyncio.run()` will not work.

As a workaround, you can use `nest_asyncio` to allow for nested loops so the newly created session can be started within the main loop.

For example:
```
import azure.functions as func
import asyncio
import aiohttp
import nest_asyncio

bp = func.Blueprint()
async def create_session():
   return aiohttp.ClientSession()

nest_asyncio.apply()
session = asyncio.get_event_loop().run_until_complete(create_session())

bp.route(route="hello")
def hello(req: func.HttpRequest) -> func.HttpResponse:
   return func.HttpResponse("HttpTrigger function processed a request!")
```
