### ISSUE TITLE
[Bug] Timer trigger mismatch between template and documentation

### ISSUE THREAD

**Issue by jomalsan** [Azure/azure-functions-python-worker#1596]
### Expected Behavior

Consistent guidance across tooling and documentation on how to use a timer trigger in the python function SDK. `app.schedule` or `app.timer_trigger`?

### Actual Behavior

It is unclear which decorator should be used in python for a timer trigger. 

The VS Code extension generates the following python code:

```python
import logging
import azure.functions as func

app = func.FunctionApp()


@app.schedule(
    schedule="0 */5 * * * *", arg_name="myTimer", run_on_startup=True, use_monitor=False
)
def timer_trigger(myTimer: func.TimerRequest) -> None:
    if myTimer.past_due:
        logging.info("The timer is past due!")

    logging.info("Python timer trigger function executed.")

```

While the documentation here uses the following: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=python-v2%2Cisolated-process%2Cnodejs-v4&pivots=programming-language-python#example

```python
import datetime
import logging
import azure.functions as func

app = func.FunctionApp()

@app.function_name(name="mytimer")
@app.timer_trigger(schedule="0 */5 * * * *", 
              arg_name="mytimer",
              run_on_startup=True) 
def test_function(mytimer: func.TimerRequest) -> None:
    utc_timestamp = datetime.datetime.utcnow().replace(
        tzinfo=datetime.timezone.utc).isoformat()
    if mytimer.past_due:
        logging.info('The timer is past due!')
    logging.info('Python timer trigger function ran at %s', utc_timestamp)
```

Personally, I have found that `app.timer_trigger` approach to work better as the `app.scheduler` method has inconsistencies in running time #1595 

### Steps to Reproduce

Generate a new function in VS Code extension with selections:
* Select python
* V2
* Timer trigger
* Cron string ("0 */5 * * * *") <- every 5 minutes to match docs

### Where are you facing this problem?

Local - Core Tools

### Additional Information

I have not see the `app.schedule` method documented anywhere, so I suspect that the python timer template is out of date

**Comment by hallvictoria** [comment]
Both decorators work. The `timer_trigger` decorator was added to stay consistent with the others (eg: `blob_trigger`), but they are the same.

The templates have been updated to reference `timer_trigger` instead of `schedule`. VSCode is using an older version of templates though, before this change went in. We'll double check to get that updated.
