### ISSUE TITLE
[Bug] Timer trigger functions with @app.schedule continue executing after a function has been stopped

### ISSUE THREAD

**Issue by jomalsan** [Azure/azure-functions-python-worker#1597]
### Expected Behavior

When I stop an azure function app, I would suspect that the function would no longer execute.

### Actual Behavior

After stopping the function app, the timer triggered function continues executing for a while. 

### Steps to Reproduce

1. Generate a new function in VS Code extension
  * Select python
  * V2
  * Timer trigger
  * Cron string ("0 * * * * *") <- every minute for quick understanding
2. Deploy to a function app (I'm using a linux consumption app)
3. Wait a bit for the app to get started
4. Open the log stream in one tab
5. In another tab stop the Function App
6. The logs for function invocations will continue. In my case it was for 5 minutes (5 extra invocations)

### Relevant code being tried

import logging
import azure.functions as func

app = func.FunctionApp()

@app.schedule(
    schedule="0 * * * * *", arg_name="myTimer", run_on_startup=True, use_monitor=False
)
def timer_trigger(myTimer: func.TimerRequest) -> None:
    if myTimer.past_due:
        logging.info("The timer is past due!")

    logging.info("Python timer trigger function executed.")

### Where are you facing this problem?

Local - Core Tools

**Comment by hallvictoria** [comment]
In Consumption, depending on the workload, the function app could be running on multiple containers. When the site is stopped, a request is sent to stop all the containers. When the container receives that request, it will then stop any upcoming invocations, but it will complete any invocations that have already been sent or are in progress. That is why some executions can still complete after the site has been stopped.

An alternative to stopping the site would be to disable the function you want to ignore: [How to disable functions in Azure Functions](https://learn.microsoft.com/en-us/azure/azure-functions/disable-function?tabs=portal)
