### ISSUE TITLE
Azure Function

### ISSUE THREAD

**Issue by PraveenAyyasamy** [Azure/azure-functions-python-worker#1605]
Hi team,

I have deployed a ARM template for integrating Cloudflare logs to Sentinel.

Deployment is succeeded, but we are facing issues in Function app.

Result: Failure Exception: KeyError: 'AZURE_STORAGE_CONNECTION_STRING' Stack: File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py", line 535, in _handle__function_load_request func = loader.load_function( ^^^^^^^^^^^^^^^^^^^^^ File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 44, in call return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/loader.py", line 220, in load_function mod = importlib.import_module(fullmodname) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1204, in _gcd_import File "<frozen importlib._bootstrap>", line 1176, in _find_and_load File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 690, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 940, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/home/site/wwwroot/AzureFunctionCloudflare/main.py", line 27, in <module> AZURE_STORAGE_CONNECTION_STRING = os.environ['AZURE_STORAGE_CONNECTION_STRING'] ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen os>", line 679, in __getitem__

**Comment by hallvictoria** [comment]
Hi @PraveenAyyasamy, thanks for reporting

It looks like the `AZURE_STORAGE_CONNECTION_STRING` environment variable is not being found. Can you add this variable as an app setting? This will add it as part of the environment variables.
