### ISSUE TITLE
Where is the location where the build() is being run?

### ISSUE THREAD

**Issue by masamori0083** [Azure/azure-functions-python-worker#1607]
#### Is your question related to a specific version? If so, please specify:
4.0
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
General
#### Question
Hello!
I'm using Azure Function. Thanks for developing it!
I'm trying to create my own trigger following [this guide](https://github.com/Azure/azure-functions-python-worker/wiki/Adding-support-for-a-new-binding-type), but I have a question about the source code.
I'm aware that eventually the build function of the FunctionBuilder class is called to make the Function available, is this correct?
Also, I can't find the part in the source code where the build is being executed.

I would like to know if there is any documentation that explains when the build is executed.

I would also like to know the relevant code section where the build is running, if you don't mind.

Thanks again!

**Comment by hallvictoria** [comment]
Hi @masamori0083, thanks for reporting. You'll want to add your changes to the [azure-functions SDK](https://github.com/Azure/azure-functions-python-library). This is where all recognized bindings are defined. The guide you're referencing is a little outdated in that sense -- the concepts are correct, but the links are outdated. I'll get those updated.

The `build` method is defined [here](https://github.com/Azure/azure-functions-python-library/blob/48a5758f636abbe3f1b0634881b7eefbb74c3cf3/azure/functions/decorators/function_app.py#L293), and called in `get_functions` [here](https://github.com/Azure/azure-functions-python-library/blob/48a5758f636abbe3f1b0634881b7eefbb74c3cf3/azure/functions/decorators/function_app.py#L3628). This is where the functions are being built. These methods are both defined in the `azure-functions` package but are called in the python worker.

`get_functions` is used in the [python worker](https://github.com/Azure/azure-functions-python-worker/tree/dev) in the `index_function_app` method [here](https://github.com/Azure/azure-functions-python-worker/blob/7e6acf36e43335ad69742923af9ff3d62b99242a/azure_functions_worker/loader.py#L264). This is where indexing the function app happens, and where all the functions are recognized.

We don't have any documentation on the indexing process, as I feel it's mainly used / looked at internally.

Hope this helps!
