### ISSUE TITLE
[Bug] cosmos_db_output bindings mixes up container_name and collection_name

### ISSUE THREAD

**Issue by DimitryNechaev** [Azure/azure-functions-python-worker#1611]
### Expected Behavior

When I use @app.cosmos_db_output(container_name="mycontainer") this container should be displayed in the function integration UI. Instead I need to specify collection_name in **kwargs to get it displaying as expected

### Actual Behavior

![Image](https://github.com/user-attachments/assets/44fb2643-0d09-42ad-924f-8a23481a4cd7)
![Image](https://github.com/user-attachments/assets/51cdf478-511d-4468-a9c1-4b7423d54349)

![Image](https://github.com/user-attachments/assets/c67be6f7-de67-4f8f-8ac3-85e27f63d2b3)
![Image](https://github.com/user-attachments/assets/2629fdf2-0c1d-44cd-aeca-8043d1e9b6a7)

### Steps to Reproduce

Create cosmos_db_output binding and see it after deployment in the integration tab of the function

### Relevant code being tried

```shell

```

### Relevant log output

```shell

```

### requirements.txt file

```shell

```

### Where are you facing this problem?

Local - Core Tools

**Comment by bhagyshricompany** [comment]
Hi @DimitryNechaev Thanks for update will check for the same and update you on this soon.
To ensure the correct behavior in the Azure portal:

Use collection_name in **kwargs explicitly when using @app.cosmos_db_output.
Alternatively, modify the function.json file manually to include the collectionName property.
if you refering any doc please update .Thanks
