### ISSUE TITLE
Unable to use azure SDKs with python

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-python-worker#164]
Created a vanilla HTTP function (works):

```python
import logging

import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    return func.HttpResponse('Hello', status_code=200)
```

I then installed the Azure SDK

```
pip install azure
```

When I try to reference one of these SDKs it throws errors for naming conficts

```python
import azure.mgmt.compute
import azure.mgmt.network.models
import azure.mgmt.storage.models
```

```
[7/25/18 8:30:37 PM]     import azure.functions  # NoQA
[7/25/18 8:30:37 PM] ModuleNotFoundError: No module named 'azure.functions'
```

**Comment by elprans** [comment]
I need a bit more context please.  How was the python worker installed?

**Comment by jeffhollan** [comment]
Just following the [quickstart here](https://github.com/Azure/azure-functions-python-worker/wiki/Create-Function-(CLI))

**Comment by jeffhollan** [comment]
Link didn’t work but it’s the “crest function via CLI” one

**Comment by elprans** [comment]
Which version of core tools are you running?  @ahmelsayed can you confirm that we *do not* use the development mode install for the python worker (`pip install -e`) in the core tools script?

**Comment by asavaritayal** [comment]
@jeffhollan what is the version of the core tools you're using? Can you also share your `requirements.txt` file?

**Comment by jeffhollan** [comment]
Tested this on latest func cli and it's working now so can close.  As any FYI my requirements.txt when **not working** had this:

```
-e git+https://github.com/Azure/azure-functions-python-worker.git@57a4dda497c4cde83288f010fef490ff9a42edb7#egg=azure_functions_python
```

But now has this

```
azure-functions==1.0.0a1
azure-functions-worker==1.0.0a3
```

**Comment by rvanmaanen** [comment]
I actually ran into this reference to GitHub too, had issues when publishing when this was still in the requirement.txt file. Wrote something about it [here](http://r-vm.com/python-on-azure-functions), where I was struggling as well. 

Maybe someone can explain why it is setup like this and not just a normal reference as Jeff says here as well?

**Comment by asavaritayal** [comment]
@rvanmaanen thanks for blogging about this! Just ran through your post and most of the rough edges you ran into earlier should now be fixed. Let us know about your experience when you give it a shot next. Happy to connect further on any feedback and recommendations you might have :) 

PS Python on v2 is not yet officially supported hence it's not mentioned on the docs. We're treating the feature as still in-development.
