### ISSUE TITLE
Upgrade worker to support Python3.7

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#166]
Now that it's out of RC. 

TBD - Investigate implications for the Azure SDK and other libraries that are only compatible with 3.6 so far.

**Comment by kapilt** [comment]
fwiw, we're doing builds/tests of azure client lib usage with 3.7, seems to work well. https://travis-ci.org/capitalone/cloud-custodian/jobs/409066825

**Comment by asavaritayal** [comment]
- Update CI to test for Python 3.7
- Updated underlying Docker image

**Comment by asavaritayal** [comment]
Thanks @priyaananthasankar . 

Posting the highlights here from standup: 
1. Changes that @elprans made yesterday make the language worker agnostic of whether the user is on `3.6` or `3.7`. These changes will go out with the next release.
2. Additional work item required is to update the docker image to use 3.7 instead. 

We'll hold back on #2 until `python3.7` is more stable.
