### ISSUE TITLE
How do I debug Python Functions in VS Code and PyCharm?

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#167]
I know we've had some changes around the port to use. Would be good to get clarity on the plan going forward. 

/cc @priyaananthasankar

**Comment by priyaananthasankar** [comment]
Thanks @asavaritayal for adding me. As of today VS code does not support attaching debugger to "pristine" processes (process threads starting outside of VS code) and Azure functions extension does not support Python. It would be great to add these to get more Python adoption.

**Comment by asavaritayal** [comment]
Closing as this is now done in VS Code.
