### ISSUE TITLE
AppVeyor Build Failure

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#168]
Issue seems to be with CosmosDB. @pragnagopa to investigate.

**Comment by asavaritayal** [comment]
https://github.com/Azure/azure-functions-host/issues/3229

**Comment by asavaritayal** [comment]
@pragnagopa can you please follow up on the App Veyor CI issue next week?

**Comment by pragnagopa** [comment]
@elprans - Is it still an issue? There were bunch of changes that went to the latest runtime. CosomosDB extensions had few fixes as well. If the issue still reproes, I will look into https://github.com/Azure/azure-functions-host/issues/3229

**Comment by elprans** [comment]
@pragnagopa It appears we're OK now: https://ci.appveyor.com/project/appsvc/azure-functions-python-worker/build/job/i9wbryd2jni2sev8
