### ISSUE TITLE
bdist_wheel is not found unless explicitly pip installed wheel

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#176]
Attached is requirements.txt file.

Steps to repro:

1) Create a fresh virtual environment and 'func new' a new app, can be a simple http trigger
2) Add the attached requirements.txt file. 
3) Publish to Linux consumption plan app

Can notice in the publish logs that **bdist_wheel is not found.** Subsequently all the wheel installations failed.
[requirements.txt](https://github.com/Azure/azure-functions-python-worker/files/2268446/requirements.txt)

Cancelled the publish and explicitly ran "pip install wheel" in the virtual env and republished, the error went away.

**Comment by asavaritayal** [comment]
@elprans should we modify [packapp.py](https://github.com/Azure/azure-functions-core-tools/blob/master/tools/python/packapp.py) to always do a `pip install wheel` before installing other packages?

**Comment by elprans** [comment]
Yes, it should be a cli dependency. /cc @ahmelsayed

**Comment by asavaritayal** [comment]
> Yes, it should be a cli dependency. 

Got it. Can you please make a PR to the core tools repo?

**Comment by ahmelsayed** [comment]
That’s right, I used to install it to get things to work, but wasn’t sure why. Then it started working without it, so I removed it. I’ll add it back. what is that package and why is it needed if it’s not a dependency of the 2 function packages?

**Comment by elprans** [comment]
Packapp needs it to produce wheels for pure Python packages. Since packapp is part of core-tools, the dependency should be installed there, similarly to distlib.

**Comment by ahmelsayed** [comment]
thanks @elprans
