### ISSUE TITLE
Add language worker consolelog key for system logs

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#181]
Console logs from language worker now need to be appended with 
https://github.com/Azure/azure-functions-host/blob/a5a9b0d79a17670ba8e5b4a6f019637aaf1bfa42/src/WebJobs.Script/Rpc/LanguageWorkerConstants.cs#L37
To show up in functions Runtime systemlogs

**Comment by elprans** [comment]
@pragnagopa Where do I put this?  `RpcLog.category`?

**Comment by pragnagopa** [comment]
RpcLog is for user logs from function code. This issue is specifically for any logs 
Written to stderr stdout streams from python worker

**Comment by elprans** [comment]
Sorry, I don't understand.  Do you mean stderr/stdout redirection from the function code?

**Comment by elprans** [comment]
@pragnagopa I need some clarification here. The worker is already doing all its logging through the  RpcLog proto, including the worker errors, there is no stdout logging.

**Comment by pragnagopa** [comment]
no action item here if you are not python worker is not writing to console log using something like 'print'
This item is specifically for writing to stdout/stderr from the language worker before grpc channel is established.

**Comment by elprans** [comment]
@pragnagopa Should _every_ output line be prefixed with `LanguageWorkerConsoleLogPrefix`?  The only output the worker may generate outside of the normal grpc comm is if there is an exception in the initial startup, which will be a multiline Python exception message.

**Comment by elprans** [comment]
@pragnagopa I opened https://github.com/Azure/azure-functions-host/pull/3369 to allow simplifying things and to obviate the need to ship a separate python file to launch the language worker.

**Comment by pragnagopa** [comment]
Any logs, that need to show up in system logs, should append LanguageWorkerConsoleLogPrefix
For example, logs that indicate
-  python worker started 
- Initialization completed after loading the functions
will help us during a CRI investigation.
@elvis - Can you please create a test app in azure and verify few error cases like throwing an unhandled exception from function code. I can verify the logs in the backend to make sure we have enough logs.

**Comment by asavaritayal** [comment]
@pragnagopa can you clarify if this applies to Rpc logs or the stdout logs? Additionally, do we need the prefix per trace line or each line or each message?

**Comment by pragnagopa** [comment]
Adding @maiqbal11 - He is looking into what traces we need from python worker

**Comment by maiqbal11** [comment]
Hi Elvis, 

Just wanted to put down a concrete example of what kinds of logging we've been referring to. Below is a code snippet from *worker.py*. I've added the `print("LanguageWorkerConsoleLog Executing main for worker", flush=True)` line to write to stdout. I had to set `flush=True` when writing this to get the log out to the host process. I see that the existing code `print(traceback.format_exc(), flush=True)` also flushes. Do you know if it is necessary to flush stdout to push the logs out (so far I've been unable to accomplish logging without this)? Additionally, if using flush is the only option, is there a significant performance penalty to flushing the buffer per message (as opposed to batching and then flushing)? 

```python
def main():
    print("LanguageWorkerConsoleLog Executing main for worker", flush=True)
    args = parse_args()

    import azure.functions  # NoQA
    import azure.functions_worker

    try:
        azure.functions_worker.start(
            args.host, args.port, args.worker_id, args.request_id,
            args.grpc_max_msg_len)
    except Exception:
        print(traceback.format_exc(), flush=True)
        raise
```

**Comment by elprans** [comment]
@maiqbal11 On POSIX flushing happens on EOL.  We do explicit output buffer flushing because the host doesn't respect that principle (I'm not sure if it's a bug or a feature).

We wouldn't be using stdout for regular logging messages, as those would go through gRPC.

**Comment by maiqbal11** [comment]
@elprans @pragnagopa 

Synced with Pragna briefly on the kinds of logging messages that should be added to help with debugging customer CRIs:

1. Message when connection with GRPC is initiated and completed. Can include server and port information here. 
2. Worker init request and response sequence
3. Function load request and response
4. Function invocation request and response

We cannot include details about the request as that contains customer data so, for now, it would be sufficient to include just traces that state, for example, "Function invocation request with id = {Id} received".
