### ISSUE TITLE
CosmosDB extension - failed to install

### ISSUE THREAD

**Issue by zivraf** [Azure/azure-functions-python-worker#184]
Failed to install the CosmosDB extension for Python 3.6.6 running Windows10
(I managed to repo this on two seperate machines) 

(env) PS <C:\Users\zivr\OneDrive - Microsoft\LocalGit\Functions-Python\ServerlessAzureMgmt>> func extensions install --package Microsoft.Azure.WebJobs.Extensions.CosmosDB --version 3.0.0-beta7
Please specify one package reference to add.
Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME> 

Python 3.6.6
Functions App core v2

Any thoughts ?

**Comment by asavaritayal** [comment]
@zivraf can you share your `function.json` file? 

What happens when you run `func extensions install` ? 

/cc @soninaren

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-host#3312
