### ISSUE TITLE
PyYAML==3.13 failed to install

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#185]
If the `requirements.txt` contains `PyYAML==3.13`, the following error is received when publishing the function app - 

```bash
Could not find a version that satisfies the requirement PyYAML==3.13 (from versions: )
No matching distribution found for PyYAML==3.13

ERROR: binary dependencies without wheels are not supported
```

The wheel error is odd since it seems that PyYAML indeed does offer wheel packages for version 3.13. See here - https://github.com/yaml/pyyaml/issues/49

**Comment by asavaritayal** [comment]
@elprans can you please investigate this?

**Comment by elprans** [comment]
@asavaritayal It only offers wheels for Windows, but not for Linux, which is a target platform.

**Comment by asavaritayal** [comment]
Thanks for confirming! @elprans so in the future I can check myself, is there a way to determine from PyPI whether a package offers linux wheels or not?

**Comment by asavaritayal** [comment]
Ah, never mind. I figured it out. Thanks :)
