### ISSUE TITLE
Visual Studio en VSTS support?

### ISSUE THREAD

**Issue by Tealons** [Azure/azure-functions-python-worker#194]
We have a solution which contains a C# Functions project and we also have several Azure Functions which are written in python. Is it or will it be possible to add a python based function project to my solution? We would prefer this to ensure that all code changes are tracked with version control in one solution. 

Also, we want to use this to enable continuous integration scenarios. I did not check yet, but I assume that deployment with VSTS is also possible for python based function projects? 

Btw: I'm not sure if this is the right place to ask this question. Please point me to the right repository if I'm wrong.

**Comment by asavaritayal** [comment]
@Tealons Are you using Functions v1 or v2?

**Comment by Tealons** [comment]
@asavaritayal I'm using v2. After some extra research it looks like I picked the wrong version? Any idea when support for Visual Studio will be implemented for v2?

**Comment by asavaritayal** [comment]
Functions v2 is already supported in Visual Studio. Here are some pointers for reference: 
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio
