### ISSUE TITLE
Publish Azure Function App fails on 2.0.1-beta.38

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#196]
Attached requirements.txt. Noticed the following error.

There was an error restoring dependencies.ERROR: ['pip', 'download', '-r', '/Users/prananth/Projects/FunctioningPython/Gutenberg/TrainBook/requirements.txt', '--dest', '/var/folders/8_/8m4c263132g8fwq0ql816zkw0000gn/T/azureworker9pk49gcc'] failed with exit code 1

[requirements.txt](https://github.com/Azure/azure-functions-python-worker/files/2380822/requirements.txt)

The app works fine locally.

**Comment by asavaritayal** [comment]
@elprans can you please investigate this issue?

**Comment by elprans** [comment]
Your `requirements.txt` contains a package which is not on PyPI:

```
  Could not find a version that satisfies the requirement en-core-web-sm==2.0.0 (from -r requirements.txt (line 21)) (from versions: )
No matching distribution found for en-core-web-sm==2.0.0 (from -r requirements.txt (line 21))
```

**Comment by priyaananthasankar** [comment]
Great! Is there a way to find out which don't exist on PyPI? Removed en-core-web-sm and it still fails. Also it would be great if a better error message gets thrown out.

**Comment by elprans** [comment]
@ahmelsayed Is there a CLI mode which runs `packapp` with `--verbose`?  

@priyaananthasankar There are multiple reasons why dependency resolution might fail.  Making extra requests to pypi is not necessary, we just need to show better diagnostics.

**Comment by priyaananthasankar** [comment]
Removed en-core-web-sm. Checked if all other packages are in PyPI. Still fails.

**Comment by elprans** [comment]
@priyaananthasankar 

> ERROR: cannot install wrapt-1.10.11 dependency: binary dependencies without wheels are not supported.  Use the --build-native-deps to try building the binary dependencies using a Docker container.

**Comment by priyaananthasankar** [comment]
So sending requests to PyPI doesn't ensure there are wheels. It gave me 200 ok for wrapt. Removed wrapt and still received the same error.

**Comment by asavaritayal** [comment]
@priyaananthasankar what's the error you're receiving now?

**Comment by priyaananthasankar** [comment]
There was an error restoring dependencies.ERROR: ['pip', 'download', '-r', '/Users/prananth/Projects/FunctioningPython/Gutenberg/TrainBook/requirements.txt', '--dest', '/var/folders/8_/8m4c263132g8fwq0ql816zkw0000gn/T/azureworker9pk49gcc'] failed with exit code

**Comment by priyaananthasankar** [comment]
Tried deploying with --build-native-deps: Fails. Works fine locally!

Command "/home/site/wwwroot/worker_venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k96eir8q/spacy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pnz5q8lu-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/site/wwwroot/worker_venv/include/site/python3.6/spacy" failed with error code -9 in /tmp/pip-build-k96eir8q/spacy/

**Comment by priyaananthasankar** [comment]
Using azure-storage is causing issues, check out this link talking about cryptography library - https://github.com/Azure/azure-storage-python/issues/219

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-core-tools#719
