### ISSUE TITLE
Release required - 1.0.0a6

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#205]
https://github.com/Azure/azure-functions-python-worker/compare/master...dev?expand=1

@elprans 
- Do a PyPI release from the master branch (1.0.0a5 to 1.0.0a6)
- Add release notes

@maiqbal11 
- Core Tools release to pin `azure-functions==1.0.0a6` and `azure-functions-worker==1.0.0a6`

**Comment by pragnagopa** [comment]
When do we need this? post ignite?

**Comment by asavaritayal** [comment]
When is the next v2 / core tools release? Can you align it with that release?

**Comment by pragnagopa** [comment]
cc : @maiqbal11 

> When is the next v2 / core tools release? Can you align it with that release?

No ETA yet. But we will plan a release soon.

**Comment by asavaritayal** [comment]
As discussed in the sync, we'll be doing a PyPI release this week.  /cc @maiqbal11 @paulbatum

**Comment by elprans** [comment]
Done: https://github.com/Azure/azure-functions-python-worker/releases/tag/1.0.0a6, https://pypi.org/project/azure-functions-worker/1.0.0a6/

**Comment by pragnagopa** [comment]
Thanks @elprans . I have tagged the release as "Pre-Release" in the release notes.

**Comment by asavaritayal** [comment]
Re-opening and assigning to @maiqbal11 for the core-tools update.

**Comment by maiqbal11** [comment]
Core tools updated: https://github.com/Azure/azure-functions-docker/pull/42
