### ISSUE TITLE
Host doesn't start on WSL due to Google.Protobuf error

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-functions-python-worker#206]
#### Summary
Starting the functions host with a Python runtime on Windows Subsystem for Linux causes error and host stops

#### Investigative information

- Timestamp: 25/09/2018
- Function App name: "Local function"
- Function name(s) (as appropriate): *HttpTriggerPython*
- Runtime: 2.0.12115.0

#### Repro steps

1. Install Azure Functions Core Tools v2.0.3
1. Use WSL Bash (with Python 3.6.6 installed)
2. Create new local Python Function App following [these steps](https://github.com/Azure/azure-functions-python-worker/wiki/Create-your-first-Python-function)
3. Create HTTP Trigger function `func new`
4. Start the host `func host start`
5. Above error about **Google.Protobuf** is shown and host exits/shuts down

#### Expected behavior

Host starts and *HttpTriggerPython* is available to be called

#### Actual behavior

The following is reported in the logs and the host simply exits and shutsdown 
```
[9/25/18 9:04:01 AM] Initializing Host.
[9/25/18 9:04:01 AM] Host initialization: ConsecutiveErrors=0, StartupCount=1
[9/25/18 9:04:02 AM] Starting JobHost
[9/25/18 9:04:02 AM] Starting Host (HostId=becolem-457235496, InstanceId=17e276be-543e-40ea-853a-f35316b350a3, Version=2.0.12115.0, ProcessId=721, AppDomainId=1,
Debug=False, FunctionsExtensionVersion=)
[9/25/18 9:04:02 AM] A host error has occurred
[9/25/18 9:04:02 AM] Microsoft.Azure.WebJobs.Script.Grpc: Could not load file or assembly 'Google.Protobuf, Version=3.5.1.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. The module was expected to contain an assembly manifest.
[9/25/18 9:04:02 AM] Stopping JobHost
```

#### Known workarounds

Use Python for Windows + PowerShell

#### Related information 

Provide any related information 

* Creating a vanilla Python project and template function using the CLI Core Tools
* No bindings used (just HTTP)
* No dependencies

**Comment by asavaritayal** [comment]
@elprans can you please look into this issue?

**Comment by benc-uk** [comment]
Yes, just tried it with JavaScript `func init --worker-runtime javascript` and get the same error.
This must be very new, only a couple of weeks ago I was testing JavaScript functions on WSL and fixing some issues with the Core Tools CLI, so didn't even think to try it

Definitely seems to be a host problem

**Comment by benc-uk** [comment]
I've raised this on the azure-functions-host repo https://github.com/Azure/azure-functions-host/issues/3537

**Comment by asavaritayal** [comment]
@benc-uk noticed that you closed the issue on the host repo? Is the python issue resolved as well?

**Comment by benc-uk** [comment]
It's resolved, but I don't know why. Closing
