### ISSUE TITLE
Deploying through VS Code shows Warmup api

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#207]
Linux Consumption Plan preview.

Created a simple HTTP trigger and deployed into azure function app through VS Code. It worked fine.
Added another HTTP trigger method that used Cosmos DB extension and redeployed to the same function app through VS Code. These were the output logs:

10:13:41 PM Honeydukes: Starting deployment...
10:13:42 PM Honeydukes: Uploading zip package to storage container...
10:18:26 PM Honeydukes: Starting deployment...
10:18:27 PM Honeydukes: Uploading zip package to storage container...
Deployment to "Honeydukes" completed.
HTTP Trigger Urls:
  WarmUp: https://honeydukes.azurewebsites.net/api/WarmUp
****

The portal also showed up WarmUp API and when GET request was sent to it, it responded 200OK Warmup complete. None of my function API's got deployed.

![image](https://user-images.githubusercontent.com/10415876/46058926-da8bcd00-c111-11e8-97ed-9fcea97850d2.png)

**Comment by asavaritayal** [comment]
This issue was moved to Microsoft/vscode-azurefunctions#668

**Comment by asavaritayal** [comment]
This issue was moved to Microsoft/vscode-azurefunctions#669
