### ISSUE TITLE
"func azure functionapp publish" gives error code 400

### ISSUE THREAD

**Issue by ErlendFax** [Azure/azure-functions-python-worker#214]
I have followed every in the tutorial, but when I run `func azure functionapp publish myApp`, it returns:
`Response status code does not indicate success: 400 (Bad Request).`

What does this mean? How can I debug this error? Anyone else experiencing this? 

EDIT:

Found out I can add `CLI_DEBUG=1` which gave me:

> GET https://management.azure.com/subscriptions?api-version=2014-04-01
> GET https://management.azure.com/subscriptions?api-version=2014-04-01
> GET https://management.azure.com/subscriptions?api-version=2014-04-01
> GET https://management.azure.com/subscriptions?api-version=2014-04-01
> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
>    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
>    at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload)
>    at Azure.Functions.Cli.Helpers.AzureHelper.GetFunctionApp(String name, String accessToken)
>    at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync()
>    at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container)

EDIT 2:

I tried pushing an that does not exist, `func azure functionapp publish myBSApp`, same response, could this indicate an error with the "connection" between me and Azure?  

EDIT 3:

I tried another method of getting this up in Azure. When I run `az functionapp deployment source config-zip  -g myRG -n myApp --src myFiles.zip`, I get:

> Failed to retrieve Scm Uri
> Traceback (most recent call last):
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
>     six.reraise(*sys.exc_info())
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
>     result = cmd(params)
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
>     return self.handler(*args, **kwargs)
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
>     result = op(**command_args)
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 170, in enable_zip_deploy
>     scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 1153, in _get_scm_url
>     raise ValueError('Failed to retrieve Scm Uri')
> ValueError: Failed to retrieve Scm Uri

I can't reach Kudu (Scm). Neither here or with Portal.

**Comment by asavaritayal** [comment]
@ErlendFax Are you able to view the Function App in the Azure portal? If so, can you please share the app name?

/cc @ahmelsayed

**Comment by ErlendFax** [comment]
Yes, I can see it. However, I can not enter/use Kudu, among a few other features under the Platform features in Portal.  Name: erlendapp

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-core-tools#778
