### ISSUE TITLE
Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by tjhgit** [Azure/azure-functions-python-worker#217]
I followed the steps of https://github.com/Azure/azure-functions-python-worker/wiki/Create-your-first-Python-function exactly.

The only thing I did differently is to use for the following command: " az functionapp createpreviewapp ..." not the location but the -plan (Here I used a basic app plan). The location parameter let to a 500 HTTP error.

So I get the HTTP function app running on azure BUT when switching the view in the portal to the function I get a red error banner with the following content:

Error:

Function (HttpTriggerPython) Error: Object reference not set to an instance of an object.
Session Id: fcca4b76f9934abba81c6a45c584f4b1

Timestamp: 2018-10-06T21:54:01.295Z

**Comment by tjhgit** [comment]
The azure function app is called: "hme1salesfc2".

The error is as described above:

Error:

Function (HttpTriggerPython) Error: Object reference not set to an instance of an object.
Session Id: f860b3f01bab4f70b4fe922d6ddd0f08

Timestamp: 2018-10-07T14:43:37.470Z

**Comment by bala16** [comment]
@tjhgit Is there a specific reason to use linux function app on dedicated app service plan or were you intending to use consumption linux app?

If either works for you can you try the consumption linux app using the instructions from https://functionscdn.azureedge.net/public/docs/linux-consumption-preview.html
( when creating the functionapp using az cli skip the plan and specify a region (East US/ West US)

Let us know if you have any questions or if you want to proceed with dedicated linux function app.

**Comment by tjhgit** [comment]
@bala16 my azure function is written in python. Does a consumption linux app work then? If yes, why is this better than the dedicated app service plan? Why would the former not lead to errors?

**Comment by bala16** [comment]
Yes. Python functions do work on consumption linux app. Refer to the following links to get started
https://functionscdn.azureedge.net/public/docs/linux-consumption-preview.html
https://github.com/Azure/azure-functions-python-worker/wiki

Here is some information on the differences between consumption and app service plans in general - https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale

We have made some improvements to the platform in consumption linux which are not available on dedicated app service plan linux apps yet. So please give consumption app a try and let us know your feedback.

**Comment by tjhgit** [comment]
Thanks. That works indeed! Is this also available and working in WestEurope?

**Comment by bala16** [comment]
Yes. It is available in West Europe. Right now they are running on one core per instance. We can definitely investigate if you notice any issues when running your app.

**Comment by tjhgit** [comment]
For WestEurope however I get an http error, when issuing this command:
`az functionapp createpreviewapp -n ds1consumptionapp -g DataScienceIS -l "WestEurope" -s ds1consumptionappstorage --runtime python --is-linux`. No problems with WestUS.

`Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/93a43d93-10d7-4439-bae3-544b173c9c6c/resourceGroups/DataScienceIS/providers/Microsoft.Web/sites/ds1consumptionapp?api-version=2018-02-01 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/93a43d93-10d7-4439-bae3-544b173c9c6c/resourceGroups/DataScienceIS/providers/Microsoft.Web/sites/ds1consumptionapp?api-version=2018-02-01 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 342, in send
    response = http_driver.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 187, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/93a43d93-10d7-4439-bae3-544b173c9c6c/resourceGroups/DataScienceIS/providers/Microsoft.Web/sites/ds1consumptionapp?api-version=2018-02-01 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 366, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 54, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/f43995/.azure/cliextensions/functionapp/azext_functionapp/custom.py", line 113, in create_function
    poller = client.web_apps.create_or_update(resource_group_name, name, functionapp_def)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/web/operations/web_apps_operations.py", line 332, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/web/operations/web_apps_operations.py", line 277, in _create_or_update_initial
    response = self._client.send(request, stream=False, **operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 369, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 54, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 342, in send
    response = http_driver.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 187, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/93a43d93-10d7-4439-bae3-544b173c9c6c/resourceGroups/DataScienceIS/providers/Microsoft.Web/sites/ds1consumptionapp?api-version=2018-02-01 (Caused by ResponseError('too many 500 error responses',))`

**Comment by bala16** [comment]
Looks like the resource group already has some apps leading to conflict. Could you try again with a different(new) resource group.

**Comment by tjhgit** [comment]
@bala16 ok that worked. The error code from python could be more intuitive ...

Now since I am using python packages that are not available as binaries, I tried to use:
func azure functionapp publish someappname --build-native-deps.

However the so deployed apps fails with the following error:

> Error:
> 
> Function (azure) Error: Failed to start language worker process for: python. bash exited with code 1 ModuleNotFoundError: No module named 'azure.functions'.
> Session Id: 8d8635558e39419495ca4f13982e5605
> 
> Timestamp: 2018-10-15T19:37:27.171Z

Also it takes quite some time until the azure function gets deployed. 

Can I not somehow just use a docker container and deploy this as an azure function, as described here: https://markheath.net/post/azure-functions-docker.

**Comment by bala16** [comment]
Are you also getting the error when running locally using the Azure Functions core tools? Can you also share the app name? Thanks.

**Comment by tjhgit** [comment]
Actually I switched again to the managed plan and build my own docker container based off 
FROM microsoft/azure-functions-base:2.0.12121.

I tested the docker image locally and it runs fine server_dns/api/forecast_func?name=func.

However when deploying the docker image I get the following error once the parallel part of the code starts:

> Result: Failure
> Exception: RuntimeError: 'MSI_ENDPOINT' required env variable was not found. You might need to restart your app/function.
> Stack:   File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 264, in _handle__invocation_request
>     self.__run_sync_func, invocation_id, fi.func, args)
>   File "/root/.pyenv/versions/3.6.4/lib/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 319, in __run_sync_func
>     return func(**params)
>   File "/home/site/wwwroot/forecast_func/main.py", line 19, in main
>     name += '&' + main_forecast(0)
>   File "/home/site/wwwroot/forecast_func/forecast_parallel.py", line 197, in main
>     list_obj = list(executor.map(func, unique_ts_core))
>   File "/root/.pyenv/versions/3.6.4/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
>     for element in iterable:
>   File "/root/.pyenv/versions/3.6.4/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
>     yield fs.pop().result()
>   File "/root/.pyenv/versions/3.6.4/lib/python3.6/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/root/.pyenv/versions/3.6.4/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception

Is concurrent futures not supported?

**Comment by bala16** [comment]
@tjhgit Please include app name so we can investigate. Did restarting the site help?

I would still like to understand why consumption plan didn't work for you. If possible could you deploy your app to consumption plan using the instructions above and let us know the app name.. Also verify if you are seeing the same issue when running locally using Azure functions core tools.

**Comment by asavaritayal** [comment]
@tjhgit Both dedicated and consumption use exactly the same underlying docker image. Here's the Dockerfile if you'd like more details - https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/python.Dockerfile. All the drivers required for `pyodbc` are pre-installed in this image. Please let us know if you still run into any issues though!

Thanks.

**Comment by tjhgit** [comment]
Thanks for the link to the Dockerfile.
