### ISSUE TITLE
Typo in Python Wiki

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-python-worker#218]
Method | Description
-- | --
logging.critical(message) | Writes a message with level CRITICAL on the root logger.
logging.error(message) | Writes a message with level ERROR on the root logger.
logging.warning(message) | Writes a message with level WARNING on the root logger.
logging.info(message) | Writes a message with level INFO on the root logger.
logging.debug(message) | Writes a message with level **CRITICAL** on the root logger.

Bolded CRITICAL should be replaced with DEBUG.

**Comment by maiqbal11** [comment]
@asavaritayal could you make the change?

**Comment by asavaritayal** [comment]
Done, thanks for pointing out!
