### ISSUE TITLE
Functions hangs when trying to read stream from URL

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#221]
This issue happens on my Mac locally. I am unable to isolate the cause.
Attached is the zip file of my function, it inferences Tensorflow InceptionV3 model

Added sample code in __init__.py to read from img url (followed predict shark example) but when running the function, it hangs - breakpoint revealed it hangs while trying to do urllib read:

```
image_url = req.params.get('img')
image_data = urllib.request.urlopen(image_url).read()
```

Unzip the attached file and just create a virtual environment and pip install to see the results.
[TEST.zip](https://github.com/Azure/azure-functions-python-worker/files/2467454/TEST.zip)

This problem was steadily reproducible if a wrong file path was given to tensorflow's File open method,

 outside of functions it fails, but within functions it hangs.

**Comment by priyaananthasankar** [comment]
Identified issue as being 403 forbidden when trying to read an image url without proper headers. I identified this by trying this out with Python shell which clearly tells me 403 forbidden, but python functions just hangs. Here is a snippet of code to try out:
**Scenario 1**

```
user_agent_header = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.19 (KHTML, like Gecko) Ubuntu/12.04 Chromium/18.0.1025.168 Chrome/18.0.1025.168 Safari/535.19'
**req_img = urllib.request.Request(image_url, headers={'User-Agent': user_agent_header})**
response_img = urllib.request.urlopen(req_img)
image_data = response_img.read()
```
Now remove the user_agent header in the line in bold above and function hangs.

**Scenario 2**

Try to read a file with wrong path using Tensorflow:

For eg: model_file is the absolute path to a model, just make it an invalid path. Function hangs.
```
with tf.gfile.FastGFile(model_file, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    _ = tf.import_graph_def(graph_def, name='')
```

**Comment by elprans** [comment]
@priyaananthasankar Can you elaborate on what you mean by "function hangs".  The scenarios you listed generate a Python exception, which is propagated to the host as a `Microsoft.Azure.WebJobs.Host.FunctionInvocationException`, and the function execution is terminated.  We have a test for that in the suite:

https://github.com/Azure/azure-functions-python-worker/blob/659c9772c00c39f12dbf6117a698ad96f1c2cbf4/tests/http_functions/unhandled_error/main.py#L1-L5

**Comment by priyaananthasankar** [comment]
@elprans : No errors are thrown. Last seen log will be "Python HTTP trigger function processed a request" Basically nothing happens. The Postman or CURL will just be executing saying "Loading" etc without any response.

**Comment by elprans** [comment]
This is indeed a bug in the worker.  Certain user exceptions crash the worker.  #225 should fix this.
