### ISSUE TITLE
Update CI to use latest CLI from storage account

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#222]
CLI builds that include the latest functions runtime  are available on 

```
https://functionsclibuilds.blob.core.windows.net/builds/2/latest/Azure.Functions.Cli.{platform}.zip
```

where platform in `linux-x64, osx-x64, win-x64, win-x86`

You can also get the version from 

```
GET https://functionsclibuilds.blob.core.windows.net/builds/2/latest/version.txt
```

Update CI to use latest CLI. This will eliminate the need to send PRs for every runtime release.

**Comment by pragnagopa** [comment]
cc: @asavaritayal @maiqbal11

**Comment by elprans** [comment]
I'm on the fence about this. Pinning the dependency version explicitly gives certain consistency across the development environments and the CI.  If we always test against the latest it might be harder to pinpoint the breakages.

**Comment by pragnagopa** [comment]
Unfortunately, the current process we have is too late to catch any regressions in the Functions Host.  Nightly scheduled CI runs with the latest host would help. Your thoughts?

**Comment by pragnagopa** [comment]
CLI is uploaded to storage only for a release. This is a not a daily upload from the dev branch. Using this feed will gives us a heads up on any regressions before the host release.

**Comment by soninaren** [comment]
> I'm on the fence about this. Pinning the dependency version explicitly gives certain consistency across the development environments and the CI. If we always test against the latest it might be harder to pinpoint the breakages.

@elprans , The latest bits has a corresponding version that you can find at `https://functionsclibuilds.blob.core.windows.net/builds/2/latest/version.txt`. You can always document the CLI version with the test run. That should enable us to pin point breakages

**Comment by soninaren** [comment]
> CLI is uploaded to storage only for a release. This is a not a daily upload from the dev branch. Using this feed will gives us a heads up on any regressions before the host release.

To clarify, we have 2 places where CLI is uploaded. One for CI tests, which is mentioned in this issue and second place for actual release.

**Comment by pragnagopa** [comment]
Ping! We have a runtime release coming up. Please address this soon. Adding a scheduled nightly build that uses the CLI works as well.

**Comment by maiqbal11** [comment]
Chatted with @soninaren  on some of the points that @elprans raised in today's Python sync. 

Elvis, you mentioned that you are currently using the Debian/Ubuntu artifact (`linux-x64`) for the CLI. This should be generated automatically whenever someone commits to the CLI repo and would be placed in **https://functionsclibuilds.blob.core.windows.net/builds/2/latest/Azure.Functions.Cli.linux-64.zip**. This is a self-contained package and should not require a .NET SDK installation to be used (@soninaren  to keep me honest here). Using this for Python Worker CI should allow earlier catches for issues as compared to using the release version.

**Comment by elprans** [comment]
I'm getting a 404 on the URL now.

**Comment by asavaritayal** [comment]
Here's the revised URL - https://functionsclibuilds.blob.core.windows.net/builds/2/latest/Azure.Functions.Cli.linux-x64.zip

**Comment by asavaritayal** [comment]
Update from sync: @fabiocav to provide more info on setting up secrets with the storage build.

**Comment by maiqbal11** [comment]
Further elaborating on what the purpose of using the CLI would be. Currently, the tests are being run with direct communication between the worker and the host (i.e. runtime). This requires the management of secrets so that endpoints can be called. Using the CLI to start the host (i.e. `func host start`) and then running against that host, however, is an anonymous scheme and would not require the management of secrets. 

Ideally, we would be testing paths that also exercise the use of secrets but the priority right now would be to use the CLI so that we can exercise the latest bits and be able to catch issues sooner than we would otherwise be able to.  

To put this concretely, this would require a move away from starting the host without using the CLI and, instead, rely on the CLI to manage the host. This way the latest CLI and host can be used along with the worker to exercise more of the latest bits.

**Comment by elprans** [comment]
@asavaritayal @maiqbal11 What about the extensions we currently install to test various bindings?  Currently, we pin these to specific versions, since `func extensions install` seems to require a specific version.  It seems inconsistent that we test on the latest CLI/host, but not the latest extensions.

**Comment by pragnagopa** [comment]
@elprans - Good point. If extensions.csproj is not present, `func extensions install` will get the latest versions.

**Comment by elprans** [comment]
@pragnagopa We have multiple test apps and we symlink the compiled extensions to each app.  We need a way to install the latest versions of the extensions by name.

**Comment by pragnagopa** [comment]
@elprans - You can use command `func extensions install --force` to force the cli to fetch the latest extensions.

**Comment by asavaritayal** [comment]
Update from sync: You should be able to create an extensions.csproj with dummy version numbers. `func extensions install --force` will ignore the versions and install the latest versions of all the listed extensions.

**Comment by maiqbal11** [comment]
> Update from sync: You should be able to create an extensions.csproj with dummy version numbers. `func extensions install --force` will ignore the versions and install the latest versions of all the listed extensions.

I believe this should be possible but still need to confirm and also see if this is the official way of achieving this.

**Comment by pragnagopa** [comment]
Yes. `func extensions install --force` is the way to get the latest extensions.

**Comment by elprans** [comment]
@pragnagopa Is there a way to determine the required version of .NET for the latest host build?

**Comment by pragnagopa** [comment]
I do not know if there a any other way apart from looking at the `<TargetFramework></TargetFramework>` on the webhost project.

Host generally moves to the latest minor version on a regular basis. As long as the CI installs the latest 
version, tests should be ok.

**Comment by anirudhgarg** [comment]
I am assuming this was for ease of testing. We already have created a pipeline for testing. closing this out.

**Comment by soninaren** [comment]
Core tools build is still uploading binaries for every build to storage for this. If those bits are not consumed we should remove that part of logic. Mainly because it is adding considerable time to the core tools builds.
