### ISSUE TITLE
Perf issues - prelim solution for s400 customer

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#223]
Email thread

**Logs:**  
[PythonFunctionsLogs.zip](https://github.com/Azure/azure-functions-python-worker/files/2475209/PythonFunctionsLogs.zip)

 
Hi @Ahmed ElSayed and @Asavari Tayal,
 
Apologies, after Ahmed sent out the local functions question, I realized I need to try load testing local as well. So I found some more interesting observations,
 
There seems to be two kinds of problems here:
 
Local performance over a set of 50 subsequent requests where
each request uses urllib library and loads an image is same as the performance on the server – averaging at 9-11 secs, and somewhere it hangs and doesn’t proceed further.
Each request loads the same image file from within the functions folder. (system path) performs worse. See image 1b –its loading the same file from same path for each request, yet the performance degrades pretty quickly
Azure server performance of a set of 50 subsequent requests using urllib library –
same as result 1a (as of Oct 12 afternoon and Oct 13)
As of Oct 12 morning when look at image 2b. That has similar local performance.
 
Problem 1 seems to be an issue with the Azure Functions Worker is causing a bottleneck with http libraries (urllib, requests library)
Problem 2 seems to be an issue with server too - I see that app insights does not show any information for CPU,RAM etc for linux app server. Attached a screenshot of this.
 
Debug information:
App name: https://inditexapp.azurewebsites.net  
Attached a zip contains the function + script that is used to test this.
script_test_time.py (change url accordingly here). If it completes it generates a graph.
In the InceptionV3Classifier functions folder download all the files from here to get the function running properly:  https://github.com/taey16/tf/tree/master/imagenet
 
Meanwhile I will try to isolate the issue as well.
 
Priya
 

 
Hi all,
 
Heads up.
 
We were able to do some image classification from InceptionV3 (Googlenet model) that is trained using Tensorflow library. The customer while def needing a better cold start is OK with the current 10 sec start, but the subsequent calls average between 8-9 seconds when its warm on Azure – which is raising eyebrows.
 
Function isn’t intense, should execute in sub seconds.
 
Here are some graphs from app insights and matplotlib:
 
The inceptionv3 model is a pb file packaged along with the function
Image is read as bytes from the URL – pretty typical stuff for ML inference.
 
Any quick pointers?
 
Regards
Priya

**Comment by asavaritayal** [comment]
@priyaananthasankar there was a bug in the language worker related to exception handling from urllib. @elprans has checked in a fix here - https://github.com/Azure/azure-functions-python-worker/commit/6068092982479932f1d2d3c315ee6835cdeac8c1 . Should be available with the next PyPI release.
