### ISSUE TITLE
Durable Functions Support for Python

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#227]
New Feature - Looking for votes and/or user input to gauge traction.

**Comment by priyaananthasankar** [comment]
+1 Absolutely needed. Working on a small sample with asyncio to simulate something similar.

**Comment by yokawasa** [comment]
+1 Yes needed!  Python has many choice of data science libraries and it definitely has long running & stateful scenario!

**Comment by tjhgit** [comment]
I am experimenting with triggering an azure batch job from an azure function. So this is completely asynchronous and you can also scale up the compute ressources easily in azure batch.

**Comment by mataralhawiti** [comment]
+1 Absolutely

**Comment by SaschaSchlemmer** [comment]
+1 for long running analytics/ML jobs

**Comment by Sarah-Aly** [comment]
This is absolutely a needed feature. I do have a customer who uses Python in Azure Functions for manipulating CSVs & creating time series with Pandas and they are an ideal case for function chaining in DF.

**Comment by t-eckert** [comment]
+1 Happy to contribute

**Comment by nroypf** [comment]
+1 Need it asap :)

**Comment by dajor** [comment]
+1

**Comment by FlippieCoetser** [comment]
currently running large data transformations with Python. Execution time is around 30 min. Having durable functions will help a lot!

**Comment by ericdrobinson** [comment]
I'm saddened to see that Python support for Durable Functions isn't available yet. I've chronicled my efforts to make my usage of the HTTPTrigger more effective/efficient for my workflow in the comments of issue #236. The documentation, however, [keeps suggesting](https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices#avoid-long-running-functions) that I take the [Durable Functions route](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-concepts#async-http) for a more reasonable experience.

Unfortunately, it looks as though I'll need to re-implement Durable Functions manually if I want to gain the suggested benefits of that approach :(

+1, indeed.

**Comment by explora21** [comment]
+1, of course

**Comment by SpicySyntax** [comment]
+1, This would be very useful for long running ML Workloads

**Comment by reynoldsa** [comment]
Absolutely +1.

**Comment by bigdatamoore** [comment]
+1 agreed.  We could use this now.

**Comment by jaryder** [comment]
+1 - Is there a timeline for when this will be available?

**Comment by svartkanin** [comment]
+1 - Definitely needed

**Comment by whataride** [comment]
+1 - Absolutely needed!

**Comment by rodbutters** [comment]
+1 - this is a MUST HAVE!

**Comment by deepbass** [comment]
This could pretty much replace spark for me, and make the dev cycle much faster because spark is much harder to write than normal python (java stack traces inside python ones anyone?)

**Comment by shanjin14** [comment]
+1

**Comment by Godase** [comment]
+1 - Absolutely needed!

**Comment by nk-gears** [comment]
Happy to contribute and looking for some update on this.  Not sure whether this repo https://github.com/kashimiz/azure-functions-durable-python is official for Durable functions

**Comment by rcarmo** [comment]
Oh please, please, PLEASE. I've been trying to do some things in Node and there are no libraries to handle what I need.

**Comment by Zieg** [comment]
+1
100% Absolutely necessary!

**Comment by anujku** [comment]
I guess this is not going anywhere even after a year ! :(

**Comment by dduransseau** [comment]
As @Sarah-Aly I do have some use case where pandas is used to manipulate multiple DataFrame and where workflow could be simplified with Durable Function.

**Comment by KonoMaxi** [comment]
We use Python Functions for small ETL processes with pandas. Durable functions would help to very elegantly structure the individual steps.

I wrote a small python package that handles chaining for me...
It transparently sends messages to queues, which preceeding jobs listen to, and monitors the execution status in an storage-account table.

All in all it works, but it feels real dirty :-(

**Comment by Zieg** [comment]
> I wrote a small python package that handles chaining for me...
> It transparently sends messages to queues, which preceeding jobs listen to, and monitors the execution status in an storage-account table.
> 
> All in all it works, but it feels real dirty :-(

Can you share it? I'm really interested in how this might be achieved, and quick-and-dirty code is nothing to be ahsamed of =)

**Comment by ubikusss** [comment]
+1

**Comment by rkaderli** [comment]
++ Yes, please!

**Comment by KonoMaxi** [comment]
> Can you share it? I'm really interested in how this might be achieved, and quick-and-dirty code is nothing to be ahsamed of =)

https://gist.github.com/KonoMaxi/b63f184bad7ffccbdcc4d818da7b6ee9

**Comment by sasukeh** [comment]
+1

**Comment by Zieg** [comment]
> See gist. Source for jobmanager + short readme + usage examples.
> 
> https://gist.github.com/KonoMaxi/b63f184bad7ffccbdcc4d818da7b6ee9

Awesome! Thanks a lot!
(Also - your code is not bad at all!!! Do not be ashamed =))

**Comment by C4P-KorbenDallas** [comment]
+1 ! happy to contribute if needed. Actually i was thinking to use JS for Durable Functions and trigger my python non-durable functions from it with HTTP requests, anyone have used this or a better approach? Thanks in advance!

**Comment by anthonychu** [comment]
As @anirudhgarg mentioned, we've started work on supporting Durable Functions. We would love to hear more details about what [patterns](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview) you plan on using and what you'll be doing with it.

**Comment by shanjin14** [comment]
> As @anirudhgarg mentioned, we've started work on supporting Durable Functions. We would love to hear more details about what [patterns](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview) you plan on using and what you'll be doing with it.

Hi Anthony, for my use case, i am calling Azure Function in ADF for some data processing related task .
So two patterns i am plan on using is Async API and function chaining.
Mainly to avoid the 2.5 minute API timeout as the file is too big or the job takes longer time to finish

**Comment by deepbass** [comment]
> As @anirudhgarg mentioned, we've started work on supporting Durable Functions. We would love to hear more details about what [patterns](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview) you plan on using and what you'll be doing with it.

I'd be looking at the usual patterns that I'd do with Durable Functions in C#/JS but being able to take advantage of Python's much larger ecosystem of ML/AI libraries - e.g. loading documents and then running NLP models over it to extract information before sending the results on to another service/human. To me it will also move a few workloads from DataBricks PySpark - generally filling the gap where the demands are beyond an individual function but really don't need the firepower & faff of a full Spark Cluster - bringing improved reliability, more straightforward & dependable programming and serverless operation. 

It'd be interesting to see how parallel training of an ML model could be achieved using something like durable entities combined with overriding the threading behaviour and instead spinning up activity functions. No idea if that would work or if the latency cost would be too high but would be cool to investigate.

**Comment by bigdatamoore** [comment]
We could also use it for the same patterns as Daniel mentioned. There’s a
ML pattern called the Rendezvous pattern that this would be helpful for.

**Comment by Zieg** [comment]
Chaining, Async API and Long-running functions are the most needed in our project, Thanks!

**Comment by C4P-KorbenDallas** [comment]
In my project, we would use the Fan out/fan in pattern to orchestrate the execution of different Functions which extract data from different sources, then it's evaluated to check for security settings and finally it's loaded to a database. Actually we're doing this orchestration with logic apps but we would prefer to move to ADF to get advantage of stateful and easy to maintain than logic apps.

**Comment by rcarmo** [comment]
I would love to do a similar pattern with Python on Linux Functions and add some statistical processing with scipy. Eventually, even evaluating ensembles of Tensorflow models...

**Comment by mattc-eostar** [comment]
Potential workaround:
Create a python function app with a custom linux image or host it on a premium plan (I think this switches billing to cost per sec vs cost per execution). This should remove the timeout right?

Then within that function app use async requests and manually call the functions you need for your distributed computing. The custom image on premium will run as long as needed and will be able to orchestrate the calls.

Would this not work?

**Comment by mattc-eostar** [comment]
@tjhgit
> I am experimenting with triggering an azure batch job from an azure function. So this is completely asynchronous and you can also scale up the compute ressources easily in azure batch.

@priyaananthasankar 
> +1 Absolutely needed. Working on a small sample with asyncio to simulate something similar.

Any luck in these adventures?

**Comment by mattc-eostar** [comment]
"early next calendar year"
https://github.com/MicrosoftDocs/azure-docs/issues/42555#issuecomment-553783372

**Comment by Zieg** [comment]
@mattc-eostar not really. Depends on how you trigger your function. If you use http trigger - then you are limited by 4 minutes timeout. Function should execute and return output within this limit, otherwise it fails. And if you want to trigger your function from Data Factory (for example)  - you are pretty much limited to http triggers.

**Comment by mattc-eostar** [comment]
> @mattc-eostar not really. Depends on how you trigger your function. If you use http trigger - then you are limited by 4 minutes timeout. Function should execute and return output within this limit, otherwise it fails. And if you want to trigger your function from Data Factory (for example) - you are pretty much limited to http triggers.

Is this true even for functions hosted on premium plan? They advertise no limit on execution time.

**Comment by anthonychu** [comment]
HTTP triggers have a [230 second timeout](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout) for how long the request can stay open. If you need to use the max function duration (up to 10 mins consumption, 60 mins Premium, "unlimited" on other plans), the HTTP function can drop a message on a queue that a longer-running queue triggered function can process. Durable Functions does this behind the scenes, and adds the ability to checkpoint progress and aggregate results.

We're targeting early 2020 for a preview of Durable Functions for Python.

**Comment by mattc-eostar** [comment]
I see what you are saying. Yes. I was operating under the assumption my use case would be using queues regardless. And great to hear. Look forward to working with that.

**Comment by gbonventre** [comment]
I need  Async API and Long-running functions. Also long-running functions that can do fan in and fan out from a queue would be perfect for many of the ETL applications my employer is currently working on.

**Comment by markl11** [comment]
"We're targeting early 2020 for a preview of Durable Functions for Python." - given that quite a few folks can't put preview features into production, when are you actually thinking that Durable Functions for Python will be GA? (frustratingly, preview features in Azure can be preview for a looooong time in my experience so I hope this will be different)

**Comment by cgillum** [comment]
@markl11 we're targeting the first half of 2020 for the GA release - i.e. no later than June, assuming things go relatively smoothly with the preview.

**Comment by WrittenLabyrinth** [comment]
+1 working on a prototype app in python and a durable function in Azure would be awesome!

**Comment by CalebHui** [comment]
+1

**Comment by anthonychu** [comment]
Just a quick update as we've been hearing from a lot of folks who can't wait to try this. Python Durable Functions is currently on track for a preview in a month or two. It'll support the core [5 workflow patterns](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp#application-patterns), with the exception of durable entities.

**Comment by anthonychu** [comment]
Reopening this as we're using this issue to track progress of Python Durable Functions support.

**Comment by Flozker** [comment]
@anthonychu any updates on when the preview will be released?

**Comment by anthonychu** [comment]
Waiting for some bits to be released in Core Tools and deployed to the service in Azure. Could have something you can try running locally in the next week or two.

**Comment by Flozker** [comment]
That's really cool! I'm planning to use durable functions to host a tensorflow model for computer vision, or do you think I should host it in AzureML and call it from a function instead?

**Comment by MattConflitti** [comment]
Try it and see! Python durable functions is going to open up a lot of doors given the orchestration capabilities. From smaller scale data pipelining to serving simpler models, it will be exciting to see how it stacks up in usability and pricing. Both of which are suspected to be great.

**Comment by anthonychu** [comment]
Hey everyone. Thanks for your patience. You can now try out Durable Functions in Python here:
https://github.com/azure/azure-functions-durable-python 🎉

There are a few pieces to release in tooling and deploy to our service before we can announce a public preview. For now, check out the [readme](https://github.com/azure/azure-functions-durable-python#durable-functions-for-python) for the current limitations and instructions on how you can try it out today.

We look forward to getting some early feedback. Please create issues [here](https://github.com/azure/azure-functions-durable-python/issues). Thanks!

**Comment by wasuaje** [comment]
+1 Here for needing this !

Thanks for the preview

**Comment by anthonychu** [comment]
Python Durable Functions is now in public preview. 🎉 Thanks for your patience everybody. Please use https://github.com/Azure/azure-functions-durable-python for feedback.

Announcement: https://azure.microsoft.com/updates/durable-functions-now-supports-python/

**Comment by StevenBorg** [comment]
Congratulations!!!!  This is great news. I've been forced to rewrite functions in C# just to get Durable Functions.  The pain of switching from Python to C# was less than dealing with coordinating my own fan-out/fan-in. Thank you!  Back to Python!

**Comment by priyaananthasankar** [comment]
> That's really cool! I'm planning to use durable functions to host a tensorflow model for computer vision, or do you think I should host it in AzureML and call it from a function instead?

You can use AML to host or run ML batch processes and then use durable to orchestrate the pipeline through monitoring pattern. Check the samples in the repo for this use case.

**Comment by Hazhzeng** [comment]
The Python Durable Functions is currently in Preview https://azure.microsoft.com/en-us/updates/durable-functions-now-supports-python/

Closing this thread as we're redirecting the related discussion to the new durable python repo https://github.com/Azure/azure-functions-durable-python

Thanks
