### ISSUE TITLE
Add support for custom routes / URL segment values for HTTP Triggers.

### ISSUE THREAD

**Issue by sjwaight** [Azure/azure-functions-python-worker#228]
It appears that the current WIP of the HTTP Trigger and Python v2 support doesn't yet allow developers to use custom routes that expose URL segments as values a developer can use in their Python Function.

Repro:

1. Create a HTTP Trigger with current in-preview tooling.
2. Modify route field in function.json (sample shown below):

```json
{
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "route": "mymethod/{prop1}/{prop2}/{start:int}/{end:int?}",
      "name": "req",
      "methods": [
        "get"
      ]
}
```
3. Attempt to access any of the URL values as variables / properties of the 'req' object.
4. 🤔

Expected:

You should, at a minimum, be able to find the segment values on the context object similar to the experience for Node developers today.

As a work around you can manually parse the URL, but this feels clunky and error prone.

**Comment by asavaritayal** [comment]
You can use the `route_params` property to obtain the values in the URL segments. Example below - 

```python
import logging

def main(req):
   
    prop1 = req.route_params['prop1']
    logging.info(f'First URL segment: {prop1}')


```

**Comment by sjwaight** [comment]
Appreciate it's still in early preview, but some documentation for this in the Developer Guide would be awesome (I'm happy to write but it looks like the wiki can't be forked).

**Comment by asavaritayal** [comment]
@sjwaight thanks for the feedback. I'll make sure to add the relevant points to the Developer Guide. 

For future reference, here's a link to the azure.functions HTTP API - https://docs.microsoft.com/en-us/python/api/azure-functions/azure.functions.httprequest?view=azure-python
