### ISSUE TITLE
InputStream BytesIO object missing seek operation.

### ISSUE THREAD

**Issue by jmo808** [Azure/azure-functions-python-worker#230]
I am unable to load serialized objects either with pickle or joblib as the InputStream object from the Blob extension does not expose the seek operation.

```
Exception: UnsupportedOperation: seek
```

**Comment by asavaritayal** [comment]
Update from sync: we won't be supporting seek as an in-built operation on InputStream, given the potential conflicts with real stream support in the future. 

@elprans can you please provide guidance on how to configure this on the user side?

**Comment by jmo808** [comment]
I worked around it by connecting to blob storage via the REST API but it’s obviously a bit more work than relying on the functions framework. Pickle and joblib require obj.seek(0) before loading the BytesIO object or they fail to load claiming a serialization error.  This prevents the loading of sklearn models from blob storage if you are using an InputStream. (And probably keras too).

Jules

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by asavaritayal** [comment]
Adding to the backlog. Two separate work items required here: 

1. Document how to use seek with InputStream. 
2. Add functionality for seek(0) as a special case.

**Comment by KarFan-FS** [comment]
+1

**Comment by Hazhzeng** [comment]
This .seek() operation here is useless since the function host does not support data streaming. Data streaming is stateful as this is anti-serverless pattern ([best practice here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices#write-functions-to-be-stateless)). We don't have plans to support this in the near future.
