### ISSUE TITLE
MSI support for linux consumption

### ISSUE THREAD

**Issue by tjhgit** [Azure/azure-functions-python-worker#232]
I can set an identity (az functionapp identity assign) for my function app and register this identity with keyvault.

However when using MSIAuthentification() in the function app I get the error message:
* Getting error “MSI_ENDPOINT not in environment” when running the function app (method: MSIAuthentification())

What am I doing wrong?

**Comment by tjhgit** [comment]
@asavaritayal : Is MSI also not supported for dedicated linux (docker) app plan? What is your suggestion on to how to access keyvault secrets from a linux app, then?

**Comment by mattchenderson** [comment]
@tjhgit We're hoping to have it supported for dedicated Linux very soon. Certainly by end of year.

**Comment by asavaritayal** [comment]
This issue was moved to Azure/Azure-Functions#1066
