### ISSUE TITLE
Adding pathlib==1.0.1 to requirements.txt causes worker to fail with 500 in the server

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-python-worker#233]
#### Investigative information
The error seen on the portal was:

[Error] Executed 'Functions.HttpTrigger' (Failed, Id=4dab531b-bebe-42f6-8f67-e391ee857b4f)
Result: Failure
Exception: TypeError: expected str, bytes or os.PathLike object, not PosixPath
Stack:   File "/home/site/wwwroot/worker_venv/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 203, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/home/site/wwwroot/worker_venv/lib/python3.6/site-packages/azure/functions_worker/loader.py", line 43, in load_function
    register_function_dir(dir_path.parent)
  File "/home/site/wwwroot/worker_venv/lib/python3.6/site-packages/azure/functions_worker/loader.py", line 20, in register_function_dir
    _submodule_dirs.append(os.fspath(path))

This does not happen when running locally. I checked packaging and everything looks good there. I noticed that `loader.py` uses `pathlib`, so maybe it needs a different version of `pathlib` and user installed `pathlib==1.0.1` is taking precedence and causing the issue (not sure)?
#### Repro steps

1. `func init <funcapp>` (select python)
2. `cd <funcapp>`
3. `func new` (select HttpTrigger)
4. `func azure functionapp publish <name> --force`
Everything works fine, the app is working as expected at this point
5. Edit `requirements.txt` and add `pathlib==1.0.1`
6. `func azure functionapp publish <name> --force`
7. Execute the function and receive a 500.

Note: function works fine locally, the problem is just in the server. Publishing with cli is fine too, I checked the zip file being sent, everything seems good there.

#### Expected behavior

Should not receive a 500 error and function should work as expected.

#### Actual behavior

The function gives a 500 status code and portal shows the error mentioned above.

#### Related information 

```txt
azure-functions==1.0.0a4
azure-functions-worker==1.0.0a4
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
pathlib==1.0.1
six==1.11.0
```

**Comment by asavaritayal** [comment]
@elprans can you investigate this?

**Comment by elprans** [comment]
`pathlib` is a standard library module in Python 3.4+ and MUST NOT be installed on later versions.

**Comment by ankitkumarr** [comment]
Thanks @elprans! I will close this issue. 

Out of curiosity, would you know what specifically causes it to fail in the server but not locally?
