### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by bowdenk7** [Azure/azure-functions-python-worker#238]
Having trouble with CORS.

#### Investigative information

Please provide the following:

- Timestamp: 2:14PM November 14th 2018
- Function App name: recommender-test-4
- Function name(s) (as appropriate): GetRecommendations

#### Repro steps

Provide the steps required to reproduce the problem:

1. Deployed [this app](https://github.com/bowdenk7/connect2018-function).
- Returns json as expected: https://recommender-test-4.azurewebsites.net/api/GetRecommendations?code=GHvuTHyv5jd5EsTK44lwQgwTQEwk2PbI6zkS7rugaVVjM7dInG4SQA==

2. Want to access from [another app](https://github.com/bowdenk7/connect2018/blob/master/client/src/views/normal-cart-view/normal-cart-view.js#L82):
```
axios.get(`https://recommender-test-4.azurewebsites.net/api/GetRecommendations?code=GHvuTHyv5jd5EsTK44lwQgwTQEwk2PbI6zkS7rugaVVjM7dInG4SQA==`)
            .then(res => {
                const data = res.data.data.children.map(obj => obj.data);
                console.log(`Response Data: ${data}` );
            }).catch((err, res) => {
                console.log(err);
            });
```

3. Cors error:
![image](https://user-images.githubusercontent.com/820883/48516479-57851a00-e818-11e8-88e1-5b884fa12c57.png)

4. Add `*` cors rule:
![image](https://user-images.githubusercontent.com/820883/48516518-6bc91700-e818-11e8-803a-f13c009e2104.png)

#### Expected behavior

At this point I would expect to see the error disappear.

#### Actual behavior

Request is going through, but error remains. So I can't actually get the body out of the response.
![image](https://user-images.githubusercontent.com/820883/48516594-99ae5b80-e818-11e8-883a-41a27f8871a5.png)

![image](https://user-images.githubusercontent.com/820883/48516675-ccf0ea80-e818-11e8-9fcd-c9ec56a9bd57.png)

#### Known workarounds

Apparently there is a way to add some headers directly to `func.HttpResponse` to make this work? But I can't figure it out...

I could do something like this in JavaScript?

```
module.exports = function (context, req) {
    context.res = {
        status: 200,
        body: "Hello " + req.query.name,
        headers: {
            'Content-Type': 'text/plain',
            'Access-Control-Allow-Origin': 'True'
        }
    };
    context.done();
}
```

**Comment by asavaritayal** [comment]
Here's the API reference for `azure.functions.HttpResponse` - https://docs.microsoft.com/en-us/python/api/azure-functions/azure.functions.httpresponse?view=azure-python

**Comment by maiqbal11** [comment]
You can try adding the headers to specify the missing information as @asavaritayal suggested. If this does not solve the issue, we can look into it some more.

**Comment by michelpf** [comment]
The only way in order to CORS to work is deactivated from Platform Features>API and configure directly to responses in my functions, just like you say. 
That's annoying because, for Python Engine, the CORS configuration in Platform Feature became useless, differently from v1 functions.

**Comment by balag0** [comment]
Yes. agreed. This is a point in time limitation until the platform supports this directly. This workaround will only be needed until then.
