### ISSUE TITLE
Support for metadata in InvocationRequest.trigger_metadata

### ISSUE THREAD

**Issue by 1st1** [Azure/azure-functions-python-worker#24]
`InvocationRequest` message has a `trigger_metadata` field.

For HTTP requests it contains the following:

```
trigger_metadata {
  key: "sys"
  value {
    json: "{\"MethodName\":\"function_name\",
            \"UtcNow\":\"2018-02-20T22:28:20.732233Z\",
            \"RandGuid\":\"610a408d-ff49-48ad-9a03-65be1b518114\"}"
  }
}
```

Do we need to make any of this available via the `Context` or `HttpRequest` objects?

cc @asavaritayal @christopheranderson @pragnagopa

**Comment by pragnagopa** [comment]
Here is an example for  accessing [queue trigger metadata](https://github.com/Azure/azure-functions-host/blob/1ab54a94916c8180105af1e43b24a483f070a53f/sample/QueueTrigger/index.js
). Metadata properties are available by accessing: context.bindingData. We should do the same here.

**Comment by 1st1** [comment]
We've already figured out how to use `triggerMetadata` for queue bindings, so this PR can be now closed.
