### ISSUE TITLE
Add worker.config.json to package metadata 

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#243]
Currently, the `worker.py` and `worker.config.json` files are not published to the `azure-functions-worker` package on PyPI.  This causes confusion in the tooling since it has to install the package from PyPI but pull these specific files from GitHub. 

Ideally, everything should be part of the same package on PyPI. 

@pragnagopa is there a reason this isn't already the case?

/cc @ankitkumarr @ahmelsayed @maiqbal11

**Comment by pragnagopa** [comment]
I have raised this concern earlier. Yes we should include these files. 
@elprans - any blockers to include these files?

**Comment by elprans** [comment]
I was hoping we could get https://github.com/Azure/azure-functions-host/pull/3369 merged so that `worker.py` is not necessary.

**Comment by elprans** [comment]
Also, bundling non-Python stuff with Python packages does not exactly make them easily accessible for outside programs.  The CLI would still have to call into `pkg_resources` to obtain the JSON file path.

**Comment by pragnagopa** [comment]
Can you rebase the PR? Do you have any suggestions for distributing worker.config.json?

**Comment by elprans** [comment]
The worker itself does not need `worker.config.json`, its format is specified and consumed by the host, so it would make sense to keep and distribute it together with the host/CLI builds.  Given the differences in packaging for different languages it seems to be more hassle than it's worth to keep `worker.config.json` with the worker implementation.

**Comment by pragnagopa** [comment]
`worker.config.json` is used by the host to discover language workers. Information provided in this file is specific to the language worker implementation. This is not a stand alone file we can include in host/cli.
Is there a concept of resource files in a pypi package? If yes, we should include `worker.config.json` and we will update the tools to fetch the file from the package

**Comment by elprans** [comment]
The most reliable way to do this with Python would be to distribute `worker.config.json` as part of the package metadata and access it with `pkg_resources`.

**Comment by pragnagopa** [comment]
@maiqbal11 - Once this issue is addressed, CLI and docker images need to be updated to pull `worker.config.json` from pkg_resources

PR https://github.com/Azure/azure-functions-host/pull/3369 needs to be merged as well.

**Comment by maiqbal11** [comment]
Closing as equivalent work is happening in https://github.com/Azure/azure-functions-python-worker/issues/286
