### ISSUE TITLE
Provide guidance for unit testing

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#244]

**Comment by elprans** [comment]
I seems like we mostly need to provide a way to construct mock input for the supported binding types.  #262 is related.

**Comment by asavaritayal** [comment]
Correct - we'll also need a wiki page enlisting examples of how to construct the mock input, best practices for unit testing and suggested CI script with Azure DevOps.

**Comment by elprans** [comment]
I've provided some guidance and examples in the Wiki: https://github.com/Azure/azure-functions-python-worker/wiki/Unit-Testing-Guide
