### ISSUE TITLE
logging.debug() doesn't seem to make it to the logs

### ISSUE THREAD

**Issue by brettcannon** [Azure/azure-functions-python-worker#248]
`info()`, `warning()`, and `error()` all show up in Application Insights, but `debug()` does not. Not sure if this is a worker issue or an Application Insights issue.

**Comment by elprans** [comment]
The default log level is `INFO`, you need to run the worker with `--log-level=DEBUG` to get the debug messages.

**Comment by brettcannon** [comment]
@asavaritayal Probably documenting how to do that for an active, deployed function would be helpful.

**Comment by andrebriggs** [comment]
> The default log level is `INFO`, you need to run the worker with `--log-level=DEBUG` to get the debug messages.

@elprans are you suggesting to do this on deploy? Couldn't an App Config setting also do the trick?

**Comment by elprans** [comment]
I'm not sure core-tools have this wired-in. @ahmelsayed?

**Comment by maiqbal11** [comment]
There are two parts to this issue: (1) The root logger not having the proper level set in the worker and (2) the Functions Host filtering logs that are at the debug level and below. 

1. The issue here is not related to the specification of `--log-level` since that is used for the logger that logs system logs. The user logs are configured to flow over the GRPC channel using the root logger. Currently, the root logger is configured to allow logging down to the `info` level, but not `debug`: 
https://github.com/Azure/azure-functions-python-worker/blob/c1b82d1575c44cf6750f9e3d32baf5a6d619fab2/azure/functions_worker/dispatcher.py#L102
We could modify this to allow logging down to the `debug` level. This won't change the functionality for the system logs since those would still be logged to the `info` level by default. Thoughts, @elprans?

2. Even if we configure the root logger to send debug messages, the host would filter them according to the logic here: https://github.com/Azure/azure-functions-host/blob/7aa2486acf4a46d805b9cceaa22117571a9672e0/src/WebJobs.Script/Extensions/ScriptLoggingBuilderExtensions.cs#L25
@brettsam, can we buy-pass this filtering logic for user debug logs? With this filter in place, users will not be able to log debug messages because it filters out anything below info level.

**Comment by maiqbal11** [comment]
@elprans, we should be fine to keep the system logs at the informational level. Those are already being sent to the table where keep our debugging information. 

As for the original issue noted here, the desired behavior can be achieved with a combination of two steps: 
1. Setting the root logger in user code to use the `debug` level (it is set to to `info` by default).
2. Configuring the `host.json` to log `Debug` messages:

```
{
  "version":  "2.0",
  "logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "default": "Debug"
    }
  } 
}
```
With these changes, the logs should be visible on both the console as well as Application Insights. @asavaritayal, we can make not of this in our development wiki. Changing the logging settings currently would require re-deployment but we might be able to introduce some app settings to achieve this if that's the route we want to go.

**Comment by jeffhollan** [comment]
@asavaritayal just cleaning up old sprint items.  Should this move to current sprint / next sprint with a docs label?

**Comment by shabbyrobe** [comment]
This is still an issue as far as I can see, I just lost quite a bit of time trying to track down why logging.debug() never makes it to the console using azure-functions-core-tools 3.0.2245. The snippet posted earlier does not help; core tools shows its own debug messages but the `logging.debug()` calls from the python worker continue to be swallowed.

If I change this line to DEBUG, I see the output I expect in the console:
https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/dispatcher.py#L122

I tried to follow the suggestion to pass `--log-level=DEBUG` to the worker, but this log level is not included in the argparse setup:
https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/main.py#L19

Furthermore, `azure-functions-core-tools` does not seem to provide a functioning mechanism to actually pass this argument, but my C# is a bit rusty, I have no development environment to use to debug that project on this work machine, and the way the code comes together to construct the config for Microsoft.Azure.WebJobs is a bit inscrutable and stringly-typed, so I couldn't quite follow it without investing significantly more time.

I did manage to discover that I _can_ pass args through to the worker using `--language-worker`, but it's prepend only and shoves the new arguments before the `worker.py` file, so it's close to useless without a shim script:

```
# exec-fa.py
import subprocess
import sys
sys.exit(subprocess.call(["python", *sys.argv[1:], "--log-level=TRACE"]))
```

```
$ func start --python  --language-worker ./exec-fa.py
```

So my shim script "works", in the sense that it starts the worker with the extra arguments appended, but the `logging.debug()` calls are still swallowed unless I manually hack `dispatcher.py:122`. This will do for me for now, but I can't share this workflow with the other developers on my team, it's unreasonable to expect them to be willing to do this.

I don't really know what to suggest here, but unless debug logging is explicitly not supported (if so, it should be documented prominently), it really seems to me like this issue should still be open.

**Comment by empz** [comment]
I got here because I really need to view debug logs from a 3rd party library (Sentry). Tried the following but it didn't worked, I can't see debug logs anywhere.
```
{
  "version":  "2.0",
  "logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "default": "Debug"
    }
  } 
}
```

**Comment by igitur** [comment]
@empz The thread above doesn't make it very clear, but you have to do 2 things. You already did one of them. But for the record, the 2 steps to achieve debug logging in Azure Functions are:
1. Set root logger level to 10

```python
logging.Logger.root.level = 10
```

2. Configure log level in `host.json`
```json
{
  "version":  "2.0",
  "logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "default": "Debug"
    }
  } 
}
```

**Comment by DanielBell-Io** [comment]
I tried this suggested [host.json ](https://stackoverflow.com/q/57648109/16105404) with no effect. @igitur

**Comment by hristochr** [comment]
> @empz The thread above doesn't make it very clear, but you have to do 2 things. You already did one of them. But for the record, the 2 steps to achieve debug logging in Azure Functions are:
> 
> 1. Set root logger level to 10
> 
> ```python
> logging.Logger.root.level = 10
> ```
> 
> 2. Configure log level in `host.json`
> 
> ```json
> {
>   "version":  "2.0",
>   "logging": {
>     "fileLoggingMode": "always",
>     "logLevel": {
>       "default": "Debug"
>     }
>   } 
> }
> ```

This fix worked for me, thanks!
