### ISSUE TITLE
python setup.py webhost step fails

### ISSUE THREAD

**Issue by ashfondu** [Azure/azure-functions-python-worker#250]
I have run into the same issue as #108  when running 'python setup.py webhost' - i get the following error. i am fairly new to Python so my ability to self resolve is basic
_Downloading Azure Functions Web Host...
Extracting Azure Functions Web Host binaries...
error: [WinError 2] The system cannot find the file specified_

The alternative instructions also makes little sense. i did download the zip and unzipped it but wasnt sure what to do next
_Alternatively, download/build manually and then specify the full path to Microsoft.Azure.WebJobs.Script.WebHost.dll either in the PYAZURE_WEBHOST_PATH environment variable, or in the .testconfig configuration file:_

**Comment by asavaritayal** [comment]
@ashfondu can you please share exact repro steps?

**Comment by ashfondu** [comment]
i followed the following guide - got to section 'setup development environment' without any errors but received the error on step 5 (run python setup.py webhost).
_Downloading Azure Functions Web Host...
Extracting Azure Functions Web Host binaries...
error: [WinError 2] The system cannot find the file specified_
https://github.com/Azure/azure-functions-python-worker/wiki/Contributor-Guide

lmk when other steps i can provide.

**Comment by elprans** [comment]
@ashfondu Make sure you have https://github.com/Azure/azure-functions-core-tools installed

**Comment by ashfondu** [comment]
Azure-function-core-tools were installed using _[npm i -g azure-functions-core-tools --unsafe-perm true]_ and the following prerequisites were also satisfied

    Python 3.6.x
    dotnetcore-sdk 2.x
    azure-functions-core-tools 2.x

**Comment by ashfondu** [comment]
Just providing an update - i was able to resolve this although not sure how but i think the error could be due to hard requirement of Python 3.6. 
I used Choclatey this time to install Azure Core Functions tool.
Used WSL instead of PowerShell. 
Thanks hope it helps.
