### ISSUE TITLE
Investigate supporting Conda

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#256]
This issue is a case for enabling conda/miniconda in the context of Python on Functions. 

#### Investigative information

Customer wanted to use fbprophet library which does not get installed through pip in both Windows and Mac. It depends on pystan library whose compilation options are best handed by conda.

#### Repro steps

Create a new function, use HttpTrigger
in __init__.py 

import fbprophet

Now enable virtual environment and do `pip install fbprophet`

Doesn't work.

Go out of virtual environment and use `conda install -c conda-forge fbprophet`  and it installs successfully. Conda knows the right kind of gcc flags needed to install pystan which is convenient for data scientists.

Either there must be some workaround to pip install fbprophet (even some compilation is fine) and a way to deploy such kind of installations.

or support conda environments.

Currently one customer is impacted, but fbprophet seems to be a library used for forecasting and is popular among certain customer domains.

**Comment by monteledwards** [comment]
Try updating to the latest version of the function core tools that was released about 5 days ago. This resolved package issues I was having.

**Comment by priyaananthasankar** [comment]
That doesn't matter as this is more related to "how to support libraries that get installed the right way in conda vs pip install"  
Func core tools isn't really an issue here, although I really wonder how is it going to package such libraries. As of now I am having trouble to pip install this library while conda install works perfectly fine.

**Comment by takumats** [comment]
I've tried it on my environment, too.
(just confirmed, fbprophet.__version__, ...)

My environment is,
- Windows 10 pro
- docker for windows (assigned 4GB memory to VM)
- wsl (ubuntu)
- azure function core tools: 2.3.199
- command: func azure functionapp publish XXXXX --build-native-deps --no-bundler

Hope it helps you!

**Comment by maiqbal11** [comment]
@priyaananthasankar, is this still an issue? We're doing preliminary investigations on how to add Conda support (\cc @asavaritayal) to broaden support for package installation. Were you able to use the suggestion in the thread to get a workaround?

**Comment by priyaananthasankar** [comment]
@maiqbal11 : Yes this is still an issue.

**Comment by arnav31** [comment]
Hey, this is still an issue for me, Could anyone give any kind of solution for this?
Error says - failed with an error code 1.
I have installed pystan 2.19.0.0 in my venv but fbprophet is giving an error.

**Comment by Ace139** [comment]
I'm also having the same issue while installing fbprophet. It's working fine with the same requirement.txt file in the local but giving error pystan is not found. 

I'm using docker to build the dependencies for Consumption Plan.

**Comment by asears** [comment]
Are there updates on this issue?  If external system dependencies are required for python environment, ability to support conda or a way of hooking into its environment prior to running pip is important.  pip distributions are broken for some Windows package installations and vice-versa.  Devs and Data Scientists will sometimes use Anaconda/conda.

Still on the roadmap for Azure Artifacts.
https://developercommunity.visualstudio.com/idea/478993/add-support-for-conda-packages-in-azure-artifacts.html

**Comment by vrdmr** [comment]
Closing this in favor for an open discussion to get more community inputs - https://github.com/Azure/azure-functions-python-worker/discussions/974
