### ISSUE TITLE
Unable to use Key Vault references

### ISSUE THREAD

**Issue by zmurphy-ms** [Azure/azure-functions-python-worker#258]
#### Investigative information

I'm trying to enable a KeyVault reference, but it's failing with KEY_ERROR both locally, and when deployed.

#### Repro steps

I followed the steps in https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references to create a KeyVault reference and added it to my App Settings.

#### Expected behavior

```os.environ['<key>']``` returns the secret value.

#### Actual behavior

```os.environ['<key>']``` causes a KEY_ERROR

<details>
<summary>Source</summary>

```python
# __init__.py

import logging
import os
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info(os.environ['<key>'])

    return "Done"
```

```txt
azure-functions==1.0.0a4
azure-functions-worker==1.0.0a4
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.11.0
```

</details>

**Comment by asavaritayal** [comment]
KeyVault references use MSI behind the scenes to authenticate, which is not available on the Linux consumption preview offering today. Adding it to the backlog for prioritization and tracking. @mattchenderson @dariagrigoriu

**Comment by asavaritayal** [comment]
This issue was moved to Azure/Azure-Functions#1065
