### ISSUE TITLE
Where to set the Connection string to BlobTrigger ?

### ISSUE THREAD

**Issue by ashfondu** [Azure/azure-functions-python-worker#259]
Hi , i am trying to setup a blob trigger using Python Function CLi , really stuck on how to make a connection the blob that will be monitored.

My questions is how to setup the connection to blob
i ran the func azure storage fetch-connection-string command to populate the local.settings.json and the output looks as follows after
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "AzureWebJobsStorage": "{AzureWebJobsStorage}",
    "blob_STORAGE": "DefaultEndpointsProtocol=https;AccountName=<name>;AccountKey=<AccountKey>"
  },
  "ConnectionStrings": {}
}
but i am fairly sure i am missing a step to tie this into the function.json
i update the value in function.json >"connection": "blob_STORAGE"
 but after i run the func host start it gives me the following errors

_Error indexing method 'Functions.BlobTrigger1'
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.BlobTrigger1'. Microsoft.WindowsAzure.Storage: Settings must be of the form "name=value".
Function 'Functions.BlobTrigger1' failed indexing and will be disabled.
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)._

Any help would be appreciated. 
Thanks

**Comment by priyaananthasankar** [comment]
Its the "{AzureWebJobsStorage}" that;s causing this issue. 
First run `func extensions install` 
Set connection string in AzureWebJobsStorage (what you set in blob_STORAGE) in your local.settings.json and then refer to **AzureWebJobsStorage** in your function.json 
See example here:
https://github.com/priyaananthasankar/parseltongue/tree/master/PyFunctionsOnACI/ForecastingApp

**Comment by ashfondu** [comment]
Priya for the win :D

**Comment by asavaritayal** [comment]
Closing as this seems to be resolve. Please feel free to re-open if you're still blocked.

**Comment by Guilhermeslucas** [comment]
This saved me! Thanks @priyaananthasankar
