### ISSUE TITLE
Provide a fake HttpRequest class for testing

### ISSUE THREAD

**Issue by brettcannon** [Azure/azure-functions-python-worker#262]
If you want to unit test your function, you need to be able to provide a fake `HttpRequest` object. Unfortunately the [`azure.functions._abc.HttpRequest`](https://github.com/Azure/azure-functions-python-library/blob/a1cdbc0063a5ed1faed4551fe916083cd9717e60/azure/functions/_abc.py#L46) has 7 methods/attribute to override. You can use [`azure.function_workers.bindings.http.HttpRequest`](https://github.com/Azure/azure-functions-python-worker/blob/e03026773f57145530224ab3a918e321a2c3efb9/azure/functions_worker/bindings/http.py#L12), but its `__init__()` wants some undocumented details (e.g. `meta.TypedDataKind`), and it also wants **everything** specified when some sensible defaults for testing would go a long way.

**Comment by asavaritayal** [comment]
@elprans do you have an update on this?

**Comment by elprans** [comment]
@asavaritayal I'm working on a PR
