### ISSUE TITLE
Docker image size comparison

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#265]
I wrote a forecasting app and launched it in ACI using Python Functions on Container, through func core tools, this uses Blob binding and is triggered through HTTP

`func --init Docker` and compiled the docker image. The code for this is here:

https://github.com/priyaananthasankar/parseltongue/tree/master/PyFunctionsOnACI/ForecastingApp

I also wrote the exact same forecasting app in my own custom container which uses Azure Blob Storage for Python + Flask for HTTP Trigger (basically does not use the functions programming model)

I see the image using functions programming model is almost 400MB more than the custom image. This is a case for running functions on AKS or ACI etc, the larger the container the more time it takes to spin it up. There must be a better case for containerized app that uses the Python functions programming model.

Check out the comparison here: https://github.com/priyaananthasankar/parseltongue/tree/master/Comparisons

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-docker#60
