### ISSUE TITLE
Custom binding support

### ISSUE THREAD

**Issue by stuartleeks** [Azure/azure-functions-python-worker#267]
Is it possible to use custom bindings with the python worker? The wiki has a page on [adding new bindings](https://github.com/Azure/azure-functions-python-worker/wiki/Adding-support-for-a-new-binding-type), but it isn't clear if this is guidance for custom bindings or just for adding new bindings to the python worker project.

#### Repro steps

Running the code with the custom binding [here](https://github.com/stuartleeks/azure-functions-custom-integration-elastic/tree/0204f581748d530d8860b458a2b449eb24b317f2/ElasticFunctionDemoPython) I get the following error

```
[18/12/2018 20:55:13] Executed 'Functions.HttpTrigger' (Failed, Id=fb1918e4-2bdb-4342-b1cb-96794692f88a)
[18/12/2018 20:55:13] System.Private.CoreLib: Exception while executing function: Functions.HttpTrigger. System.Private.CoreLib: Result: Failure
Exception: FunctionLoadError: cannot load the HttpTrigger function: unknown type for elasticMessage binding: "elastic"
Stack:   File "C:\source\_cust\elastic\ElasticFunctionsOutput\ElasticFunctionDemoPython\.env\lib\site-packages\azure\functions_worker\dispatcher.py", line 206, in _handle__function_load_request
    function_id, func, func_request.metadata)
  File "C:\source\_cust\elastic\ElasticFunctionsOutput\ElasticFunctionDemoPython\.env\lib\site-packages\azure\functions_worker\functions.py", line 179, in add_function
    f'unknown type for {param.name} binding: "{desc.type}"')
.
```

#### Expected behavior

Expected behaviour is that custom bindings are loaded and executed as with, e.g. JavaScript

#### Known workarounds

n/a

**Comment by asavaritayal** [comment]
@stuartleeks the wiki page provides instructions on how to add new bindings to the python worker project. Any contributions are welcome.

The work to enable all custom bindings (node functions like behavior) is captured by the issue here - https://github.com/Azure/azure-functions-python-worker/issues/66

Out of curiosity, which binding are you hoping to use?

**Comment by stuartleeks** [comment]
@asavaritayal - I have created a custom binding in the repo I originally linked to and want to be able to used that from python :-)
