### ISSUE TITLE
Request to add an __init__.py file

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-python-worker#268]
Would it be possible to add an `azure/__init__.py` file with this content (explicit namespace)?-
```
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

**Problem-**
I am blocked on this to be able to remove `azure-functions-worker` dependency from user's `site-packages`. Doing so, makes `azure` namespace in two different path. I understand that PEP 420 allows namespace support with no `__init__.py` file. But, right now, several other azure packages (eg - `azure-cosmos`, `azure-datalake`) come with an `__init__.py` file with this line -  `__import__('pkg_resources').declare_namespace(__name__)`

Unfortunately, this causes problems because PEP 420 style implicit namespace and `declare_namespace` are not compatible together. So, importing `azure.functions` ends up failing. Using `pkgutil.extend_path` would solve the problem because it's compatible with `declare_namespace` as well as PEP 420 style namespace.

The only other way to solve this is to delete `azure/__init__.py` from user's site-packages while packaging which seems hacky and is probably not the best approach.

Please let me know if you are aware of other/better ways to fix this problem.

**Comment by elprans** [comment]
@ankitkumarr `__import__('pkg_resources').declare_namespace(__name__)` is a bit more robust with respect do different kinds of packages and does essentially the same thing as `extend_path`.

**Comment by elprans** [comment]
Also, `azure-functions-python-library` would need to be modified in the same way.

**Comment by ankitkumarr** [comment]
@elprans, Thanks for the fast response!
Looks like `__import__('pkg_resources').declare_namespace(__name__)` doesn't support implicit namespace though.

So, if I have

user-site-packages/
----------azure (no `__init__.py`)/
------------------a_package/

container-site-packages/
user-site-packages/
----------azure/
--------------`__init__.py`(with `pkg_resources.declare_namespace`)/
--------------a-package/

`import azure.a_package` will fail in this case. (Sorry for my bad diagram above)

However, if instead of `pkg_resources.declare_namespace`, `extend_path` was used, it would work fine. It seems like they added support for `extend_path` in PEP 420, but not for `pkg_resources.declare_namespace`.

Please correct me if I am wrong.

**Comment by elprans** [comment]
You're right about the PEP 420 compatibility in `extend_path`.  However, it is my understanding that the root issue is the incompatibility with packages using `pkg_resources.declare_namespace`.  It seems to me that the most robust way is to use the same namespace mechanism across all packages under the `azure` namespace.  Using `extend_path` in the worker might not fix all import issues with `user-site-packages` containing a pure `azure` namespace, as it depends on the order of imports.

**Comment by elprans** [comment]
Well, the edge case is if any pure namespace package is imported _before_ the worker itself.  It may be impossible due to how the things are structured now, but this case still exists.  Ignoring that `extend_path` would work.

**Comment by ankitkumarr** [comment]
By pure namespace package, do you mean something like `azure/pythonfile.py`? Then, trying to do `import azure.pythonfile`?

**Comment by elprans** [comment]
No, sorry. By pure namespace I meant 'implicit namespace', i.e. a PEP 420 package, i.e a package without `__init__.py`.

**Comment by ankitkumarr** [comment]
Thanks for the clarification. I think that works fine. Even if the pure package is imported before the worker.

**Comment by asavaritayal** [comment]
@elprans do you have an update on this?

**Comment by elprans** [comment]
@asavaritayal: #277
