### ISSUE TITLE
Python DateTime Error For Blob Events In Event Grid Azure Function

### ISSUE THREAD

**Issue by eragonriddle** [Azure/azure-functions-python-worker#269]
# Issue Description
The Azure Event Grid Trigger function in python throws an error on receiving a blob event. The error is related to DateTime format. The date returned by the blob event to the python function cannot be parsed by python as the millisecond value has seven digits. E.g. the date '2018-12-09T23:47:03.285137Z'  cannot be parsed by python as the millisecond value has seven digits which is not recognized in python.

```
Result: Failure
Exception: ValueError: time data '2018-12-12T03:16:34.2191989Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
Stack:   File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 250, in _handle__invocation_request
    pytype=pb_type_info.pytype)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 285, in from_incoming_proto
    trigger_metadata=trigger_metadata)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/bindings/eventgrid.py", line 94, in from_proto
    event_time=cls._parse_datetime(body.get('eventTime')),
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 181, in _parse_datetime
    raise last_error
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 176, in _parse_datetime
    dt = datetime.datetime.strptime(datetime_str, fmt)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
```

# Steps to reproduce issue

```bash
#### STEP 1: CREATE AZURE FUNCTION

groupName="<resource_group_name>"
location="westeurope"
functionStorageName="<function_storage_account_name>"
appinsightsKey="<application_insights_instrumentation_key>"
appName="<function_app_name>"

#### CREATE RESOURCE GROUP

az group create --name $groupName --location $location

#### REGISTER EVENT GRID PROVIDER NAMESPACE

az provider register --namespace Microsoft.EventGrid

#### CREATE STORAGE ACCOUNT FOR FUNCTION APP
az storage account create --name $functionStorageName --location $location --resource-group $groupName --sku Standard_LRS --kind StorageV2

#### CREATE FUNCTION APP
az functionapp create --resource-group $groupName --os-type Linux --consumption-plan-location $location --runtime python --name $appName --storage-account $functionStorageName

#### CONFIGURE APP INSIGHTS FOR FUNCTION
az functionapp config appsettings set --name $appName --resource-group $groupName --settings "APPINSIGHTS_INSTRUMENTATIONKEY=$appinsightsKey"

#### STEP 2: WRITE FUNCTION CODE AND PUBLISH
func init testfunction --worker-runtime python
cd testfunction
func new --language python --template "Azure Event Grid trigger" --name EventGridTrigger
func azure functionapp publish $appName

#### STEP 3: CREATE A STORAGE ACCOUNT WHOSE EVENTS NEED TO BE RECORDED
generalStorageName="<storage_account_name>"
az storage account create --name $generalStorageName --location $location --resource-group $groupName --sku Standard_LRS --kind StorageV2
storageId=$(az storage account show --name $generalStorageName --resource-group $groupName --query id --output tsv)
accountKey=$(az storage account keys list --account-name $generalStorageName | grep "value" | awk -F ": " '{print $NF}' | sed 's/"//g' | head -1)

#### STEP 4: GET FUNCTION MASTER KEY FROM AZURE PORTAL (browse to 'Manage' section under the EventGridTrigger function)
functionMasterKey="<function_master_key>"
endpoint="https://$appName.azurewebsites.net/runtime/webhooks/eventgrid?functionName=EventGridTrigger&code=$functionMasterKey"

#### STEP 5: REGISTER EVENT GRID SUBSCRIPTION
az eventgrid event-subscription create --resource-id $storageId --name "myevtgridtrig" --endpoint $endpoint

#### STEP 6: UPLOAD A FILE TO STORAGE BLOB TO TEST EVENT
az storage container create --name test1 --account-name $generalStorageName --account-key $accountKey
echo "hello" > hello.txt
az storage blob upload --container-name test1 --account-name $generalStorageName --account-key $accountKey --file hello.txt --name "hello.txt"
```
#### STEP 7: REVIEW MONITOR OR APP INSIGHTS FOR LOGS/ERRORS

# Resources
* https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid#python-example
* https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-quickstart?toc=%2fazure%2fevent-grid%2ftoc.json

**Comment by priyaananthasankar** [comment]
High priority for many customers looking at this pattern @asavaritayal

**Comment by elprans** [comment]
@kavithamadhavaraj In this particular case, unfortunately, there are no workarounds.

**Comment by nicklooo** [comment]
> @elprans Any workarounds for this issue until the pull request is closed? Thanks in advance.

After we publish linux function app to Azure, we will be able to find a ZIP file in project folder, which is uploaded to storage and our function app will run from it.
https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-V2-hosting-options

So we can unzip the ZIP file and chance the code as https://github.com/Azure/azure-functions-python-worker/pull/306/commits/ecab0cf2ac64720b76c9e61cbf045f1162cf03e0

Then upload it to a storage account as a blob, get Shared Access Signature for the uploaded ZIP file (make sure you set expired date properly)

Copy the SAS URL and replace WEBSITE_RUN_FROM_ZIP value in your function app Application Settings, then restart your function app.

Now your function app will run from the modified ZIP file you upload.

**Comment by kavithamadhavaraj** [comment]
@nicklooo Tried the option you had shared but after restarting, my function is not listed anymore. (Both in portal & vscode, I could not see my function). This is how I generated the SAS.

![image](https://user-images.githubusercontent.com/12605428/52394916-242df080-2ad2-11e9-9775-b2c316600a59.png)

**Comment by nicklooo** [comment]
@kavithamadhavaraj  You need both **Read** and **List** Permissions

![image](https://user-images.githubusercontent.com/39934445/52410378-206e8e00-2b13-11e9-964f-ec60cad55d23.png)

**Comment by kavithamadhavaraj** [comment]
@nicklooo @elprans  I made changes to the meta.py file present in` /worker_venv/lib/python3.6/site-packages/azure/functions_worker/bindings/` of the zip file. Uploaded to blob storage and updated the SAS url, restarted the app, still facing the same error. The app is picking up the zip provided. However it doesn't seem to use the ./site packages folder from the zip. Am I missing something? Will be really helpful if you could provide some pointers here. Have been struggling with this for hours. Thanks.

![image](https://user-images.githubusercontent.com/12605428/52441247-27fb5a80-2b46-11e9-9c69-f6703c8dec93.png)

**Comment by nicklooo** [comment]
@kavithamadhavaraj 
Should be this folder: {zip folder}\.python_packages\lib\python3.6\site-packages\azure\functions_worker

Works well for me:
![image](https://user-images.githubusercontent.com/39934445/52457739-63be1080-2b96-11e9-9551-07ccd43fbe7b.png)

**Comment by kavithamadhavaraj** [comment]
@nicklooo Hi, my zip folder has `/worker_venv/lib/python3.6/site-packages/azure/functions_worker/bindings/` this path only. I'm using --build-with-native-deps flag. This makes the folder structure to the above mentioned one. If not, I can see `{zip folder}\.python_packages\lib\python3.6\site-packages\azure\functions_worker` in my zip file. Nevertheless, when i made changes to the packages & my function app code, the new changes from the later was reflecting the portal but the fix in the package file didn't work.
