### ISSUE TITLE
Data persists across function execution

### ISSUE THREAD

**Issue by gattjoe** [Azure/azure-functions-python-worker#271]
#### Investigative information

Please provide the following:

- Timestamp: 1/1/19 10:30 AM EST
- Function App name: SecEngFunctionTestV2
- Function name(s) (as appropriate): SSLScan

#### Repro steps

1. Run the function against microsoft.com and receive results for microsoft.com
2. Run the function against hotmail.com and receive results for both microsoft.com and hotmail.com

#### Expected behavior

Receive results from only one run.

#### Actual behavior

When I run the function n times, I receive the results from all runs.

#### Known workarounds

None, but I can probably code around it.

#### Related information 

Provide any related information 

* Links to source
* Bindings used
* Dependencies

[__init__.txt](https://github.com/Azure/azure-functions-python-worker/files/2719432/__init__.txt)

requirements.txt

azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.12.0
nassl==2.1.2
cryptography==2.4.2
tls-parser==1.2.1
sslyze==2.0.3
idna==2.8
asn1crypto==0.24.0
cffi==1.11.5
pycparser==2.19

**Comment by asavaritayal** [comment]
@elprans can you investigate this?

**Comment by elprans** [comment]
@gattjoe You are using a global variable to accumulate the results across multiple invocations.   The global state is not guaranteed to be pristine on every invocation in the same way it's not guaranteed in a regular app server.  This behavior is also desirable for cases where you need to cache the result of an expensive computation between function invocations.

@asavaritayal We should probably document this clearly in the programming model section.

**Comment by asavaritayal** [comment]
Addressed in this PR - https://github.com/MicrosoftDocs/azure-docs-pr/pull/78522
