### ISSUE TITLE
Noisy Error Messages for Import Module Failure

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#273]
_From @raahmed on January 3, 2019 21:35_

Context: Running Python on Functions in Linux (Preview)
Severity:
Medium( Time Confusing - causes Developer Frustration)

Reproduction Steps:
0.  Add an 'import azure.storage' to your code - without installing azure.storage locally.
1. Execute 'func host start'.
2. Notice that Functions error messages are quite noisy - which makes it difficult to find relevant information. On occasion, multiple pages worth of errors have to be scrolled up to find what is needed. 
![image](https://user-images.githubusercontent.com/25991359/50662648-05c95800-0f5c-11e9-8899-056d0c05e724.png)
3. After multiple pages worth of scrolling, the true cause is found:
![image](https://user-images.githubusercontent.com/25991359/50662661-1083ed00-0f5c-11e9-9c94-0367bcc698ce.png)

Mitigation Steps:
0. Reduce the noise in the error messages so that it is easier to find the error. 

_Copied from original issue: Azure/Azure-Functions#1090_

**Comment by fabiocav** [comment]
@asavaritayal assigning this to Triaged for review today.

**Comment by jeffhollan** [comment]
Guessing since this is popping up on the Day 1 experience stuff this should be a P1.  Potentially a P0.  Wondering if we should also have a day-1 label as that's been an important workstream across languages.

**Comment by asavaritayal** [comment]
Moving to 52 based on discussion during standup.

**Comment by asavaritayal** [comment]
@ankitkumarr can help with the investigation.

**Comment by Hazhzeng** [comment]
Thanks @ankitkumarr, we can modify the [traceback ](https://docs.python.org/3.7/library/traceback.html#traceback.print_tb) setting.

A quick and dirty fix to shorten the exception is to limit the stack trace in `dispatcher.py:190` (e.g. `stack_trace = ''.join(traceback.format_tb(exc.__traceback__, 2))`)

As we discussed, there are a few possible ways to allow our users to modify exception serializer:
1. add a setting option for the stack trace limit
2. allow users to pass in an exception handler

**Comment by asavaritayal** [comment]
Scoping issue down to import module error, per discussion in the scrum. @elprans may be able to advise.

**Comment by elprans** [comment]
For reference, Python uses this when rendering tracebacks natively:

https://github.com/python/cpython/blob/0f4e8132820947d93eccf31b9e526b81c6ffa53d/Python/import.c#L1484

We can do the same before rendering the traceback for the proto response here:

https://github.com/Azure/azure-functions-python-worker/blob/e7b848941411289b47222689bdb07ad6eb560224/azure/functions_worker/dispatcher.py#L191
