### ISSUE TITLE
Integration testing for language worker, core tools and docker image

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#274]
Details below

**Comment by maiqbal11** [comment]
We will need to create a setup which can replicate end to end user scenarios: Using core tools to create functions and then publishing them to Linux. We would use the latest core tools, language worker and docker image for this. Will provide further updates once I have further clarity on what all we need to include.

**Comment by maiqbal11** [comment]
Created an issue from core-tools perspective so we can ensure that deployment options do not break when changes are made to worker: https://github.com/Azure/azure-functions-core-tools/issues/971. The eventual goal should be to decouple them entirely and simply expose a config that the core tools use as an entry point.

**Comment by maiqbal11** [comment]
Testing from Core-tools perspective: https://github.com/Azure/azure-functions-core-tools/issues/971

**Comment by maiqbal11** [comment]
OGF Testing for user experience: https://github.com/Azure/azure-functions-core-tools/issues/1040.

**Comment by maiqbal11** [comment]
Should be in a good state with our testing for Python: CI on Python worker, OGF testing and integration testing with Core Tools/Docker. Any improvements at this point should be incremental and can be tracked in new work items.
