### ISSUE TITLE
Release 1.0.0b3

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-python-worker#279]
We should do a release with the current bits in the repo. We were planning to do this before the break but did not want to risk interrupting the public preview.  

Once the release is done, I can make the corresponding changes to the core tools and the Docker image.

**Comment by asavaritayal** [comment]
@elprans do you have an update on this?

**Comment by elprans** [comment]
I'll post a release as soon as https://github.com/Azure/azure-functions-python-library/issues/7 lands

**Comment by elprans** [comment]
Done.
