### ISSUE TITLE
Is there a Twilio out binding available yet ?

### ISSUE THREAD

**Issue by ashfondu** [Azure/azure-functions-python-worker#280]
Hi wondering if there is a twilio binding available to use with Azure Python functions. I tried "func extension install --package Twilio --version 5.24.1" but the binding still show up as unregistered. 
I also tried the twilioSms binding as recommended by https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-twilio but not having any luck either.

I am able to get Twilio to work in code by using the client = Client(account, token) format but was wondering if there is an out of box for this.

**Comment by maiqbal11** [comment]
Hi @ashfondu, there are no out-of-the-box implementations yet for Python. There are plans to expose raw data binding types (#66) so that users can implement their own bindings as needed.
