### ISSUE TITLE
Create a nuget package with the worker that can be included in the runtime build

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-python-worker#286]
Today [node, powershell, and java ](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/WebJobs.Script.csproj#L38-L40) all have nuget packages that put the right files for their workers under `/workers/` when building `azure-functions-host` repo. The python worker is the only one that doesn't do that, causing the build process for CLI, and Docker to explicitly download the worker from github to bundle with the runtime. 

The pros of that approach is that building a given release or commit of the runtime, will bring in the correct worker automatically without having to maintain a separate mapping of which worker goes with which runtime version.

**Comment by asavaritayal** [comment]
I'm not aware of any downsides. @pragnagopa @fabiocav thoughts? For context, the Python worker is currently a PyPI package.

**Comment by maiqbal11** [comment]
PR is out for this: https://github.com/Azure/azure-functions-python-worker/pull/311/
