### ISSUE TITLE
Using multiple outputs as parameters not working

### ISSUE THREAD

**Issue by FlippieCoetser** [Azure/azure-functions-python-worker#296]
### Send data to a single output binding
Two options are available to send data to an output binding (HTTP Request / Response example below).

#### Using `func.Out[T]`
a HTTP Response message is produced by using `.set(T)` method on `func.out[T]`.
The parameter `reponse` in `main.py` and name `response` in `function.json` is the same 

#### `main.py`

```python
import logging
import azure

def main(request: azure.functions.HttpRequest,
         response: azure.functions.Out[azure.functions.HttpResponse]):
    HttpResponse = azure.functions.HttpResponse("HTTP Response", status_code=200)
    # Response is provided using .set method on func.Out[T] 
    response.set(HttpResponse)
    return 
```

#### `function.json`

```json
{
  "scriptFile": "main.py",
  "entryPoint": "main",
  "bindings": [
    {
      "name": "request",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "function"
    },
    {
      "name": "response",
      "type": "http",
      "direction": "out"
    }
  ]
}
```

#### Using function `return T`
a HTTP Response message is produced by using the `main` functions return value.
Notice the return value `HttpResponse` in `main.py` and name `$return` in `function.json` 

#### `main.py`

```python
import logging
import azure

def main(request: azure.functions.HttpRequest) -> azure.functions.HttpResponse: 
    HttpResponse = azure.functions.HttpResponse("HTTP Response", status_code=200)
    # Response is provided using methods return value 
    return HttpResponse
```

#### `function.json`

```json
{
  "scriptFile": "main.py",
  "entryPoint": "main",
  "bindings": [
    {
      "name": "request",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "function"
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ]
}
```

#### Using a mix: Function return T and `func.Out[T]`
1. a HTTP Response message is produced by using the `main` functions return value.
2. a message to queue storage is produced by using `.set(T)` method on `func.out[T]`.
3. The parameter `queue` in `main.py` and name `queue` in `function.json` is the same
4. Notice The return value `HttpResponse` in `main.py` and name `$return` in `function.json`

#### `main.py`
```python
import logging
import azure

def main(request: azure.functions.HttpRequest,
         queue: azure.functions.Out[azure.functions.QueueMessage]) -> azure.functions.HttpResponse:
    HttpResponse = azure.functions.HttpResponse("HTTP Response", status_code=200)
    Message = ("message")
    queue.set(Message)
    return HttpResponse
```

#### `function.json`

```json
{
  "scriptFile": "main.py",
  "entryPoint": "main",
  "bindings": [
    {
      "name": "request",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "function"
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    },
    {
      "name": "queue",
      "type": "queue",
      "direction": "out",
      "queueName": "out",
      "connection": "AzureWebJobsStorage"
    }
  ]
}
```

# Bug
#### Using only `func.Out[T]`

1. a HTTP Response message is produced by using  `.set(T)` method on `func.out[T]`.
2. a message to queue storage is produced by using `.set(T)` method on `func.out[T]`.
3. The parameter `queue` in `main.py` and name `queue` in `function.json` is the same
4. The parameter `response` in `main.py` and name `response` in `function.json` is the same

#### `main.py`
```python
import logging
import azure

def main(request: azure.functions.HttpRequest,
         queue: azure.functions.Out[azure.functions.QueueMessage],
         response: azure.functions.Out[azure.functions.HttpResponse]):
    HttpResponse = azure.functions.HttpResponse("HTTP Response", status_code=200)
    Message = ("message")
    queue.set(Message)
    response.set(HttpResponse)
    return
```

#### `function.json`

```json
{
  "scriptFile": "main.py",
  "entryPoint": "main",
  "bindings": [
    {
      "name": "request",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "function"
    },
    {
      "name": "response",
      "type": "http",
      "direction": "out"
    },
    {
      "name": "queue",
      "type": "queue",
      "direction": "out",
      "queueName": "out",
      "connection": "AzureWebJobsStorage"
    }
  ]
}
```

## Current Behavior
1. Initiate Debug session in VS Code
2. Trigger the Function App
3. Exception is thrown

![image](https://user-images.githubusercontent.com/3672126/51677705-bdd9a600-1fda-11e9-9e77-474c83b3ce57.png)

## Expected Behavior
Produces an HTTP Response and Add a new message to the Queue Storage

Azure Functions Core Tools 2.4.290
Function Runtime Version 2.0.12265.0

**Comment by asavaritayal** [comment]
@elprans can you investigate this issue?

**Comment by FlippieCoetser** [comment]
@maiqbal11 @asavaritayal I am still not able to send data to multiple output bindings. However, this time, no error is thrown the app just freezes. Could you please reopen this issue again?

**Comment by maiqbal11** [comment]
Hi @FlippieCoetser, I was unable to repro locally based on the original example you provided. Could you share what core tools version you're using as well as your requirements.txt?

**Comment by maiqbal11** [comment]
Hi @FlippieCoetser, I was able to run the app you provided using both Visual Studio Code and via the command line without any modifications. Can you confirm that your requirements.txt has `azure-functions-worker==1.0.0b4`?

**Comment by FlippieCoetser** [comment]
@maiqbal11 thanks for the help!
in my `requirements.txt` I have the following:

```
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
pandas==0.23.4
six==1.12.0
```
I need to upgrade the azure-functions-worker.
Let me do that and check.

Thanks for the help!
