### ISSUE TITLE
[Placeholder]Add support for reloading environment variables

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#298]
Implement handlers for environment reload requests
defined here: https://github.com/Azure/azure-functions-language-worker-protobuf/blob/73896fd4bf1ec13183ad638e80e3d5a9c19c58cb/src/proto/FunctionRpc.proto#L69-L71

FunctionEnvironmentReloadRequest  is sent by the functions host during specialization when a language worker is started in placeholder mode.

cc @asavaritayal @maiqbal11

**Comment by fabiocav** [comment]
@asavaritayal this work is blocked and beyond capacity for this sprint. So I'm moving this to Triaged.

**Comment by fabiocav** [comment]
Blocked on breaking changes announcement period
