### ISSUE TITLE
Programming Model : Binding Data

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#3]
Trigger data and bindings will be communicated to the main() function via method arguments whose **name**s are specified in **function.json**. 

#### Inputs
There are two types of inputs: 1. trigger input and 2 . additional input. Although they are different in function.json, their usage is identical in the Python code. 

```python
# main.py
def main(trigger_input, binding_input):
	# functions logic here
```

#### Outputs

Outputs can be expressed both in 1. return value and 2. output parameters. If there is only one output, we recommend using it as the return value. For multiple outputs, you have to use the function arguments.

To use the return value of your function as an output binding, label it using **name : $return** in **function.json**.

```javascript
//function.json
{ 
	"direction": "in", 
	"name": "my_input"
},
{ 
	"direction": "out", 
	"name": "$return"
}
```
```python
# main.py
def main(my_input):
    # function logic here
    return 'Value of the output binding.'
```

To produce multiple outputs, use the named function arguments of type ```azurefuncs.Out``` . For example - 

```javascript
// function.json
{
    "name": "trigger_input",
    "direction": "in"
},
{
    "name": "$return",
    "direction": "out"
},
{
    "name": "other_output",
    "direction": "out",
}
```

```python
# main.py
def main(trigger_input, other_output: azurefuncs.Out):
    
    other_output = trigger_input
    return 'Value of the output binding.'
```

## Data Types

We will use function annotations (type hints) to define the data type of the binding arguments. The runtime will use this information to determine how to pass data into and return data from a function execution. For example - 

```python
# main.py
def main(my_input : str) -> bool:
	print(f'Hello {my_input}')
	return True

```
Alternately, you can define the **dataType** attribute in the function.json configuration.

**Comment by 1st1** [comment]
A few thoughts on this topic:

1. `azure.functions.Out` should behave like `typing.Generic`, i.e. allow to specify its subtype in square brackets: `azure.functions.Out[int]`. `Out` parameters should define `Out.set(val)` method to set a new value for the argument, and `Out.get()` to get the current value of the argument.

    * BTW, what happens if a user calls `Out.get()` on a variable that has no value set? A `LookupError` exception?

2. While it's possible to deduce parameter types from `function.json`, I think it's still a good idea to **require** specifying types explicitly as part of functions' signatures for the following benefits:

    * it enable IDEs and tools like mypy to reason about the code;
    * programmers don't need to look at *both* `function.json` *and* the Python file to understand what parameters actually mean; this also improves maintainability of the code in the long run;
    * it eliminates the possibility of name clashes—the type is the only thing that determines what the parameter is doing; its name can be anything.

    This is a stricter API design option which can be relaxed at some point of the future.  If we make typing optional, it would be very challenging to make it required later.

3. The return value of a function is marshalled into an `InvocationResponse` message, which encodes the actual value as a `TypedData` message:

    ```protobuf
    message InvocationResponse {
      string invocation_id = 1;
      repeated ParameterBinding output_data = 2;
      TypedData return_value = 4;
      StatusResult result = 3;
    }

    message TypedData {
      oneof data {
        string string = 1;
        string json = 2;
        bytes bytes = 3;
        bytes stream = 4;
        RpcHttp http = 5;
        sint64 int = 6;
        double double = 7;
      }
    ```

    Therefore we can only "auto guess" some Python types like `bytes`, `str`, `azure.functions.HttpResponse`, `int`, etc.  For example, `int` type in Python has unlimited precision, so it's not always possible to pack a Python integer into `sint64`.  Therefore, I propose to raise a `TypeError` if a function returns something that we can't marshal.  Another option would be to allow returning only `str`, `bytes`, and `azure.functions.HttpResponse`.

    Additionally, the `json` type looks a bit ambiguous to me: returning a JSON string from a function worker is indistinguishable from returning a regular string.  Maybe we need to add an `azure.functions.JSON` datatype, to enable this pattern:

    ```python
    def main(req: azure.functions.HttpRequest):
        return azure.functions.JSON('{"a": 123}')
    ```

**Comment by elprans** [comment]
> Additionally, the json type looks a bit ambiguous to me: returning a JSON string from a function worker is indistinguishable from returning a regular string. Maybe we need to add an azure.functions.JSON

The return value is described in `function.json`, so the worker can obtain the actual type from function metadata.

**Comment by 1st1** [comment]
>> Additionally, the json type looks a bit ambiguous to me: returning a JSON string from a function worker is indistinguishable from returning a regular string. Maybe we need to add an azure.functions.JSON
>
> The return value is described in function.json, so the worker can obtain the actual type from function metadata.

Makes sense. I've created an issue for that: https://github.com/Azure/azure-functions-python-worker/issues/19

**Comment by 1st1** [comment]
> 1. `azure.functions.Out` should behave like `typing.Generic`, i.e. allow to specify its subtype in square brackets: `azure.functions.Out[int]`. `Out` parameters should define `Out.set(val)` method to set a new value for the argument, and `Out.get()` to get the current value of the argument.

Done.

>    * BTW, what happens if a user calls `Out.get()` on a variable that has no value set? A `LookupError` exception?

Will create an issue for this to discuss.

> 2. It's possible to deduce parameter types from `function.json`, I think it's a good idea to **encourage**  specifying types explicitly as part of functions' signatures for the following benefits:

Done. Types are now optional.  Need to create an issue to implement a check that would enforce that types in functions.json match with Python annotations.

> 3. I also propose to require that parameters names and types declared in `function.json` **must** match function parameters in Python.  This allows for **fast** and unambiguous binding of input data to arguments.

Done.

> 4. We'll also need a magic parameter name for `Context`:

Done.

> 5. The return value of a function is marshalled into an `InvocationResponse` message, which encodes the actual value as a `TypedData` message:

WIP.

**Comment by 1st1** [comment]
Everything described in this issue is now, except the question about `Out.get()` behaviour:

Consider the following function:

```
import azure.functions as azf

def main(request: azf.HttpRequest, response: azf.Out[azf.HttpResponse):
    response.get() # will return None  (!!!)

    response = azf.HttpResponse(status_code=301)
    response.set(response)

    response.get() # will return "azf.HttpResponse(status_code=301)"
```

So the current behaviour is to return `None` for `Out` bindings that don't have a value set (instead of raising an error).  This is similar to how NodeJS binding is implemented and I think it's OK for Python too.

**Comment by 1st1** [comment]
Closing this issue.
