### ISSUE TITLE
Error launching app locally

### ISSUE THREAD

**Issue by abhinavbom** [Azure/azure-functions-python-worker#301]
Launching `azure host start` command is throwing below error:

> Azure Functions Core Tools (2.4.290 Commit hash: 81e16deef7c013d24f33a3f240154468f4c84493)
> Function Runtime Version: 2.0.12265.0
> [1/27/19 1:43:34 AM] Starting Rpc Initialization Service.
> [1/27/19 1:43:34 AM] Initializaing RpcServer
> [1/27/19 1:43:34 AM] Building host: startup suppressed:False, configuration suppressed: False
> [1/27/19 1:43:35 AM] Reading host configuration file '/Users/abhinavsingh/final_azure_project/host.json'
> [1/27/19 1:43:35 AM] Host configuration file read:
> [1/27/19 1:43:35 AM] {
> [1/27/19 1:43:35 AM]   "version": "2.0"
> [1/27/19 1:43:35 AM] }
> [1/27/19 1:43:35 AM] Initializing Host.
> [1/27/19 1:43:35 AM] Host initialization: ConsecutiveErrors=0, StartupCount=1
> [1/27/19 1:43:35 AM] LoggerFilterOptions
> [1/27/19 1:43:35 AM] {
> [1/27/19 1:43:35 AM]   "MinLevel": "None",
> [1/27/19 1:43:35 AM]   "Rules": [
> [1/27/19 1:43:35 AM]     {
> [1/27/19 1:43:35 AM]       "ProviderName": null,
> [1/27/19 1:43:35 AM]       "CategoryName": null,
> [1/27/19 1:43:35 AM]       "LogLevel": null,
> [1/27/19 1:43:35 AM]       "Filter": "<AddFilter>b__0"
> [1/27/19 1:43:35 AM]     },
> [1/27/19 1:43:35 AM]     {
> [1/27/19 1:43:35 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
> [1/27/19 1:43:35 AM]       "CategoryName": null,
> [1/27/19 1:43:35 AM]       "LogLevel": "None",
> [1/27/19 1:43:35 AM]       "Filter": null
> [1/27/19 1:43:35 AM]     },
> [1/27/19 1:43:35 AM]     {
> [1/27/19 1:43:35 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
> [1/27/19 1:43:35 AM]       "CategoryName": null,
> [1/27/19 1:43:35 AM]       "LogLevel": null,
> [1/27/19 1:43:35 AM]       "Filter": "<AddFilter>b__0"
> [1/27/19 1:43:35 AM]     }
> [1/27/19 1:43:35 AM]   ]
> [1/27/19 1:43:35 AM] }
> [1/27/19 1:43:35 AM] FunctionResultAggregatorOptions
> [1/27/19 1:43:35 AM] {
> [1/27/19 1:43:35 AM]   "BatchSize": 1000,
> [1/27/19 1:43:35 AM]   "FlushTimeout": "00:00:30",
> [1/27/19 1:43:35 AM]   "IsEnabled": true
> [1/27/19 1:43:35 AM] }
> [1/27/19 1:43:35 AM] SingletonOptions
> [1/27/19 1:43:35 AM] {
> [1/27/19 1:43:35 AM]   "LockPeriod": "00:00:15",
> [1/27/19 1:43:35 AM]   "ListenerLockPeriod": "00:00:15",
> [1/27/19 1:43:35 AM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
> [1/27/19 1:43:35 AM]   "LockAcquisitionPollingInterval": "00:00:05",
> [1/27/19 1:43:35 AM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
> [1/27/19 1:43:35 AM] }
> [1/27/19 1:43:35 AM] Starting JobHost
> [1/27/19 1:43:35 AM] Starting Host (HostId=ns000155-1579447960, InstanceId=d32bc38e-0ca5-4a57-9c26-3815cee81272,Version=2.0.12265.0, ProcessId=8844, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=~2)
> [1/27/19 1:43:35 AM] Loading functions metadata
> [1/27/19 1:43:35 AM] 1 functions loaded
> [1/27/19 1:43:35 AM] WorkerRuntime: python. Will shutdown other standby channels
> [1/27/19 1:43:35 AM] Starting language worker process:python  "/usr/local/Cellar/azure-functions-core-tools/2.4.290/workers/python/worker.py" --host 127.0.0.1 --port 61379 --workerId fbdd750d-26b8-4249-a83c-9a7fd974ec2e --requestId 33a2e057-cb67-4327-84c3-3de544fcdfe7 --grpcMaxMessageLength 134217728
> [1/27/19 1:43:35 AM] python process with Id=8848 started
> [1/27/19 1:43:35 AM] Generating 1 job function(s)
> [1/27/19 1:43:35 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.4.290/workers/python/worker.py", line 31
> [1/27/19 1:43:35 AM]     print(traceback.format_exc(), flush=True)
> [1/27/19 1:43:35 AM]                                        ^
> [1/27/19 1:43:35 AM] SyntaxError: invalid syntax
> [1/27/19 1:43:35 AM] Language Worker Process exited.
> [1/27/19 1:43:35 AM] python exited with code 1
> [1/27/19 1:43:35 AM]  SyntaxError: invalid syntax.
> [1/27/19 1:43:35 AM] Starting language worker process:python  "/usr/local/Cellar/azure-functions-core-tools/2.4.290/workers/python/worker.py" --host 127.0.0.1 --port 61379 --workerId f4a7037d-e0b4-4c8a-9fd2-9cd3411db2c4 --requestId 9feb6a8b-2116-495c-97ff-1aaaa108e7f7 --grpcMaxMessageLength 134217728
> [1/27/19 1:43:35 AM] Found the following functions:
> [1/27/19 1:43:35 AM] Host.Functions.dummy-queue
> [1/27/19 1:43:35 AM]
> [1/27/19 1:43:35 AM] Host initialized (276ms)
> [1/27/19 1:43:35 AM] Host started (300ms)
> [1/27/19 1:43:35 AM] Job host started
> [1/27/19 1:43:35 AM] python process with Id=8852 started
> [1/27/19 1:43:35 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.4.290/workers/python/worker.py", line 31
> [1/27/19 1:43:35 AM]     print(traceback.format_exc(), flush=True)
> [1/27/19 1:43:35 AM]                                        ^
> [1/27/19 1:43:35 AM] SyntaxError: invalid syntax
> [1/27/19 1:43:35 AM] Language Worker Process exited.
> [1/27/19 1:43:35 AM] python exited with code 1
> [1/27/19 1:43:35 AM]  SyntaxError: invalid syntax.
> [1/27/19 1:43:35 AM] Starting language worker process:python  "/usr/local/Cellar/azure-functions-core-tools/2.4.290/workers/python/worker.py" --host 127.0.0.1 --port 61379 --workerId d4780169-d383-4b0b-ae9b-d65eaf4b3f47 --requestId e4871195-0871-43b7-ba19-b5c54eb75ae1 --grpcMaxMessageLength 134217728
> [1/27/19 1:43:35 AM] python process with Id=8856 started
> [1/27/19 1:43:35 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.4.290/workers/python/worker.py", line 31
> [1/27/19 1:43:35 AM]     print(traceback.format_exc(), flush=True)
> [1/27/19 1:43:35 AM]                                        ^
> [1/27/19 1:43:35 AM] SyntaxError: invalid syntax
> [1/27/19 1:43:35 AM] Language Worker Process exited.
> [1/27/19 1:43:35 AM] python exited with code 1
> [1/27/19 1:43:35 AM]  SyntaxError: invalid syntax.
> Hosting environment: Production
> Content root path: /Users/abhinavsingh/final_azure_project
> Now listening on: http://0.0.0.0:7071
> Application started. Press Ctrl+C to shut down.
> [1/27/19 1:43:40 AM] Host lock lease acquired by instance ID '000000000000000000000000A3D2FD6C'.
> [1/27/19 1:44:15 AM] Language Worker Process exited.
> [1/27/19 1:44:15 AM] The operation has timed out.

The App does launch after this error, but when I trigger the function(QueueTrigger), it shows below error:

```
[1/27/19 2:15:45 AM] Host lock lease acquired by instance ID '000000000000000000000000D146FB5E'.
[1/27/19 2:15:50 AM] Executing 'Functions.dummy-queue' (Reason='New queue message detected on 'dummy-queue'.', Id=f68e504d-51f1-4617-8ffd-a9ae5ad403fa)
[1/27/19 2:15:51 AM] Executed 'Functions.dummy-queue' (Failed, Id=f68e504d-51f1-4617-8ffd-a9ae5ad403fa)
[1/27/19 2:15:51 AM] System.Private.CoreLib: Exception while executing function: Functions.dummy-queue. System.Private.CoreLib: Failed to start language worker for: python. One or more errors occurred. (python exited with code 1
```

**Comment by asavaritayal** [comment]
@abhinavbom did you install the required extensions for Queue trigger (`func extensions install`) ?

**Comment by abhinavbom** [comment]
The suggestion helped. Thanks! closing the issue.
