### ISSUE TITLE
Update Contributor Guide to Include Common Error

### ISSUE THREAD

**Issue by t-eckert** [Azure/azure-functions-python-worker#302]
On MacOS Sierra and newer, the OS' included OpenSSL is depreciated and no longer used by Python 3.6 and above. Rather, a copy of OpenSSL is included in the download of Python and a bash command must be manually run to install default root certificates. 

If the user has not run the command, they will not be able to download the Microsoft.Azure.WebJobs.Script.WebHost.dll when running `python setup.py webhost` as the library file is hosted using HTTPS. They will get the following error: 

```
could not download Azure Functions Web Host binaries from https://ci.appveyor.com/api/buildjobs/onhbleqih3dsapp0/artifacts/Functions.Binaries.2.0.12136.no-runtime.zip: URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),)
```

It may be worthwhile to add a note in the Contributor Wiki that a common cause for this error is solved by running the `Install Certificates.command`. Additionally, if this exception is raised, perhaps a hint to this solution could be added. I will look at adding that on my fork if it seems like a good way forward.

**Comment by asavaritayal** [comment]
Thanks @t-eckert

**Comment by stefanushinardi** [comment]
Closing as we already included these info in the [troubleshooting guide](https://docs.microsoft.com/en-us/azure/azure-functions/recover-python-functions?tabs=vscode)
