### ISSUE TITLE
Always on functionality?

### ISSUE THREAD

**Issue by AlverezYari** [Azure/azure-functions-python-worker#309]
```python
# __init__.py

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    return "Done"
```

```txt
azure-functions==1.0.0a4
azure-functions-worker==1.0.0a4
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.11.0
```

</details>
-->

**Comment by asavaritayal** [comment]
@AlverezYari I'm not sure what your question is. Could you please elaborate?

**Comment by AlverezYari** [comment]
Sorry, was in rush when I put that in. My apologies! Anyway, we've got our new function running on a App Service plan, but the start up time for it after it sleeps seems excessively long. I would like to have it always up and ready to go (ie: no sleep or very quick startup time). What's the best way to accomplish that with the Python based function apps?

**Comment by asavaritayal** [comment]
No worries, thanks for the context. 

`Always On` is available as an application setting when running on an App Service Plan. There are two ways to set this: 

1. Portal UI 

![image](https://user-images.githubusercontent.com/8435148/52071910-cf6e0100-2538-11e9-9ad7-1507b55767b5.png)

2. CLI 

https://docs.microsoft.com/en-us/cli/azure/functionapp/config?view=azure-cli-latest#az-functionapp-config-set

/cc @ggailey777 maybe we should clarify this explicitly in the Functions docs.

**Comment by AlverezYari** [comment]
![image](https://user-images.githubusercontent.com/13000137/52074302-2aaaee00-254f-11e9-9068-7fe7b97e1add.png)

@asavaritayal 

I'm going to assume I'm missing this option because I've selected the wrong kind of AppService plan?

**Comment by AlverezYari** [comment]
@ahmelsayed Specifically it was/is a EastUSLinuxDynamicPlan which I think is the default if you follow the guides. I was able to get this working redeploying to a new Linux App Serivce plan in the (PremiumV2: 1 Small) tier. I had to completely redeploy the function to make that switch however, as I could not find a good way to trigger a switch from the portal or cli. Probably working as intended but overall the whole app service plan method was pretty confusing and the documentation that I was seeing had a lot of conflicting info. Thanks for looking into this!

**Comment by ahmelsayed** [comment]
Yes, as you pointed out Always On is only available for **dedicated** app service plans, not consumption a.k.a: dynamic. You also can't move a Linux app between dedicated and consumption since the underlying resources are very different. I'm actually not sure if you can do that for the Windows apps, I'll have to check. 

Recreating the application as dedicated like you did is the right way to go, and you should be able to see Always On in the settings (in fact I think it should be enabled by default as well)
