### ISSUE TITLE
Profile Python Worker cold start

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-python-worker#314]
We need to breakdown the cold start numbers that the Python Worker is experiencing. Will need to include the following areas, among others potentially:

1. Host starting on Service Fabric Mesh
2. Worker process start up - including function loading 
3. Latency from downloading and unzipping files

**Comment by fabiocav** [comment]
@maiqbal11 this issue may need to be broken down so we can better track the individual tasks.

**Comment by maiqbal11** [comment]
Tracking latency related to zip files: https://github.com/Azure/azure-functions-python-worker/issues/360

Host startup and specialization: https://github.com/Azure/azure-functions-python-worker/issues/361

**Comment by maiqbal11** [comment]
Closed #360 and #361 as we have high level profiles from our metrics tables. Keeping this issue open as low level profiling might be useful as well.

**Comment by asavaritayal** [comment]
Closing as this is now done. Thanks @maiqbal11 !
