### ISSUE TITLE
Output Cosmos multi documents

### ISSUE THREAD

**Issue by dajor** [Azure/azure-functions-python-worker#315]
In C# it is possible to output more than one document to cosmos. Is there a way to output in python as well more than one document.

It works with one document but I found now way to pass to doc.set a array

**Comment by asavaritayal** [comment]
I believe you can pass a Tuple. @elprans can confirm

**Comment by elprans** [comment]
Any iterable containing instances of `azure.functions.Document` should work.

**Comment by asavaritayal** [comment]
@dajor I'm closing the issue. Please feel free to re-open if the suggestion above doesn't work for you.
