### ISSUE TITLE
func init does not init project properly in Debian container

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#321]
Using a Debian container to develop:

Azure Functions tooling for python 3.6 (debian) does not init if the directory already exists.

​See the attached docker file, and attempt to run the func init in a newly created directory.

build the docker file

run the docker file:

docker run -it <myrepo>/cloud-custodian-python36

mkdir 'mydir'

# In Bash
python3.6 -m venv .env
source .env/bin/activate

# In PowerShell
py -3.6 -m venv .env
.env\scripts\activate​

func init mydir

cc: @plooploops

**Comment by ankitkumarr** [comment]
@priyaananthasankar can you please share the Dockerfile or the error you are seeing?

**Comment by priyaananthasankar** [comment]
@plooploops : Can you please give the info asked by Ankit?

**Comment by ankitkumarr** [comment]
Closing this as stale issue. Please re-open with more info if still facing issues.
