### ISSUE TITLE
Cannot import email.mime with Python (v3.6) Azure Function v2

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-python-worker#328]
_From @chisqrd on February 14, 2019 20:4_

I cannot seem to email from an python azure function on linux consumption plan. I created a function with Visual Studio Code and it does locally run fine.

`requirements.txt` has the following

`azure-functions==1.0.0b3 ` 
`azure-functions-worker==1.0.0b3  `
`grpcio==1.14.2  `
`grpcio-tools==1.14.2  `
`protobuf==3.6.1  `
`six==1.12.0  `
`psycopg2==2.7.6.1  `
`azure-keyvault  `
`azure-common  `

Where it errors out is 
`from email.mime.multipart import MIMEMultipart`
though I did verify right before that email package was in sys.modules. 

The error I get is the following
>2019-02-14T17:46:30.945 [Error] An error occurred: No module named 'email.mime'

Is this a known issue or am i missing something?

_Copied from original issue: Azure/Azure-Functions#1129_

**Comment by maiqbal11** [comment]
@chisqrd, could you provide the following info:

Timestamp:
Function App name:
Function name(s) (as appropriate):
Core Tools version:

Sharing your source code would also be very helpful.

**Comment by chisqrd** [comment]
Timestamp: 2019-02-14T17:46:30.945 [Error] An error occurred: No module named 'email.mime'
Function App: multi-scenario-env-alerting
Function Name: multi-scenario-env-alert
Version: azure-functions-core-tools@2.4.317 

related part of the code is as follows

    def send_my_mail(self,to, fr, subject, text, files={},server='smtp.office365.com'):
        slib = self.import_library('smtplib')
      
        try:
            from email.mime.multipart import MIMEMultipart
            from email.mime.base import MIMEBase
            from email.mime.text import MIMEText
            from email import encoders
            from email.utils import formatdate  
            msg = MIMEMultipart()
            msg['From'] = fr
            msg['To'] = to
            msg['Date'] = formatdate(localtime=True)
            msg['Subject'] = subject
            msg.attach( MIMEText(text) )

            for filekey,filevalue in files.items():
                part = MIMEBase('application', "octet-stream")
                part.set_payload(filevalue)
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', 'attachment; filename="%s"'% filekey)
                msg.attach(part)

            smtp = slib.SMTP(self.smtpserver,self.smtpport)
            smtp.ehlo()
            smtp.starttls()
            smtp.ehlo()
            smtp.login(self.sender,self.get_secret_value(self.sender_secret_name))
            smtp.sendmail(fr, to, msg.as_string() )
            smtp.close()
            self.logging.info("Successfully sent email")

        except slib.SMTPException as e:
            self.logging.error("Unable to send email: %s" %(e))
        except Exception as ex:
            self.logging.error("An error occurred: %s" %(ex))

**Comment by sjvdm** [comment]
Same issue here!

**Comment by maiqbal11** [comment]
@ankitkumarr, can you see if you are able to repro this? I'm on Antares servicing loop and might not be able to get to this for some time.

**Comment by CommonCrisis** [comment]
Same issue!

**Comment by ankitkumarr** [comment]
Apologies for the delay here. 
I was able to reproduce this issue. You can mitigate it by using the `--no-bundler` flag while publishing. 
So, you can use `func azure functionapp publish <appname> --build-native-deps --no-bundler`. 

We are working on improving our publishing pipeline through platform changes. Until then, please continue to use that flag if you experience issues with certain modules.

Using that flag, you may see some performance decrease (longer cold start). Additional details on the flag can be found [here](https://aka.ms/func-python-publish).

Let me know if you continue to see issues after using that flag.

**Comment by chisqrd** [comment]
This worked for me. You may need to delete your function app and do the deployment from scratch

**Comment by ankitkumarr** [comment]
@chisqrd thank you for the update! You shouldn't have to do that ideally. There might have been a different issue with your function app. 
So, I wouldn't recommend doing that unless it doesn't work otherwise.

@maiqbal11, feel free to close this issue, I don't have the right access.

If you continue to see related problems, please re-open this issue.
