### ISSUE TITLE
Empty Service Bus messages cause an error

### ISSUE THREAD

**Issue by JasonBSteele** [Azure/azure-functions-python-worker#330]
#### Investigative information

- Developing locally
- Core Tools version: 2.4.317

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a Function with a Service Bus Topic trigger using VS Code Azure Functions Extension
2. Update  the bindings to reference a topic subscription
3. Populate the Topic with test messages, some of which have UserProperties and an actual message payload, some of which only have UserProperties and no message payload

#### Expected behavior

The Function should be triggered successfully for both types of message

#### Actual behavior

For the messages with an empty payload the following error occurs:

```
Exception: TypeError: unable to decode incoming TypedData: unsupported combination of TypedData field None and expected binding type serviceBusTrigger
Stack:   File "d:\Workspace\MyPythonFunction\.env\lib\site-packages\azure\functions_worker\dispatcher.py", line 250, in _handle__invocation_request
    pytype=pb_type_info.pytype)
  File "d:\Workspace\MyPythonFunction\.env\lib\site-packages\azure\functions_worker\bindings\meta.py", line 291, in from_incoming_proto
    f'unable to decode incoming TypedData: '
.
```

#### Known workarounds

The workaround is to ensure all messages have a payload regardless of whether it is used or not.

#### Related information 

My Bindings:

```
{
  "scriptFile": "__init__.py",
  "disabled": false,
  "bindings": [
    {
      "name": "msg",
      "type": "serviceBusTrigger",
      "direction": "in",
      "topicName": "MyTopic",
      "subscriptionName": "MySubscription",
      "connection": "MyServiceBus_SERVICEBUS"
    }
  ]
}
```

**Comment by asavaritayal** [comment]
@elprans Ping, can you look into this?

**Comment by asavaritayal** [comment]
@elprans do you have an update on this?

**Comment by asavaritayal** [comment]
Ping. @elprans

**Comment by elprans** [comment]
@asavaritayal I'm looking into this today.
