### ISSUE TITLE
imaplib.IMAP4.error: Unknown IMAP4 UID command: MOVE

### ISSUE THREAD

**Issue by docgregt** [Azure/azure-functions-python-worker#334]
I am receiving the following error in my python function app deployed in azure. This error does not exist in local 3.6 environment running in VS Code.
An Error occuredTraceback (most recent call last):
  File "/home/site/wwwroot/SharedCode/EmailReader.py", line 27, in moveMessage
    result = M.uid('MOVE', msg_uid, '/Processed')
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/imaplib.py", line 867, in uid
    raise self.error("Unknown IMAP4 UID command: %s" % command)
imaplib.IMAP4.error: Unknown IMAP4 UID command: MOVE

This is a valid command in python as can be seen here:
https://bugs.python.org/issue33336
for all versions of python.
Seems like something is out of date in the azure environment.
How to resolve the issue in the deployed function app?

**Comment by asavaritayal** [comment]
@elprans can you take a look at this? May or may not be a language worker error but would be great if you can help narrow down.

**Comment by docgregt** [comment]
Is python 3.7 available? I saw somewhere it was available soon. Maybe that will solve it?

**Comment by elprans** [comment]
Looks like https://bugs.python.org/issue33336 Updating to the last 3.6.x should help

**Comment by docgregt** [comment]
@elprans , that is what i figured, but how do i do that? I am using following to deploy function app:
func azure functionapp publish i4servicespyapi --build-native-deps --no-bundler
I am using latest 3.6.x on my system and the code works fine there. But once deployed it seems the function app service is using an older version (like 3.6.6). How to upgrade it?

**Comment by elprans** [comment]
This is something that needs to be updated in the base image. Cc @maiqbal11

**Comment by maiqbal11** [comment]
@ahmelsayed to confirm. The latest release should have Python 3.6.8 in the image. Has that Docker release gone out yet?

**Comment by ahmelsayed** [comment]
It's in West US, rolling the update to East US today.

**Comment by ahmelsayed** [comment]
should be in West US, East US, and West Europe now.

**Comment by docgregt** [comment]
I just verified that my issue is now resolved. Thanks for resolving the python version issue. From my view this issue can be closed.

**Comment by ahmelsayed** [comment]
Thanks for verifying. South east Asia should be updated now as well.
