### ISSUE TITLE
Failed to execute script worker,AttributeError: module 'azure.functions_worker' has no attribute 'start'.

### ISSUE THREAD

**Issue by Flexron** [Azure/azure-functions-python-worker#335]
#322 was closed, so I open a new one issue for the same error.

Publish function using **func azure functionapp publish app_name --build-native-deps --no-bundler** was working perfectly (That is why #322 was closed)
I have updated my function and so I have tried to re-publish the function but I got the same error again.

Error : 
> Function (confluence_call) Error: Failed to start language worker process for: python. bash exited with code 255 [84] Failed to execute script worker,AttributeError: module 'azure.functions_worker' has no attribute 'start'.

There is my requirement.txt : (It didn't change since #322 )
> azure-functions
>azure-functions-worker
>azure-storage
>azure-storage-blob
>grpcio==1.14.2
>grpcio-tools==1.14.2
>protobuf==3.6.1
>six==1.12.0
>pandas

I have also tried to republish the function with the previous version of the code worked Monday but got the same error too. 
I even tried to just make a new function following this documentation https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli-linux but nothing to do the error is always here.

**Comment by ankitkumarr** [comment]
@Flexron, can you update your azure-functions-core-tools version and try again? The latest version is `2.4.317`.

**Comment by asavaritayal** [comment]
@Flexron are you still seeing the error? Closing as issue should be resolved with a Core Tools update. Please feel free to re-open if this is not the case.
