### ISSUE TITLE
VS Code extension 0.14.0 not prompting for Storage account on Windows

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-functions-python-worker#338]
Azure Functions VS Code extension 0.14.0.
VS Code 1.31.1.
Windows 10.

Create Azure Function, select Timer Trigger.
In side by side tests, on Mac this prompted user for a storage account, on Windows it didn't.

Subsequently running function locally fails due to AzureWebJobsStorage not set.

**Comment by asavaritayal** [comment]
@EricJizbaMSFT I can't transfer this issue to the VS Code repo due to permission issues.

**Comment by EricJizbaMSFT** [comment]
We have an open issue to track improvements to AzureWebJobsStorage. Copied and added a comment here: https://github.com/Microsoft/vscode-azurefunctions/issues/976#issuecomment-466487139

**Comment by asavaritayal** [comment]
Closing issue in favor of the one in the VS Code repo.
