### ISSUE TITLE
Creating new project in VS Code is very slow on Windows

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-functions-python-worker#339]
VS Code 1.31.1
Azure Functions extension 0.14.0.
Create a new project, use browse to create new folder, and select Python as language. 
Project creation takes minutes on Windows compared to seconds on Mac.

**Comment by asavaritayal** [comment]
@EricJizbaMSFT I can't transfer this issue to the VS Code repo due to permission issues.

**Comment by EricJizbaMSFT** [comment]
Copied here: https://github.com/Microsoft/vscode-azurefunctions/issues/1029

**Comment by asavaritayal** [comment]
Closing issue in favor of the one in the VS Code repo.
