### ISSUE TITLE
Relative file paths don't work as expected in Azure Functions

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-functions-python-worker#340]
Suppose you create an Azure function which opens a config file in the same folder as __init__.py.
Running locally the code might look like:

    with open('myconfig.json') as configFile:
        configData = json.load(configFile)

As a published function, the working folder is the parent, so the code would need to be changed to:

    with open('functionname/myconfig.json') as configFile:
        configData = json.load(configFile)

This prevents simple "lift and shift" of functions to Azure.

If there are good reasons for the relative path being the Project folder instead of the function folder and it can't be fixed, then please consider this a doc issue. I.e. make this more prominently documented.

**Comment by asavaritayal** [comment]
@elprans know we've spoken about this before a couple of times. Seems to pop up very frequently as users don't find the current pattern(s) intuitive. What do we need to enable the relative file path?

**Comment by elprans** [comment]
The correct access pattern is not to rely on the value of the current working directory and use an absolute path obtained from `__file__`.  This is true for any Python script, not just Python functions:

Example:

```python

import pathlib

with open(pathlib.Path(__file__).parent / 'myconfig.json'):
    ...
```

**Comment by asavaritayal** [comment]
@elprans I think there's a need here to distinguish between the correct access pattern and the intuitive pattern. **Is there a reason we cannot enable both?** This would match the experience provided by any Python script.

**Comment by elprans** [comment]
@asavaritayal There is no way to do it safely.  The current working directory is shared for the entire process which runs multiple functions.  Switching the current directory on every function invocation is impossible to do due to concurrency.

**Comment by asavaritayal** [comment]
@fabiocav @pragnagopa I imagine we have a similar issue for JavaScript and .Net as well. What's the behavior and recommended pattern for other languages?

**Comment by fabiocav** [comment]
@asavaritayal that's not really an issue there, as using the pattern mentioned by @elprans above is common and what we recommend. We also provide a context with the function directory, which is often use to create the needed paths.

**Comment by asavaritayal** [comment]
Discussed with @fabiocav offline and we think the way to mitigate here is with better error handling and documentation. 

Here's the error I receive on trying to directly access a file in the function directory - 

```
Python HTTP trigger function processed a request.
[2/27/19 7:12:38 PM] Executed 'Functions.HttpTrigger' (Failed, Id=44ab374c-5429-44aa-a4d1-2cbbc1cf0b5a)
[2/27/19 7:12:38 PM] System.Private.CoreLib: Exception while executing function: Functions.HttpTrigger. System.Private.CoreLib: Result: Failure
[2/27/19 7:12:38 PM] Exception: FileNotFoundError: [Errno 2] No such file or directory: 'function.json'
[2/27/19 7:12:38 PM] Stack:   File "/Users/asavaritayal/quickpythontest/myproj/.env/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 288, in _handle__invocation_request
[2/27/19 7:12:38 PM]     self.__run_sync_func, invocation_id, fi.func, args)
```

```
Exception: FileNotFoundError: [Errno 2] No such file or directory: 'function.json'
```

@elprans can we add more info to the error above clarifying the required syntax?

**Comment by asavaritayal** [comment]
Docs item addressed in this PR - https://github.com/MicrosoftDocs/azure-docs-pr/pull/78522

**Comment by antopolskiy** [comment]
> Docs item addressed in this PR - https://github.com/MicrosoftDocs/azure-docs-pr/pull/78522

The doc link is broken.

**Comment by vsub21** [comment]
> The correct access pattern is not to rely on the value of the current working directory and use an absolute path obtained from `__file__`. This is true for any Python script, not just Azure functions:
> 
> Example:
> 
> ```python
> import pathlib
> 
> with open(pathlib.Path(__file__).parent / 'myconfig.json'):
>     ...
> ```

Super helpful, thanks.

**Comment by kryten68** [comment]
Well, as a new user of Azure Functions of the Python variety I can vouch for the fact that diddling around trying to work out why configparser is able to read my config.ini just fine locally, but breaks when published is really no fun. 

Surely the objective should be to reduce and remove delta's between the local dev experience and that when deployed?
