### ISSUE TITLE
Only _master host key is valid

### ISSUE THREAD

**Issue by rdlucas2** [Azure/azure-functions-python-worker#343]
My scenario:
Created two function apps in different regions. let's say blue and green. Create a traffic manager, listing blue and green as app service endpoints. Route all traffic to blue to start. Using authLevel admin on the function. Send x-functions-key header with _master key for blue. In green function app, add a custom host key that matches the _master blue key. Update traffic manager to send traffic to green. Get 401 unauthorized. Updating the x-functions-key header to green _master works. Tried to work around using authLevel function - but can't add a custom function level key in the interface.

Problem:
Adding a custom host key is not recognized.

**Comment by asavaritayal** [comment]
@fabiocav @ahmelsayed do we support custom keys for Linux?

**Comment by fabiocav** [comment]
Yes, this should work.

@rdlucas2 can you share more details on how you've added the key?

**Comment by rdlucas2** [comment]
I added via ther portal interface for "Function app settings"

![image](https://user-images.githubusercontent.com/1649129/53697584-a7c0c180-3da0-11e9-88fa-aefca864720f.png)

**Comment by anirudhgarg** [comment]
Closing old issues. This should work - if it still doesnt work and is a problem please let us know and re-open.
