### ISSUE TITLE
Support for Multipart / MIME request data

### ISSUE THREAD

**Issue by berndverst** [Azure/azure-functions-python-worker#349]
**Feature Request: Provide support for multipart / MIME request data**

Currently it is difficult to handle multipart data requests, e.g. file uploads (as are typical for HTML FORM POSTs) as multipart/formdata. Only with the help of third party libraries (such requests-toolbelt) or deep understanding of the multipart MIME RFCs can such request data be accessed at this time.

#165 would be a possible solution. This would allow reliance of Flask's built in understanding of MIME data.

**Comment by asavaritayal** [comment]
We should expand the `azure.functions.HttpRequest` API surface to include `files` for all uploaded files and `form` for form data. 

@elprans assigning you to the issue, let me know if you have any thoughts/comments on the proposal.

**Comment by asavaritayal** [comment]
@elprans do you have an update on this?

**Comment by elprans** [comment]
@asavaritayal Working on a PR, will submit shortly.
