### ISSUE TITLE
Implement all the message types in StreamingMessage

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#355]
Functions host will start sending various messages defined under StreamingMessage: https://github.com/Azure/azure-functions-language-worker-protobuf/blob/dev/src/proto/FunctionRpc.proto#L20

To avoid breaking language worker, please implement all of them otherwise grpc will start throwing errors.
Note: only dummy implementations needed for now to avoid breaking changes

**Comment by pragnagopa** [comment]
cc: @asavaritayal @maiqbal11

**Comment by asavaritayal** [comment]
Re-assigning to @elprans for this sprint.

**Comment by pragnagopa** [comment]
ping!

**Comment by elprans** [comment]
@pragnagopa I'll submit a PR shortly

**Comment by elprans** [comment]
@pragnagopa The current implementation seems to already handle unknown message gracefully, so I don't think any action is necessary on this one at this time:

https://github.com/Azure/azure-functions-python-worker/blob/b31ede864d664e10388a7b0802ae162c0ea6abaa/azure/functions_worker/dispatcher.py#L186-L192

**Comment by pragnagopa** [comment]
Ask here is to support all messages explicitly. For any messages that have a response message, for example: FunctionEnvironmentReloadResponse send success as host will use this information.

When host starts sending these messages to take advantage of the new support, language worker needs to be updated to handle messages best suited for that language.

**Comment by elprans** [comment]
@pragnagopa So the worker should send a Success response even if the requested feature is not supported?  Maybe adding an explicit `StatusResult.NotSupported` would be better?  How would we handle scenarios where the worker is unable to handle a particular request *in principle*?

**Comment by pragnagopa** [comment]
Yes. Good point. For the messages we have now, it is required by the worker to either handle it or return success.  For future messages, host will be responsible for sending new types of messages only to supported workers.

**Comment by elprans** [comment]
@pragnagopa Should we add the new `StatusResult` to the protocol?

**Comment by pragnagopa** [comment]
For now, all the messages in the proto file are required to be supported by the language worker.  I will update proto file to add `StatusResult.NotSupported` for future breaking changes.

**Comment by asavaritayal** [comment]
@elprans do you have any update on this one? Please let us know if you need any help from the onsite team.
