### ISSUE TITLE
ModuleNotFoundError: No module named 'PyInstaller'

### ISSUE THREAD

**Issue by Dammi87** [Azure/azure-functions-python-worker#356]
When publishing my Python module, I get the following error
` ModuleNotFoundError: No module named 'PyInstaller'`

Which happens when I run this command
`func azure functionapp publish <name> --build-native-deps`

Even though I can see that it has installed properly during the build.

Adding the --no-bundle does not work either (I added PyInstaller to requirements.txt, remove it there as well to verify)

#### Investigative information

Please provide the following:

- Timestamp:
- Function App name: NA
- Function name(s) (as appropriate):
- Core Tools version: 
   - func --version: 2.3.199
   - docker 18.06.1-ce-win73 (19507)
   - OS Windows 10

#### Repro steps

[repro.zip](https://github.com/Azure/azure-functions-python-worker/files/2931655/repro.zip)

#### Expected behavior

When I tried the same command around a month ago, it worked perfectly fine. My build also works fine locally. 

#### Actual behavior

Provide a description of the actual behavior observed.

#### Other info

> Getting site publishing info...
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0'..done
Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0'...done
Running 'docker exec -t 73d715 mkdir -p /home/site/wwwroot/'..done
Running 'docker cp C:\Users\AdamFjelsted\AppData\Local\Temp\tmpE919tmp/. 73d715:/home/site/wwwroot'..done
Running 'docker cp C:\Users\Adam.Fjelsted\AppData\Local\Temp\tmpFCF0.tmp 73d715:python_docker_build.sh'..done
Running 'docker cp C:\Users\Adam.Fjelsted\AppData\Local\Temp\tmpFD01.tmp 73d715:python_bundle_script.py'..done
Running 'docker exec -t 73d715 chmod +x /python_docker_build.sh'..done
Running 'docker exec -t 73d715 chmod +x /python_bundle_script.py'..done
Running 'docker exec -t 73d715 /python_docker_build.sh'..................done
Running 'docker kill 73d715'..done
Error running docker exec -t 73d7157c13353760e69744753f6cb0def42400785013b610e2c0bc80d9003aa5 /python_docker_build.sh.

**Comment by ankitkumarr** [comment]
This is related to Pyinstaller having issues with pip 19.0. See workaround- https://github.com/Azure/azure-functions-core-tools/issues/1100

I can make an update to work around this problem when I am back.

**Comment by ankitkumarr** [comment]
Oh, and the workaround flag is `--no-bundler` and not `--no-bundle`.

**Comment by IainColledge** [comment]
func azure functionapp publish funcname --build-native-deps --no-bundler --force fails for some reason.

**Comment by maiqbal11** [comment]
Can you share your `requirements.txt`? Might be the case that you still have `PyInstaller` listed in your requirements even though it is not required for the `--no-bundler` path.

**Comment by IainColledge** [comment]
Thanks for the reply, this is the requirements.txt

```
asn1crypto==0.24.0
astroid==2.1.0
azure-common==1.1.18
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.5
azure-functions==1.0.0b3
azure-functions-worker==1.0.0b3
azure-nspkg==3.0.2
azure-storage-common==1.4.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.5
grpcio==1.14.2
grpcio-tools==1.14.2
idna==2.8
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
mypy==0.670
mypy-extensions==0.4.1
protobuf==3.6.1
ptvsd==4.2.3
pycparser==2.19
pylint==2.2.2
python-dateutil==2.8.0
requests==2.21.0
six==1.12.0
typed-ast==1.3.1
urllib3==1.24.1
wrapt==1.11.1
```

**Comment by maiqbal11** [comment]
@IainColledge, can you try upgrading pip to 19.03 for now? A fix was released in 19.02: https://github.com/pypa/pip/issues/6163#issuecomment-462014864. 

@Dammi87, realized that you were the one who had originally posted the issue. Is it resolved now?

**Comment by IainColledge** [comment]
Isn't this the pip in the docker container that is being run, not the host?

On the host am running 18.1

**Comment by maiqbal11** [comment]
@IainColledge, yes, you're correct. This is running in the Docker and I can see that 19.0 is the current pip version in Docker. Is this the first error you see when you run publish or is there a stack before this?

@ahmelsayed, did we make any changes recently that might cause this error to manifest? Can we update the image to use pip 19.3? I'm also not sure why this would get triggered in the `--no-bundler` path since that does not use `PyInstaller`.

**Comment by IainColledge** [comment]
Thanks, yup this is the first error.

Updating the image to pip 19.3 would be awesome.

**Comment by asavaritayal** [comment]
This should now be fixed in the base docker image - https://github.com/docker-library/python/blob/fac7efee47f0c188f3ea21a328ec3109612fd0cf/3.6/stretch/slim/Dockerfile#L103. Please feel free to re-open if you still see any issues.
