### ISSUE TITLE
Trigger function from Azure Sql Database

### ISSUE THREAD

**Issue by mdudis** [Azure/azure-functions-python-worker#365]
I want to trigger Azure python functions from a row insert into Azure SQL Database. Is there any binding available for this?

**Comment by maiqbal11** [comment]
Hi @mdudis, currently there is no implementation for this and it's difficult to say when we would be able to provide it. That being said, you should be able to use logic apps for triggering using SQL: https://docs.microsoft.com/en-us/azure/connectors/connectors-create-api-sqlazure#add-sql-trigger. Once you have the data, and depending on your workload, you should be able to call into your running Python function via HTTP: https://docs.microsoft.com/en-us/azure/connectors/connectors-native-http. You could also write the SQL data onto a queue (https://docs.microsoft.com/en-us/connectors/azurequeues/) which could be combined with a queue trigger. These are not the ideal solution by any means, but hopefully they will prove useful for your scenario. Closing the ticket as there are no slated plains for the SQL trigger yet.
