### ISSUE TITLE
Issue publishing function interacting with azure blobs

### ISSUE THREAD

**Issue by Chris-May** [Azure/azure-functions-python-worker#367]
#### Investigative information

Please provide the following:

- Timestamp: 2019-03-20 10am EDT
- Function App name: mkldsfxappexternaldatalx002
- Function name(s) (as appropriate):
- Core Tools version: 2.4.419

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create an azure function (any kind)
2. `pip install azure-storage-blob`
3. Try to publish

#### Expected behavior

Provide a description of the expected behavior.

Expected to be able to publish the fucntion

#### Actual behavior

Provide a description of the actual behavior observed.

Deploy fails because `azure-storage-blob` requires `cryptography`

```
There was an error restoring dependencies.ERROR: cannot install cryptography-2.6.1 dependency: binary dependencie s without wheels are not supported.  Use the --build-native-deps option to automatically build and configure the  dependencies using a Docker container. More information at https://aka.ms/func-python-publish
```

#### Known workarounds

It seems Docker is the recommended workaround, but Docker is unavailable in Windows 7.

#### Related information 

Provide any related information 

* Links to source

I can recreate it by creating any Azure python function and adding `azure-storage-blob` to the `requirements.txt` file

* Contents of the requirements.txt file
```
azure-functions==1.0.0b3
azure-functions-worker==1.0.0b4
azure-storage-blob==1.5.0

```

**Comment by asavaritayal** [comment]
This'll be solved by the DevOps integration and Cloud Build. @ColbyTresness do you have any doc pointers or existing issues to share for this one?

**Comment by ColbyTresness** [comment]
@ahmedelnably has a set of docs for the pipelines integration being released in about a week.

**Comment by ahmedelnably** [comment]
This will be the link for the documentation, should be live by early next week

https://aka.ms/functions-azure-devops

**Comment by aorsten** [comment]
I'm getting this issue, and do not have Docker available. 
It is exactly as stated, I have created an Azure Function blob-trigger, and am using `azure-storage-blob`. And I get this error:

```
There was an error restoring dependencies.ERROR: cannot install cryptography-2.6.1 dependency: binary dependencies without wheels are not supported.  Use the --build-native-deps option to automatically build and configure the dependencies using a Docker container. More information at https://aka.ms/func-python-publish
```

**Comment by asavaritayal** [comment]
If Docker is not available, the recommendation is to set up a Continuous Deployment pipeline using Azure DevOps. More information is available here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops

**Comment by Chris-May** [comment]
Thanks!
