### ISSUE TITLE
DevOps Strategy for Python Functions

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#368]
The current pipeline: https://github.com/Azure/azure-functions-devops-build/blob/master/sample_yaml_builds/linux/consumption/python-consumption.yml does not work.

Currently the pipeline that uses a bash script is the one that works. This performs CI and CD in one single script, which isn't ideal. There are multiple issues:

1. Declaring service principal as variables.
2. No clear separation of CI and CD.

Ideally, the customer expects:

1. Efficient packing and running from a zip (run from zip on linux will greatly help here) 
2. Deal with virtual environment creation and install of environment dependencies 

I know the product is in preview and DevOps task support is early, but this is a placeholder for the same.

Another customer deployment used this pipeline, but customer complains it is very slow, but it is the right way to separate CI and CD.

**Comment by maiqbal11** [comment]
Thanks for pointing this out @priyaananthasankar. There are some limitations in the approach right now that we're working to address. \cc @Hazhzeng, @Francisco-Gamino, @asavaritayal.

**Comment by asavaritayal** [comment]
@priyaponders have you tried the `azure functionapp devops-build create` command to setup the pipeline? This should provision E2E CD without the bash script.

**Comment by asavaritayal** [comment]
@priyaponders have you tried the `azure functionapp devops-build create` command to setup the pipeline? This should provision E2E CD without the bash script.

**Comment by genscape-agodfrey** [comment]
To expand on this, when attempting to setup ci/cd we identified that without zipdeploy being an option, deploying from a server OS seems impossible. Attempting to run "func azure functionapp publish" when using Docker EE on windows server 2019 (which is using LCOW) we get the error "filesystem operations against a running hyper-v container are not supported "

**Comment by Hazhzeng** [comment]
@genscape-agodfrey Sorry for the inconvenience. There's an alternative way to deploy your local function app into Azure.
You may want to try `az functionapp devops-build create` command in Azure CLI to setup an Azure DevOps build/release pipeline for your functionapp. https://docs.microsoft.com/en-us/cli/azure/functionapp/devops-build?view=azure-cli-latest

Azure CLI is an Azure resource management tool. You may want to download it here.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

If you overcome any issues, feel free to raise them under https://github.com/Azure/azure-functions-devops-build/issues

**Comment by bmc-msft** [comment]
While not one of the above supported methods, I wanted to use slots for my deployment.  I went with building docker containers & using the az cli to deploy.

My Dockerfile: 
```
FROM mcr.microsoft.com/azure-functions/python:2.0
COPY . /home/site/wwwroot
RUN cd /home/site/wwwroot && pip install -r requirements.txt
```

In my CD, I use this to set a specific functions container instance to use container version I want:
`az webapp config container set --ids ${RESOURCE_ID} --slot ${TARGET_SLOT_NAME} -i ${TARGET_IMAGE_ID}`

Later on in the CD pipeline, once I have verified the setup is how I want, I use the following to handle the swapping:
`az webapp deployment slot swap --slot ${TARGET_SLOT_NAME} --ids ${RESOURCE_ID}`

**Comment by asavaritayal** [comment]
Closing the issue as there don't seem to be any pending items here.

**Comment by genscape-agodfrey** [comment]
@asavaritayal a pending item would be allowing the CLI to be used by CI/CD systems besides azure devops. The current approach violates build once, deploy to many.

**Comment by ahmedelnably** [comment]
@genscape-agodfrey  We do not have any plan to add support for 3rd party CI/CD systems to our Azure CLI, other than the current support for Azure Pipelines (DevOps)

**Comment by bmc-msft** [comment]
@ahmedelnably I would like to build once, deploy many with Azure Pipelines, but the current provided mechanisms do not allow that.

If you note in my comment, I have to package the application by hand and deploy it with az-cli, rather than use the provided tools.

**Comment by ahmedelnably** [comment]
Understood, but that would be a general question about Azure DevOps. creating the deployment artifact can be done either using the Azure Function Core Tools, or from you can also use the DevOps portal and use the built in templates to do the build once, 
For the deploy many, you can either use az functionapp deployment config-zip (while using the same zip file for more than one app), or create multiple release pipelines for the deploy many part.

We are also going to get slots support for az functionapp commands in Az CLI 2.0.67 (should be released tomorrow June 18)

More info about these templates are here: https://aka.ms/functions-azure-devops

**Comment by genscape-agodfrey** [comment]
@ahamad-MS if zip deploys can be made to work for the python functions, then yes, we would be happy using the azure function core tools. Last I checked zip deploys with azure python functions were not possible.
