### ISSUE TITLE
Deploy on Azure Function with private python package

### ISSUE THREAD

**Issue by Frantche** [Azure/azure-functions-python-worker#370]
Hi 

I am using Azure Python Function for tasks that need to be done once a day. They are triggered by MS Flow using http. 

Some code is shared between functions and functionapps. This code is now contained in a python package host in a private Azure DevOps repository. 

When i’m using Azure Function locally. I have no issues.

But when I am deploying the app from my laptop using : Function azure FunctionApp publish <Function name> --build-native-does, I have got the following error : no matching distribution found for 

How can I set an access to my private azure repos during Azure Function deployment ?

Best regard

Frantche

**Comment by asavaritayal** [comment]
To install a private package, you'll need to setup a DevOps pipeline. Here's a sample template - https://github.com/Azure/azure-functions-devops-build/blob/master/sample_yaml_builds/linux/consumption/python-consumption.yml

You can use the `az functionapp devops-build command` to help you create the pipeline.
