### ISSUE TITLE
Performance degradation | subprocess.call()

### ISSUE THREAD

**Issue by gkgaurav31** [Azure/azure-functions-python-worker#372]
The requirement is to convert PDF to PNG using ImageMagick on Azure WebApp for Containers.

Using base image: ubuntu:16.04

This works perfectly fine on a VM but takes too long on Azure WebApp for Containers. (with similar configurations). Since custom image is being used, everything is the same.

The following method is the slowest:

subprocess.call([
        "convert",
        "-density",
        "{}".format(resolution),
        tmpfilepath_pdf,
        tmpfilepath_png,])

The temporary files are saved in the container file system itself. (No volume mounted.)
There is not much improvement when using Premium App Service Plan as well.

Python Version: 3.6.1

**Comment by asavaritayal** [comment]
@gkgaurav31 this repo is dedicated to Azure Functions only. Please use the channels here - https://azure.microsoft.com/en-us/support/create-ticket/ to create a support ticket for Web Apps for Containers.
