### ISSUE TITLE
Importing local module into Python function fails

### ISSUE THREAD

**Issue by Kagigz** [Azure/azure-functions-python-worker#374]
Hello,

I've looked at these issues already: [#278](https://github.com/Azure/azure-functions-python-worker/issues/278) and [#219](https://github.com/Azure/azure-functions-python-worker/issues/219) but I keep having an issue when trying to import a local module into a Python function.

I'm using Python 3.7 and not 3.6 so it could be the reason why I can't get this to work. I'm working on a function created by someone else (with Python 3.6) and I want to run it locally. I have no issues running it but when I try to make an http request I get an error related to the import of a local module.

Here's my project structure:

```
functions_python
    |_ ml-service
        | __init__.py
        | model_helper.py
        | function.json
```
I want to import model_helper into init, and here are some of the things I tried:

from . import model_helper (no module named model_helper)
from ..ml-service import model_helper (Invalid syntax)
from functions_python.ml-service import model_helper (Invalid syntax)
import functions_python.ml-service (Invalid syntax)
from \_\_app__.ml-service import model_helper (Invalid syntax)
import \_\_app__.ml-service (Invalid syntax)

The reason I'm trying to import a module is because I have a class in there (used in a sklearn pipeline) and apparently you can't have it in \_\_init__.py

**Comment by Kagigz** [comment]
I don't have the code on GitHub yet, I need to generalize first (but I'm planning on doing it soon). In the meantime, here's what it looks like:

\_\_init.py__
```
#########
# IMPORTS
#########

import logging
import azure.functions as func
import base64, json
import requests
import os
import io

import spacy
import json
import nltk
import pandas as pd
import csv
import numpy as np
import string

from string import punctuation
nltk.download("stopwords")
from nltk.corpus import stopwords
from spacy.lemmatizer import Lemmatizer
from spacy.lang.en import LEMMA_INDEX, LEMMA_EXC, LEMMA_RULES
from spacy.tokenizer import Tokenizer

nlp = spacy.load('en_core_web_sm')

import sklearn
from sklearn import cluster
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.feature_extraction.stop_words import ENGLISH_STOP_WORDS
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.base import TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score


import azure.cosmos.cosmos_client as cosmos_client
from azure.storage.blob import BlockBlobService, PublicAccess


import pickle

from . import model_helper

# TEXT PROCESSING

.... (helper functions used in the sklearn pipeline)


# GETTING MODELS FROM BLOB STORAGE

def getLocalModel(path):
    try:
        model = pickle.load(open(path, 'rb'))
        print("Model retrieved.")
        return model
    except Exception as e:
        print(e)


def getModel(filename,path,blobConfig):
    try:
        blob_service = BlockBlobService(account_name=blobConfig['ACCOUNTNAME'], account_key=blobConfig['KEY'])
        blob_service.get_blob_to_path(blobConfig['CONTAINER'], filename, path)
        print("Pickle file retrieved from blob storage.")
        model = pickle.load(open(path, 'rb'))
        print("Model retrieved.")
        return model
    except Exception as e:
        print(e)

# GETTING PREDICTIONS

def getPrediction(txt,modelP,modelB):

    testTxt = [txt]

    # Precise model
    predictionP = modelP.predict(testTxt)[0]
    print("Precise prediction: ", predictionP)

    # Broad model
    predictionB = modelB.predict(testTxt)[0]
    print("Broad prediction: ", predictionB)

    prediction = predictionB
    if predictionP[0] == predictionB:
        prediction = predictionP

    print("Final prediction: ", prediction)
    return prediction


def main(req: func.HttpRequest) -> func.HttpResponse:

    logging.info('ml-service function processed a request.')

    payload = req.get_json()
    text = payload["text"]

    # BLOB STORAGE CONFIG

    blobConfig = {
        ...
    }
    
    # GETTING MODELS 

    modelP = getModel('...',os.path.join(os.getcwd(),"ml-service", "..."),blobConfig)
    modelB = getModel('...',os.path.join(os.getcwd(),"ml-service", "..."),blobConfig)


    label = getPrediction(text,modelP,modelB)


    return func.HttpResponse(
            json.dumps([ { 'label': label } ]),
            status_code=200, headers = { 'Content-Type': 'application/json' }
        )
```

model_helper
```
# Imports & helper methods...

class CleanTextTransformer(TransformerMixin):
    def transform(self, X, **transform_params):
        return [processText(text) for text in X]
    def fit(self, X, y=None, **fit_params):
        return self
    def get_params(self, deep=True):
        return {}
```

When I try to make a request, after importing model_helper with `from . import model_helper`, here's what I get:
![image](https://user-images.githubusercontent.com/16519462/55491888-90425600-5636-11e9-8a06-916069c9ace8.png)


**Note:** When I try to run the python script as is (outside of a Python function), everything works as expected. I planned on just copying/pasting everything into init.py but I ran into an issue with the CleanTextTransformer class, hence the model_helper module.

**Comment by maiqbal11** [comment]
From with your `__init__.py` file, can you do a dump of your modules (using `sys.modules`) and include it here? Want to check if our namespace is being registered.

**Comment by Kagigz** [comment]
Here it is:
[modules.txt](https://github.com/Azure/azure-functions-python-worker/files/3039689/modules.txt)

**Comment by maiqbal11** [comment]
The `modules.txt` file you've shared looks to be in a binary format. Something like the following should be sufficient to get a string representation:

```
import sys
with open('modules.txt', 'w') as f:
    f.write(str(sys.modules))
```

**Comment by Kagigz** [comment]
You're right sorry I used 'wb' instead of just 'w'. Here it is (for good this time):
[modules.txt](https://github.com/Azure/azure-functions-python-worker/files/3039747/modules.txt)

**Comment by maiqbal11** [comment]
Searching for `__app__` in the `modules.txt` file I'm seeing that the modules are getting registered correctly so they should be importable. We can try to see if this is an issue with Python 3.7 (or perhaps even the Anaconda distro which I see that you're using). Can you try creating a Python 3.6 virtual environment and running the function from within that? 
1. Instructions here on creating the environment and activating: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python#create-and-activate-a-virtual-environment. 
2. `pip freeze > requirements.txt` from within your app (outside of the virtual environment) 
3. Install the requirements inside the virtual environment after activating it: `pip install -r requirements.txt`
4. Run the function using `func host start` and see if the results are different

**Comment by Kagigz** [comment]
@maiqbal11 I have tried in a Python 3.6 virtual environment and it now works. The issue was indeed linked to the Python version. Do you know if v3.7 will be supported soon?

Thanks for your help

**Comment by maiqbal11** [comment]
@Kagigz, glad to hear! We need to be able to support both Python 3.6 and 3.7 since many core ML libraries currently have not been ported over to 3.7. This requires some infrastructure work on our part which will happen over the next few months. We are expecting to be able to support 3.7 within the year.
