### ISSUE TITLE
Function get_body() or req.body doesn't seem to return the actual HTTP request body

### ISSUE THREAD

**Issue by christian-vorhemus** [Azure/azure-functions-python-worker#380]
I have a simple HTTP triggered function which should receive a binary image and upload it to Azure Storage. The upload process fails because the HTTP request body seems to be malformed.

#### Investigative information

azure-common==1.1.18
azure-functions==1.0.0b3
azure-functions-worker==1.0.0b4

#### Repro steps

1) Create a Python Function App with the following code (note: same behaviour on JavaScript/TypeScript apps):

```
import logging
import azure.functions as func
from azure.storage.blob import BlockBlobService, PublicAccess
import sys

def main(req: func.HttpRequest, outputblob: func.Out[func.InputStream]) -> func.HttpResponse:
    logging.info('endpoint function processed a request.')

    command = req.route_params.get('command')
    file_binary = req.get_body()
    sz = sys.getsizeof(file_binary)

    outputblob.set(file_binary)
    return func.HttpResponse("Success", status_code=200)
```

2) Make a POST request to this function with a binary image in the body (Content-Type: image/png)

![code2](https://user-images.githubusercontent.com/3229424/54722737-8d8b2f80-4b65-11e9-980e-ad5dd0e5caae.png)

3) req.get_body() returns a binary object which is larger than it should be. This is what Fiddler tells me:

![code3](https://user-images.githubusercontent.com/3229424/54722744-93811080-4b65-11e9-8c68-8704eaba579c.png)

And this is what I see when debugging:

![code1](https://user-images.githubusercontent.com/3229424/54722746-97149780-4b65-11e9-9b86-047766d08f3d.png)

The file is ~635KB large and increased to ~1.1MB when accessing req.get_body()

#### Expected behavior

req.get_body() should return the raw binary HTTP request body

#### Related information 

Possibly related to #3875 - but this is closed?

**Comment by jimbobbennett** [comment]
@maiqbal11 - there is a reproduction at https://github.com/jimbobbennett/PythonFunctionsBodySizeBugRepo

If I upload binary file data the data that arrives is different to the data sent - the size of the body of the request is larger and the data is different.

If you launch the function app in that repo, then run the app.py file in the App folder you will see the bug in action.

I am using:
Azure Functions Core Tools (2.5.553 Commit hash: b63f2d6f5479718ca276f7b585a8cc6b9bc57c4f)
Function Runtime Version: 2.0.12382.0

**Comment by maiqbal11** [comment]
This is looking to be an issue on our end. Will update with details on the fix.

**Comment by maiqbal11** [comment]
The raw body behavior is not consistent across different content types. For `application/json`, it will use the actual raw body and send as is. However, for `application/octet-stream` types, the raw body is transmitted as a string instead of raw bytes (https://github.com/Azure/azure-functions-host/blob/71a6ab35770c33165f1543c51397013d0446a32f/src/WebJobs.Script/Rpc/MessageExtensions/RpcMessageConversionExtensions.cs#L162). 

We need to make changes to the Host so that it sends the correct raw bytes to the worker. This will require the worker and Host to implement support for custom capabilities when the worker is being started.

**Comment by maiqbal11** [comment]
\cc @asavaritayal

**Comment by Atala** [comment]
Hey,
Thanks for pointing this out (I was getting mad). I have two questions here :
(1) is there any workaround for now
(2) if I manage to patch this, how to be sure my code won't break once it is fixed ?
(Sorry to hurry you up I need this quickly for a project)
Thanks,

**Comment by maiqbal11** [comment]
\cc @pragnagopa

**Comment by fabriziomiano** [comment]
For what is worth, here's a workaround that did work for me. 
Essentially, as far as I understood, the image to be sent in the POST request, has to be converted to base64 first. 
The `get_body()` method now won't mess up with the bytes.
However, you need to decode the base64. Once this has been converted, you can pass it to `np.frombuffer()`, etc.
Hope it helps
Cheers

```
import base64
import numpy as np
import cv2 as cv


def main(req: func.HttpRequest) -> func.HttpResponse:
    base_64_image_bytes = req.get_body()
    image_bytes = base64.b64decode(base_64_image_bytes)
    img_nparr = np.frombuffer(image_bytes, dtype=np.uint8)
    image = cv.imdecode(img_nparr, cv.IMREAD_COLOR)
    cv.imwrite(TEMP_IMAGE_FILENAME, image)
    return func.HttpResponse("Done", status_code=200)

```

**Comment by S-Tensor** [comment]
> For what is worth, here's a workaround that did work for me.
> Essentially, as far as I understood, the image to be sent in the POST request, has to be converted to base64 first.
> The `get_body()` method now won't mess up with the bytes.
> However, you need to decode the base64. Once this has been decoded, you can pass it to `np.frombuffer()`, etc.
> Hope it helps
> Cheers
> 
> ```
> import base64
> import numpy as np
> import cv2 as cv
> 
> 
> def main(req: func.HttpRequest) -> func.HttpResponse:
>     base_64_image_bytes = req.get_body()
>     image_bytes = base64.b64decode(base_64_image_bytes)
>     img_nparr = np.frombuffer(image_bytes, dtype=np.uint8)
>     image = cv.imdecode(img_nparr, cv.IMREAD_COLOR)
>     cv.imwrite(TEMP_IMAGE_FILENAME, image)
>     return func.HttpResponse("Done", status_code=200)
> ```

I follow same but nothing received

**Comment by S-Tensor** [comment]
> I have a simple HTTP triggered function which should receive a binary image and upload it to Azure Storage. The upload process fails because the HTTP request body seems to be malformed.
> 
> #### Investigative information
> azure-common==1.1.18
> azure-functions==1.0.0b3
> azure-functions-worker==1.0.0b4
> 
> #### Repro steps
> 1. Create a Python Function App with the following code (note: same behaviour on JavaScript/TypeScript apps):
> 
> ```
> import logging
> import azure.functions as func
> from azure.storage.blob import BlockBlobService, PublicAccess
> import sys
> 
> def main(req: func.HttpRequest, outputblob: func.Out[func.InputStream]) -> func.HttpResponse:
>     logging.info('endpoint function processed a request.')
> 
>     command = req.route_params.get('command')
>     file_binary = req.get_body()
>     sz = sys.getsizeof(file_binary)
> 
>     outputblob.set(file_binary)
>     return func.HttpResponse("Success", status_code=200)
> ```
> 
> 1. Make a POST request to this function with a binary image in the body (Content-Type: image/png)
> 
> ![code2](https://user-images.githubusercontent.com/3229424/54722737-8d8b2f80-4b65-11e9-980e-ad5dd0e5caae.png)
> 
> 1. req.get_body() returns a binary object which is larger than it should be. This is what Fiddler tells me:
> 
> ![code3](https://user-images.githubusercontent.com/3229424/54722744-93811080-4b65-11e9-8c68-8704eaba579c.png)
> 
> And this is what I see when debugging:
> 
> ![code1](https://user-images.githubusercontent.com/3229424/54722746-97149780-4b65-11e9-9b86-047766d08f3d.png)
> 
> The file is ~635KB large and increased to ~1.1MB when accessing req.get_body()
> 
> #### Expected behavior
> req.get_body() should return the raw binary HTTP request body
> 
> #### Related information
> Possibly related to #3875 - but this is closed?

Have you resolve your issue ??

**Comment by rajatbansal01** [comment]
> I have a simple HTTP triggered function which should receive a binary image and upload it to Azure Storage. The upload process fails because the HTTP request body seems to be malformed.
> 
> #### Investigative information
> azure-common==1.1.18 azure-functions==1.0.0b3 azure-functions-worker==1.0.0b4
> 
> #### Repro steps
> 1. Create a Python Function App with the following code (note: same behaviour on JavaScript/TypeScript apps):
> 
> ```
> import logging
> import azure.functions as func
> from azure.storage.blob import BlockBlobService, PublicAccess
> import sys
> 
> def main(req: func.HttpRequest, outputblob: func.Out[func.InputStream]) -> func.HttpResponse:
>     logging.info('endpoint function processed a request.')
> 
>     command = req.route_params.get('command')
>     file_binary = req.get_body()
>     sz = sys.getsizeof(file_binary)
> 
>     outputblob.set(file_binary)
>     return func.HttpResponse("Success", status_code=200)
> ```
> 
> 2. Make a POST request to this function with a binary image in the body (Content-Type: image/png)
> 
> ![code2](https://user-images.githubusercontent.com/3229424/54722737-8d8b2f80-4b65-11e9-980e-ad5dd0e5caae.png)
> 
> 3. req.get_body() returns a binary object which is larger than it should be. This is what Fiddler tells me:
> 
> ![code3](https://user-images.githubusercontent.com/3229424/54722744-93811080-4b65-11e9-8c68-8704eaba579c.png)
> 
> And this is what I see when debugging:
> 
> ![code1](https://user-images.githubusercontent.com/3229424/54722746-97149780-4b65-11e9-9b86-047766d08f3d.png)
> 
> The file is ~635KB large and increased to ~1.1MB when accessing req.get_body()
> 
> #### Expected behavior
> req.get_body() should return the raw binary HTTP request body
> 
> #### Related information
> Possibly related to #3875 - but this is closed?

I am getting the decreased size from the original one.
