### ISSUE TITLE
How to add new binding type without changing python worker

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#381]
Wiki https://github.com/Azure/azure-functions-python-worker/wiki/Adding-support-for-a-new-binding-type describes how to add a new binding type that requires updating python worker.

@elprans - Can python worker handle binding type converters defined in a referenced library? 

cc @anthonychu @jeffhollan @asavaritayal @maiqbal11 @fabiocav

**Comment by elprans** [comment]
@pragnagopa As long as the binding adapter is registered by the virtue of being imported and extending the `InConverter` and `OutConverter`, the worker doesn't care where the code is at.  That said, loading and importing that third-party library is likely going to be a hassle.  Fortunately, Python has a standard mechanism that allows building "plugins" by declaring a special pkgresources entrypoint.

**Comment by anthonychu** [comment]
This sounds pretty good to me. I'm happy to test this out by writing the first adapter if you can add the extensibility point to the worker.

@pragnagopa I'm assuming that, like Java, we're going to ask the service teams to create and maintain their own packages. My main concern is around CI/CD infrastructure. We were lucky that the SignalR Service team had the expertise to build the maven pipeline for the Java library. I don't think they have the same expertise in Python (and if they do, some other team might not). Is there a way we can have the service teams own the code but make it easy for them to build and publish these packages to PyPI?

**Comment by pragnagopa** [comment]
@elprans  - Can you please look into  what needs to be updated /provided to load third-party library in the python worker?

@anthonychu - Yes, service teams should own the binding. I will open a tracking issue to provide better CI/CD pipeline for partner teams. Until then, binding owners need to test and release to PyPI manually.

**Comment by pragnagopa** [comment]
@elprans  - Any update on this?

**Comment by pragnagopa** [comment]
Ping!

**Comment by elprans** [comment]
@pragnagopa Working on a PR right now.

**Comment by pragnagopa** [comment]
@elprans  - Once you have the changes, please update the instructions  in the wiki [Adding-support-for-a-new-binding-type](https://github.com/Azure/azure-functions-python-worker/wiki/Adding-support-for-a-new-binding-type)

**Comment by elprans** [comment]
@pragnagopa Will do!

**Comment by pragnagopa** [comment]
Ping!

**Comment by elprans** [comment]
See #398. I also updated the Wiki page.

**Comment by anthonychu** [comment]
Thanks. I'll test this out with the SignalR Service bindings in mid-May. Any plans to create a repo with a sample binding? Would be extremely useful since the end-to-end tests that require the function host aren't necessarily easy to setup.

**Comment by pragnagopa** [comment]
@anthonychu  - I have opened tracking items to improve E2E test setup and publishing extension packages by the partner teams:
- https://github.com/Azure/azure-functions-host/issues/4364
- https://github.com/Azure/azure-functions-python-worker/issues/404
I do not have an ETA on when these issues will be addressed. Until then, please test manually and follow https://github.com/Azure/azure-functions-python-worker/wiki/Release-Instructions to publish to pypi
