### ISSUE TITLE
Deploying to Azure fails (python_docker_build killed)

### ISSUE THREAD

**Issue by Kagigz** [Azure/azure-functions-python-worker#382]
When trying to deploy my python function to Azure with the command `func azure functionapp publish funcname --build-native-deps`, I have this error after a while:

![image](https://user-images.githubusercontent.com/16519462/55858730-ba34d480-5b70-11e9-9b41-445a15bcbbe1.png)

I created a new python 3.6 environment, created the function app, installed all the libraries I needed, did `pip freeze > requirements.txt`.

The functions run locally without any issue.

I did have to remove a line (en-core-web-sm) from the requirements because I had an error:
![image](https://user-images.githubusercontent.com/16519462/55859265-02a0c200-5b72-11e9-92c7-d3e585edea99.png)

Here is what's in my requirements:

```
asn1crypto==0.24.0
azure-common==1.1.18
azure-cosmos==3.0.2
azure-functions==1.0.0b3
azure-functions-worker==1.0.0b4
azure-storage-blob==1.5.0
azure-storage-common==1.4.0
blis==0.2.4
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
cryptography==2.6.1
cymem==2.0.2
grpcio==1.14.2
grpcio-tools==1.14.2
idna==2.8
jsonschema==2.6.0
murmurhash==1.0.2
nltk==3.4
numpy==1.16.2
pandas==0.24.2
plac==0.9.6
preshed==2.0.1
protobuf==3.7.1
pycparser==2.19
python-dateutil==2.8.0
pytz==2018.9
requests==2.21.0
scikit-learn==0.20.3
scipy==1.2.1
singledispatch==3.4.0.3
six==1.12.0
sklearn==0.0
spacy==2.1.3
srsly==0.0.5
thinc==7.0.4
tqdm==4.31.1
urllib3==1.24.1
wasabi==0.2.1
```

Any idea what might be causing this?

**Comment by Kagigz** [comment]
Apparently the problem is with spacy, as when you remove it the function app can be built.

**Comment by maiqbal11** [comment]
Could you also share the version of core tools you're running using `func --version`? @ankitkumarr, have you seen this issue with building native dependencies before?

**Comment by christian-vorhemus** [comment]
Potentially, this is an out-of-memory issue. I was in the same situation, then I gave docker more RAM (2GB -> 6GB) and now _pip install_ runs through without problems.

**Comment by Kagigz** [comment]
@maiqbal11 my version is 2.4.498

The problem was the memory, thanks @christian-vorhemus!
