### ISSUE TITLE
best/better/quicker way of publishing changes to function __init__.py or function.json without publishing all app content?

### ISSUE THREAD

**Issue by rquintino** [Azure/azure-functions-python-worker#385]
Hi, I'm testing azure functions new linux consumption plan with python.
Is there any way of making publishing/updating faster for function code/settings changes only? Currently takes several minutes even when nothing in requirements was changed. :( 
Doing something wrong? 
thanks!

**Comment by maiqbal11** [comment]
@ankitkumarr to comment this. I believe there were some caching changes landing soon that would account for specifically this case.

**Comment by maiqbal11** [comment]
Transferring to the core tools repo as this is related to publishing. @ankitkumarr should be able to follow up on when the tooling changes are landing that would make this possible.

**Comment by ankitkumarr** [comment]
@rquintino, this is actually taken care of in the latest `azure-functions-core-tools` release. We have started to cache dependencies, and if your `requirements.txt` hasn't changed, we don't try and redownload the dependencies.

Please give it a try and let us know if it works out for you!

**Comment by maiqbal11** [comment]
@rquintino, closing the issue as the changes in question should already have landed and be usable. Feel free to re-open if you face any challenges.

**Comment by rquintino** [comment]
Hi @maiqbal11 , @ankitkumarr ,  thanks for the update and new features, they help. But still when we change only some code on __init__.py we're seeing a huge delay on uploading the full app package, 5 min and counting while I write this. 

Any hope for partial publishing of the changed files only? init.py is under few kbytes, nothing more was changed really.

thanks!
