### ISSUE TITLE
Python function execution consistency

### ISSUE THREAD

**Issue by WalidMustapha** [Azure/azure-functions-python-worker#386]
### Issue
I'm having a strange consistency issue when I try running one of my functions. When I make small, seemingly insignificant, modification to my python script, the likelihood of the function running decreases. When it doesn't run, I get following log output:

2019-04-13T14:24:53 Welcome, you are now connected to log-streaming service.
2019-04-13T14:24:56.773 [Information] Executing 'Functions.finn-old-homes' (Reason='This function was programmatically called via the host APIs.', Id=830c1f21-f356-4408-996d-14405f629e11)
2019-04-13T14:26:53 No new trace in the past 1 min(s).

However, If I modify my python script in a way which only affects the execution time (reducing the number of items in my loops dramatically), the function is able to execute successfully. This shouldn't be the case considering I opted for an App service plan.

Is this a bug or am I doing something wrong?

### Environment info
Pricing tier: (B1: 1)
Functions Version: 2.0
Worker: Python
azure CLI version: 2.0.61
Resource Group: finn-resourcegroup
Functions app: finn
App Service plans: finnserviceplan

**Comment by maiqbal11** [comment]
Are you making edits to your app directly via portal?

**Comment by WalidMustapha** [comment]
As far as I know, that's not possible with Python as it's in preview mode. I'm making the changes locally and deploying with the Functions Core Tools.

**Comment by maiqbal11** [comment]
Can you describe your scenario in more detail? I'm seeing that the function in question is timer triggered once every minute. That might be related to why reducing execution time leads to the function working correctly more often.

**Comment by WalidMustapha** [comment]
I think I figured out the issue. If you take a look at Operation ID "uS6GQyRpdbg=" for function _finn-old-homes_ you will see it failed due to the timeout value being exceeded. The script executes somewhat faster on my local machine than what I had originally allocated as "functionTimeout" in _host.json_, so I was a bit surprised the timeout value had been reached. I'm uncertain why there are performance differences. Could it be related to writing to Blob storage or http requests from my script?

I just doubled "functionTimeout" to 10 hours and ran the job. Hopefully, 10 hours should be more than sufficient for getting the task done. I will get back to you with results.

**Comment by maiqbal11** [comment]
> Could it be related to writing to Blob storage or http requests from my script?

This could potentially be the case. The App Service Plan has a 30 minute timeout by default in v2.x (https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout), but there is no upper limit. It's hard to say why this might be happening without knowing the specifics of what your function is doing.

**Comment by maiqbal11** [comment]
Hi @WalidMustapha, is this issue resolved with the timeout change?

**Comment by WalidMustapha** [comment]
Hi @maiqbal11,

Sorry I didn't get back to you sooner. I ended up deploying using Apache Airflow which accomplishes what I was looking for from Azure functions by using DAG file definition. I never managed to get the function working with the timeout change, but I didn't have time to debug.

**Comment by maiqbal11** [comment]
@WalidMustapha, sorry to hear about that. I'll close the issue for now. Feel free to re-open if you need more assistance on this.
