### ISSUE TITLE
Bindings Contribution Strategy - Python

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#393]
The contribution workflow for Python bindings seem cumbersome in terms of local implementation and testing. It is possible through a hacky method of tweaking the func core tools path to a python deps location where new rich type binding needs to be copied.

Need  a cleaner approach.

[Python Functions Binding Contribution.docx](https://github.com/Azure/azure-functions-python-worker/files/3120236/Python.Functions.Binding.Contribution.docx)

**Comment by maiqbal11** [comment]
Thanks for compiling this @priyaananthasankar!

**Comment by elprans** [comment]
I’m working on a way to make this process easier.

**Comment by priyaananthasankar** [comment]
@elprans : I have raised PR's for the Kafka trigger/bindings in both azure-functions-python-worker and library repos. Can this be merged soon?

**Comment by maiqbal11** [comment]
@elprans, can you provide details on how the entry point will be used once it is loaded? For example, is it sufficient to just include `import kafka` at the top of a function and then use the type annotation `kafka.KafkaEvent` or is there something else that needs to happen? Currently, the wiki has information on what we can do to register the binding but not how we use it.

**Comment by elprans** [comment]
Nothing special needs to be done. Just import and use.

**Comment by anirudhgarg** [comment]
I am not sure if there is any action item here. Closing this out.
