### ISSUE TITLE
HTTP Triggers and Bindings

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#4]
HTTP webhook triggers and HTTP output bindings will use  request and response objects to represent the HTTP messaging. 

#### Request Object
The **request** object has the following attributes.

**Attribute** | **Data Type** | **Description**
-------------|----------|----------------
method | str | HTTP method of the request
url | str | Url of the request
headers | dict | HTTP headers sent with the request
data | dict | Form data parameters
params | dict | Query string parameters
body | bytes | Raw HTTP request body

#### Response Object
The **response** object has the following attributes.

**Attribute** | **Data Type** | **Description**
-------------|----------|----------------
headers | dict | Response headers
status_code | int | HTTP response status code
content | str, bytes, dict | Contents of the response

Similar to any other binding, the HTTP request and response objects can be accessed using the name attribute from function.json.

Example - [https://github.com/Azure/azure-functions-python-worker/tree/master/Samples/HttpTrigger1](https://github.com/Azure/azure-functions-python-worker/tree/master/Samples/HttpTrigger1)

**Comment by 1st1** [comment]
I'm wondering if we actually want to pass `Response` object as an argument.  It seems that Azure Java allows users to just return it, which would look like this in Python:

```python
def main(req: Request):
    return Response(status_code=404)
```

There's really no requirement for us to instantiate the `Response` object outside of the `main()` function.  I believe that JavaScript worker allows to simply return `{status: 404}` hash.

**Comment by brettcannon** [comment]
I say just return it. Pre-allocating is not worth it and feels like boilerplate overhead in the function signature to me.

**Comment by 1st1** [comment]
Yep, working on a PR to implement that right now.

**Comment by asavaritayal** [comment]
What if the the HttpResponse is not bound to the method return value? Can the user still set its value in the function?

**Comment by 1st1** [comment]
Yes, you can declare it as an "out" binding with a different name from $return, and it will work too.

**Comment by 1st1** [comment]
Everything here is now implemented in the `dev` branch.
