### ISSUE TITLE
GA availability for python Azure Functions 2.x ?

### ISSUE THREAD

**Issue by vihangs** [Azure/azure-functions-python-worker#407]
Any idea when Python will be GA available for Azure Functions 2.x ?

**Comment by asavaritayal** [comment]
Unfortunately, we're unable to share this information publicly at this time. Please tune into https://azure.microsoft.com/en-us/updates/?product=functions for future announcements.

**Comment by ankitkumarr** [comment]
FYI, Azure Functions on Python was announced GA today https://twitter.com/AzureFunctions/status/1163511532417765376
