### ISSUE TITLE
Old environment variables should be cleared on reload

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-python-worker#410]
On handling an environment reload request, we should remove any existing. In other words, the only environment variables should be those that come from the reload request as [here](https://github.com/Azure/azure-functions-java-worker/blob/12dcee7ca829a5f961a23cfd1b03a7eb7feae5e0/src/main/java/com/microsoft/azure/functions/worker/handler/FunctionEnvironmentReloadRequestHandler.java#L53)

cc: @pragnagopa , cc:@maiqbal11

**Comment by mhoeger** [comment]
@asavaritayal - i think this may be more important than a Backlog item because 1. the other implementation may cause incorrect behavior and 2. the fix is likely a breaking change

**Comment by pragnagopa** [comment]
Right. Added P1 label as this is a required change for placeholders.

**Comment by maiqbal11** [comment]
@pragnagopa, @mhoeger, I'm assuming that this does not refer to system environment variables and simply the app settings that are loaded as environment variables?

**Comment by pragnagopa** [comment]
Process environment variables need to be replaced as we do not want anything left over from the process that started in placeholder mode. 

@maiqbal11 - Are there any environment variables you are concerned about?

**Comment by anirudhgarg** [comment]
Assigned to Maheer to follow up with Marie. If this is needed for placeholder then should be done immediately.

**Comment by pragnagopa** [comment]
Yes this is needed for placeholders. Process state that was started during placeholder mode  cannot be carried over after specialization.
@maiqbal11 / @anirudhgarg - please make sure this is addressed and released before placeholder changes  in the host get released.

**Comment by maiqbal11** [comment]
@pragnagopa, I'm not concerned about any particular environment variables, but I'm also not sure what side effects might happen if we entirely clear the environment for a running process. For example, is the host using some environment variables persistently even after specialization? If not, then this should be trivial to implement. Could you point me to how this is being done for Java? If it's just a matter of clearing everything and then loading the new settings, it should be very easy to implement.

**Comment by pragnagopa** [comment]
@maiqbal11 - See here for Java worker changes: https://github.com/Azure/azure-functions-java-worker/blob/dev/src/main/java/com/microsoft/azure/functions/worker/handler/FunctionEnvironmentReloadRequestHandler.java#L53

> I'm also not sure what side effects might happen if we entirely clear the environment for a running process

Only way to confirm no side effects is to try this out. I am not aware of any issues with this approach and this is the intended design. We cannot carry stale environment settings from the process that started in placeholder mode.
