### ISSUE TITLE
How to receive events batch in Eventhub triggered function

### ISSUE THREAD

**Issue by joal42** [Azure/azure-functions-python-worker#411]
#### Investigative information
I have a eventhub triggered function in python and want to receive events in batch.

In function.json set `cardinality` to `many`
  "cardinality": "many",
What should the parameter in main function to pass a list of events?

This example can only get one event data:
`def main(event: func.EventHubEvent):`

**Comment by pragnagopa** [comment]
@asavaritayal  - This needs to be documented. Receiving a batch of eventhub events is the recommended approach.
@elprans  - Can you share sample code for receiving an array or list of eventHubEvent?

**Comment by asavaritayal** [comment]
@1st1 @elprans once you provide a sample, I can go update the documentation.

**Comment by maiqbal11** [comment]
While working on a different EventHub issues, came across this issue: https://github.com/Azure/azure-webjobs-sdk/issues/1830. Looks like setting `cardinality` to `many` has the potential to error out if valid json is not provided. Wanted to make a note of this because I ran into this with our default EventHub template in core tools. If we are going to be recommending `cardinality : many` as a way to get batched events, we should at least ensure that the default experience works.

**Comment by joal42** [comment]
@maiqbal11 Thanks for linking the webjobs issue. I set to `many` and use the input as bytes. And then, I convert bytes to array of string. It looks working fine. It would be better if you can share some default usage example.

**Comment by joal42** [comment]
@maiqbal11 I found that I loose eventhub meta data, like `offset` if I use batch model. Could you also help with how to get eventhub meta date in batch processing?

**Comment by pragnagopa** [comment]
For batch processing, trigger data and metadata is received as an array via RPC. Please see java sample code here: https://github.com/Azure/azure-functions-java-worker/blob/dev/endtoendtests/src/main/java/com/microsoft/azure/functions/endtoend/EventHubTriggerTests.java#L27
Note: SystemPropertiesArray is populated by the java worker.

@elprans / @maiqbal11  - Does python worker expose an array of metadata?

**Comment by joal42** [comment]
@pragnagopa Thanks for your information. I checked the similar test code path https://github.com/Azure/azure-functions-python-worker/blob/dev/tests/test_eventhub_functions.py
I didn't find the similar metadata array populated.
@elprans @maiqbal11  It would be nice if you can help with it.

**Comment by maiqbal11** [comment]
The SystemPropertiesArray isn't currently being populated by the Python worker. Will need to make a change that allows it to handle this case.
