### ISSUE TITLE
I am trying to deploy python function to azure

### ISSUE THREAD

**Issue by Pratyusha91** [Azure/azure-functions-python-worker#412]
#### Investigative information

Please provide the following:

- Timestamp:05/08/2019 
- Function App name:NA
- Function name(s) (as appropriate):NA
- Core Tools version: Visual Studio Code

#### Repro steps

Provide the steps required to reproduce the problem:
Following the doc https://code.visualstudio.com/docs/python/tutorial-azure-functions#_visual-studio-code-python-and-the-azure-functions-extension

Installed the required extensions

#### Expected behavior

Provide a description of the expected behavior.
Need to run successfully and deploy to azure 

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Links to source
* Contents of the requirements.txt file
* Bindings used

<
import logging
import azure.functions as func
def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    name = req.params.get('name')
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get('name')

    if name:
        return func.HttpResponse(f"Hello {name}!")
    else:
        return func.HttpResponse(
             "Please pass a name on the query string or in the request body",
             status_code=400
        )

Error is at import azure.functions

-->

**Comment by asavaritayal** [comment]
Closing in favor of the known issue tracked here - https://github.com/Azure/azure-functions-core-tools/issues/1194. As mitigation, you can manually run `pip install azure-functions` in your local environment. Feel free to re-open if this doesn't fix the issue.
