### ISSUE TITLE
Cosmos Gremlin Binding

### ISSUE THREAD

**Issue by lanrongwen** [Azure/azure-functions-python-worker#413]
The current binding options for Cosmos include getting all records, a single record based off ID, or a SQL statement.  This limits the Graph Capabilities of the Gremlin instance.  Can we get a Gremlin Query added to the binding options?  It would be mutually exclusive to the ID/SQL Query that are already supported.

**Comment by asavaritayal** [comment]
With the current bindings, it's not possible to query through the Gremlin API. You can work around this by using your own Gremlin client and not the bindings. 

Adding to the 'unknown' to gauge traction.

**Comment by anirudhgarg** [comment]
Closing this issue as this is stale at this point and havent seen a lot of demand for the Gremlin based API - further this is a question for CosmosDB binding overall.
