### ISSUE TITLE
Service Bindings for Python

### ISSUE THREAD

**Issue by lanrongwen** [Azure/azure-functions-python-worker#414]
In other languages such as C#, you can get an instance of the client through the binding, allowing you to do more queries or updates in code than you can do in the functions.json document.  This is especially helpful when you need to query and update a record.  Is this on the roadmap or even possible in Python Functions?

**Comment by asavaritayal** [comment]
Renaming to reflect the feature name - "Service Bindings". This is currently not available for any of the out-of-process languages in Functions 2.0 (Node, Java, PowerShell). Currently unplanned, will put it on the backlog to gauge traction. Any info you can share about the specific scenarios you're hoping to enable would help us prioritize better.

**Comment by lanrongwen** [comment]
I see it break down into 3 things that I've done in C# to make the code easier/more efficient that are hard to do in just a straight function.json binding currently available in Python.
* Reading data by doing multiple queries against the data set made visible from the binding.
* Updating entries, such as in a storage table.
* More control over the objects created, such as manipulating things that will be put in a queue (time to live, time to visible).
Having it limited to what is in function.json means I would have to do multiple bindings to get the different data, which can make the code less clean.
Or I can have it return all records and sort it in the function, but that's not very efficient from a functional resource and time to run point of view.
Or I can import all the libraries and not use the bindings, which means you loose a lot of the ease of use that Functions have to offer.

**Comment by Hazhzeng** [comment]
This function.json is part of our architecture which is designed to supporting multiple language workers. Our Python worker needs to align with NodeJs/Java/PowerShell worker etc.

We decide to keep the azure-functions SDK as simple as possible for the ease of bootstrapping a function project. If a simple trigger needs to gather resources from different services, please consider using the related SDKs (azure-storage-blob, azure-cosmos etc.)
