### ISSUE TITLE
Feature: pipenv as dependency manager

### ISSUE THREAD

**Issue by casparjespersen** [Azure/azure-functions-python-worker#417]
pipenv is a modern package dependency management system, allowing for better handling of requirements and virtual environments. This is a request to use Pipfile as requirement handler for Python Azure Functions. 

#### Expected behavior

- Having a Pipfile in top-level directory should dictate required packages
- Packages under ‘—dev’ should be ignored 

#### Known workarounds

- Using ‘freeze’ to generate ‘requirements.txt’ dynamically in build environment

#### Related information 

* https://github.com/pypa/pipenv

**Comment by Brolymon** [comment]
whats going on with this?

**Comment by vrdmr** [comment]
Not planned.
