### ISSUE TITLE
Test generic binding support via SignalR

### ISSUE THREAD

**Issue by elprans** [Azure/azure-functions-python-worker#420]
As a continuation of #66 and #409, add tests for SignalR and Table Storage bindings.

**Comment by pragnagopa** [comment]
updated the title to reflect singnalR only. Testing table storage should be trivial. PR #409 should include E2E test for table storage bindings

**Comment by anirudhgarg** [comment]
This is dependent on https://github.com/Azure/azure-functions-python-worker/pull/409

**Comment by maiqbal11** [comment]
@anthonychu already wrote a cool article highlighting this functionality: https://dev.to/azure/end-to-end-serverless-real-time-iot-with-python-4i2b 😄
