### ISSUE TITLE
Supportability detectors for runtime version errors

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#425]
**Scenario**
Function apps built using a version different than 3.6.x can be published to Azure today. In the event that the app is using features incompatible with the version supported in Azure, we want to provide basic supportability detector(s) to catch the errors and recommend mitigation.

**Comment by Hazhzeng** [comment]
This is done in AppLens Detector:
**LinuxFxVersion Language Check**
