### ISSUE TITLE
[Docs] Managed Identity sample for Python

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#426]
Working with Managed Identities from within a function is documented here: https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity#obtaining-tokens-for-azure-resource

There is currently no example for Python. Given that MIs are now supported on Linux App Service and Premium plans, we should provide a Python sample as well. 

/cc @ggailey777

**Comment by asavaritayal** [comment]
MSI will be enabled for Linux consumption platform with ANT 83 deployment.

**Comment by anirudhgarg** [comment]
We have added a sample in Python here:
https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity#code-examples

**Comment by ezra-at-lumedic** [comment]
Why no example of a pure (and simpler) ActiveDirectoryMsi based authentication?  The two-step approach -- getting a token, then sending the token to the ODBC driver -- is not longer needed with Version 17 of the driver.  Why not show the simple approach?  Also, would you please make sure it also works on Linux as the prerequisites are a bit different than on the Windows image.

**Comment by joedevgee** [comment]
can we use MI auth in blob trigger for python?
for example, if I have `"<CONNECTION_NAME_PREFIX>__blobServiceUri": "https://example.blob.core.windows.net"`
I should be able to use below decorator in my blob trigger
```python
@app.blob_trigger(
    arg_name="input",
    path="rms/extracts/{timestamp}/{name}.csv",
    connection="<CONNECTION_NAME_PREFIX>__blobServiceUri",
)
```
pls let us know if this is possible and if so, please give an example
