### ISSUE TITLE
Update pythonpath in cli and docker to allow user dependencies to take precedence

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#434]
In order to give control to the users to pick a version of azure.function library, worker needs to use package that comes as part user code and not worker dependency. This is needed for
- Users to opt-in when to upgrade extension bundles version
- To able to pin to a version of azure.functions
   - Need to remove installing azure.function from https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/arm32v7/python.Dockerfile#L36
  - Need to remove installing azure.function from Core tools

In order to avoid breaking existing python function apps, worker needs to load default version of azure.functions if user code did not include azure.functions package.
cc: @asavaritayal @maiqbal11 @anirudhgarg @ankitkumarr

**Comment by pragnagopa** [comment]
Lets discuss this offiline

**Comment by elprans** [comment]
The crux of the issue here is how to replace the `RpcHttp` protobuf.

**Comment by pragnagopa** [comment]
@elprans - Assuming you meant comment in the issue #135 . Let's discuss on the other issue.

**Comment by asavaritayal** [comment]
Notes from offline sync: We won't remove the library. Instead, will prioritize user provided dependencies over system dependency.

**Comment by pragnagopa** [comment]
@maiqbal11 - Please look at using pkg_resources to ensure python worker uses the right version of dependencies https://setuptools.readthedocs.io/en/latest/pkg_resources.html
