### ISSUE TITLE
cryptography dependency issue

### ISSUE THREAD

**Issue by akshaybabloo** [Azure/azure-functions-python-worker#435]
**Edit:**

I tried doing 

```
func azure functionapp publish neucube-instance-function --build-native-deps
```

It's been more than an hour and I just don't see any result.

#### Investigative information

Please provide the following:

- Timestamp:
- Function App name: neucube-instance-function
- Function name(s) (as appropriate): CreateNeuCubeInstance
- Core Tools version: 2.7.1158

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create an HttpTrigger app and add one of the packages that are depending on `cryptography` package
2. Pack it with - `func pack`

#### Expected behavior

Should be able to pack without any error.

#### Actual behavior

I get the following error:

```
(.env) (base) PS>func pack
Deleting the old .python_packages directory
pip download -r C:\Users\aksha\Documents\GitHub\neucube-instance-function\requirements.txt --dest C:\Users\aksha\AppData\Local\Temp\azureworkerxw_irip_
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest C:\Users\aksha\AppData\Local\Temp\azureworker04mqlqca adal==1.2.1
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest C:\Users\aksha\AppData\Local\Temp\azureworker04mqlqca asn1crypto==0.24.0
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest C:\Users\aksha\AppData\Local\Temp\azureworker04mqlqca azure_common==1.1.21
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest C:\Users\aksha\AppData\Local\Temp\azureworker04mqlqca azure_mgmt_containerinstance==1.4.1
There was an error restoring dependencies.ERROR: cannot install cryptography-2.6.1 dependency: binary dependencies without wheels are not supported.  Use the --build-native-deps option to automatically build and configure the dependencies using a Docker container. More information at https://aka.ms/func-python-publish
```

I shouldn't be getting this error as the `cryptography-2.6.1` do provide wheels 🤔 

#### Known workarounds

None so far

<details>
<summary>Source</summary>

```python
# __init__.py

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    return "Done"
```

```txt
sentry-sdk==0.8.0
azure-mgmt-containerinstance==1.4.1
pymongo==3.8.0
azure-servicebus==0.50.0
```

</details>

**Comment by akshaybabloo** [comment]
OK, there was an issue with `az` CLI, building locally worked for me

**Comment by szaher** [comment]
What was the issue with az cli. 

I am facing the exact same problem with my function. I can't use --build-native-deps as I have some private packages that I am fetching from local repo.

Any idea how to fix that ?
