### ISSUE TITLE
Blocked connecting to sql from python azure functions

### ISSUE THREAD

**Issue by writetokavitha** [Azure/azure-functions-python-worker#441]
I am trying to host a timer trigger python based azure function that runs periodically. I am blocked connecting from python azure functions to sql. Same error has been reported in public thread that’s been closed but theres no clear resolution.
https://github.com/Azure/azure-functions-python-worker/issues/249

Since this is blocking my current work. would like to know if this is a supported scenario/has workaround/alternative drivers to connect to sql so I can look for alternative Azure services like Azure batch to host this python job if azure function will not work.

 [Error] Executed 'Functions.TimerTrigger' (Failed, Id=45de9d66-99f0-43e8-9b5e-eda45c5768f5) Result: Failure Exception: Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)") Stack: File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py"

**Detailed Error:**
2019-05-23T00:16:08.922 [Information] Executing 'Functions.TimerTrigger' (Reason='This function was programmatically called via the host APIs.', Id=45de9d66-99f0-43e8-9b5e-eda45c5768f5)
2019-05-23T00:16:09.034 [Information] ['/azure-functions-host/workers/python', '/root/.pyenv/versions/3.6.8/lib/python3.6', '/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages', '/home/site/wwwroot', '/home/site/wwwroot/.python_packages/lib/python3.6/site-packages', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages']
2019-05-23T00:16:09.043 [Information] Python timer trigger function ran at 2019-05-23T00:16:09.024444+00:00
2019-05-23T00:16:09.088 [Error] Executed 'Functions.TimerTrigger' (Failed, Id=45de9d66-99f0-43e8-9b5e-eda45c5768f5) Result: Failure Exception: Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)") Stack: File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 288, in _handle__invocation_request self.__run_sync_func, invocation_id, fi.func, args) File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run result = self.fn(*self.args, **self.kwargs) File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 347, in __run_sync_func return func(**params) File "/home/site/wwwroot/TimerTrigger/__init__.py", line 126, in main conn = pyodbc.connect(dbAccessStr

**Code used:**
import datetime
import logging

import azure.functions as func
from sklearn.datasets import load_iris 
import pyodbc       
import os
import sys

def main(mytimer: func.TimerRequest) -> None:
    logging.info(sys.path)
    utc_timestamp = datetime.datetime.utcnow().replace(
        tzinfo=datetime.timezone.utc).isoformat()

    if mytimer.past_due:
        logging.info('The timer is past due!')

    logging.info('Python timer trigger function ran at %s', utc_timestamp)

    print("Testing...")
    dbConnectionString = "<Connection string>"

    def getConnectionStringAttribute(conn_string, name):
        return conn_string[conn_string.find(name) + len(name) + 1:conn_string.find(';', conn_string.find(name))]
        
    dbDriver = '{ODBC Driver 13 for SQL Server}'
    dbServer = getConnectionStringAttribute(dbConnectionString, "Server").split(',')[0]
    dbPort = getConnectionStringAttribute(dbConnectionString, "Server").split(',')[1]
    database = getConnectionStringAttribute(dbConnectionString, "Initial Catalog")
    dbUsername = getConnectionStringAttribute(dbConnectionString, "User ID")
    dbPassword = getConnectionStringAttribute(dbConnectionString, "Password")
    dbAccessStr = 'DRIVER=' + dbDriver + ';SERVER=' + dbServer + ';PORT=' + dbPort + ';DATABASE=' + database + ';UID=' + dbUsername + ';PWD=' + dbPassword

    conn = pyodbc.connect(dbAccessStr)
    cursor = conn.cursor()
    cursor.execute("SELECT TOP 10 * from dbo.MLAutoRetrainRunInfo_v3 ORDER BY Id DESC")
    row = cursor.fetchone()
    s = ""
    while row != None:
        s = s + "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" % (str(row[0]), str(row[1]), str(row[2]), str(row[3]), str(row[4]), str(row[5]), str(row[6]), str(row[7]), str(row[8]))
        row = cursor.fetchone()
        
    print(s)

**Comment by maiqbal11** [comment]
Resolving based on offline discussion. Solution was to use OBDC Driver 17 for SQL Server since that is what we currently install in the image.

**Comment by writetokavitha** [comment]
The following code now work to connect from python azure functions on linux - the fix is to use 
dbDriver = '{ODBC Driver 17 for SQL Server}'


Code used:
import datetime
import logging
import azure.functions as func
from sklearn.datasets import load_iris
import pyodbc
import os
import sys
def main(mytimer: func.TimerRequest) -> None:
logging.info(sys.path)
utc_timestamp = datetime.datetime.utcnow().replace(
tzinfo=datetime.timezone.utc).isoformat()
if mytimer.past_due:
    logging.info('The timer is past due!')

logging.info('Python timer trigger function ran at %s', utc_timestamp)

print("Testing...")
dbConnectionString = "<Connection string>"

def getConnectionStringAttribute(conn_string, name):
    return conn_string[conn_string.find(name) + len(name) + 1:conn_string.find(';', conn_string.find(name))]
    
dbDriver = '{ODBC Driver 17 for SQL Server}'
dbServer = getConnectionStringAttribute(dbConnectionString, "Server").split(',')[0]
dbPort = getConnectionStringAttribute(dbConnectionString, "Server").split(',')[1]
database = getConnectionStringAttribute(dbConnectionString, "Initial Catalog")
dbUsername = getConnectionStringAttribute(dbConnectionString, "User ID")
dbPassword = getConnectionStringAttribute(dbConnectionString, "Password")
dbAccessStr = 'DRIVER=' + dbDriver + ';SERVER=' + dbServer + ';PORT=' + dbPort + ';DATABASE=' + database + ';UID=' + dbUsername + ';PWD=' + dbPassword

conn = pyodbc.connect(dbAccessStr)
cursor = conn.cursor()
cursor.execute("SELECT TOP 10 * from dbo.MLAutoRetrainRunInfo_v3 ORDER BY Id DESC")
row = cursor.fetchone()
s = ""
while row != None:
    s = s + "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" % (str(row[0]), str(row[1]), str(row[2]), str(row[3]), str(row[4]), str(row[5]), str(row[6]), str(row[7]), str(row[8]))
    row = cursor.fetchone()
    
print(s)
