### ISSUE TITLE
[Docs] Change documentation in the Python Developers guide to reflect that we now support CORS

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#444]
Linux consumption platform is not providing this out of the box.

**Comment by jashan05** [comment]
@asavaritayal When can we expect this to be delivered. I am already facing this issue and not able to fix the CORS issues within my Azure functions

**Comment by asavaritayal** [comment]
@jashan05 You can already enable the scenario for your function by setting the `ACCESS-CONTROL-ALLOW-CREDENTIALS` header in the HTTP response. Current backlog item is tracking the documentation work only.

**Comment by jashan05** [comment]
@asavaritayal  could you please provide an example may be... I am not able to wrap my head around it. :)

**Comment by wboleksii** [comment]
@asavaritayal Can you provide example? I've tried setting it in  `func.HttpResponse(data, headers=headers)`, but it doesn't work.

**Comment by balag0** [comment]
@jashan05  You will need to use something like this (if required replace * with the domain you will be using to make the request)
    headers = {"Access-Control-Allow-Origin": "*"}
    return func.HttpResponse("Hello", headers = headers)

@wboleksii  Can you provide more details on what is not working?

**Comment by balag0** [comment]
@jashan05  Try the following (if required replace * with the domain you will be using to make the request)

```
headers = {"Access-Control-Allow-Origin": "*"}
return func.HttpResponse("Hello", headers = headers)

```
@wboleksii Can you provide more details on what is not working?

**Comment by wboleksii** [comment]
@balag0 
Apparently when you change a plan from Linux Consumption to App Service, something goes wrong. I recreated resources from scratch and now it's working fine.

**Comment by fabiocav** [comment]
@asavaritayal should this move to sprint 53? Should we put this back in `Triaged`?

**Comment by asavaritayal** [comment]
> @jashan05  Try the following (if required replace * with the domain you will be using to make the request)

```
headers = {"Access-Control-Allow-Origin": "*"}
return func.HttpResponse("Hello", headers = headers)

```

Adding @ggailey777 and @craigshoemaker to formalize into the developer guide as a workaround for a known limitation.

**Comment by Olcina** [comment]
Hi, first of all. Thanks for your comments, I was able to add the headers to the pre-flight. 

Nevertheless, I needed to add the OPTIONS  method to all the `httpTrigger` functions in `functions.json`, as it's required for CORS requests in chrome.
```
      "methods": [
        "get",
        "options"
     ]
```
Is that the expected behavior? I have another functions project in `javascript` language and I didn't need to add the OPTIONS method.

**Comment by ggailey777** [comment]
Tracking this requirement internally [here](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1579697).

**Comment by anirudhgarg** [comment]
We know support CORS natively in Python Consumption now. @ggailey777 we dont need the workaround anymore. Can we please change the documentation on the Python Developers page to reflect that.

**Comment by anirudhgarg** [comment]
Will close this out when the documentation is updated. Will keep it open till then.

**Comment by anirudhgarg** [comment]
Can close this out - we have cleaned up the documentation.
