### ISSUE TITLE
Nuget artifact generated by the Python worker is version specific

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-python-worker#450]
`azure-functions-python-worker` creates nuget artifact using Python 3.6. This means that all the native binaries are created only for Python 3.6. 

This causes `azure-functions-core-tools` to be unable to support other versions of Python for Functions in Python. This will be true for all apps, because `grpc` has native binaries, for example - `cygrpc.cpython-36m-darwin.so` in `grpc._cython` that is used by the worker.

As you can see from the example above, because Python version 36 is specified above (because the binary was created for 36), this gets rejected by any other Python interpreter (say 3.7) giving this error - 
`ImportError: cannot import name 'cygrpc' from 'grpc._cython'`

@asavaritayal, @maiqbal11, @anirudhgarg I am not sure what the best solution might be, but this will be a blocker from allowing any users to publish apps from multiple Python version.

Maybe we should go back to installing `azure.functions_worker` on user's machine directly.

Update: It's not just Python version, they would also need to have the target architecture (64 bit) as well.

**Comment by maiqbal11** [comment]
@pragnagopa, @fabiocav as well, this might tie into the earlier discussion we had about supporting multiple versions of dependencies for different platforms via the `worker.config.json`. Do we also want include a versioning for languages within that? Something like `<language>.<os>.<architecture_version>.<language_version>`? We can then choose which version of the worker to run based on the user specifying the worker runtime language **and** its version?

**Comment by pragnagopa** [comment]
We need to start creating issues for adding support for 3.7 addressing this issue will be part of updating tooling to support 3.7

**Comment by ankitkumarr** [comment]
Had a chat with @pragnagopa, ideally we would want to be thinking about solving the bigger problem of supporting multiple versions everywhere (local, azure, etc). This should be kept in mind before we make any decisions.

Until we have resolved that problem, we could have this workaround --

Publish only 3.6 compatible nuget with the host / core-tools. If users have 3.7 or other versions that are not supported, link them to the docs about how to manually install 3.7 version worker and replace the existing one locally. We would point them to the path `workers/python/deps`, ask them to clear it out and have them `pip install --target` it there. That would also mean for core-tools to be able to know what version is the worker on the path compatible for (3.6 or 3.7). 

Instead of doing it manually, it can be automated via core-tools but we don't want to implement this workaround or a hack if the core issue will be addressed later.

**Comment by anirudhgarg** [comment]
We decided not do this for 3.6. This will be relevant when we move to 3.7. Moving to backlog.
