### ISSUE TITLE
Unable To Deploy ANY Python Azure Function (There was an error restoring dependencies.ERROR:))

### ISSUE THREAD

**Issue by dgan11** [Azure/azure-functions-python-worker#459]
Basically, I am unable to deploy my Timer Triggered Azure Function through any method (Terminal or VSCode) when there is anything in my requirement.txt file. Whenever I leave the requirements.txt file empty, the function will deploy successfully. I have been mainly working with VSCode.

#### Investigative information

Please provide the following:

- Timestamp: 9:33 AM (CST) 6/13/2019
- Function App name: timervscodefunctionapp
- Function name(s) (as appropriate): TimerExample
- Core Tools version: lastest version

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior
To Deploy the Timer Triggered Azure Function succesfully.

#### Actual behavior
Always get this error...

`> Executing task: . .env/Scripts/activate && func pack <

Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 52.77 ms for c:\Users\hpyy\Desktop\vscodeAzureFuncTest\extensions.csproj.
  extensions -> c:\Users\hpyy\Desktop\vscodeAzureFuncTest\bin\extensions.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.63

Deleting the old .python_packages directory
pip download -r c:\Users\hpyy\Desktop\vscodeAzureFuncTest\requirements.txt --dest C:\Users\hpyy\AppData\Local\Temp\azureworkerqogh4kuu

**There was an error restoring dependencies.ERROR: ['pip', 'download', '-r', 'c:\\Users\\hpyy\\Desktop\\vscodeAzureFuncTest\\requirements.txt', '--dest', 'C:\\Users\\hpyy\\AppData\\Local\\Temp\\azureworkerqogh4kuu'] failed with exit code 2**

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.`

#### Related information 

Provide any related information 

* Links to source
--Steps Followed: https://code.visualstudio.com/docs/python/tutorial-azure-functions
--Setup Instructions followed:https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python (prerequisites)

* Contents of the requirements.txt file
`azure-functions==1.0.0b4
azure-functions-worker==1.0.0b4
azure-cli==2.0.65
beautifulsoup4==4.7.1
bs4==0.0.1
cx-Oracle==7.1.3
DateTime==4.3
requests==2.21.0`

**Comment by dgan11** [comment]
![func_pack_error](https://user-images.githubusercontent.com/37032548/59458755-bfb4d200-8de0-11e9-9db9-59812ecc67ad.png)

**Comment by maiqbal11** [comment]
@dgan11, are you still facing this issue?

**Comment by anirudhgarg** [comment]
Closing this issue out as we havent heard from @dgan11
