### ISSUE TITLE
Importing modules exposes no functions

### ISSUE THREAD

**Issue by GeordieGuy** [Azure/azure-functions-python-worker#463]
#### Investigative information

Please provide the following:

I have a function which extends the basic "hello name" functionality by importing textstat (an external module) and returning the Flesch Kincaid readability of the parsed body. The requirements.txt includes textstat, and pip appears to install it, it appears in the zip file that is created by core tools, but 500s. Debugging shows that while the module appears to be imported, the Python interpreter is complaining that it has no member called flesch_kincaid_grade - or ANY other member at all, the import is importing nothing

#### Repro steps

Provide the steps required to reproduce the problem:

add textstat to requirements.txt

add import textstat to hello name mvp imports

replace return with return textstat.flesch_kincaid_grade(name)

#### Expected behavior

return value is a float 

#### Actual behavior

Function 500s, debugger shows no member

#### Known workarounds

None

**Comment by asavaritayal** [comment]
@GeordieGuy are you running locally on your machine or in Azure?

**Comment by GeordieGuy** [comment]
Both in Azure and locally using VSCode Tools

**Comment by maiqbal11** [comment]
Hi @GeordieGuy, I'm unable to repro with VSCode and when published in Azure. It's worth noting that `textstat` has potential compatibility issues with Python 3: https://github.com/shivam5992/textstat/issues/7. Are you using an environment with Python 2 only?

**Comment by maiqbal11** [comment]
Closing as stale. Please re-open if you are still facing the issue.
