### ISSUE TITLE
PermissionError when running C binary that reads and writes files

### ISSUE THREAD

**Issue by thorhj** [Azure/azure-functions-python-worker#465]
I have create an Azure Python Function that uses [PuLP](https://pythonhosted.org/PuLP/) to solve linear problems. This library creates a problem file in /tmp and then calls a C binary (included in the PuLP package in site-packages) to solve the problem. This binary writes a file to /tmp with the result. The C binary throws a permission error, and I believe it has to do with writing the result file.

It works locally on my Windows PC, and I was also able to run the code on the docker image mcr.microsoft.com/azure-functions/python:2.0 (with root access). When I publish to Azure Functions and run the function, I receive a PermissionError:

```txt
Request was invalid: Traceback (most recent call last):
  File "/home/site/wwwroot/func_solve/__init__.py", line 19, in main
    solution = solve(goal, variables, constraints)
  File "/home/site/wwwroot/library/solver.py", line 43, in solve
    problem.solve()
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/pulp/pulp.py", line 1671, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/pulp/solvers.py", line 1367, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/pulp/solvers.py", line 1427, in solve_CBC
    cbc = subprocess.Popen(args, stdout = pipe, stderr = pipe)
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/pulp/solverdir/cbc/linux/64/cbc'Request was invalid: Traceback (most recent call last):
  File "/home/site/wwwroot/func_solve/__init__.py", line 19, in main
    solution = solve(goal, variables, constraints)
  File "/home/site/wwwroot/library/solver.py", line 43, in solve
    problem.solve()
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/pulp/pulp.py", line 1671, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/pulp/solvers.py", line 1367, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/pulp/solvers.py", line 1427, in solve_CBC
    cbc = subprocess.Popen(args, stdout = pipe, stderr = pipe)
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/pulp/solverdir/cbc/linux/64/cbc'
```
I have verified that there is execution permission to the binary.

Does the binary have restricted permissions? Is it not valid to write files to the disk?

**Comment by balag0** [comment]
Can you share the appname / deployment method. Can you also try writing to /tmp from python code directly to see if this is something specific to the pulp library?

**Comment by thorhj** [comment]
Function App: cbx-staging-westeu-function-solver

I deploy using Azure DevOps with the Azure Core Tools CLI command:

```func azure functionapp publish cbx-staging-westeu-function-solver --build-native-deps```

I have just added the function ```func_binarytest``` in which I circumvent PuLP entirely and call the binary myself in order to get some better logging. The binary is located in my shared code folder at ```/home/site/wwwroot/library/solvers/cbc/linux/64/cbc```.

I have also added a flag to run it from the ```/tmp``` folder instead, but this yields the same results.

In the function I write a problem file to ```/tmp```, and that is not causing issues. There seems to be no permission errors with the /tmp folder.

The ```PermissionError``` I am seeing is raised when calling ```subprocess.Popen``` as below (i.e. the exception is raised *before* I receive an exit code):

```python
    try:
        cbc = subprocess.Popen(args)
        if cbc.wait() != 0:
            raise Exception("Solver returned error code")
    except Exception:
        logging.error('Exception while executing solver')
        raise
```

Log printout of ```args``` is:

```txt
/home/site/wwwroot/library/solvers/cbc/linux/64/cbc /tmp/6d414334f9b24382a3f230068b020a0e-pulp.mps max branch printingOptions all solution /tmp/6d414334f9b24382a3f230068b020a0e-pulp.sol
```

or if executing from ```/tmp```:

```txt
/tmp/cbc /tmp/8efc24c956e64ce08af7b65b29573170-pulp.mps max branch printingOptions all solution /tmp/8efc24c956e64ce08af7b65b29573170-pulp.sol
```

**Comment by thorhj** [comment]
Any progress or timeline on this?

**Comment by feloff** [comment]
Having the same issue

**Comment by balag0** [comment]
As a workaround could you try - https://stackoverflow.com/questions/55132619/how-to-add-and-execute-a-binary-in-azure-functions

os.popen('chmod u+x /home/site/wwwroot/BlobTrigger/ffmpeg').read()

**Comment by thorhj** [comment]
@balag0 I tried to do what you suggested, but it doesn't change anything.
I have also been checking the execute permission using the following snippet, so I am confident that the binary has execute permission:

```python
    if not os.access(solver_path, os.X_OK):
        raise Exception(f'No execution access on {solver_path}')
```

where `solver_path` is the absolute path to the binary.

**Comment by Rfaering** [comment]
I am having the same issue, so I tried to use custom image instead, based on this article
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image

This **_did solve the issue_** and I were able to use PuLP on both premium plan and dedicated plan.

But I did not do any real changes to the image except install dependencies and create a http endpoint. Should this not behave the same way as the image used in the consumer plan ?

**Comment by stefanushinardi** [comment]
As pointed out, the workaround is to use custom container. Please reopen if you feel the issue is not yet solved
