### ISSUE TITLE
Exceptions in adding async tasks inside async def main

### ISSUE THREAD

**Issue by joal42** [Azure/azure-functions-python-worker#470]
#### Investigative information
I need to add async task inside the function code. I need to add a new event loop or add my tasks to current event loop. However, I got exception while adding new async tasks. The error msg I got is 
`This event loop is already running` or ` Cannot run the event loop while another loop is running`

#### Repro steps
```
async def main(req:func.EventHubEvent):
        args=[1,2,3,4,5,6]
        try:    
            logging.info("---Add async tasks---")
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            loop.run_until_complete(
                a_sync_function(args))
            loop.close()
       except Exception as e:
         print("Exceptions in async tasks: {}".format(str(e)))
```    
I tried `asyncio.new_event_loop()` and `asyncio.get_event_loop()`. Both of them threw exceptions. 
It works if I use `def main()` instead of `async def main()`

Anyone has idea for how to get the exception passed? 
Cloud anyone give example of how to add async tasks under async def main()?

**Comment by elprans** [comment]
In async mode you already have an event loop running, `asyncio.get_event_loop().create_task(coro)` should work.

**Comment by joal42** [comment]
Thanks @elprans It works with using create_task(). 
```
async def main(req:func.EventHubEvent):
        args=[1,2,3,4,5,6]
        try:    
            logging.info("---Add async tasks---")
            loop = asyncio.get_event_loop()
            task = loop.creat_task(coro)
            await task
       except Exception as e:
         print("Exceptions in async tasks: {}".format(str(e)))
```
