### ISSUE TITLE
python worker killed (restarts) when trying to download a large file

### ISSUE THREAD

**Issue by pjboardman** [Azure/azure-functions-python-worker#474]
I have a function that has been working for a couple of months. This function downloads decently-sized datasets (average 30-40 MB, let's say). It is now failing in a strange way on a payload that is about ~250MB.

Here's a sample snippet of the download:

```python
tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.csv').name

        with requests.get(url, headers=headers, params=params, stream=True) as r:
            r.raise_for_status()

            with open(tmp_file, 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    if chunk:
                        f.write(chunk)
```

I get the following "error" (it's actually severityLevel=1 in AppInsights) , and then the worker restarts:

``` 
/azure-functions-host/workers/python/start.sh: line 74:    41 Killed                  python $DIR/worker.py $@
```

#### Investigative information

Running in a container based on ```microsoft/azure-functions-python3.6:2.0```

**Comment by pjboardman** [comment]
Additional details (not sure how related this is). After the above error message, I see the following message regarding ServiceBus locks (this is a Service Bus triggered function):

```fail: Host.Executor[0]
      MessageReceiver error (Action=RenewLock, ClientId=MessageReceiver6[removed], EntityPath=[removed], Endpoint=[removed])
Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:410e27ff-c006-4d24-88fd-549fba15eeed, TrackingId:a798db55-2f08-4cdd-95f8-db31e20f71f5_B17, SystemTracker:prod-incontext-research:Topic:study.fieldingcompleted|disqualification, Timestamp:2019-07-05T18:25:42
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnRenewLockAsync(String lockToken)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass75_0.<<RenewLockAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.RenewLockAsync(String lockToken)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.RenewLockAsync(Message message)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.RenewMessageLockTask(Message message, CancellationToken renewLockCancellationToken)
```

Here is the host.json:
```
{
  "version": "2.0",
  "extensions": {
    "serviceBus": {
      "prefetchCount": 0,
      "messageHandlerOptions": {
        "autoComplete": true,
        "maxAutoRenewDuration": "00:30:00",
        "maxConcurrentCalls": 2
      }
    }
  },
  "functionTimeout": "00:30:00"
}
```

Service bus subscription lock duration was set at 1 minute. I bumped it up to 5 minutes and get the same results (note that total execution time from start to process being killed is around 3 minutes).

Here is a sample timeline:
2019-07-05T18:22:45.2619127Z:   Function starting
2019-07-05T18:25:43.987572Z:  41 Killed (message above)
2019-07-05T18:25:44.5746049Z:  Service Bus Lock Exception

**Comment by anirudhgarg** [comment]
Hello @pjboardman can you please confirm if you are still seeing this issue.

**Comment by pjboardman** [comment]
@anirudhgarg I haven't looked at this in over 2 months. We came up with a work around.

**Comment by anirudhgarg** [comment]
@pjboardman  thanks. Can you please confirm what your work around was as it will benefit others who are seeing the same issue. Thanks !

**Comment by pjboardman** [comment]
We ran the process outside of the azure function
