### ISSUE TITLE
Timer trigger function start fail

### ISSUE THREAD

**Issue by huier23** [Azure/azure-functions-python-worker#476]
I run my python function on Azure and set it will be started each 1 minute.  However, the function do not work for a long time and i got the error issue as below:
 
_AttributeError: module 'azure.functions_worker' has no attribute 'start'_

#### Investigative information

Please provide the following:

- Timestamp: 2019-07-02 01:00:59.998
- Function App name: tmMonitor
- Function name(s) (as appropriate): TimerTrigger
- Core Tools version: 2.4.498

**Comment by TheHunter896** [comment]
This might help you https://github.com/Azure/azure-functions-core-tools/issues/1050

**Comment by huier23** [comment]
TheHunter896, thanks for your reply.
I have not use `func host start` to run my Function since I run my function on Azure not in local.

**Comment by Hazhzeng** [comment]
Hey @huier23,

Thanks for reporting the issue and sorry for the late reply.
Could you share your requirements.txt content?
There is a known issue on using **other azure modules along with functions_worker**. (e.g. https://github.com/Azure/azure-functions-python-worker/issues/489)

If this is the case, we've made a [fix ](https://github.com/Azure/azure-functions-python-worker/pull/479) and the issue should be gone in the next release.

The current work around is to remove `__init__.py` from
`$ python -c "import azure;print(azure.__file__)"`

**Comment by equidevium** [comment]
I tried this @Hazhzeng and it did not do any difference for me. 
What i cannot understand is that this happens only for one my projects. 
I double checked pip freeze if there is any difference between the rest of my packages and versioning seems to be the same for both.

**Comment by Hazhzeng** [comment]
@equidevium Thanks for following up with me. This is a know issue in 1.0.0b9. The solution we made is moving **azure.functions_worker** out of the **azure** namespace to prevent user facing azure packages.

However, since the azure-functions-core-tools is still 2 versions behind, you may want to use the [mitigation](https://github.com/Azure/azure-functions-python-worker/issues/489) for now.
