### ISSUE TITLE
cannot import 'run' (aio_compat.py) (only fails in my local environment using VSCode)

### ISSUE THREAD

**Issue by saulcruz** [Azure/azure-functions-python-worker#481]
I have a very simple azure function that gets a parameter (please see the code at the bottom) and returns a HttpResponse, after running it it fails with:

```
cannot import name 'run'
  File "c:\users\saul.cruz\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\azure\functions_worker\aio_compat.py", line 84, in <module>
    from asyncio import run, get_running_loop  # NoQA
  File "c:\users\saul.cruz\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\azure\functions_worker\main.py", line 6, in <module>
    from . import aio_compat
  File "c:\users\saul.cruz\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 5, in <module>
    from azure.functions_worker.main import main
```

This only happens locally, the deployed function is working appropriately in the azure function service

#### Investigative information

Please provide the following:

- Timestamp: 2019-07-08T19:05:00
- Function App name: HttpTriggerFTPCheck
- Function name(s) (as appropriate):
- Core Tools version: win-x64.2.7.1373
- Python version : Python 3.6.7 :: Anaconda, Inc.

#### Repro steps

Provide the steps required to reproduce the problem:

I only have a very simple function that gets a parameter and returns a JSON response with that parameter's value..

1. Debug `__init__.py`

It's been working for almost one week and suddenly the following error started happening:
This only happens in my local environment (PC), not the actual azure function that is deployed already.
Not sure about  what is going on, I've seen this when there are circular dependencies, but I'm not sure about this case.

#### Expected behavior

Provide a description of the expected behavior.

Response  with:

`"result": "saul"`

#### Actual behavior

Provide a description of the actual behavior observed.

It's been working for almost one week and suddenly the following error started happening:

```
cannot import name 'run'
  File "c:\users\saul.cruz\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\azure\functions_worker\aio_compat.py", line 84, in <module>
    from asyncio import run, get_running_loop  # NoQA
  File "c:\users\saul.cruz\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\azure\functions_worker\main.py", line 6, in <module>
    from . import aio_compat
  File "c:\users\saul.cruz\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 5, in <module>
    from azure.functions_worker.main import main
```

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Links to source
* Contents of the requirements.txt file
* Bindings used

```python
#__init__.py
import logging
import json
import azure.functions as func


def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    name = req.params.get('name')
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get('name')

    if name:
        return func.HttpResponse(json.dumps({'result': name}))
    else:
        return func.HttpResponse(
             "Please pass a name on the query string or in the request body",
             status_code=400
        )
```

```txt
azure-functions==1.0.0a4
azure-functions-worker==1.0.0a4
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.11.0
```

`functions.json`

```json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

</details>

**Comment by saulcruz** [comment]
Workaround was to move all of my files to a new directory. Not sure why but that fixed it.

**Comment by rajeshr6r** [comment]
Hello Saul,

I also got this issue and moving the folder contents to a different folder didnt work .

**Comment by Rutikhal** [comment]
Today morning I also have such an issue with my local dev Azure Function and VSCode

**Comment by moregd3** [comment]
I also started getting this issue today. May be issue with latest vscode update but its not actual issue.If you see the code where it breaks, it is in try-catch and in catch it is passed. So basically, for some reason vscode is throwing exception even if it it handled. So to move with our debugging, just press F5 and code will run further.There are more such exceptions, so you wil have to keep presssing F5 till you reach your actual code.

**Comment by Rutikhal** [comment]
I have created new  empty http-trigger Azure Function in VSCode to check (in another folder). I have the same problem when starting function in debug mode. My file with code is closing and   I have an error with opening aio_compat.py
Exception has occurred: ImportError
cannot import name 'run'
  File "c:\users\rutikhal\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6\windows\x64\azure_functions_worker\aio_compat.py", line 84, in <module>
    from asyncio import run, get_running_loop  # NoQA
  File "c:\users\rutikhal\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6\windows\x64\azure_functions_worker\main.py", line 6, in <module>
    from . import aio_compat
  File "c:\users\rutikhal\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6\windows\x64\worker.py", line 59, in <module>
    from azure_functions_worker import main


if I press F5 I have  another 

Exception has occurred: ModuleNotFoundError
No module named 'grpc_tools'   opening another file


Exception has occurred: ModuleNotFoundError
No module named 'grpc_health'

Exception has occurred: ModuleNotFoundError
No module named 'grpc_reflection'

Exception has occurred: ImportError
cannot import name 'enable_deterministic_proto_serialization'

Yes, after that my code is opened again.
But it should not work like this. I have not updated anything from yesterday.

**Comment by anirudhgarg** [comment]
We will investigate this - do you remember if you updated anything ?

**Comment by Rutikhal** [comment]
Nope, yesterday I had no any errors, I have not updated anything.

**Comment by Rutikhal** [comment]
what I see that Python extension in VSCode was updated recently: "2020.5.86398 (8 June 2020)"

**Comment by rajeshr6r** [comment]
Ok. So its not just me. I'm a bit finicky now with installing extensions .

**Comment by Rutikhal** [comment]
it seems that it is really ms-python.python ( Python extension in VSCode)  issue, because my workaround was to uninstall ver. 2020.5.86398, disabled autoupdate of extensions in VSCode, install manually one of the previous version 2020.5.80290 of this ext. using link from this case
https://github.com/microsoft/vscode-python/issues/12217

**Comment by luabud** [comment]
This doesn't seem to be an issue in the Python extension, this can also be reproduced with other extensions such as CMake Tools and Docker. We're tracking the issue upstream to VS Code here: https://github.com/microsoft/vscode/issues/99699.

FWIW I can still reproduce the same issue when manually installing previous versions of the Python extension, so I'm not sure what is going on.
