### ISSUE TITLE
Incorrect handling of binary input

### ISSUE THREAD

**Issue by osoftware** [Azure/azure-functions-python-worker#490]
#### Investigative information

- Timestamp: 18.07.2019 08:40:28
- Function App name: not deployed yet
- Core Tools version: 2.7.1373 Commit hash: cd9bfca26f9c7fe06ce245f5bf69bc6486a685dd
- Function Runtime Version: 2.0.12507.0

#### Repro steps

I'm creating a simple function that reads a blob containing an image and processes it with OpenCV. Initially I used a `HttpTrigger` receiving a `multipart/form-data` `POST` request containing an image but struggled with the problem described here. Then I moved to a simple `GET` request which contains a reference to a blob in Azure Storage, just to discover the very same problem.

#### Expected behavior

When reading the stream, I should get the exact binary content of the blob.

#### Actual behavior

When reading the stream, I get a buffer containing an utf-8 string full of � (`0xEF 0xBF 0xBD`) replacement chars.

#### Related information 

When investigating why OpenCV fails to load the image I first figured out the size of the input is wrong (it's larger than it should be), then noticed the content *somehow* resembles the blob but is also full of Unicode replacement characters.

When i debugged into the worker internals I figured out that `from_proto()` method in `BlobConverter` always receives `data` with `data_type` of `string` which leads later to unnecessarily applying `data.string.encode('utf-8')`. Similar thing happens in case of binary files sent within HTTP POST requests.

So it seems that internal ProtoBuf representation of function requests incorreclty represents binary data as string leading to unnecessary utf-8 conversions in Python code.

<details>
<summary>Source</summary>

```python
# __init__.py
import logging
import azure.functions as func

def main(req: func.HttpRequest, image: func.InputStream) -> func.HttpResponse:
    try:
        data = image.read()
        return func.HttpResponse(do_stuff(data))
    except Exception as ex:
        return func.HttpResponse("Bad Request", status_code=400)
```

```json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get"
      ]
    },
    {
      "type": "blob",
      "name": "image",
      "connection": "******************",
      "direction": "in",
      "path": "inspections/{Query.name}"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

</details>

**Comment by daker** [comment]
Dup of #437, you need to install azure-functions-core-tools 2.7.1471

**Comment by osoftware** [comment]
I upgraded to 2.7.1480. The problem remains.

**Comment by daker** [comment]
@osoftware 
> I upgraded to 2.7.1480. The problem remains.

See : https://github.com/Azure/azure-functions-python-worker/issues/437#issuecomment-515148998 the runtime is not yet deployed on azure

**Comment by maiqbal11** [comment]
Runtime deployment is complete. Issue should be resolved.
