### ISSUE TITLE
Queue output binding changing timezone on timestamp inside JSON

### ISSUE THREAD

**Issue by dxkaufman** [Azure/azure-functions-python-worker#499]
#### Investigative information

Please provide the following:

- Timestamp:   7/24/2019 3:04:09.649 PM
- Function App name: shpy
- Function name(s) (as appropriate):  SegmentEvents, RawData, EventProcessing
- Core Tools version:  2.7.1480

#### Repro steps

Provide the steps required to reproduce the problem:

Not sure I can exactly provide reproduction steps, but here's what's happening.

SegmentEvents function takes webhooks from a service called Segment and pushes the JSON content of each, unmodified, into two queues, one for RawData and one for EventProcessing.  

I can see in my console log that the original timestamp element is in UTC:

[7/24/19 11:51:31 PM]   "originalTimestamp": "2019-07-24T22:03:41.265+00:00",

When it comes through to either RawData or EventProcessing, it is in PDT, and I can see it that way in the queue:

![image](https://user-images.githubusercontent.com/26446314/61836220-1a0b6e80-ae34-11e9-8b38-e9c6ec6f2344.png)

I am busily trying to write code to convert back to UTC, but then I decided to see if I could figure out where it was getting changed, assuming I was doing it somehow, but it seems to be happening in the set command...

Here's the segment processor:

def main(req: func.HttpRequest, rawdata: func.Out[func.QueueMessage], event: func.Out[func.QueueMessage]) -> func.HttpResponse:

    content = req.get_body().decode('utf-8')
    logging.info(f'incoming event: {content}')

    logging.info('writing event to event processing & raw data queues')
    event.set(content)
    rawdata.set(content)

    status_code = 200

    return func.HttpResponse(content, status_code=status_code, mimetype='application/json')   ## send the content back to the requester so I can see it in my tests

These are the bindings for the http trigger (SegmentEvents):

{
    "scriptFile": "segment.py",
    "bindings": [
      {
        "authLevel": "function",
        "type": "httpTrigger",
        "direction": "in",
        "name": "req",
        "methods": [
          "post"
        ]
      },
      {
        "type": "http",
        "direction": "out",
        "name": "$return"
      },
      {
        "name": "rawdata",
        "type": "queue",
        "direction": "out",
        "queueName": "%RawDataQueue%",
        "connection": "Storage" 
      },
      {
        "name": "event",
        "type": "queue",
        "direction": "out",
        "queueName": "%EventProcessingQueue%",
        "connection": "Storage" 
      }
    ]
  }

And for one of the queue triggers:

{
  "scriptFile": "rawdata.py",
  "bindings": [
    {
      "name": "msg",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "%RawDataQueue%",
      "connection": "Storage"
    }
  ]
}

#### Expected behavior

Provide a description of the expected behavior.

timestamps with tz offset at the end, such as +00:00, should be passed through as is, which happens with those ending in Z (instead of +00:00)

#### Actual behavior

Provide a description of the actual behavior observed.

When the timestamp ends in +00:00, the timestamp is being rewritten to local time (assume it is the server local since my app service is in US West).  This is not happening with timestamps ending in Z:

2019-007-24T17:01:08.256+00:00 gets written as 2019-007-24T10:01:08.256-07:00 while 2019-007-24T17:01:08.256Z is not changed.

#### Known workarounds

Provide a description of any known workarounds.

I have been trying to write code to change it back to UTC when it comes through this way, but for some reason it is going the wrong way!  That's a separate issue, obviously.

#### Related information 

Provide any related information 

* Links to source
* Contents of the requirements.txt file
* Bindings used

**Comment by anirudhgarg** [comment]
Closing out and cleaning old issues. If this is still an issue please re-open. We also did some changes around timezone and this is possibly also fixed.

**Comment by dxkaufman** [comment]
Yes, it appears to be fixed.
