### ISSUE TITLE
Execution Context

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#5]
The  runtime will use a **context** object to pass data to and from the Python function. This is primarily used to reference metadata and  information related to a specific execution of the function. For example -

```python
# main.py
def main(context):
	return context.invocation_id 
```
Similarly, the following attributes can be accessed using context: 

**Attribute** | **Description**
-------------|----------------
**invocation_id** | Unique identifier of the function execution.
**function_name** | Name of your function.
**function_directory** | Directory path to where your script is located.

Context is accessible in two ways: 

1. Via the reserved keyword - 'context'
```python
# main.py
def main(context):
	return context.function_name 
```

2. By declaring 'Context' type for a method argument
```python
# main.py
def main(foo: Context):
	return foo.function_directory 
```

**Comment by 1st1** [comment]
This has been implemented in full and committed to the `dev` branch. Closing this issue, please open a new one if we need to add new methods/properties to the `Context` object.
