### ISSUE TITLE
How to set Storage Blob Filename, Content-Type, etc. on output binding?

### ISSUE THREAD

**Issue by askpatrickw** [Azure/azure-functions-python-worker#507]
When using an output binding to blob storage, the default values show how to use {rand-guid} in the path to generate a file in blob storage.

How do you specify a filename of your own choosing?

#### Investigative information

Please provide the following:

>VSCode Version: 1.36.1 (user setup)
>Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
>Date: 2019-07-08T22:59:35.033Z
>Electron: 4.2.5
>Chrome: 69.0.3497.128
>Node.js: 10.11.0
>V8: 6.9.427.31-electron.0
>OS: Windows_NT x64 10.0.18362

- Core Tools version: 
>az --version
>azure-cli                         2.0.69
>command-modules-nspkg               2.0.3
>core                              2.0.69
>nspkg                              3.0.4
>telemetry                          1.0.3

### Reasearch

Stackoverflow, GitHub and the docs haven't point me int he right direction. Is it just not possible?

Should I  just use Storage in the function without using the binding? (potential workaround)

**Comment by askpatrickw** [comment]
Got it working.. but I didn't use the storage blob output binding. Here's a summary, I'd love to know if this was _supposed to be_ doable from the bind as I could not figure it out.

I'm summarizing the code and file changes here, this is not my actual code. Apologize for any mistakes in advanced

**requirements.txt**

```
azure-storage-blob
```

**local.settings.json**
Because I had attempted to use an blob output bind, I have an applicaton setting that has the info I need to connect to the storage account.

```python
myStorageBlob="DefaultEndpointsProtocol=https;AccountName=MYSTORAGEACCOUNT;AccountKey=AWAY2LONGSTRING;EndpointSuffix=core.windows.net"
```

**/myFunction/\_\_init\_\_.py**

```python
import io
import logging
import os


import azure.functions as func
from azure.storage.blob import BlockBlobService, PublicAccess


def main(
    req: func.HttpRequest,
) -> func.HttpResponse:
    logging.info("Gate API Triggered")

    # Not Showing GET method

    # POST
    if req.method == "POST":
        try:
            # image is the form field name I used in my POST
            image = req.files["image"]
        except ValueError:
            return func.HttpResponse(
                # This make more sense with the code I left out.
                "Please pass a valid object in the request body",
                status_code=400,
            )
        else:
            # Convert the semicolon seperated string to a dict
            myStorageBlob_settings = os.environ.get("myStorageBlob")
            temp_obj = dict(item.split("=", 1) for item in myStorageBlob_settings.split(";"))
            
            # Use the BlockBlobService
            bbs = BlockBlobService(
                account_name=temp_obj["AccountName"],
                account_key=temp_obj["AccountKey"]
            )
            bbs.create_blob_from_stream(
                # The container
                container_name="my-container",
                
                # the filename uploaded
                blob_name=image.filename,
                
                # the stream of the file
                stream=image.stream,
                
                # the mime-type
                content_settings=ContentSettings(content_type='image/png')
            )
            return func.HttpResponse(
                "Created",
                status_code=201
                )
```

**Comment by maiqbal11** [comment]
Hi @askpatrickw, should be able to set the file name for your blob using the output binding. An example is given here where you specify the output path: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#output---python-example. 

We recognize that the output binding does not support all features that you would get from the storage SDK. In those cases, we actually do advise the use of the storage SDK to perform more complex and granular operations. So your example which makes use of the storage blob SDK seems perfectly fine! Closing for now as it does not look like we have any further action on this.
