### ISSUE TITLE
Python worker doesn't log errors correctly when it's crashing the host

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-python-worker#515]
In CRI number: 138373870, the runtime container is in a crash loop due to 

       Traceback (most recent call last):
         File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
           from azure.functions_worker import main
       ModuleNotFoundError: No module named 'azure.functions_worker'

Those errors aren't being logged anywhere. I needed to set `AZURE_FUNCTIONS_ENVIRONMENT=Development` to see these errors. 

Runtime Version: 2.0.12612.0

**Comment by ahmelsayed** [comment]
This could be due to a known issue with dedicated linux that's being fixed in ANT84.

**Comment by thedoupub** [comment]
Hello there.

We are having a huge problem with our hosts crashing constantly and at random intervals.

Can you please elaborate where i am supposed to set the AZURE_FUNCTIONS_ENVIRONMENT=Development  so that i can see what exactly is happening? 

Suddenly it feels that both our staging and production environments started crashing without any code change from our side. 

And there is nowhere in the logs something that we can hold up onto to see what is happening.

**Comment by ahmelsayed** [comment]
Where are you checking the logs?

`AZURE_FUNCTIONS_ENVIRONMENT=Development` is an environment variable. If you're using App Service, they are called AppSettings in UI/API. If you're deploying a container set it as an env var. This causes very verbose logging to stdout. 

If you are using app service, if you can share [more details](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) I can take a look at the logs from our side.

**Comment by thedoupub** [comment]
I checked the logs on the live metrics in telemetry. The thing is that for our case it seems that in the telemetry or anywhere else like monitoring ( and any other place that we can find logs ) they are quite unreliable.

We are running on consumption plan.

The function runtime is unable to start.
Session Id: dfbfe9bb6c2146c5b014feffedace105

Timestamp: 2019-08-30T07:28:37.237Z 

and this is the error i got this morning.

**Comment by ahmelsayed** [comment]
How are you publishing your functions? I'm only seeing timeouts due to slow startup. That slow startup should be much improved if you either: use a recent core-tools to publish with `--build-native-deps` option, or recreate your app and then you can use `--build remote` option. Both should improve the startup time significantly and not cause those timeouts. 

After 5 timesouts the UI gives up and displays the message above.

**Comment by thedoupub** [comment]
I am deploying with Azure Devops which is practically the same like --build-native-deps. 
The trick that i did and it resolved my issue was to delete the function apps and recreate them. Then all went completely fine. No problems at all. It sounds a bit weird as a solution but it did the trick. 

Btw sorry that this thread went out of scope.
