### ISSUE TITLE
Import Error when importing modules within same Azure Function

### ISSUE THREAD

**Issue by cgearing** [Azure/azure-functions-python-worker#516]
Hi there,

This seems to be a new issue - I have a Function App using Python 3.6 and the most recent core tools that was working fine at the end of July (30/07/2019), however when I went to test it yesterday I found that I was receiving 500s.  Looking at the logs, I can see lots of import errors, like below:

```
Result: Failure
Exception: ModuleNotFoundError: No module named 'CostModelling'
Stack:   File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 239, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/site/wwwroot/CostModelling/__init__.py", line 6, in <module>
    from CostModelling.cost_modelling.config import cost_modelling_controller
``` 

#### Investigative information

Please provide the following:

- Timestamp: 2019-08-14 08:18:12.845 
- Function App name: Cost-Modelling-CG
- Function name(s) (as appropriate): CostModelling
- Core Tools version: 2.7.1505

#### Expected behavior

Provide a description of the expected behavior.

Importing from modules within the app should work. 

#### Actual behavior

Provide a description of the actual behavior observed.

I get an Import Error from the worker.

#### Known workarounds

Using relative imports works

```
from .cost_modelling.config import CostModellingController
```

**Comment by jayhub42** [comment]
They changed how imports need to be structured.

example: `from __app__.SharedCode import myFirstHelperFunction`
 
[updated documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#folder-structure)

**Comment by maiqbal11** [comment]
Hi @cgearing, we basically guarantee two kinds of imports to work:

1. Explicit relative imports such as the one you mentioned in your workaround 
2. Absolute imports using `__app__` as the function app root directory. In this case, the `__app__` module is equivalent to `CostModelling`. We made the decision to enable this behavior because the name of the Function App Root is not guaranteed to be `CostModelling` when you publish to Azure. 

Hope this helps!

**Comment by cgearing** [comment]
Thanks @maiqbal11 - that's really helpful!

**Comment by JosXa** [comment]
So users are expected to ditch automatic imports, autocompletion, and linting completely? How do I make this weird `__app__` thing work with the VSCode tooling or PyCharm?
