### ISSUE TITLE
Support private packages deployment

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#517]
Multiple customer requirements don't necessarily have a package published onto PyPI. While this works locally, it is not possible to deploy private packages into Azure using the options available with core tools. 

For eg: if there is a python library in Github repo with its own setup.py, should be able to build a distribution for it and use it locally and the core tools should be able to zip the locally built packages and deploy.

**Comment by drcrook1** [comment]
I'm in need of this.  Right now I'm doing a CI process that copies the raw source from a package I distribute on a private pypi (ADO Artifacts).  

This copy process worked a few weeks ago but appears to now be broken; still diagnosing how to get my private package into the functions currently.

**Comment by kulkarnisonia16** [comment]
Please clarify and vote on the scenarios below:

Scenario 1: Clone git repo and setup.py to install package in the app 
Scenario 2: Install from a private pypi that does not require auth and is publicly accessible 
Scenario 3: Install from a private pypi that requires auth
Scenario 4: Install from a private pypi that is on-prem/behind firewall with no public endpoint.

Thanks!

**Comment by Hazhzeng** [comment]
Hi @priyaananthasankar,

After I write a scenario for supporting PyTorch (using alternative facebook PyTorch index) in Azure Functions, I think we can support private index with Basic Auth.

Sample requirements.txt:
```
--extra-index-url https://username:password@my.package.repo/simple
my-package=1.0.0
```
