### ISSUE TITLE
cosmos document triggered functions throws import error after prolonged/sustained use. 

### ISSUE THREAD

**Issue by jayhub42** [Azure/azure-functions-python-worker#518]
I have two functions that watch a Cosmos collection for changes. When I have a sustained flow of documents both functions start throwing import errors for packages that worked for the preceding executions. Then stop executing. 

Both functions use requests to post versions of the document to other systems. 
Error is on first non-standard import (requests for one and oauth2 for the other) 

#### Investigative information

Please provide the following:

- Timestamp: 2019-08-14T17:45:47.6867962Z
- Function App name: itsc-workOrders
- Function name(s) (as appropriate): foo_post & push_to_bar
- Core Tools version: 2.0.12575.0 (~2)

#### Repro steps
Provide the steps required to reproduce the problem:

Step 1. documentTrigger function needs to import requests or “non standard” python package listed in requirements.txt
Step 2. Create 50+ new documents in a watched collection at a rate of 1 document per second (up to 5 seconds) 
Step 3. Monitor DocumentTrigger logs for errors. 

#### Expected behavior

Provide a description of the expected behavior.

I would expect imports to work consistently between executions. 

#### Actual behavior

Provide a description of the actual behavior observed.

function apps work as expected until they start throwing import errors. 

timestamp | id | operation_Name | success | resultCode | duration | operation_Id | cloud_RoleName | invocationId
-- | -- | -- | -- | -- | -- | -- | -- | --
2019-08-14T17:45:47.6867962Z | \|c47928667446e745a254ec8a75c33cd1.1b9a16ef77cb3f40. | foo_post | FALSE | 0 | 417.5621 | c47928667446e745a254ec8a75c33cd1 | itsc-workorders | b9c0be38-08ec-49f3-8d4c-26ed46f3fa0c
2019-08-14T17:28:28.7559993Z | \|e426d6adccb1d347bfc1807b76a99cda.c2ee8fb2bec3ea48. | foo_post | TRUE | 0 | 12874.3147 | e426d6adccb1d347bfc1807b76a99cda | itsc-workorders | 8280b56d-853a-467b-b8a8-8e8b68ca4890

invocation details error:
```
Result: Failure
Exception: ModuleNotFoundError: No module named 'oauth2'
Stack:   File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 239, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/site/wwwroot/foo_post/__init__.py", line 3, in <module>
    import oauth2 as oauth
```

#### Known workarounds

Provide a description of any known workarounds.

Adding a delay between POSTs to the my HttpTrigger function seams to add enough delay to keep the DocumentTriggers working for a bit. 

I have also noticed some system delay between when the documents are created/changed and when the DocumentTrigger function executes, this also helps until the execution rate gets to fast. 

#### Related information 

Provide any related information 

requirements.txt
oauth2
requests

**Comment by maiqbal11** [comment]
@jayhub42, I believe the underlying cause for this is the same as https://github.com/Azure/azure-functions-python-worker/issues/553. Closing out this one. We can use the other one for tracking.
