### ISSUE TITLE
Duplicate binding data in gRPC messages

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-functions-python-worker#519]
### Scenario
When customer sends a BlobTrigger package with 70MB, the function host will eat up to 210MB.
This is a known issue in function host. Fixes may require in Python worker side.

### Related Issues
https://github.com/Azure/azure-functions-host/issues/4735 (Host)
https://github.com/Azure/azure-functions-host/issues/3845 (Node worker)
https://github.com/Azure/azure-functions-host/issues/3722 (Node worker)

### Action Item on Python Worker
Similar to https://github.com/Azure/azure-functions-nodejs-worker/pull/238/files , we need to check duplicated trigger data. Only populate trigger metadata if it is not populated.

**Comment by Hazhzeng** [comment]
The issue is caused by duplicated data in
1. Request's $req->value
2. TriggerMetadata: req->value
3. TriggerMetadata: $req->value

There are two parts we need to implement:

1. The python worker needs to ask the host to trim off the redundant data in TriggerMetadata
Host Reference: https://github.com/Azure/azure-functions-host/commit/f6aeef80d966a5a6b332328fce38d96c3d7fe582
Node Worker Reference: https://github.com/Azure/azure-functions-nodejs-worker/commit/3b51b6f169fd7a392dd15339d26e5deee60ccbac

2. The python worker needs to reconstruct the TriggerMetadata from request
Host Reference: https://github.com/Azure/azure-functions-host/pull/4660/files
Node Worker Reference: https://github.com/Azure/azure-functions-nodejs-worker/commit/f4b85e4bee

**Comment by anirudhgarg** [comment]
Waiting for merge.
