### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#52]
Currently, the Python version is locked down at `3.6.4`

Once support for further versions is added, we'll make it configurable using the workflow below: 

1. Use the version specified in `requirements.txt` in the root folder.
2. Use the value specified in the `Python version` app setting in the Azure Portal.
3. Default to 3.6.4 if none of the above are specified.

**Comment by bacongobbler** [comment]
Just confirming, but you meant `runtime.txt`, not `requirements.txt`, right? The latter's commonly used to pin dependencies with `pip freeze > requirements.txt`.

e.g. https://github.com/heroku/heroku-buildpack-python#specify-a-python-runtime
