### ISSUE TITLE
No deliveryCount for Service Bus binding in Python

### ISSUE THREAD

**Issue by antonioschaffert** [Azure/azure-functions-python-worker#524]
Node and C# have deliveryCount for Service Bus, but can't seem to find it for Python.

This is useful in order to know how many times to retry a message in case of failure. Any idea on how to accomplish this at this point?

**Comment by asears** [comment]
Is it part of message header?

https://azure.github.io/azure-sdk-for-python/ref/azure.servicebus.html

**Comment by maiqbal11** [comment]
Closed in https://github.com/Azure/azure-functions-python-library/pull/26. Should be available in Azure if you publish with `azure-functions==1.04`. Core tools release is pending for this and should happen in ~1-2 weeks.
