### ISSUE TITLE
Trouble making input blob bindings to work on my phyton function.

### ISSUE THREAD

**Issue by luisdlp** [Azure/azure-functions-python-worker#535]
I"m having trouble making my input blob binding to work against my function. 

I have my function bindings defined like this in my function.json file:
 {
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "[functionname]",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */2 * * * *"
    },
    {
      "name": "inputblob",
      "type": "blob",
      "path": "configs/config.json",
      "connection": "octopodmodelsaccountconnection",
      "direction": "in"
    }
  ]
}

My __init__.py file is calling the function like this:
def main([functionname]: func.TimerRequest, inputblob: func.InputStream) -> None:
    logging.info('Python Queue trigger function processed %s', inputblob.name)

My local.settings.json file looks like this:
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "octopodmodelsaccountconnection": "[connection string to octopodmodelsaccountconnection]",
    "AzureWebJobsStorage": "[connection string to octopodmodelsaccountconnection]"
  }
}

When I run this function locally in VS Code and set up a breakpoint in the logging line, inputblob.name is "None".  

What am I missing?

**Comment by maiqbal11** [comment]
Can you confirm that the path to the blob itself is correctly specified?

**Comment by kulkarnisonia16** [comment]
Closing as there has not been any activity on this in last 2 weeks. Please re-open if needed.
