### ISSUE TITLE
System.Security.Authentication.AuthenticationException

### ISSUE THREAD

**Issue by gattjoe** [Azure/azure-functions-python-worker#536]
#### Investigative information

Please provide the following:

- Timestamp: 8/30/2019, 1:57:09 PM (Local time)
- Function App name: fct05e1dv
- Function name(s) (as appropriate): OCSPCheck
- Core Tools version: 2.7.1585

#### Repro steps

1. curl http://fct05e1dv.<PRIVATE>.com/api/ocspcheck?name=www.github.com

#### Expected behavior

OCSP Result

#### Actual behavior

Nothing happens, I have to log into Application Insights to find out the error.
[requirements.txt](https://github.com/Azure/azure-functions-python-worker/files/3561170/requirements.txt)

#### Related information 

Provide any related information 

* I fixed the issue on my own by rewriting the function to NOT use pyOpenSSL. Perhaps creating connections with raw sockets is what is causing this error?

**Comment by asears** [comment]
Did you deploy with this command?

```
func azure functionapp publish 'functionname' --build-native-deps --additional-packages "python3-dev libevent-dev python-pyopenssl"  
```

Perhaps it's not picking up the open ssl dependencies?  Since this is running in function apps runtime there may be some security issue.

Might need libssl-dev & openssl packages too.  
What was alternate approach?

**Comment by gattjoe** [comment]
Hi, I did not deploy with the "--additional-packages" option (I didn't know about it).

The alternate approach was that I figured out how to do it with sslyze and cryptography, which both work perfectly fine.

**Comment by gattjoe** [comment]
@asears Give me a few days, I will restore my old code from source and try to publish using your guidance above to see if that fixes it and others can learn from this error.

**Comment by kulkarnisonia16** [comment]
Closing as you were able to figure out a workaround. Thanks!
