### ISSUE TITLE
Referencing modules section on docs.microsoft.com

### ISSUE THREAD

**Issue by fernandoBRS** [Azure/azure-functions-python-worker#538]
Hi,

Recently I had some problems to reference modules on my Azure Function and based on the closed issue #81 I found out I should use relative import syntax:

```python
from . import example
```
I would like to recommend add a section about this on Microsoft docs to improve developers experience so they don't need to spend time going to GitHub closed issues to figure out.

**Comment by kulkarnisonia16** [comment]
Thanks - its documented here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python
