### ISSUE TITLE
azure function work fine on local but when deployed fail to reference py dependencies

### ISSUE THREAD

**Issue by ElanReep** [Azure/azure-functions-python-worker#546]
after successfull deployment to azure, calling the function return with error refrence the py files,
these files are located on same dir as the init file , the import is relative with from . import XXX as said , locally work perfect after deployment azure env cant ref the py required files.

my function is at  https://reeptecv.azurewebsites.net/api/gettecv

i am using venv to host this function - local run and deployment being done from within this env.

the init py been generated auto by Func function so it is being recognize but the other py been added manually and it looks like they cant be refrenced from the azure deployed function

Thanks
Elan

**Comment by maiqbal11** [comment]
Can you share a tree diagram of your exact folder structure and what file you are importing into which file?

**Comment by ElanReep** [comment]
dir structure for my func:

 

envdir

--.venv

--myfuncdir

----.python_packages

----.vscode

----requirements.txt

----otherfiles

----myfunc

--------__init__.py

--------dep1.py

--------dep2.py

 

local run : 

envdir\ myfuncdir > func host start

 

 

i have added the relative path:

from . import dep1

 

as said locally work fine on azure i am getting err 500

 

 

 

looked at the errors in azure portal 

overall azure complains on some RPC issue

I think it relates to the dependencies in the site packages 

If I pip list the venv it has all the necessary packages, if I look in the .venv/Lib/site-packages they r there,  but azure function cant access these

 

I have tried adding to my code :

sys.path.append(os.path.abspath(os.path.join(os.path.dirname( __file__ ), '.venv/Lib/site-packages')))

but still the 500 err from portal

 

 

err from portal :

Result: Failure

Exception: ModuleNotFoundError: No module named 'cv2'

Stack:   File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 239, in _handle__function_load_request

    func_request.metadata.entry_point)

  File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/loader.py", line 66, in load_function

    mod = importlib.import_module(fullmodname)

  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "/home/site/wwwroot/gettecv/__init__.py", line 4, in <module>

    from . import REEP_TCEV_restapi as tcev

  File "/home/site/wwwroot/gettecv/REEP_TCEV_restapi.py", line 4, in <module>

    import cv2

**Comment by ElanReep** [comment]
dir structure for my func:

envdir
--.venv
--myfuncdir
----.python_packages
----.vscode
----requirements.txt
----otherfiles
----myfunc
--------__init__.py
--------dep1.py
--------dep2.py

local run : 
envdir\ myfuncdir > func host start


i have added the relative path:
from . import dep1

as said locally work fine on azure i am getting err 500

looked at the errors in azure portal (see below)
azure thru insight tools also complains on RPC issue

I think it relates to the dependencies in the site packages 
If I pip list the venv it has all the necessary packages, if I look in the .venv/Lib/site-packages they r there,  but azure function cant access these

I have tried adding to my code :
sys.path.append(os.path.abspath(os.path.join(os.path.dirname( __file__ ), '.venv/Lib/site-packages')))
but still the 500 err from portal


err from portal :
Result: Failure
Exception: ModuleNotFoundError: No module named 'cv2'
Stack:   File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 239, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/site/wwwroot/gettecv/__init__.py", line 4, in <module>
    from . import REEP_TCEV_restapi as tcev
  File "/home/site/wwwroot/gettecv/REEP_TCEV_restapi.py", line 4, in <module>
    import cv2



thank you !!!

**Comment by maiqbal11** [comment]
Is `cv2` some custom library? Is it part of your requirements.txt?

**Comment by anirudhgarg** [comment]
@ElanReep closing this out since we didnt hear from you. Please let us know if you still need help and reactivate.
