### ISSUE TITLE
Null input binding throws an exception

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-python-worker#548]
When attempting to use an input binding to something like CosmosDB, if the input binding is empty (e.g. referencing an ID that isn't there), the function throws right away (with an error about not able to convert `NoneType` to `func.Document` or `str` or whatever).  However, with other languages like JavaScript, the function still executes, the input binding is just null.  This prevents doing things like gracefully handling a null input binding and returning an error.

https://stackoverflow.com/questions/57979944/azure-function-written-in-python-has-500-when-id-binding-points-doesnt-have-a

**Comment by tiptop96** [comment]
Any idea on how to get started on fixing this? Do we know what code is causing this?

**Comment by jeffhollan** [comment]
Yes @maiqbal11 mentioned yesterday there is some validation code somewhere that we would remove to prevent this check which isn’t necessary

**Comment by maiqbal11** [comment]
We decode the data from Cosmos but right now we aren't checking for the case where the data in `None`: https://github.com/Azure/azure-functions-python-library/blob/edce123f18b2b45d0d18c0bccd6e934290af0dee/azure/functions/cosmosdb.py#L24. Will add a fix shortly.

**Comment by aarsan** [comment]
Running into this problem as well

**Comment by Hazhzeng** [comment]
The fix has been merged to the python library, it will go with the next 1.0.5 release.
