### ISSUE TITLE
Update Python worker imports to use proper paths

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-python-worker#549]
The commit in the central gRPC repo has been reverted since the imports were affecting the host and the rest of the language workers
https://github.com/Azure/azure-functions-language-worker-protobuf/pull/43/files

**Comment by anirudhgarg** [comment]
@pragnagopa curious on whether this is still needed. What was the original issue we were trying to resolve here ?

**Comment by pragnagopa** [comment]
@anirudhgarg  - Sorry. This has been a while. I cannot recall intention of the original PR. Need to trace the commits and commnets in issues/PRs linked.
