### ISSUE TITLE
Session Enabled Queue Message Properties Not Being Populated

### ISSUE THREAD

**Issue by datasloths** [Azure/azure-functions-python-worker#558]
When using Azure Service Bus Queues that are session enabled the ServiceBusMessage object is not completely populated.  The message_id and message_body are populated, but all other properties are null.  This is using a ServiceBusTrigger input binding.  The C# version of this function works fine and properties are populated.

#### Repro steps

1.) Create Python Function App + Azure Service Bus Queue with sessions enabled
2.) Update ServiceBusExtension to 3.1.0 in extensions.csproj
3.) Add "isSessionsEnabled" : true to function.json
4.) Add code in function to log session_id or other properties on the input binding
5.) Put message onto Queue.

#### Expected behavior

Properties will be populated with properties of message that was put onto the queue.

#### Actual behavior

1.) Logging will show the correct SessionId in a log message that starts with "Trigger Details:"
2.) Logging message added in code will show properties are null except for message_id and body.

#### Known workarounds

No known workarounds

#### Related information 

Provide any related information 

* Links to source
* Contents of the requirements.txt file
* Bindings used

![image](https://user-images.githubusercontent.com/56081426/66056780-45c66700-e4fd-11e9-8f98-049957adb245.png)
![image](https://user-images.githubusercontent.com/56081426/66056823-5676dd00-e4fd-11e9-84d8-1a43c3c7780f.png)

**Comment by anirudhgarg** [comment]
@Hazhzeng  can you have a look at this. We have gotten another CRI for this.

**Comment by vinodc** [comment]
We're running into this issue as well. Has there been any progress on identifying a potential solution?

**Comment by anirudhgarg** [comment]
hello folks - we have identified the missing properties and we are working on adding these. These changes should be rolled out in 3-4 weeks if not earlier.

**Comment by Hazhzeng** [comment]
Sorry for the late reply. The fix has been rolled-out in last years July. Closing this issue now.
If you have any other questions, please open a new issue.

**Comment by sidkri** [comment]
It looks like this is still an issue and I created a new issue to track the fix: #957
