### ISSUE TITLE
Validate Functions v3 Preview

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-python-worker#559]
Details will be coming soon. Opening issues right now to track. 

Functions v3 preview (on .NET Core 3) is coming soon and we'd like the language worker owners to take it for a spin first and let us know if there are any issues.

Initial plan:
- Build details coming early Mon Oct 7, with a CLI build and a private site extension links.
- Would like some kind of signoff by EOD Wed Oct 9
    - That signoff is up to the language worker owner. Can be a test suite run, or even some manual validation with the CLI and/or production.

**Comment by anirudhgarg** [comment]
This is done and we have released V3
