### ISSUE TITLE
Cannot load `*.so` libraries in a directory specified by AppSetting(Environment variables) `LD_LIBRARY_PATH`.

### ISSUE THREAD

**Issue by horihiro** [Azure/azure-functions-python-worker#560]
I want to load so libraries for python package `opencv-python-headless`.

#### Investigative information

- Timestamp: 2019-10-06 03:48:02 (UTC)
- InvocationId: 58ab63f9-096e-423a-be88-ef1870d98a79
- Function App name: pythonfunc1
- Function name(s) (as appropriate): HttpTrigger
- Core Tools version: 2.7.1633

#### Repro steps

1. Deploy function app package including some so files.<br>
The file structure is following.
```
$ tree .
.
├── host.json
├── HttpTrigger
│   ├── function.json
│   ├── __init__.py
│   └── sample.dat
├── local.settings.json
├── proxies.json
├── requirements.txt
└── tmp
    ├── libglib-2.0.so.0
    └── libgthread-2.0.so.0
```

2. Set App Setting `LD_LIBRARY_PATH` to `/home/site/wwwroot/tmp` in order to load above so files.
![image](https://user-images.githubusercontent.com/4566555/66263992-03bc5e80-e838-11e9-821c-f93d57dde436.png)

3. Execute the function.

#### Expected behavior

`import cv2` in \_\_init__.py will work without any error/exception

#### Actual behavior

Following exception occurred, of cause http response code is 500.

```
Result: Failure
Exception: ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```
![image](https://user-images.githubusercontent.com/4566555/66263975-ade7b680-e837-11e9-99e8-07bf9e36e7ae.png)

I confirmed that `/home/site/wwwroot/tmp` was set to enviroment variable `LD_LIBRARY_PATH` by using `os.getenv('LD_LIBRARY_PATH')` in my function program.
I'm not sure why `*.so` libraries in a path specified by LD_LIBRARY_PATH cannot be loaded even though the path can be set appropriately in the environment variable `LD_LIBRARY_PATH`.

#### Known workarounds

The function with following code instead of `import cv2`

```python
import ctypes
import importlib

exlibpath = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/tmp/'
ctypes.CDLL(exlibpath + 'libglib-2.0.so.0')
ctypes.CDLL(exlibpath + 'libgthread-2.0.so.0')

cv2 = importlib.import_module('cv2')
```

#### Related information 

* Links to source
* Contents of the requirements.txt file
* Bindings used

<details>
<summary>Source</summary>
Function code:

```python
# __init__.py

import logging
import os
import urllib.request as rq
import re
import azure.functions as func
import mimetypes

import cv2

# work around code
# import ctypes
# import importlib

# exlibpath = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/tmp/'
# ctypes.CDLL(exlibpath + 'libglib-2.0.so.0')
# ctypes.CDLL(exlibpath + 'libgthread-2.0.so.0')

# cv2 = importlib.import_module('cv2')

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    image_url = req.params.get('image_url')
    if not image_url:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            image_url = req_body.get('image_url')

    if image_url:
        local = re.sub(r'^.*/([^/]+)$', r'\1', image_url)
        rq.urlretrieve(image_url, '/tmp/' + local)
        im = cv2.imread('/tmp/' + local)
        gry = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
        cv2.imwrite('/tmp/gray_' + local, gry)
        with open('/tmp/gray_' + local, 'rb') as f:
            mimetype = mimetypes.guess_type('/tmp/gray_' + local)
            return func.HttpResponse(f.read(), mimetype=mimetype[0])
        # return func.HttpResponse(f"Hello {image_url}!")
    else:
        return func.HttpResponse(
             "Please pass a image_url on the query string or in the request body",
             status_code=400
        )
```

requirements.txt:

```txt
opencv-python-headless
```

</details>

**Comment by horihiro** [comment]
I tried to confirm that `LD_LIBRARY_PATH` is valid on docker by simple command.

When executing `mcr.microsoft.com/azure-functions/python` without `LD_LIBRARY_PATH`, `ImportError: libgthread-2.0.so.0` occurred on `import cv2`.

```bash
# without LD_LIBRARY_PATH environment variable
$ docker run --rm -it -v $(wslpath -w $PWD):/home/site/wwwroot mcr.microsoft.com/azure-functions/python sh -c 'pip install opencv-python-headless && python'
Collecting opencv-python-headless
  Downloading https://files.pythonhosted.org/packages/1f/dc/b250f03ab68068033fd2356428c1357431d8ebc6a26405098e0f27c94f7a/opencv_python_headless-4.1.1.26-cp36-cp36m-manylinux1_x86_64.whl (22.1MB)
     |████████████████████████████████| 22.1MB 2.0MB/s
Collecting numpy>=1.11.3 (from opencv-python-headless)
  Downloading https://files.pythonhosted.org/packages/e5/e6/c3fdc53aed9fa19d6ff3abf97dfad768ae3afce1b7431f7500000816bda5/numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl (20.4MB)
     |████████████████████████████████| 20.4MB 1.4MB/s
Installing collected packages: numpy, opencv-python-headless
Successfully installed numpy-1.17.2 opencv-python-headless-4.1.1.26
WARNING: You are using pip version 19.2.2, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Python 3.6.9 (default, Aug 14 2019, 13:09:32)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

And with `-e LD_LIBRARY_PATH=/home/site/wwwroot/tmp`, `import cv2` was successful.

```bash
# with LD_LIBRARY_PATH environment variable
$ docker run --rm -it -e LD_LIBRARY_PATH=/home/site/wwwroot/tmp -v $(wslpath -w $PWD):/home/site/wwwroot mcr.microsoft.com/azure-functions/python sh -c 'pip install opencv-python-headless && python'
Collecting opencv-python-headless
  Downloading https://files.pythonhosted.org/packages/1f/dc/b250f03ab68068033fd2356428c1357431d8ebc6a26405098e0f27c94f7a/opencv_python_headless-4.1.1.26-cp36-cp36m-manylinux1_x86_64.whl (22.1MB)
     |████████████████████████████████| 22.1MB 1.5MB/s
Collecting numpy>=1.11.3 (from opencv-python-headless)
  Downloading https://files.pythonhosted.org/packages/e5/e6/c3fdc53aed9fa19d6ff3abf97dfad768ae3afce1b7431f7500000816bda5/numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl (20.4MB)
     |████████████████████████████████| 20.4MB 1.7MB/s
Installing collected packages: numpy, opencv-python-headless
Successfully installed numpy-1.17.2 opencv-python-headless-4.1.1.26
WARNING: You are using pip version 19.2.2, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Python 3.6.9 (default, Aug 14 2019, 13:09:32)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
```

So it seems that this issue is not related to docker.

**Comment by anirudhgarg** [comment]
Please refer to: https://github.com/Azure/azure-functions-python-worker/issues/497

**Comment by horihiro** [comment]
#497 is an issue for only OpenCV library.
But this issue is related to not only for loading it but also for loading any other SO libraries.

**Comment by mlazowik** [comment]
Python uses `ld` to find libraries via `LD_LIBRARY_PATH`, but `ld` is not present in the runtime. https://hg.python.org/cpython/rev/385181e809bc

**Comment by horihiro** [comment]
Thanks @mlazowik !

I confirmed that `ld` is not present in container image `mcr.microsoft.com/azure-functions/python` by following command, and I cannot find `ld`, what you wrote is true.

```sh
$ docker run --rm -it  mcr.microsoft.com/azure-functions/python sh -c "which ld"

$
```

Do you have a plan to add `ld` to the container image?

**Comment by mlazowik** [comment]
Ok, so this solved a problem, but not the one mentioned in this issue. Adding `binutils` made `find_library` work, but `CDLL` uses different ways for locating libraries for loading, see this bug: https://bugs.python.org/issue18502

The error in this issue is clearly about not being able to locate a known filename (`CDLL` part), not about not being able to find the filename (`find_library` part).

**Comment by anirudhgarg** [comment]
@horihiro @mlazowik we  have added the binutils to the python images and also added the .so libraries needed for OpenCV. Not sure at this point how we can fix this issue of loading any *.so so closing this out.
