### ISSUE TITLE
Problem with slow long running Function and Storage Queue

### ISSUE THREAD

**Issue by tiptop96** [Azure/azure-functions-python-worker#564]
I hope this is the right place to ask this specific question (although my question didn't really fit the base template for issues). If it is let me know if I should provide further details and if not please point me in the right direction.

I have a timer function is Azure that is supposed to send ~20k messages to an Azure Storage Queue trough an output binding. It starts by spending ~13 minutes fetching these messages in batches, serializing and appending them to a list. Then the list is passed to the output binding as in the example code below. A rough estimate is that the average message size is around 14kb (accounting for the UTF-16 encoding used by Azure Storage Queue) when doing this. However no messages ever appear on the queue and the function eventually times out.

I have previously successfully sent ~25k messages to azure Storage Queue from another function in this project. A rough estimate is that the average message size was around 8kb when doing this. The data was collected from and SQL database with a query that takes ~25 sec. If i recall correctly the messages took a few minutes to land on the queue but other than that, no problems.

I have also increased the `functionTimeout` in my `host.json` to 6 hours, thinking that this would eliminate timeout issues..

In both functions I am using and output binding called `msg`. Similar to this but with different datasources.

```python
result = []
for item in data_source.get_next_obj():
    result.append(json.dumps(item))
msg.set(result)
```

The total data being passed should be around 150-160% of that sent in the successful scenario and it taking more than 6 hours to finish seems odd in comparison.

How could this be taking so much longer?
Could the binding be invalid/unusable after the initial data collection?
Are there any other caveats that I am unaware of?

**Comment by maiqbal11** [comment]
I'm assuming that you are on Dedicated as well hence the 6 hour time-out limit? Does the scenario work  if you sent the data in smaller batches rather than sending the entire (~280 MB in your case) data set in one go? 

The initial data collection should not affect the behavior of the output binding in this case. They are unrelated. There are potentially some gRPC limits that we might be running into if the data is larger - hence the suggestion to try sending in smaller chunks.

**Comment by tiptop96** [comment]
Well in my specific case "data_source" is actually a call to a rest service that i iterate trough using an offset and limit parameter. So i get N items in a batch and then add them to the list.

That solution would require me to keep a state regarding where to resume the querying.

I currently just use the python lib for azure storage to manually send data as i collect it. Still it would be great to be able to use bindings.

**Comment by ijoosong** [comment]
@tiptop96 if you can try using durable functions, [specifically fan out fan in](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-cloud-backup?tabs=csharp), this might help you with your issue!
