### ISSUE TITLE
Unable to use pyodbc and SQLAlchemy

### ISSUE THREAD

**Issue by shril** [Azure/azure-functions-python-worker#566]
In my local development environment (Windows 10 + Python 3.6), I am successfully able to run the function app.
When I push it to Azure Cloud Function, it builds properly.

Although, I get this error when I make POST request - 

```
Exception while executing function: Functions.create_assessment Result: Failure
Exception: OperationalError: (pypyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired')
(Background on this error at: http://sqlalche.me/e/e3q8)
```

#### Investigative information

Please provide the following:

- Timestamp: 22/10/2019, 18:48:09 (Local time)
- Function App name: assistrestapi

#### Repro steps

Python Code - 

```
from sqlalchemy import create_engine
import pypyodbc

params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=********************;"
    "DATABASE=******************;"
    "UID=***********;"
    "PWD=*************"
)

engine = create_engine(
    "mssql+pyodbc:///?odbc_connect={}".format(params),
    module=pypyodbc,
    echo=True
)
```

Then I push my function app using the following command - 

```func azure functionapp publish assistrestapi```

Contents of `requirement.txt` - 

```
azure-functions
SQLAlchemy
python-dateutil
pyodbc
pypyodbc
```

**Comment by anirudhgarg** [comment]
@shril can you please confirm what version of func core tools you are  using ?

**Comment by anirudhgarg** [comment]
Also do you know if the modules that you are using work on Linux ? It could be that the module(SQLAlchemy) is only available for Windows and know that in Azure Functions we run Python only on Windows

**Comment by shril** [comment]
Hi @anirudhgarg, thanks for such a prompt response.
I am currently using Version 2.x of Azure Func Core Tools. I followed this documentation for installation: [Link](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#v2).
I am currently using Windows 10 for Local Development.

SQLAlchemy is a Python Library, hence it is platform agnostic.
I think the issue is in the PyODBC driver. I have installed a PyODBC driver in my local dev setup, but I am unable to replicate that for Function App Environment.

**Comment by shril** [comment]
@anirudhgarg I have solved the issue, apparently, it's working without the use of pypyodbc.

Sharing the code below for the community

```
params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=**********;"
    "DATABASE=**********;"
    "UID=**********;"
    "PWD=**********"
)

engine = create_engine("mssql+pyodbc:///?odbc_connect={}".format(params))
