### ISSUE TITLE
How to access file in root directory in function app

### ISSUE THREAD

**Issue by Kagigz** [Azure/azure-functions-python-worker#567]
Hi,

I'm using an env variable to store the name of a file (json) that I want to use in one of the functions in my function app.
Locally, I just use "mappings.json" for a file located at the root level, and it works.
But after publishing to my function app, I get an error saying the file is not found. I tried with "%HOME%/mappings.json", "./mappings.json"... But no luck.

So how can I reference a file located in the root folder after publishing to a function app?

**Comment by Hazhzeng** [comment]
You can use the following code snippet
```
import os
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
```

**Comment by sudarrshan** [comment]
can we write a `XML` file inside the `wwwroot` folder from function's `__init__.py` file  by using 
```python open('abs-file-path', 'wb+') ```
?
