### ISSUE TITLE
Importing modules : No module named xxxx (sklearn pipelines effect)

### ISSUE THREAD

**Issue by VedAustin** [Azure/azure-functions-python-worker#568]
I am experiencing issues when running the app locally vs on Azure.
When running locally, the function app is running fine. However when deploying the func on Azure, I get the following message:
```
Exception while executing function: Functions.TagAPI Result: Failure
Exception: ModuleNotFoundError: No module named 'utilities'
Stack:   File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 310, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 429, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/TagAPI/__init__.py", line 19, in main
    text_clf = joblib.load(f)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 595, in load
    obj = _unpickle(fobj)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.6/pickle.py", line 1338, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python3.6/pickle.py", line 1388, in find_class
    __import__(module, level=0)
```
I am loading a sklearn pipe model saved using `joblib`. I have taken care to ensure that the classes are shared between the server(serving models) and builder (building models) from the `utilities` folder.
My dir structure is as below:
```
azfn_api
|_ models
    |_ model1
|_ HttpTrigger
   |_ __init__.py
   |_ function.json
|_ utilities
    |_ nlp_utilities
```

Additionally this is what I have in the `__init__.py`:
```
# __init__.py
from ..utilities.nlp_utilities import ensemble_models, spacy_tokenizer, CleanText

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    with open(pathlib.Path(__file__).parent.parent / "models" / "model1", 'rb') as f:
        text_clf = joblib.load(f)
```
The `job lib.load` is the source of the problem here since it does not recognize the `utilities` module and it requires the `Cleantext` class and `spacy_tokenizer` function
How is that when I run it locally in debug mode (VS Code), I can make `curL` requests successfully but when I make the same requests when it running on Azure, it get the above error?

**Comment by anirudhgarg** [comment]
Hi Ved, how did you deploy the app ? do you have the required python modules specified in requirements.txt ?

**Comment by VedAustin** [comment]
Hi Anirudh .. the app was deployed from VS Code. My requirements.txt is as below:
```
azure-functions
numpy
pandas
scikit-learn
scipy
spacy
```

**Comment by anirudhgarg** [comment]
Can you try move everything that you require for your app within the HttpTrigger folder

**Comment by VedAustin** [comment]
This is my new structure:
```
ve_tag_api
|_ tag_api_new
   |_ api.py
   |_ function.json
   |_ nlp_utilities
   |_ model1
   |_ build_model.py
```

```
# api.py
from . import nlp_utilities
def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    with open(pathlib.Path(__file__).parent / "model1", 'rb') as f:
        text_clf = joblib.load(f)
```

```
# build_model.py
from . import nlp_utilities
# Follow steps to save the model
    with open(pathlib.Path(__file__).parent / "model1", 'wb') as f:
        joblib.dump(text_clf, f)
```

I build the model from here:
`ve_tag_api $ python -m tag_api_new.build_model`

Again when I debug this from VS Code .. it runs fine. When I deploy it, it returns the following error:
```
Exception while executing function: Functions.tag_api_new Result: Failure
Exception: ModuleNotFoundError: No module named 'tag_api_new'
Stack:   File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 310, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 429, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/tag_api_new/api.py", line 14, in main
    text_clf = joblib.load(f)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 595, in load
    obj = _unpickle(fobj)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.6/pickle.py", line 1338, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python3.6/pickle.py", line 1388, in find_class
    __import__(module, level=0)
```

**Comment by VedAustin** [comment]
I have also tried to build and deploy using this:
`func azure functionapp publish <appname> --build-native-dep`
However this returns the error:
`Cannot use '--build-native-deps' along with '--build' flag`
Instead i deployed without the --build flag
`func azure functionapp publish <appname>`
and it deploys fine. I believe the above dockerizes the app locally and deploys it to Azure?
Again when I run the func locally:
`func host start` .. I make POST requests successfully. Totally different story on Azure. 
Any help appreciated.

**Comment by Hazhzeng** [comment]
Hi @VedAustin ,

Sorry for the late reply, the issue falls through the cracks.
This core-tool should be fixed now and you can upgrade it by running `npm install -g azure-functions-core-tools`.

Please try again and use `func azure functionapp publish <appname>` to deploy your function app. Feel free to tag me if you're still running into issues.

**Comment by VedAustin** [comment]
Hi @Hazhzeng .. I tried with the latest release and am still running into issues. I am planning to switch over to app service plan (not ideal) from consumption plan (ideal) and see if that resolves the issue.

**Comment by VedAustin** [comment]
Deploying the app under the 'app service plan' works great. Looks like the issue is specific under the 'consumption plan'.

**Comment by gagansalaria** [comment]
Hello!..I am facing the same issue with Azure functions - Linux - consumption plan. Locally the app works fine however getting ModuleNotFoundError when deployed to azure.

I have tried below with --build-native-deps flag as well.

Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
Exception: ModuleNotFoundError: No module named 'google.auth'

**Comment by anirudhgarg** [comment]
@gagansalaria can you please open a new issue. Please also provide your requirements.txt

**Comment by Hazhzeng** [comment]
@VedAustin, could you share me with your linux consumption function app name?
That would help us inspect the log from our end.

**Comment by VedAustin** [comment]
@Hazhzeng Could I DM you instead the app name?

**Comment by Hazhzeng** [comment]
Hey @VedAustin 
Please follow the link https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately to share me with your invocation id, thanks.

**Comment by VedAustin** [comment]
Can you try this "e908c3a4-b394-45d8-874b-c0a8d588b62d" and see if this is the id that you are looking for?

**Comment by Hazhzeng** [comment]
Hi @VedAustin I'm not able to find your this function app activity in the last 10 days.
As mentioned in the document, could you also share me with your function app **Region** and the **Timestamp** for this activity? Thanks.

**Comment by VedAustin** [comment]
Sorry this was more than 10 days ago.
Region: WestUS2
Timestamp [UTC] | 2020-01-03T19:30:18.6381481Z

**Comment by Hazhzeng** [comment]
Hey @VedAustin,
Sorry for the late reply, seems like the import syntax is a little bit off in your function app (e.g. `from ..nlp_utilities import *`.
The **\_\_app__** module is referring to the **Function App Root**, but not the **function folder**.
Our Python worker does not register **Function App Root** as a package but we do for all child folder, please place the utilities in a separate `SharedCode` folder and follow the instruction [here](https://github.com/Azure/azure-functions-python-worker/issues/584) for proper import.
