### ISSUE TITLE
Python Function Deploy from Azure Pipeline failing

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-functions-python-worker#569]
@anthonyrs06 commented on [Thu Oct 24 2019](https://github.com/Azure/azure-functions-core-tools/issues/1625)

Failing to deploy python Function App to Azure. 

Failure from an Azure Pipeline: 
![image](https://user-images.githubusercontent.com/6324704/67534963-2e127680-f696-11e9-93f7-45a80dfc4bf2.png)

Failure from VSCode: 
![image](https://user-images.githubusercontent.com/6324704/67534988-44b8cd80-f696-11e9-80ef-a7017c4f4a84.png)

My function app name is: vscanpythonfunction
App Service is: bridgeasp

From the pipeline it looks like an availability issue but from VSCode it looks like my app package is too big? Is there a max size limit that can be deployed? 

Let me know what additional information I can provide. 

---

@anthonyrs06 commented on [Fri Oct 25 2019](https://github.com/Azure/azure-functions-core-tools/issues/1625#issuecomment-546449319)

UPDATE - I decreased my package size and was able to deploy via VSCode. After that I was getting 500 errors where App Insights showed this error: 

> did not find any initialized language workers

However, today I am receiving

![image](https://user-images.githubusercontent.com/6324704/67593950-e426a080-f728-11e9-8229-34c39918c878.png)

where App Insights shows:

![image](https://user-images.githubusercontent.com/6324704/67593166-29e26980-f727-11e9-811b-5a9560000009.png)

It seems that servers are up then receive a request and crash?

**Comment by Hazhzeng** [comment]
Hey @anthonyrs06, thanks for reporting.

1. The --build-native-deps flag will resolve dependencies defined in requirements.txt to .python_packages, the maximum entries are 65536.
    1. To avoid compressing too many files from your local machine, please update your Azure Functions Core Tools to the latest version.
    2. Add a **.funcignore** file in your project root, add `.python_packages/`, `your_virtual_environment_path/` in it.
    3. Deploy to Azure Function using `func azure functionapp publish vscanpythonfunction`, this should initiate a remote build which resolves project dependencies on our servers.
2. I just take a look into the logs of your function app, and seems like the **VScanBlobTrigger** is crashing your function app. This is an issue when Function Extension Bundles are not resolved correctly, please consider using https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register
3. Also, would you mind sharing your **extensions.csproj** and **host.json** file to me? That helps me pin down the additional issue you may be facing.
