### ISSUE TITLE
Local dev environment cannot access get_body() data for chunked transfer

### ISSUE THREAD

**Issue by tezzigator** [Azure/azure-functions-python-worker#574]
It does work fine in the production Azure Function environment, but returns zero bytes/char data if used in a local development.

VSCode ver 1.39.2 Win10
Core Tools version:  (npm) azure-functions-core-tools@2.7.1846
Azure Functions Core Tools (2.7.1846 Commit hash: 58c671341fda1c52bd46e1aa8943cb26e467830)
Function Runtime Version: 2.0.12858.0
Azure Functions VSCode extension ver 0.20.0

```python
# __init__.py

datatosign = req.get_body().decode('utf-8')
```

```txt
azure-functions==1.0.4
azure-keyvault==1.0
base58check==1.0.2
msrestazure==0.6.2
```

**Comment by maiqbal11** [comment]
@tezzigator, can you share details of the request that you are sending and the full code that you are running?

**Comment by tezzigator** [comment]
Here is a sample request:
```
T 2019/11/06 03:04:50.173510 X:58530 -> Y:5001 [AP] #51
POST /keys/tz3 HTTP/1.1.
accept: application/json;q=1,application/bson;q=0.100,application/octet-stream;q=0.200.
content-type: application/json.
host: test.com:5001.
transfer-encoding: chunked.
.
57.
"027a06a7706a76cd0ed61c7b9a3e63178c3ebb37d24ed0c80358e860ddeab665ea2bcdfa2c00000a66a8"
.
0.
.
```
As far as code of the function, something like would show what I mean:
```
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
    return func.HttpResponse(req.get_body().decode('utf-8'))
```
Where it works in production function but not local development

**Comment by Hazhzeng** [comment]
Thanks for reporting this issue. @tezzigator 

AFAIK, this is an existing [issue on function host](https://github.com/Azure/azure-functions-host/issues/4926). The reason is the host will send python worker the request header first (but without the body).

We're still waiting on an ETA for this one.

**Comment by kulkarnisonia16** [comment]
Closing as this is a host issue (which is linked here). Thanks!
