### ISSUE TITLE
Linux Consumption Plan : Python deployment function with third party packages not working

### ISSUE THREAD

**Issue by dho3007** [Azure/azure-functions-python-worker#575]
Hello,

We deployed a python function in a Linux Consumption Plan platform with third party requirements (in requirements.txt i.e. google-auth google-oauth) using "--build remote"option in func CLI and we faced an error 500 "Exception: ModuleNotFoundError: No module named 'google.oauth2'" (packages are present in zipfile). 
The same function deployed on a Linux App Service Plan with the same func CLI deployment "--build remote" worked like a charm ! 

Any idea ?

Thanks in advance

**Comment by Hazhzeng** [comment]
Hi @dho3007,

Thanks for reaching us. Unfortunately, I cannot reproduce the issue.
https://hazeng-fa-github-lin-con-python.azurewebsites.net/api/httptrigger

My requirements.txt:
azure-functions
google-oauth
google-api-python-client

To help us pin down the issue, would you mind sharing your function app name and requirements.txt? Thanks.
