### ISSUE TITLE
Blob Input Binding doesn't receive the blob.

### ISSUE THREAD

**Issue by terminalstderr** [Azure/azure-functions-python-worker#576]
Blob Input Binding doesn't receive the blob. 

I followed the tutorial for setting up a BlobTrigger, it worked as expected. After switching the trigger to HTTP instead of Blob, and making the blob into an input binding, the myblob object in my python script does not have the data I expect it to.

#### Investigative information

Please provide the following:
- Core Tools version: 2.7.1846

#### Repro steps

Setup a python 3 azure function with this function.json and code.

##### function.json
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ]
    },
    {
      "name": "myblob",
      "type": "blob",
      "direction": "in",
      "path": "tinker/function.json",
      "connection": "AzureWebJobsStorage"
    }
  ]
}
```

##### __init__.py
```
import logging
import azure.functions as func

def main(req: func.HttpRequest, myblob: func.InputStream):
    logging.info(f"Python blob trigger function processed blob \n"
                 f"Name: {myblob.name}\n"
                 f"Blob Size: {myblob.length} bytes")
```

##### Reproduction Steps
1. Upload tinker/function.json in the AzureWebJobsStorage storage account, with some data. This is just a test file.
2. Run the azure function locally using the Azure func runtime.

#### Expected behavior

There will be accurate information logged about function.json.
```
[11/14/2019 19:23:38] Python blob trigger function processed blob 
Name: tinker/function.json
Blob Size: 355 bytes
```

#### Actual behavior

The myblob binding doesn't have any contents.

```
[11/13/2019 20:39:49] Python blob trigger function processed blob 
Name: None
Blob Size: None bytes
```

**Comment by Hazhzeng** [comment]
Hi @terminalstderr, unfortunately, the metadata of the blob binding (e.g. name, length) is not provided by the function host, but you can still access the raw data in blob binding via `myblob.read()`.

To access the full metadata of a blob, we recommend using [Azure Storage SDK](https://pypi.org/project/azure-storage-blob).

**Comment by terminalstderr** [comment]
Okay. I do find it confusing that there a difference in the metadata of the blob binding (e.g. name, length) between Blob Trigger vs the Blob Input Binding. 

I have already moved to using the Azure Storage SDK 😁👍
