### ISSUE TITLE
Improve error logging on function load

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#579]
This is follow up from a sev2 CRI where function failed to load but no details in error message.
Ensure exception is set on Function Load errors.

**Comment by dariagrigoriu** [comment]
@pragnagopa is it possible to clarify if this is in the context of Python only?

**Comment by pragnagopa** [comment]
Yes. This issue is to ensure python worker sets exception on [FunctionLoadResponse](https://github.com/Azure/azure-functions-language-worker-protobuf/blob/dev/src/proto/FunctionRpc.proto#L214)

**Comment by Hazhzeng** [comment]
Checked the line https://github.com/Azure/azure-functions-python-worker/blame/850409ab1057a78adf605e1c7a74e9e0fbd3c8b7/azure_functions_worker/dispatcher.py#L281 and we do set exception field on Functions Load Failure.

Tested with a broken trigger, the exception can be found in app insight and function's logs.
![image](https://user-images.githubusercontent.com/48038149/84216179-96736400-aa7d-11ea-9cd1-6adf3b918801.png)
