### ISSUE TITLE
Log if function is async

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-python-worker#580]
Currently, we do not have a way of identifying if a function is running synchronously or asynchronously. User often point to issues pertaining to performance when they are running synchronously and a switch async/await constructs often resolves these issues. We should add logging from the worker that is able to detect if the function is async vs. sync.

**Comment by RobertoBorges** [comment]
> Currently, we do not have a way of identifying if a function is running synchronously or asynchronously. User often point to issues pertaining to performance when they are running synchronously and a switch async/await constructs often resolves these issues. We should add logging from the worker that is able to detect if the function is async vs. sync.

Any workaround ?
