### ISSUE TITLE
Azure Functions Python Import Behavior

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-python-worker#584]
Currently, the Azure Functions Python runtime supports two different flavors of imports (locally and in Azure) from within files in Function folders:

1. **Explicit** relative imports 
2. Absolute imports with the Function App folder referred to as `__app__`

**Implicit** relative imports are **not supported** out of the box. 

Consider the following folder structure:

```
__app__
 | - MyFunction
 | | - __init__.py
 | | - function.json
 | | - example.py
 | - SharedCode
 | | - myFirstHelperFunction.py
 | | - mySecondHelperFunction.py
 | - host.json
 | - requirements.txt
```

The following imports will work from within the file `__app__\MyFunction\__init__.py`:

1. `from . import example` (explicit relative)
2. `from ..SharedCode import myFirstHelperFunction` (explicit relative)
3. `from __app__ import SharedCode` (absolute)
4. `import __app__.SharedCode` (absolute)

The following imports will **not** work from within the file `__app__\MyFunction\__init__.py` out of the box:

1. `import example` 
2. `from example import some_helper_code`
3. `import SharedCode`

**Comment by keitherskine** [comment]
This is great, @maiqbal11 .  Good information about what does and does not work.  If it could be added to the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#folder-structure) for Python functions, even better!

**Comment by maiqbal11** [comment]
\cc @anirudhgarg, @kulkarnisonia16

**Comment by brandonmbanks** [comment]
Thanks for this @maiqbal11. Very helpful.

**Comment by anirudhgarg** [comment]
This is documented now and hence removing the pin.
