### ISSUE TITLE
Installing packages with build dependency in setup.py

### ISSUE THREAD

**Issue by th3ragex** [Azure/azure-functions-python-worker#588]
I am trying to deploy a python azure function which depends on the 'tslearn' package.

https://pypi.org/project/tslearn/
https://github.com/rtavenar/tslearn/blob/master/setup.py

This package has a 'setup.py' dependency to `numpy` and `cython` which means both have to be installed in advance before being able to install it. Even locally i am not able to setup an empty virtual environment in one go from scratch by using `pip3` and a `requirements.txt` .

Example requirements.txt
```
azure-functions
numpy
pandas
scikit-learn
cython
tslearn
```

Which options do i have to get this package up and running in an azure function?

**Comment by Whadup** [comment]
Getting in on this: Is there any way to do this besides running a custom docker image with multiple pip install commands in it?

Possible quick-fix could be to process the requirements line-by-line: `cat requirements.txt | xargs -i{} pip install {}`.

**Comment by Hazhzeng** [comment]
Hi @th3ragex , unfortunately, we currently don't have a built-in solution for resolving multiple requirements.txt file in one go.

Here are the alternatives which may meet your requirements:
1. Thanks @Whadup for pointing out custom image solution, you can **create a custom image** and deploy it to Azure Functions Linux App Service plan. Dockerfile example's below:
```
# FROM mcr.microsoft.com/azure-functions/python:2.0-python3.7
FROM mcr.microsoft.com/azure-functions/python:2.0-python3.6

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY requirements.txt /
RUN pip install -r /requirements.txt
RUN pip install -r /extra_requirements.txt
COPY . /home/site/wwwroot
```

2. This may be a little tedious to set up, but you can choose one of the CI/CD platform (e.g. [GitHub Actions](https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/linux-python-functionapp-on-azure.yml#L41), [Azure DevOps](https://github.com/Azure/azure-functions-devops-build/blob/master/sample_yaml_builds/linux/consumption/python-consumption.yml#L25)) for resolving dependencies before deploying to function app. This solution is available in both Linux Consumption and Linux App Service plans.

**Comment by Whadup** [comment]
Is the second option available for bitbucket?On Dec 10, 2019 20:16, "Hanzhang Zeng (Roger)" <notifications@github.com> wrote:Hi @th3ragex , unfortunately, we currently don't have a built-in solution for resolving multiple requirements.txt file in one go.
Here are the alternatives which may meet your requirements:
Thanks @Whadup for pointing out custom image solution, you can create a custom image and deploy it to Azure Functions Linux App Service plan. Dockerfile example's below:
# FROM mcr.microsoft.com/azure-functions/python:2.0-python3.7
FROM mcr.microsoft.com/azure-functions/python:2.0-python3.6

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY requirements.txt /
RUN pip install -r /requirements.txt
RUN pip install -r /extra_requirements.txt
COPY . /home/site/wwwroot

This may be a little tedious to set up, but you can choose one of the CI/CD platform (e.g. GitHub Actions, Azure DevOps) for resolving dependencies before deploying to function app. This solution is available in both Linux Consumption and Linux App Service plans.

**Comment by Hazhzeng** [comment]
@Whadup, yep, seems like we have the azure-functions in bitbucket pipeline https://bitbucket.org/microsoft/azure-functions-deploy/src/master/README.md

**Comment by th3ragex** [comment]
@Hazhzeng Thanks for your feedback. 

I have been trying python with Azure Functions for a smaller demo project hoping to speed up my deployment with an experience similar to C# Functions. 

Before i've been using Azure ML Workspace deployments into an ACI which support Conda deployments and somewhat dokerfiles. The API allows building an image remotely which is very convenient. AKS would have been an overkill.
The consumption plan of Azure Functions made them seem very attractive for a dumb ML model with low CPU requirements in combination with the easy/automatic scale out. But even Azure ML Workspace deployments have their limitations. The base docker image is very minimalistic and doesn't come with gnu and other dependencies to build PIP packages. The esiest way to get some of these self building PIP packages running was to migrate them to Conda. 
But sadly Conda is not an option for Azure Functions, yet (?).

I didn't knew Azure Functions support docker images out of the box. Thanks for pointing this out @Whadup . As Windows 10 user this also means additional deployment steps through Linux. For an production scenario CI/CD would come in handy.

I would really love to see a unified python experience in Azure. It is a bit irritating that there are multiple different behaving options to run python on Azure, each with it's own pros and cons.
