### ISSUE TITLE
Use environment variables for connection binding in functions.json

### ISSUE THREAD

**Issue by nicolai92** [Azure/azure-functions-python-worker#597]
Hello,

We heavily use blog-triggered Azure Functions. For this to work, one needs to set a `connection` in `functions.json` file, which is a connection string to Azure Storage. This connection string has to be present in `local.settings.json` for local debugging - otherwise, Azure Function does not start correctly.

Problem:
As we work with 3 different environments, we would like to use environment variables for the connection string. Otherwise, when switching the environment with `envFile`, we manually need to change the connection string in `local.settings.json`, too.

#### Investigative information

- Timestamp: 20/11/2019
- Core Tools version: azure-functions-core-tools@3
- OS: macOS 10.15.1

#### Repro steps

1. Export an environment variable, e.g. `export STORAGE_URL="..."`
2. Use the name of the environment variable inside `function.json` for `connection` (for blob-triggered function)
3. Start Azure Function locally
4. Azure Function complains, that the value set for `connection` is not present in `local.settings.json`

#### Expected behavior

Azure Function tries to get `connection` string from environment variables, if not present in `local.settings.json`.

#### Actual behavior

Azure Functions does not start properly.

**functions.json**
```json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "blob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "demo/{name}",
      "connection": "STORAGE_URL"
    }
  ]
}

```

**Error**
```sh
The 'demo' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.demo'. Microsoft.Azure.WebJobs.Extensions.Storage: Storage account connection string 'STORAGE_URL' does not exist. Make sure that it is a defined App Setting.
```

**Comment by Hazhzeng** [comment]
Hey @nicolai92, the local.settings.json is only intended to be used when developing on your local machihne (stage or prod environment should be configured in Azure Functions' app settings)

The function.json does not accept `environment variables` defined outside local.settings.json.

If you want to test against different environments from you local machine, you can create two sets of local.settings.json, say `local.stage.settings.json` an `local.dev.settings.json`.

And use a wrapper script to switch between different environment
```sh
#!/bin/sh
if [ -f "local.settings.json" ]; then
  mv local.settings.json backup.json
fi
cp local.dev.settings.json local.settings.json
func host start
```
