### ISSUE TITLE
Documentation about managing connections in python.

### ISSUE THREAD

**Issue by tiptop96** [Azure/azure-functions-python-worker#600]
I cannot find any docs/examples on how to in practice manage connections using Azure Functions python.

As I am running into SNAT port exhaustion and have been adviced to reuse connections (database clients and http).

Is there such documentation?

**Comment by maiqbal11** [comment]
Hi @tiptop96, our current recommendation is to use global variables to manage connections. You can see an outline (though not specific to connections) of how to accomplish this here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#global-variables.

**Comment by anirudhgarg** [comment]
Closing.
