### ISSUE TITLE
Error when Azure function is getting executed through Table storage

### ISSUE THREAD

**Issue by aklimovych** [Azure/azure-functions-python-worker#604]
When Azure function is getting executed through Table storage I get this error:

```
System.Private.CoreLib: Exception while executing function: Functions.TableTimerTrigger. System.Private.CoreLib: Result: Failure
Exception: FunctionLoadError: cannot load the TableTimerTrigger function: type of outputTable binding in function.json "table" does not match its Python annotation "Document"
Stack:   File "C:\Users\User\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6\WINDOWS\X64\azure_functions_worker\dispatcher.py", line 245, in _handle__function_load_request
    function_id, func, func_request.metadata)
  File "C:\Users\User\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6\WINDOWS\X64\azure_functions_worker\functions.py", line 208, in add_function
    f'type of {param.name} binding in function.json '
```
- Timestamp: 09-Jan-20 20:30:00
- Function App name: huntflow
- Function name(s) (as appropriate): TimerTrigger
- Core Tools version: 2.7.1948
- Python 3.6.8

**Comment by maiqbal11** [comment]
This is potentially because there is an inconsistency in your code declaration if `Document` (meant for CosmosDB) and what you have in your `function.json`. You can try removing the `Document` annotation to see if that helps.

**Comment by aklimovych** [comment]
I want use output binding Azure Table storage. My configuration file (function.json):
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "mytimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */5 * * * *"
    },
    {
      "type": "table",
      "direction": "out",
      "name": "outputTable",
      "tableName": "test",
      "connection": "AzureWebJobsStorage"
    }
  ]
}
```
I tried use diferent types of declaration, but every time i have the same error.
Maybe you have example using output binding Table storage for Azure functions v2?

**Comment by maiqbal11** [comment]
We don't have an explicit type declared for table storage. You can use the parameter as is. Example in the following PR: https://github.com/Azure/azure-functions-python-worker/pull/475

**Comment by aklimovych** [comment]
Thank you very much!
