### ISSUE TITLE
Update Documentation for Conda Support Guidance

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#611]
Update documentation to reflect the following:

If specific Python libraries are used (namely fb prophet or pystan) or if binaries are used that only conda environment knows how to compile with the right Linux distro flags etc, then Azure Functions will not support those specific libraries.
It will be great if this can be updated in the docs - as multiple customers who are ML based ask this question regularly. Might be worth redirecting them to app service + containers for these specific cases.

**Comment by Hazhzeng** [comment]
I've made an example for using conda environment with Azure Functions in [here](https://github.com/Hazhzeng/functions-conda).

Has been discussed with Sonia and Anirudh.

**Comment by vrdmr** [comment]
Closing in favor of Discussion https://github.com/Azure/azure-functions-python-worker/discussions/974
