### ISSUE TITLE
Python Function App show only 6 operations

### ISSUE THREAD

**Issue by Joehannus** [Azure/azure-functions-python-worker#612]
What is the maximum number of operations a Python function app using a Linux consumption plan can have? We deployed a function app last friday that has 37 operations. But only 6 are shown in the Azure Portal for the function app in question. We do see output for all 37 operations in Application Insights though.

I can't find any information about this in the documentation.

**Comment by anirudhgarg** [comment]
Do you mean functions ? I dont think we have a limit for the number of functions in a function app. The portal might be restricting how many functions are shown. I can confirm and circle back.

**Comment by Hazhzeng** [comment]
This is a stale issue, feel free to open a new issue if you run into it again.
