### ISSUE TITLE
Exception: ModuleNotFoundError: No module named 'azure.cosmosdb'

### ISSUE THREAD

**Issue by philippbussche** [Azure/azure-functions-python-worker#617]
Hi,
running my function locally through VSCode works fine but I am getting a HTTP Server 500 when executing it in Azure.

This is what I see in Insights:
```
Result: Failure
Exception: ModuleNotFoundError: No module named 'azure.cosmosdb'
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 242, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/site/wwwroot/cities/__init__.py", line 6, in <module>
    from azure.cosmosdb.table.tableservice import TableService
```

Following is the content of my requirements.txt, which I am using:
```
azure-common==1.1.24
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.0.8
azure-nspkg==3.0.2
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
cryptography==2.8
idna==2.8
pycparser==2.19
python-dateutil==2.8.1
requests==2.22.0
six==1.14.0
urllib3==1.25.8
``` 
I am deploying my function including function app, plan and storage account using Pulumi.

**Comment by philippbussche** [comment]
I may know what the issue is here. In my Pulumi code I am creating a
new azure.appservice.ArchiveFunctionApp resource which has an archive property. This results in a function app being created which references an archive on blob storage. It looks like with this type of deployment the requirements.txt is never used (as it would be if I would run my func azure functionapp publish command triggering a local or remote build).
Let's assume I can only deploy functions which reference an archive with Pulumi. Would there be a way to construct an archive for a Python function that would be "complete" meaning all the dependencies are added ?
I ran 
```
pip install  --target="<PROJECT_DIR>/.python_packages/lib/site-packages"  -r requirements.txt
```
to add to the archive but that does not seem to be enough.

**Comment by Hazhzeng** [comment]
Hi @philippbussche,

Running `pip install  --target="<PROJECT_DIR>/.python_packages/lib/site-packages"  -r requirements.txt` does create the artifacts.

However, since the Azure Functions runtime is on Linux x64, you need the libraries have **manylinux1_x86_64 wheel**. Simple way to do so is the run `pip install  --target="<PROJECT_DIR>/.python_packages/lib/site-packages` on a X64 Linux machine and deploy the project along with ./python_packages
