### ISSUE TITLE
502 error with docker & python azure function with cold start

### ISSUE THREAD

**Issue by kubmir** [Azure/azure-functions-python-worker#618]
Hello,

I have a problem with the combination of **Python Azure function v2** and **docker container with pm4py package**. For the first start after some time (cold start), the application is not working for several minutes. It throws error 502 with message:

502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

After the application has successfully started (after several minutes), I get message _app is up and running_ and everything is working as expected. The problem returns with the next cold start.

Application insights does not include any logs for these long-term requests.

#### Investigative information

Please provide the following:

- Timestamp: for example 18.2.2020 21:50 (GMT +1)
- Function App name: processminer
- Function name(s) (as appropriate): ProcessMiner
- Core Tools version: v2.0

#### Repro steps

Visit https://processminer.azurewebsites.net after some time to enforce cold start of function app.

#### Expected behavior

Application is started in a few seconds.

#### Actual behavior

A cold start of the application takes a few minutes and causes a 502 error.

#### Known workarounds

I don't know of any.

#### Contents of the requirements.txt file:

azure-functions==1.0.7
pm4py==1.2.9
azure-storage-blob==12.1.0
pathlib
pybase64==1.0.1

#### Related information

Docker file (combination of docker file for python azure function and pm4py docker file):

```
FROM mcr.microsoft.com/azure-functions/python:2.0-python3.7

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install nano vim
RUN apt-get -y install git
RUN apt-get -y install python3-pydot python-pydot python-pydot-ng graphviz
RUN apt-get -y install python3-tk
RUN apt-get -y install zip unzip
RUN apt-get -y install gcc gfortran python-dev libopenblas-dev liblapack-dev cython
RUN apt-get -y install g++ libboost-all-dev libncurses5-dev wget
RUN apt-get -y install libtool flex bison pkg-config g++ libssl-dev automake
RUN apt-get -y install libjemalloc-dev libboost-dev libboost-filesystem-dev libboost-system-dev libboost-regex-dev python3-dev autoconf flex bison cmake
RUN apt-get -y install libxml2-dev libxslt-dev libfreetype6-dev libsuitesparse-dev
RUN pip install -U wheel six cython pytest
RUN pip install pyvis==0.1.7.0 networkx==2.4 matplotlib==3.1.1 numpy==1.17.3 ciso8601==2.1.2 lxml==4.4.1 graphviz==0.13 pandas==0.25.2 scipy==1.3.1 scikit-learn==0.21.3 pytz==2019.3
RUN pip install pydotplus==2.0.2 pulp==1.6.10 intervaltree==3.0.2
RUN pip install ortools==7.4.7247 prefixspan==0.5.2 fasttext==0.9.1 pybind11==2.4.3 pyarrow==0.13.0

COPY requirements.txt /
RUN pip install -r /requirements.txt

COPY . /home/site/wwwroot
```

**Comment by kubmir** [comment]
Hello, I would like to ask if anyone has any info about this issue. I have not solved it yet.

**Comment by balag0** [comment]
Since the app is using a custom container the cold start will involve pulling the image from docker which seems to be taking a long time. Http requests will time out after 230 seconds afte which the app will return a 502.

Potential mitigations
Scale up to a larger worker. (This still might not work if the bottleneck is docker network latency)
Switch to linux consumption plan (but this doesnt support custom containers currently so you might have to switch to Run-From-Package for deployment)

Let me know if you need help with any of these options.

**Comment by yubozhao** [comment]
I am encountering this issue as well with EP1 plan.  I understand the polling from docker registry takes a while. Since I am also using ACR for Docker image, I expect it is faster than polling from the Docker hub or any other container registry services
