### ISSUE TITLE
WEBSITE_RUN_FROM_PACKAGE + Build Options

### ISSUE THREAD

**Issue by lewalt000** [Azure/azure-functions-python-worker#619]
#### Investigative information
I am trying to determine the expected behavior when using `WEBSITE_RUN_FROM_PACKAGE` (https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package) combined with the options for publishing to Azure that make use of 3rd party dependencies specified in `requirements.txt` (https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#publishing-to-azure).

In particular, I would like to use the "remote build" option (https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#remote-build), but don't see a way to do this when using `WEBSITE_RUN_FROM_PACKAGE`.

I am attempting to use the "Custom Dependencies" option (https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#custom-dependencies) to package dependencies into the zip file deployed using `WEBSITE_RUN_FROM_PACKAGE`, but am still getting errors that the packages aren't able to be imported.

Is there a recommended way to include 3rd party Python dependencies when using `WEBSITE_RUN_FROM_PACKAGE`?

In particular, I'm trying to use the `requests` package.

**Comment by Hazhzeng** [comment]
Hi @lewalt000,

Unfortunately, currently, we don't support remote build mixing with WEBSITE_RUN_FROM_PACKAGE.

Could you give me the detailed **import errors**?
Thanks in advance.

**Comment by lewalt000** [comment]
Hi @Hazhzeng - Thank you for confirming the expected behavior when using `WEBSITE_RUN_FROM_PACKAGE`.

I no longer have the import errors handy, but it was the generic issue of trying to `import requests` and the package was not found.

I resolved this by changing my code to use `urllib` instead, which is a builtin package.

If I wanted to use a 3rd party package with `WEBSITE_RUN_FROM_PACKAGE`, I would need to include those in the zip file used by `WEBSITE_RUN_FROM_PACKAGE`, correct?

**Comment by Hazhzeng** [comment]
@lewalt000 Nice, glad to hear you figure it out by yourself. Yes, you need to include the 3rd party packages in WEBSITE_RUN_FROM_PACKAGE.

If the import still doesn't work, one thing to keep in mind is that our Azure Functions runtime in on Linux Debian stretch (v2 function app)/buster (v3 function app), if you resolve the packages on Windows without remote build, it may have native dependencies (os-libraries) mismatch issue.
