### ISSUE TITLE
Update build script to generate nuget packages that match release tags

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#629]
Currently nuget package version generated use current date. This does not follow nuget versioning as installing latest package in VS shows a warning about downgrading.

All the azure functions repos follow similar pattern for versioning - packages generated match release tags.

**Comment by Hazhzeng** [comment]
This is done and there's a new release wiki for it
https://github.com/Azure/azure-functions-python-worker/wiki/Release-Instructions
