### ISSUE TITLE
Python functions Japan East/West regions deployment is failing

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#630]
From feedback:

Tried to deploy a Function app (Python) to Azure via VSCode Azure pane.

Select the folder to zip and deploy: BlobPyFunc(local folder name)
Select subscription
Create new Function App in Azure: BlobPyFunc
Select a runtime: Python 3.6
Select a location for new resources: Japan East
However, an error occurred. "Requested features are not supported in region. Please try another region."
The same thing happened when Japan West is selected.

Also tried to deploy a Function app (Python) to Azure via VSCode command-line tool.

But the same errors occurred when either Japan East or Japan West is selected.

According to the list below, Azure Functions should be supporting both Japan East and Japan West.
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=functions&regions=japan-west,japan-east

Eventually, it finally worked once East Asia is selected.

I tried to deploy a Function app (Python) to Azure via VSCode Azure pane.

Select the folder to zip and deploy: BlobPyFunc(local folder name)
Select subscription
Create new Function App in Azure: BlobPyFunc
Select a runtime: Python 3.6
Select a location for new resources: Japan East
However, an error occurred. "Requested features are not supported in region. Please try another region."
The same thing happened when Japan West is selected.

I also tried to deploy a Function app (Python) to Azure via VSCode command-line tool.
But the same errors occurred when either Japan East or Japan West is selected.

**Comment by balag0** [comment]
Linux consumption regions are tracked at https://github.com/Azure/azure-functions-host/wiki/Linux-Consumption-Regions

(Currently Japan regions are not supported)

**Comment by balag0** [comment]
Also there is an arm api (/georegions) to get the list of supported regions that vs code should use if it is not already to avoid allowing selection of non-supported regions.

**Comment by anirudhgarg** [comment]
Yes Japan is not supported yet for Linux Consumption. Going to close it out.
