### ISSUE TITLE
Document pre-installed Python packages 

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#633]
As part of many customer asks and CSA requests, we have seen a pattern of folks wanting to know what packages are pre-installed in the serverless ecosystem and what a customer needs to add in their requirements.txt.

For eg:  does the existing serverless infra already install latest versions of the UUID library? if so what version does it have?
If someone tries to use the latest version of UUID in their requirements.txt that might not have compatibility with older versions they will get to know through error messages.
Can this be published?

This has also been an ask when comparing competitor products.

**Comment by anirudhgarg** [comment]
Roger just assigned this to you. Please document this in a wiki in this repo.

**Comment by cecilphillip** [comment]
Somewhat related to azure/azure-functions-python-library#52
I'd like to see the the included packages and versions documented. In particular the expected behavior when installing azure-functions

**Comment by Hazhzeng** [comment]
@anirudhgarg @priyaananthasankar @cecilphillip 
I created a Wiki page for the preinstalled libraries: https://github.com/Azure/azure-functions-python-worker/wiki/Preinstalled-Python-Libraries
