### ISSUE TITLE
Add samples for automation, web scenarios

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-python-worker#636]

**Comment by vrdmr** [comment]
Automation sample done: https://docs.microsoft.com/en-us/samples/azure-samples/azure-functions-python-list-resource-groups/azure-functions-python-sample-list-resource-groups/

**Comment by vrdmr** [comment]
[Flask](https://docs.microsoft.com/en-us/samples/azure-samples/flask-app-on-azure-functions/azure-functions-python-create-flask-app/) and [FastAPI](https://docs.microsoft.com/en-us/samples/azure-samples/fastapi-on-azure-functions/azure-functions-python-create-fastapi-app/) examples done.
