### ISSUE TITLE
Missing logs when processing large file via Blob Trigger

### ISSUE THREAD

**Issue by pwankhade** [Azure/azure-functions-python-worker#641]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Azure function developed in Python 3.7
#### Question
**Main Question:**
I have configured a Blob triggered Azure function that reads the blob file and stores it in Event hub. The function works only for a small file. I tried uploading a file of 22MB and the function never got triggered. Does the azure function support that sort of files. Also I couldn't find any documentation that helps on this. Is there?

**Extra Info if possible**
In addition I see that the storage associated to the function carries some of the files related to the triggers and bindings. Is there any azure documentation that explains this?

**Comment by Josh-a-e** [comment]
@pragnagopa any idea when this might get released?

**Comment by anirudhgarg** [comment]
@Josh-a-e  - this will be released in the next 2-3 weeks by end of May at the latest.

**Comment by Josh-a-e** [comment]
@anirudhgarg Awesome, thanks for letting me know. I’ve had to add a listener to the poison queue and retry just using the metadata that is provided there, but I look forward to this getting released so I can remove that 👌

**Comment by TobiTh** [comment]
@anirudhgarg Is there an update for the release date?

**Comment by vrdmr** [comment]
@TobiTh - We are doing a release now - it got delayed due to some new issues. Once the release is complete, I'll update the status. The release should be done in no more than 2 weeks.

**Comment by TobiTh** [comment]
@vrdmr I see that a new release is available. Do we need to change the python azure-function library version or is it only a part of the azure function runtime. If it is the ladder, how do we update or function so that it can process files with >4MB size?

**Comment by anirudhgarg** [comment]
This is deployed now. @TobiTh you should be able to have a blob for instance that is greater than 4MB and that will be successfully processed by the Python Worker
