### ISSUE TITLE
How to enrich the logger with custom properties?

### ISSUE THREAD

**Issue by empz** [Azure/azure-functions-python-worker#642]
Running some Azure Function (runtime 3) with Python 3.7 and Application Insights configured.

Doing logging.info("message") works. This get sent as a TRACE to AppInsights. But it's not very useful if we can't enrich an execution's logging context with custom properties so that we can easily query by these afterwards. 

Is this even supported on Azure Functions for Python? 

What's the relation between Python Azure Functions and the [Opencensus library which is shown as the recommended AI SDK for Python](https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python)?

Or should I just use a 3rd party logging framework (i.e. Sentry, Datadog, etc)

**Comment by tuckeryatesjvion** [comment]
Custom log properties are very important to me as well. I'd love to be able to push relevant identifiers to the customDemensions field in applicationinsights traces, then be able to easily isolate logs related to those identifiers. 

I've had some trouble searching for documentation on this feature, although I suspect it is supported. Can any of the MSFT team link anything relevant?
