### ISSUE TITLE
Exceptions for a file size in Azure Blob Input trigger

### ISSUE THREAD

**Issue by pwankhade** [Azure/azure-functions-python-worker#644]
I have created a basic Azure function with Bindings and triggers. The use case is that, on a new file(csv) added to a blob storage the azure function should trigger and transfer the file content to Event hub. 

This function is working as expected for very small files. When a file of size around 22Mb was uploaded the I get an error message in logs 
``` Event is too large. Event is approximately 61326722b and max size is 245760b```

From what I have read across different sources this load should be something that the function should be able to handle.

The file that I uploaded is still not the actual load that this setup needs to handle.

So I would like to know what could be the best way in handling a large file processing with Azure functions? Is Azure function actually designed to handle that and if not what Azure services could be used for such large files.

Technical Details:
Version of Azure Function- 3
Language- Python
In Trigger- Blob Storage
Out Binding- Event Hub

**Comment by vrdmr** [comment]
Adding a reference link: https://github.com/Azure/azure-functions-python-worker/issues/641#issuecomment-606657142.
