### ISSUE TITLE
Send WorkerStatusResponse when receiving WorkerStatusRequest. Send Capability "WorkerStatus" on Init

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-python-worker#660]
When host sends a "WorkerStatusRequest" , the worker needs to return "WorkerStatusResponse". The latency from request to response is used for scale decisions for out-of-proc languages.

Reference Java commit: https://github.com/Azure/azure-functions-java-worker/commit/fbf0e4b62a1ddcb778cf7604c425082bdb743cb5

cc: @pragnagopa @mathewc

**Comment by Hazhzeng** [comment]
Hi @Yojagad,

Is this WorkerStatusRequest a recurring event? Or is it a one-off event?
If possible please point me to the host code for this.

Thanks,
Roger

**Comment by pragnagopa** [comment]
It is a recurring event. Also, need send capability "WorkerStatus" in order to take perf improvements being made in PR: https://github.com/Azure/azure-functions-host/pull/5897
