### ISSUE TITLE
ModuleNotFound Error | I have an Azure function DevOps pipeline which runs file for Azure Function Runtime 2 but fails on Azure Function Runtime3

### ISSUE THREAD

**Issue by Deepanshu2017** [Azure/azure-functions-python-worker#666]
I have an Azure function DevOps pipeline. 
This pipeline I create for Azure function Runtime V2 and it works fine.
I have around 5-6 azure function within same app and all are compatible with Python 3.8

V2 is running on Python3.6 and V3 on Python 3.8

I recently tried to move from Azure function V2 to V3 and I expected the pipeline to build and succeed. But whenever I'm trying to Run the azure function from new app, I receive "ModuleNotFound Error".

The only difference between my Function V2 and V3 runtime is, V2 is hosted on docker and V3 is not.

![image](https://user-images.githubusercontent.com/8173602/80694686-7c477d00-8af2-11ea-9317-99944ed511a8.png)

I do have proper requirements.txt and it is working fine with V2

**Comment by Deepanshu2017** [comment]
Update:
I tried to change V3 to use Python 3.6 and it works.

**Comment by Hazhzeng** [comment]
Thanks for reporting this @Deepanshu2017,

Our team has composed a troubleshooting guide in our wiki page for Module Not Found error 
https://github.com/Azure/azure-functions-python-worker/wiki/Module-Not-Found-Issues

I think in your case, maybe the azure-keyvault version you're using is too old to support Python 3.8
Try following the steps [Update Package To The Latest Version](https://github.com/Azure/azure-functions-python-worker/wiki/Module-Not-Found-Issues#update-package-to-the-latest-version) and see if it resolves your issue.

**Comment by Hazhzeng** [comment]
Also, please check in your `azure-pipelines.yml` **UsePythonVersion** task. See if you have updated the version value to 3.8
