### ISSUE TITLE
[Improvement] Block azure.functions module collided trigger names

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-functions-python-worker#671]
###### Please provide the following:

- Timestamp: 5/6/2020
- Function App name: fa-clipy
- Function name(s) (as appropriate): **http**
- Core Tools version:

###### Provide the steps required to reproduce the problem:
1. Create a python function app
2. Create an HTTP trigger with the name "http"
3. Deploy the function app to a Linux Dedicated app.
4. Hit /api/http endpoints

###### Provide a description of the expected behavior.
The function should go through and execute.

###### Provide a description of the actual behavior observed.
The function app throws a 500 (functions not found in azure module) due to a name collision with azure.functions.http module.

###### Provide a description of any known workarounds.
Rename trigger name "http" to "httptrigger"

###### Provide the requirements.txt file to help us find out module related issues.
azure-functions

###### Provide any related information

* Links to source
* Bindings used

**Comment by Hazhzeng** [comment]
cc: @divyagandhii

**Comment by hallvictoria** [comment]
V2 programming model addresses this issue.
