### ISSUE TITLE
HttpResponse attempt to attempt to do json.dumps 

### ISSUE THREAD

**Issue by nlasnoski** [Azure/azure-functions-python-worker#674]
https://nathanlasnoski.com/2020/05/07/return-json-from-azure-functions-with-python/

Potential to have HTTP response attempt json dump if passed anything other than a string.  Or... make that even the default response in general.  

###### Please provide the following:

- Timestamp:
- Function App name:
- Function name(s) (as appropriate):
- Core Tools version:

###### Provide any related information

* Links to source
* Bindings used

**Comment by Hazhzeng** [comment]
Hi @nlasnoski,

Thanks for your suggestions.
Python is part of the Azure Functions family and the behavior of HTTP trigger needs to align with our family products (.NET/Java/Node/PowerShell). Our HTTP trigger is capable of returning raw body and it is our common use case. Making the Python functions to automatically return JSON dumps will violate this behavior.
