### ISSUE TITLE
Investigate making the number of threads in the Azure Functions Python Worker thread pool configurable

### ISSUE THREAD

**Issue by anirudhgarg** [Azure/azure-functions-python-worker#675]
Currrently the Azure Functions Python Worker restricts the number of threads in the default thread pool to 1. We want to experiment with possibly offering a configurable values for the customer to change this to a higher value.

There is already a detailed discussion here: https://github.com/Azure/azure-functions-python-worker/issues/236 if it makes sense to allow multiple threads in the Python Worker thread pool. 

This is the line of code which has to be changed.        

https://github.com/Azure/azure-functions-python-worker/blob/6068092982479932f1d2d3c315ee6835cdeac8c1/azure/functions_worker/dispatcher.py#L56

**Comment by anthonychu** [comment]
Thanks for linking to the thread. This is the missing piece of information for me:

https://github.com/Azure/azure-functions-python-worker/issues/236#issuecomment-440433382

We already have a solution for I/O bound code with asyncio. If CPU-bound workloads can't be solved by threading, we probably don't need to investigate this too much. Increasing the worker process count is probably the best solution when running on multi-core compute and the overhead of extra processes is justified.

**Comment by anirudhgarg** [comment]
@anthonychu I am wondering if it still makes sense to investigate this for cases when the underlying api's do not implement async equivalents but there are I/O bound calls - if a single worker is running on multiple threads that might help ? I am assuming when we are asking customers to implement their own thread pool thats what we are hoping will help ? 

Since the implementation looks to be pretty simple - we should be able to test this out fairly easily ? What do you think ?
