### ISSUE TITLE
[Improvement] Can we fake trigger a timer function

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-python-worker#676]
During the debugging of a timer trigger-based function locally, we need to tweak the timer trigger values to get the trigger generated. It would be nice to have a feature to somehow trigger a timer countdown locally using VSCode.

**Comment by anthonychu** [comment]
Feature already exists in VS Code: 
![image](https://user-images.githubusercontent.com/3982077/84796657-bb9c3100-afad-11ea-8433-2aa94b71a13d.png)

You can also trigger by hitting an admin webhook:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-manually-run-non-http

Could potentially expand to other triggers and tooling (Core Tools). Best to file issues at their respective repos:

https://github.com/microsoft/vscode-azurefunctions
https://github.com/Azure/azure-functions-core-tools

**Comment by anirudhgarg** [comment]
Looks like there is a way to do this. Closing this.

**Comment by vrdmr** [comment]
Thanks for the pointers, @anthonychu.
