### ISSUE TITLE
[BUG] gRPC max message size issue

### ISSUE THREAD

**Issue by gohar94** [Azure/azure-functions-python-worker#678]
### Investigative information

- Timestamp: Mon May 11 20:55:52 PDT 2020
- Function App name: jupyterless
- Function name(s) (as appropriate): jupyterless
- Core Tools version: Not using Core Tools. Using azure-functions-host running locally.

### Repro steps

1. Step A: Start azure function's host with the AzureWebJobsScriptRoot environment variable pointing to the function root.
2. Step B: Invoke the function through an HTTP request and another blob input which has a size greater than 4MB.

### Expected behavior

The function should successfully run with the blob input.

### Actual behavior

The function throws an exception in the debugger (VSCode):
```
Exception has occurred: _MultiThreadedRendezvous
<_MultiThreadedRendezvous of RPC that terminated with: status = StatusCode.RESOURCE_EXHAUSTED details = "Received message larger than max (8005196 vs. 4194304)" debug_error_string = "{"created":"@1589243718.140000000","description":"Received message larger than max (8005196 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":191,"grpc_status":8}" >
 File "f:\foo\functions_runtime\azure-functions-python-worker\azure_functions_worker\dispatcher.py", line 553, in __poll_grpc  for req in grpc_req_stream:
```

### Known workarounds

Blobs smaller than 4MB work fine.

### Contents of the requirements.txt file:
```
azure-functions
azure-storage-blob
dill
tblib==1.4.0
pandas
aiohttp
```

### Related information
I have tried running with the default version of the python worker that azure-functions-host (dev branch) uses and that works fine.
However, when I used this local version of the worker, I noticed this behavior.

**Comment by gohar94** [comment]
@pragnagopa @Hazhzeng I think this behavior was attempted to be fixed under [this](https://github.com/Azure/azure-functions-python-worker/pull/632) PR but probably it is still not fixed or I'm not doing something correctly. Please help with this, thanks.

**Comment by pragnagopa** [comment]
> when I used this local version of the worker

Can you give us more details on the setup ? which version of host? from dev branch or the e2e tests in this repo?

**Comment by anirudhgarg** [comment]
@gohar94  - I think this is not yet deployed in production.

**Comment by gohar94** [comment]
@pragnagopa I am using the dev branch of the azure-functions-host and dev branch of azure-functions-python-worker.
@anirudhgarg I see, but I am using local version of the worker and the host (as mentioned above) and this problem is occurring when using dev branch of of this worker repo. When I use the default version that the host (again, dev branch) picks up, it works fine.

**Comment by anirudhgarg** [comment]
@gohar94 do you mean that the version that comes with core tools ? That also has a previous version. Please just wait for the deployments to happen which will in the next 2-3 weeks.
