### ISSUE TITLE
Azure Functions Beta runtime error "Status: 404 Not Found"

### ISSUE THREAD

**Issue by Krande** [Azure/azure-functions-python-worker#68]
Hi,

I tried running the code examples located in the docs using the beta version of Azure Functions but I am getting a "Status: 404 Not found" error when trying to run it. I have tried restarting the function server and re-writing/stripping the code, but without luck. Any ideas as to why this is happening?

main.py
```
import azure.functions

def main(req: azure.functions.HttpRequest) -> str:
    user = req.params.get('user', 'User')
    return f'Hello, {user}!
```

function.json
```
{
  "scriptFile": "main.py",
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

**Comment by 1st1** [comment]
You should run `$ python -m azure.worker.testutils --script-root=<dir with your functions>` command, otherwise it's configured for serving a `tests/http_functions` folder.  I'll go ahead and make `--script-root` required, so that it's less confusing.

**Comment by Krande** [comment]
Hi, thank you for the quick answer. This is the first time I am testing the Beta runtime, so I think I have missed something essential in my initial set-up compared to using the v1.0 runtime. After switching my function to a beta runtime, are you suggesting that I should use Kudu for setting my script-root? I tried but it could not find the "azure.worker module". And I notice the default python is still 2.7. Btw I am on a consumption plan and I tried testing the code using the Portal and through a httpWebRequest (where both results in the 404 error).

**Comment by 1st1** [comment]
I think that at this point it's only possible to test the new Python worker **locally** on your machine. You can find instructions on how to do that on [this](https://github.com/Azure/azure-functions-python-worker/wiki/Setting-up-development-environment) wiki page.

cc @asavaritayal

**Comment by Krande** [comment]
Okay, that explains it:) thanks!
