### ISSUE TITLE
TimeTrigger Azure Function Python API pass ScheduleStatus to function

### ISSUE THREAD

**Issue by claria** [Azure/azure-functions-python-worker#681]
#### What problem would the feature you're requesting solve? Please describe.
The TimeTrigger Function pass a TimerRequest[1] object to the executed function. Unlike in the C# interface, the only property of the TimerRequest object is the past_due attribute. 

#### Describe the solution you'd like
Pass all the information, which are discussed and listed in [2], e.g. the ScheduleStatus.

```{`
    "Schedule":{
    },
    "ScheduleStatus": {
        "Last":"2016-10-04T10:15:00+00:00",
        "LastUpdated":"2016-10-04T10:16:00+00:00",
        "Next":"2016-10-04T10:20:00+00:00"
    },
    "IsPastDue":false
}```

[1]https://docs.microsoft.com/de-de/python/api/azure-functions/azure.functions.timerrequest?view=azure-python
[2]https://docs.microsoft.com/de-de/azure/azure-functions/functions-bindings-timer?tabs=csharp

**Comment by Servot** [comment]
any update on this?

**Comment by finn-wa** [comment]
As a workaround, you can set the input parameter to be `str`. Then you get all of the data in JSON format, and you can make your own class if you wish. For example:
_function.json_
```json
{
  "scriptFile": "sample.py",
  "bindings": [
    {
      "direction": "in",
      "type": "timerTrigger",
      "name": "timerJson",
      "schedule": "0 0 3 * * *"
    }
  ]
}
```
_sample.py_
```py
import logging
from timer_request import TimerRequest

def main(timerJson: str):
    timer = TimerRequest(timerJson)
    if timer.past_due:
        logging.warn(f"{summary_req.name} timer is past due!")
    logging.info(timer.schedule_status.last)
```
_timer_request.py_
```py
import json
from datetime import datetime
from dateutil import parser

class ScheduleStatus:
    """
    Represents a timer schedule status.
    - last: Last recorded schedule occurrence
    - next: Expected next schedule occurrence
    - last_updated: The last time this record was updated. This is used to
      re-calculate Next with the current Schedule after a host restart.
    """

    last: datetime
    next: datetime
    last_updated: datetime

    def __init__(self, json_dict: dict):
        self.last = parser.isoparse(json_dict["Last"])
        self.next = parser.isoparse(json_dict["Next"])
        self.last_updated = parser.isoparse(json_dict["LastUpdated"])


class TimerRequest:
    """
    A more complete version of the TimerRequest with a ScheduleStatus.
    """

    schedule_status: ScheduleStatus
    past_due: bool

    def __init__(self, json_str: str):
        json_dict = json.loads(json_str)
        self.schedule_status = ScheduleStatus(json_dict["ScheduleStatus"])
        self.past_due = json_dict["IsPastDue"]
```

**Comment by TroyWitthoeft** [comment]
@finn-wa Thanks for this!  Will use it.  Was working on a function app last week that had multiple timer triggers.  With multiple triggers firing at once, it can be a bit difficult to sus out which log messages belong to which trigger.  Was trying to get some of that schedule info into the logs.  

Honestly, something like this would make the python feature set match more closely with C#.

**Comment by KhaoticMind** [comment]
Any update on this issue? The workaround works as described but is a workaround, the timer parameter should work as documented.

**Comment by vrdmr** [comment]
We are actively working on this issue, along with another similar issue - https://github.com/Azure/azure-functions-python-worker/issues/858. We'll keep you updated. Apologies for the delay.
