### ISSUE TITLE
[BUG] Service Bus Default Template

### ISSUE THREAD

**Issue by allenc97** [Azure/azure-functions-python-worker#682]
###### Please provide the following:

- Core Tools version: azure/functions/azure-functions-core-tools@3: stable 3.0.2534, HEAD

###### Provide the steps required to reproduce the problem:

Currently, the default template for ServiceBus based functions is 
```
import logging

import azure.functions as func


def main(message: func.ServiceBusMessage):
    # Log the Service Bus Message as plaintext

    message_content_type = message.content_type
    message_body = message.get_body().decode("utf-8")

    logging.info("Python ServiceBus topic trigger processed message.")
    logging.info("Message Content Type: " + message_content_type)
    logging.info("Message Body: " + message_body)
```

Suppose I send the message 
``` msg = sb.Message('{1:3}', broker_properties={'ContentType': 'application/json'}) ```
through the ServiceBus python API as following [docs](https://docs.microsoft.com/en-us/rest/api/servicebus/message-headers-and-properties), the content type field does not appear to be set. Infact, looking at the source code of Message, it does not appear that broker_properties is event dealt with anymore. I.e

```
def __init__(self, body, encoding='UTF-8', **kwargs):
        subject = kwargs.pop('subject', None)
        # Although we might normally thread through **kwargs this causes problems as MessageProperties won't absorb spurious args.
        self.properties = uamqp.message.MessageProperties(encoding=encoding, subject=subject)
        self.header = uamqp.message.MessageHeader()
        self.received_timestamp = None
        self.auto_renew_error = None
        self._annotations = {}
        self._app_properties = {}
        self._encoding = encoding
        self._expiry = None
        self._receiver = None
        if 'message' in kwargs:
            self.message = kwargs['message']
            self._annotations = self.message.annotations
            self._app_properties = self.message.application_properties
            self.properties = self.message.properties
            self.header = self.message.header
            self.received_timestamp = datetime.datetime.now()
        else:
            self._build_message(body)
```

###### Provide a description of the expected behavior.

It appears that the default use case is causing an issue, as the Python API for servicebus does not appear to allow setting of content type. I am unsure rather this bug falls upon the functions team or the servicebus team, but the default template provided using functions on VSCode is breaking, but should not. 

###### Provide a description of the actual behavior observed.

It would be nice for the default template to work when I send it a simple message.

###### Provide any related information

* Links to source
* Bindings used

**Comment by Hazhzeng** [comment]
Hi @allenc97,

Thanks for raising the issue and providing us with a sample test code.

I've tried out your test sample with a .NET Core **Microsoft.Azure.ServiceBus** SDK, the Content-Type is passed correctly into the function via a Message Object.

It seems like the issue you're facing is a misalignment in the **azure-servicebus** Python SDK's implementation. I will transfer the ticket to them.

**Comment by Hazhzeng** [comment]
To unblock from this issue, I would suggest,
1. Use Microsoft.Azure.ServiceBus in .NET Core if possible.
2. Passing the ContentType into the message instead of broker properties, and manually parse the content according to message's ContentType field.

@allenc97, please follow the update on https://github.com/Azure/azure-sdk-for-python/issues/11751 thread.
Feel free to reopen the ticket again if you have any confusions on our side.
