### ISSUE TITLE
cannot import 'run' (aio_compat.py) (fails in local environment using VSCode)

### ISSUE THREAD

**Issue by Rutikhal** [Azure/azure-functions-python-worker#690]
I have created new  empty http-trigger Azure Function in VSCode to check (in another folder). I have the same problem when starting function in debug mode. My file with code is closing and   I have an error with opening aio_compat.py
Exception has occurred: ImportError
cannot import name 'run'
  File "c:\users\rutikhal\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6\windows\x64\azure_functions_worker\aio_compat.py", line 84, in <module>
    from asyncio import run, get_running_loop  # NoQA
  File "c:\users\rutikhal\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6\windows\x64\azure_functions_worker\main.py", line 6, in <module>
    from . import aio_compat
  File "c:\users\rutikhal\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6\windows\x64\worker.py", line 59, in <module>
    from azure_functions_worker import main

if I press F5 I have  another 

Exception has occurred: ModuleNotFoundError
No module named 'grpc_tools'   opening another file

Exception has occurred: ModuleNotFoundError
No module named 'grpc_health'

Exception has occurred: ModuleNotFoundError
No module named 'grpc_reflection'

Exception has occurred: ImportError
cannot import name 'enable_deterministic_proto_serialization'

Yes, after that my code is opened again.
But it should not work like this. I have not updated anything from yesterday.

_Originally posted by @Rutikhal in https://github.com/Azure/azure-functions-python-worker/issues/481#issuecomment-641796097_

**Comment by Rutikhal** [comment]
it seems that it is really ms-python.python ( Python extension in VSCode)  issue, because my workaround was to uninstall ver. 2020.5.86398, disabled autoupdate of extensions in VSCode, install manually one of the previous version 2020.5.80290 of this ext. using link from this case
https://github.com/microsoft/vscode-python/issues/12217

**Comment by Hazhzeng** [comment]
VSCode has just released the latest version (2020.5.86806) of Python Extension .
Please update the extension to the latest version and it will fix this issue.
