### ISSUE TITLE
[BUG] EventHubEvent implementation does not reflect the Event Hub message structure

### ISSUE THREAD

**Issue by daawnee** [Azure/azure-functions-python-worker#693]
### Investigative information

- Python version: 3.7

### Repro steps

1. Create an Azure Function with Event Hub trigger
2. Observe the structure of the `EventHubEvent` parameter in the main function:
  `def main(event: `[`azure.functions.EventHubEvent`](https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/_eventhub.py#L7)`):`
  or the interface it is implementing: [`azure.functions._abc.EventHubEvent`](https://github.com/Azure/azure-functions-python-library/blob/e008cbf1c3fcb602407fce45a8a5f906bcbe900b/azure/functions/_abc.py#L304)

### Expected behavior

The structure of the [`EventHubEvent`](https://github.com/Azure/azure-functions-python-library/blob/e008cbf1c3fcb602407fce45a8a5f906bcbe900b/azure/functions/_abc.py#L304) interface (and [implementation](https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/_eventhub.py#L7)) should reflect the actual data structure of the event hub message.

Practically the `EventHubEvent` should match the Python SDK for Event Hub [`EventData`](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/azure/eventhub/_common.py#L72) implementation.

### Actual behavior

The [`azure.functions.EventHubEvent`](https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/_eventhub.py#L7) does not match the structure of [`azure.eventhub.EventData`](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/azure/eventhub/_common.py#L72). Some attributes are entirely missing, such as:
- `properties`
- `system_properties`

### Known workarounds

None.

### Contents of the requirements.txt file:

N/A

### Related information

* [`azure.functions.EventHubEvent`](https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/_eventhub.py#L7)
* [`azure.functions._abc.EventHubEvent`](https://github.com/Azure/azure-functions-python-library/blob/e008cbf1c3fcb602407fce45a8a5f906bcbe900b/azure/functions/_abc.py#L304)
* [`azure.eventhub.EventData`](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/azure/eventhub/_common.py#L72)

**Comment by anirudhgarg** [comment]
Discussed with @Hazhzeng. We are looking to see if we can add the raw json payload.

**Comment by anthonychu** [comment]
I took a quick look at this as well. There might be an additional issue when the `cardinality` of the trigger is set to `one`. Even the basic `enqueued_time`, `offset`, etc were missing for me.

Problem might be here: https://github.com/Azure/azure-functions-python-library/blob/e008cbf1c3fcb602407fce45a8a5f906bcbe900b/azure/functions/eventhub.py#L128-L139

Looks like the trigger metadata has different properties than what the code is expecting so the mapping doesn't work.

**Comment by anirudhgarg** [comment]
Yes we have already added the enqueued_time but it is not deployed. https://github.com/Azure/azure-functions-python-worker/issues/639. Since this will be an ongoing issue with the SDK changing we are planning to add a raw body property so that customers can get the raw payload

**Comment by anthonychu** [comment]
@anirudhgarg Can you share more information on what's changing in the metadata that breaks this? Exposing the raw data just passes on the problem, and any app that is dependent on the raw data will still break.

**Comment by anirudhgarg** [comment]
Lets make sure that this works for cardinality 1 and cardinality many

**Comment by daawnee** [comment]
@Hazhzeng What is the ETA for this fix to be generally available?

**Comment by anirudhgarg** [comment]
@daawnee I will check up on this today, We should have already deployed this but I will confirm today.

**Comment by daawnee** [comment]
In [v1.3](https://github.com/Azure/azure-functions-python-library/blob/01075c797bf465ad8121de09c3e118c844e1a16e/azure/functions/_abc.py#L307) I don't see any change in the interface, so probably it has not been released, yet.

**Comment by anirudhgarg** [comment]
Yes the deployment is going on right now - we are hoping it should finish by the end of next week if not earlier.

**Comment by anirudhgarg** [comment]
Deployment is done, we have added the properties now. Closing this out.
