### ISSUE TITLE
Change authlevel through env variables

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#695]
We want to be able to switch authlevels of all functions using env variable. 

Background: When running azure function in container, it uses authlevel:function even if developing locally if authlevel is set to function in function.json. Instead of changing authlevel:function to authlevel:anonymous one by one for every function, we want to be able to switch the authlevel for all function with env vars.

According to the azure functions documentation, this seems possible by using the %xxx% expressions:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings

<img width="983" alt="csefeedback_1" src="https://user-images.githubusercontent.com/10415876/84987625-5c493880-b0f5-11ea-8f2b-a61dbcb96bee.png">

**Comment by Hazhzeng** [comment]
Hi @priyaananthasankar,

It this issue Python worker specific, or is this a feature request to the host?
Just want to get more context before we decide to make the change.

**Comment by thomasfrederikhoeck** [comment]
For me this is python specific but I guess it is for the host? It would make it much easier for doing end-2-end testing with docker-compose, if you could disable the auth instead of doing workarounds.

**Comment by thomasfrederikhoeck** [comment]
I would be nice to do it with an extra option to `AzureWebJobsSecretStorageType` https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobssecretstoragetype

**Comment by vrdmr** [comment]
In future, with new programming model work we are doing, this could be handled by the an easy approach. How it'll look like soon:

```python
import azure.functions as func

app = func.FunctionApp(auth_level=func.AuthLevel.ANONYMOUS)

@app.function_name(name="HttpTrigger1")
@app.route(route="hello") # HTTP Trigger
def test_function(req: func.HttpRequest) -> func.HttpResponse:
     return func.HttpResponse("HttpTrigger1 function processed a request!!!")
```

So you can convert this to be an environment variable.
```python
import azure.functions as func

app = func.FunctionApp(auth_level=ENV_VARIABLE)

@app.function_name(name="HttpTrigger1")
@app.route(route="hello") # HTTP Trigger
def test_function(req: func.HttpRequest) -> func.HttpResponse:
     return func.HttpResponse("HttpTrigger1 function processed a request!!!")
```

**Comment by thomasfrederikhoeck** [comment]
@vrdmr that looks promising :-)

**Comment by YunchuWang** [comment]
@thomasfrederikhoeck Hi Thomas, thanks for raising this issue, with python v2 new programming model released, you can set authlevel from environment var at runtime, please refer to the doc and the pictures for example
https://techcommunity.microsoft.com/t5/azure-compute-blog/azure-functions-v2-python-programming-model/ba-p/3665168#:~:text=The%20v2%20new%20programming%20model,by%20easy%20to%20reference%20documentation.
<img width="978" alt="image" src="https://user-images.githubusercontent.com/12449837/213894127-06dd0c06-0977-436e-a052-d2fdaad5279a.png">
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/12449837/213894134-a9e7480c-1696-4030-b696-e636cb1845a8.png">
