### ISSUE TITLE
Application Properties are not part of event

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-functions-python-worker#698]
@NayangiriGoswamiGit commented on [Fri Jun 19 2020](https://github.com/Azure/azure-sdk-for-python/issues/12135)

I route IoTHub Device Telemetry messages to its default events end point.
Than it triggers serverless function written in python with IotHub's eventhub binding.
The received event in azure serverless function does not contain application properties which has been set by device.
Here is code:
```
import azure.functions as func

def main(events: func.EventHubEvent):
    event_body = event.get_body().decode('utf-8')
```

When I do dir(event), it shows me,
['EventHubEventbody', '_EventHubEventenqueued_time', '_EventHubEventiothub_metadata', '_EventHubEventoffset', '_EventHubEventpartition_key', '_EventHubEventsequence_number', 'abstractmethods', 'class', 'delattr', 'dict', 'dir', 'doc', 'eq', 'format', 'ge', 'getattribute', 'gt', 'hash', 'init', 'init_subclass', 'le', 'lt', 'module', 'ne', 'new', 'reduce', 'reduce_ex', 'repr', 'setattr', 'sizeof', 'slots', 'str', 'subclasshook', 'weakref_', '_abc_impl', 'enqueued_time', 'get_body', 'iothub_metadata', 'offset', 'partition_key', 'sequence_number']

Which does not show application_properties anywhere.

---

@chunyu3 commented on [Mon Jun 22 2020](https://github.com/Azure/azure-sdk-for-python/issues/12135#issuecomment-647410362)

The package azure.functions is not mgmt, seems it is data-plan. Add service team to look at it. thanks.

**Comment by Hazhzeng** [comment]
Hi @Imazuel,

Thanks for reporting this issue. I've already made a PR to expose the **metadata** field in eventhub and service bus: https://github.com/Azure/azure-functions-python-library/pull/61

Currently, we're waiting for a deployment.

Thanks,
Roger

**Comment by anirudhgarg** [comment]
These properties have been added.  Please try. Closing this out.
