### ISSUE TITLE
Moving Linux Consumption runtime cwd to /home/site/wwwroot

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-functions-python-worker#700]
### Background
Since many customers reporting the current working directory (cwd) is not pointing to Functions Project root folder based on their assumption, we decide to change the function runtime current working directory to **/home/site/wwwroot** (previously, the cwd is set to a random location **/tmp/functions/standby/wwwroot** in **Linux Consumption** plan).

This change is shipped with Python worker release [1.0.4](https://github.com/Azure/azure-functions-python-worker/releases/tag/1.0.4) and deployed to production on June 21, 2020.

### Rational
We want to ease the process for developers to refer files from their code.
Say we have a simple Azure Functions project which has the following folder structure.
```
├───FileTrigger
│       function.json
│       __init__.py
│
├───static
|       content.txt
│   host.json
│   requirements.txt
```
Previously, to get the file **./static/content.txt** from the code **\_\_init\_\_.py**, our developers need to resolve the current path manually:
```python
def main(req: func.HttpRequest) -> func.HttpResponse:
    trigger_path = os.path.abspath(os.path.dirname(__file__))
    file_path = os.path.join(trigger_path, '..', 'static', 'content.txt')
    with open(file_path, "r") as f:
        file_content = f.readline()
```
Now we introduce a new way to do file IO. As we fix the cwd and point to **/home/site/wwwroot**, our customer can assume the cwd is the project root, which makes the code much cleaner:
```python
def main(req: func.HttpRequest) -> func.HttpResponse:
    file_path = './static/content.txt'
    with open(file_path, "r") as f:
        file_content = f.readline()
```

### Note
This change will not break the old file reference method. However, it may affect some customers running on **Linux Consumption**, since **/home/site/wwwroot** is **read-only**. If your function app attempts to write content into cwd, or derive path based on cwd, this change may break your code.

Since the file system in Linux Consumption plan is not persistent, we highly recommend writing temporary files into **/tmp** folder. To store persistent file in Linux Consumption plan, please refer to [BYO storage on Linux Consumption](https://github.com/Azure/Azure-Functions/wiki/Bring-your-own-storage-(Linux-consumption)).

If you're facing file system issues or want to temporarily opt-out this fix, please set **PYTHON_ROLLBACK_CWD_PATH = 1** in your app setting. We will keep supporting this rollback flag till the end of September 25, 2020. Since then, we will move all customers onto the new cwd path.

Please leave comments if you have any questions about this change, thanks.

**Comment by priyaananthasankar** [comment]
This is a good  change. For eg: while referencing to a TF model in the samples, I had to do the os.path.join and it also is a good approach to do relative path references. Also would be great to document this in the wiki.

**Comment by anilvemula0** [comment]
Hello,
By making /home/site/wwwroot read-only, python package nimbusml is giving Function not implemented exception. Im posting the error for clear understanding. I'd set PYTHON_ROLLBACK_CWD_PATH = 1 but it still not helping me. I think while initiating the function nimbusml is trying to write something to the location it installed and its giving OSError.

Result: Failure Exception: OSError: [Errno 38] Function not implemented: '/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/nimbusml/internal/libs/pybridge.so' Stack: File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 259, in _handle__function_load_request func_request.metadata.entry_point) File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 29, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/loader.py", line 73, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 994, in _gcd_import File "<frozen importlib._bootstrap>", line 971, in _find_and_load File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "<frozen importlib._bootstrap>", line 994, in _gcd_import File "<frozen importlib._bootstrap>", line 971, in _find_and_load File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 665, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 678, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/home/site/wwwroot/observational/__init__.py", line 7, in <module> from nimbusml import Pipeline, FileDataStream File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/nimbusml/__init__.py", line 33, in <module> os.chmod(dotso, 0o755)
![image](https://user-images.githubusercontent.com/51697552/86463047-62bcee80-bd4a-11ea-8f4a-5bf26f52562c.png)

**Comment by benvermeersch** [comment]
> Hello,
> By making /home/site/wwwroot read-only, python package nimbusml is giving Function not implemented exception. Im posting the error for clear understanding. I'd set PYTHON_ROLLBACK_CWD_PATH = 1 but it still not helping me. I think while initiating the function nimbusml is trying to write something to the location it installed and its giving OSError.
> 
> ```
> Result: Failure Exception: OSError: [Errno 38] Function not implemented: '/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/nimbusml/internal/libs/pybridge.so' Stack: 
> File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 259, in _handle__function_load_request func_request.metadata.entry_point) 
> File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 29, in call return func(*args, **kwargs) 
> File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/loader.py", line 73, in load_function mod = importlib.import_module(fullmodname) 
> File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) 
> File "<frozen importlib._bootstrap>", line 994, in _gcd_import 
> File "<frozen importlib._bootstrap>", line 971, in _find_and_load 
> File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked 
> File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed 
> File "<frozen importlib._bootstrap>", line 994, in _gcd_import 
> File "<frozen importlib._bootstrap>", line 971, in _find_and_load 
> File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked 
> File "<frozen importlib._bootstrap>", line 665, in _load_unlocked 
> File "<frozen importlib._bootstrap_external>", line 678, in exec_module 
> File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed 
> File "/home/site/wwwroot/observational/__init__.py", line 7, in <module> from nimbusml import Pipeline, FileDataStream 
> File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/nimbusml/__init__.py", line 33, in <module> os.chmod(dotso, 0o755)
> ```
> 
> ![image](https://user-images.githubusercontent.com/51697552/86463047-62bcee80-bd4a-11ea-8f4a-5bf26f52562c.png)

@anilvemula0 we seem to have the same issue, caused by the nimbusml library to chmod a file. Did you manage to resolve this eventually?

Long story short: we're trying to unpickle a model using NimbusML which tries to chmod pybridge.so (as per the source code: https://github.com/microsoft/NimbusML/blob/master/src/python/nimbusml/__init__.py), which is giving errors because of the /home/site/wwwroot folder being readonly.
