### ISSUE TITLE
[Improvement] Adding types to function/method parameters to help with static analysis

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-python-worker#704]
###### Please provide the following:

**Comment by Hazhzeng** [comment]
Thanks Varad, this is related to the bug in PR https://github.com/Azure/azure-functions-python-worker/pull/632, setting the GRPC message to None, which limits the GRPC message size to (4MB).

Also, @Hazhzeng remember to add an E2E test scenario to test a large blob scenario (100MB).
