### ISSUE TITLE
Document Linux/Windows consumption plan max worker instance limits

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#711]
Can the linux worker instances for consumption plan and its limits be documented? For eg: I heard adhoc that the worker instance limit is 50 and it might also be throttled depending upon spike data for a specific region.

When a customer is scaling their app using Linux consumption plan vs Windows, and if they notice considerable difference between both with instance limits while scaling, we frequently field a question as to what are the limits for Linux consumption and why it is less etc.

Documenting this in a wiki (as this seems subject to change a lot) would setup some expectations.

**Comment by vrdmr** [comment]
Resolved by Flex Consumption limits.
