### ISSUE TITLE
Implement WorkerHeartbeat

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#712]
Implement WorkerHeartbeat defined here: https://github.com/Azure/azure-functions-language-worker-protobuf/blob/dev/src/proto/FunctionRpc.proto#L136

This can be a simple log message that worker sends every 10secs.

This will help during CRI analysis. As of now it is not possible to figure out health of the worker until we see crash logs.

**Comment by pragnagopa** [comment]
@Hazhzeng - Lets discuss offline what is the best way to implement this. Ideally, this would run on a dedicated thread to ensure hearts beats are sent even when an invocation is in progress.

**Comment by vrdmr** [comment]
Currently - the status proto implementation works as the worker heartbeat currently. We'll figure out to implement this in the future later. Putting this as an internal discussion point to look at.
