### ISSUE TITLE
Unable to use python-ldap module in Python function

### ISSUE THREAD

**Issue by nerdicwalker** [Azure/azure-functions-python-worker#718]
Publishing an Python Azure function with python-ldap=='any version' in the requirements.txt gives this error:  

    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.3.1 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/opt/python/3.6.10/include/python3.6m -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.6/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:3:0:
    Modules/common.h:15:18: fatal error: lber.h: No such file or directory
     #include <lber.h>
                      ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/python/3.6.10/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qj9wtbk4/python-ldap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qj9wtbk4/python-ldap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ai2o64pj/install-record.txt --single-version-externally-managed --home /tmp/pip-target-exktg8na --compile --install-headers /tmp/pip-target-exktg8na/include/python/python-ldap Check the logs for full command output.

command issued: func azure functionapp publish function-app-name

with func azure functionapp publish function-app-name --build-native-deps --additional-packages "libldap2-dev libsasl2-dev python3-dev" the build is successful, but using the python-ldap module results in an error:
" Result: Failure Exception: ModuleNotFoundError: No module named '_ldap ''

**Comment by anthonychu** [comment]
Transferring issue to Python Worker repo to see if we can add these dependencies in our images.

**Comment by nerdicwalker** [comment]
@anthonychu if I use northeurope (instead of westeurope) the module python-ldap works just fine after building with the --build-native-deps --additional-packages "libldap2-dev libsasl2-dev python3-dev" parameters.

**Comment by stefanushinardi** [comment]
Due to inactivity, closing this. Please open again if the issue still persists

**Comment by epiczain1234** [comment]
try:
ARCHFLAGS="-arch x86_64" pip3 install python-ldap
