### ISSUE TITLE
Move ping test queue_functions to top dir

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#72]
[Ping](https://github.com/Azure/azure-functions-python-worker/tree/dev/tests/queue_functions/ping) test is generic not related to queues. Move to [tests](https://github.com/Azure/azure-functions-python-worker/tree/dev/tests) dir

**Comment by 1st1** [comment]
That's not possible to do, as it has to be with all other functions that the WebHost loads *at the same directory level*.

**Comment by 1st1** [comment]
Closing this one for now.
