### ISSUE TITLE
[BUG] Wrong encoding when reading binary data from Azure blob storage

### ISSUE THREAD

**Issue by shwars** [Azure/azure-functions-python-worker#720]
It is not possible to correctly read binary data from bound Azure Blob Storage in Python Azure Function when debugging locally. This issue is also described here: https://github.com/Azure/azure-functions-host/issues/4374. Looks like the problem is related to incorrect utf-8 decoding of binary data.

###### Please provide the following:

- Core Tools version: 3.0.2630, 2.7.2628 (tested in both)

###### Provide the steps required to reproduce the problem:

1. Bound Azure Function to input blob parameter b_in
2. Specify the parameter to the function as  `b_in: func.InputStream`
3. Get binary data as `binary = b_in.read()`

###### Provide a description of the expected behavior.

Binary data should directly correspond to the data in the blob storage

###### Provide a description of the actual behavior observed.

Binary data is wrong. In my case, first bytes in the binary file were 80 04 95 78 19 01 00 00 ... (in hex), and bytes obtained in `binary` variable are EF BF BD 04 EF BF BD 19 01 00 00 ... - note that they start with unicode replacement character (which means that most probably UTF-8 decoding took place).

###### Provide a description of any known workarounds.

One can store the data in base64 encoding, but that would unnecessarily complicate the code.

###### Provide the requirements.txt file to help us find out module related issues.

azure-functions
pandas>=1.0.3
matplotlib
scipy
numpy

###### Provide any related information

<details>
<summary>Code</summary>

**`function.json`**

```json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    },
    {
      "type": "blob",
      "direction": "in",
      "name": "covblob",
      "path": "snapshot/current",
      "connection": "e2estore_STORAGE"
    }
  ]
}
```

**`__init__.py`**
```python
import logging
import pandas as pd
import pickle
import azure.functions as func


def main(req: func.HttpRequest, covblob: func.InputStream) -> func.HttpResponse:

    country = req.params.get('country') or 'Russia'

    logging.info('covidata function triggered with country={} and blob with len={}'.format(country,covblob.length))

    binary = covblob.read()
    logging.info("binary is {}, len={}".format(binary[:15],len(binary)))

    data = pickle.loads(binary)
    
    df = data[country]

    res = df.to_csv()

    return func.HttpResponse(res,status=200)
```

</details>

**Comment by stefanushinardi** [comment]
@shwars could you link a sample file you were trying to load?

I tried to replicate with the code below, but was not able to repro the error you were getting

<details>
<summary>Code</summary>

**`function.json`**

```json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "myblob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "sample-workitems/{name}",
      "connection": "AzureWebJobsStorage"
    }
  ]
}

```

**`__init__.py`**
```python
import logging
import pickle
import azure.functions as func


def main(myblob: func.InputStream) :
    p = myblob.read()
    dict = pickle.loads(p)
    logging.info(dict)    
```

</details>

P.S: I generated pickled file of a a dictionary and pickled it. The pickle file was then uploaded to storage emulator GUI. 


Thanks!

**Comment by shwars** [comment]
@stefanushinardi the pickle file that I used is available here: https://1drv.ms/u/s!AlIe5IxDja83lGQhcvzKd-9518qz?e=KlClrQ, but I think the essence of the problem is with incorrect reading of any binary file (any binary is treated as UTF-8 encoding, and invalid characters are escaped/replaced by 0xEFBF sequence).

**Comment by stefanushinardi** [comment]
@shwars I see. @vrdmr and I did some verification on our side on loading binary and comparing the values from local python env and functions setup, but was not able to repro the issue.

What was the error that you encountered while executing the script you embedded? 

On my side, I was able to load the pickle file that you pasted as well as getting the country key, However, I was receiving a tuple object. The first entry is a float and the second entry is a df. Your particular script seems to throw an error if I tried to invoke ``` .to_csv()``` from the tuple.  


Regardless, I verified both in functions setup using local emulator and local python env loading from local file system were able to load the map. Both shape and values that I checked seems to match in these environment

**Comment by shwars** [comment]
@stefanushinardi @vrdmr - if you were able to get the tuple, it means that you have not experienced the error. I was getting an error when doing pickle.loads. I have never tried it with local storage emulator, I was using real azure storage. I will try to set up a sample azure function in the cloud and share with you.

**Comment by shwars** [comment]
I wrote two azure functions - one to generate storage file with all bytes from 0x00 to 0xFF, and another one - to read it. The one that writes the blob works with not problem, but when I read the file - here is what I get after doing
```python
blb = inblb.read()
res = blb.hex()
logging.info("Got from storage:\n"+res)
```
```
Got from storage:
000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7fefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbd
```
Both azure functions are in the ZIP archive here: https://1drv.ms/u/s!AlIe5IxDja83lGUaMH8PJDaVB6ro?e=WB7467. The error happens BOTH when running the function locally, and when deployed to Azure. Let's get in touch in Teams if having direct access to resource group with the function would be of any help.

**Comment by stefanushinardi** [comment]
@shwars. @vrdmr  and ! took your code and try to repro it. 

What we are seeing is that if we compare the string representation of the bytes(i.e. ```print(str(binary))```), we get:

```
Python HTTP trigger function processed a request.
b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff'
Got from storage:
b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff'
```

And we decode it to be hex string(i.e. ```print(binary.hex())```), we get:
```
Python HTTP trigger function processed a request.
000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
Got from storage:
000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff
```

In both cases, we do not see any issue in writing and reading binary to storage via Azure functions. Therefore, I am closing the issue and feel free to open it again if you think that the issue still persists on your side.

Thanks!

**Comment by shwars** [comment]
It is important to specify "dataType": "binary" parameter in `function.json` binding to avoid this. If the `dataType` is not specified - string is assumed, and the extra encoding step to utf-8 happens.

**Comment by anthonychu** [comment]
Might be an opportunity to add some docs on the data type property or increase visibility if it already exists. @ggailey777

**Comment by shwars** [comment]
> Might be an opportunity to add some docs on the data type property or increase visibility if it already exists. @ggailey777

I will propose some additions to [this doc](https://docs.microsoft.com/en-US/azure/azure-functions/functions-bindings-storage-blob-input?tabs=python) (which was the first one I came across when looking for details), once we have a bit more clarity on [another issue](https://github.com/Azure/azure-functions-python-worker/issues/740) with Python parameter typing. @stefanushinardi  also suggested [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#trigger-and-binding-definitions) where `dataType` is described, but it was not easily discoverable for me.
