### ISSUE TITLE
OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by barakVaturi** [Azure/azure-functions-python-worker#722]
hello,

I'm trying to create a file in Azure function APP python (3.6.8) 
I create the file in the code:

f= open(upload_file_path, mode='wb+', buffering=1)

where: upload_file_path = os.path.join(local_path, fileName)

and trying to upload it to a blobstorage:
with open(upload_file_path,'rb') as data:
        blob_client.upload_blob(data)

then the error  OSError: [Errno 30] Read-only file system jumps

thank you

**Comment by AnatoliB** [comment]
@barakVaturi What is in the `local_path` variable? Please note that many directories on Azure Functions are read-only. Here is the recommended way to create temporary files: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#temporary-files.

**Comment by barakVaturi** [comment]
the local path:
 local_path = str(pathlib.Path(__file__).parent) 

im using pathlib.

sorry i thought i uploaded it

**Comment by AnatoliB** [comment]
@barakVaturi What is in `file`? If this is the location of the file that contains the currently running code, this location is indeed read-only on Azure. Please use the `/tmp` directory instead (see the doc link in my previous comment).
