### ISSUE TITLE
Python worker throws ERROR: no currently running Dispatcher is found,AttributeError: 'EnumTypeWrapper' object has no attribute 'System'

### ISSUE THREAD

**Issue by divyagandhii** [Azure/azure-functions-python-worker#729]
Fixes the rest of the dispatcher not found issue.
Azure Functions Python Worker is using a Protobuf version of 3.12
Customer could break our worker code by brining a Protobuf package < 3.8.0
Issue Protobuf < 3.8.0: protocolbuffers/protobuf#6028
Fix released Protobuf >= 3.8.0: protocolbuffers/protobuf@0de6577
image
![image](https://user-images.githubusercontent.com/44176589/88230268-efaae780-cc26-11ea-993c-8589b6a6289e.png)

We should use the backward compatible syntax in worker RpcLogCategory.

Tracking issue for rollout for fix of https://github.com/Azure/azure-functions-python-worker/pull/725

@Hazhzeng please keep on updating this issue as the fix for this rolls out.

**Comment by divyagandhii** [comment]
Please use this tracking issue to decide when you can revert the linuxfxversion back to "python|<version>" format and remove the pinned image.

**Comment by Hazhzeng** [comment]
Currently we're in the no fly zone, will release the new Python images once no fly is lifted. Once the new image is deployed to all regions, I will update this thread. Thanks for your patience.

**Comment by Hazhzeng** [comment]
This issue is fixed and a new announcement is made
https://github.com/Azure/app-service-announcements/issues/287
