### ISSUE TITLE
Documentation on Deploying Python functions to Premium

### ISSUE THREAD

**Issue by atjohns2** [Azure/azure-functions-python-worker#730]
I'm attempting to deploy our Azure Python functions onto Premium for performance/runtime reasons but I'm unable to get it working.

I've followed the guidelines here: https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package but they seem mostly related to Windows. 

I have tried..
- Deploying through our existing pipeline which was already utilizing WEBSITE_RUN_FROM_PACKAGE = true. This pipeline still deploys successfully to our Consumption plan.
- Manually changing the WEBSITE_RUN_FROM_PACKAGE value to the blob storage location of the package. 
- Deploying using the Azure CLI command 'func azure functionapp publish'

Regardless when I go to my functions I see this...
![image](https://user-images.githubusercontent.com/4114777/88289805-cab88200-ccc3-11ea-8f8f-1f95b26823c6.png)

Which routes me to the documentation I referenced above. Is there any other documentation to deploying these, or something obvious I'm missing?

**Comment by balag0** [comment]
Can you check if the app has these 2 app settings
https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentazurefileconnectionstring

WEBSITE_CONTENTSHARE
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING

If you can share the app name I can also verify the config. (https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by atjohns2** [comment]
I was able to resolve my issues by deploying to EastUS instead of EastUS2. There must have been some sort of support feature missing for this in EastUS2.
