### ISSUE TITLE
[BUG] Function is sometimes executed in incorrect worker

### ISSUE THREAD

**Issue by cgearing** [Azure/azure-functions-python-worker#732]
- Timestamp: 2020-08-05 09:21:30.663
- Function App name: cost-modelling-cg
- Function name(s) (as appropriate): CostModelling
- Core Tools version: 2.7.1948

### Repro steps

Step 1. Create a function app using Python 3.6 and install dependencies either using a venv or directly to site packages. 
Step 2. Deploy the function.

### Expected behavior

I would expect the function to work correctly.

### Actual behavior

We occasionally get 500 responses and the logs indicate an import error.  Interestingly, the stack trace for the 500 indicates the function is being run by the Python 3.7 worker, not 3.6, which would definitely break things!

```
/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 266, in _handle__function_load_request func_request.metadata.entry_point) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 34, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 32, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/loader.py", line 76, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/CostModelling/__init__.py", line 7, in <module> from .cost_modelling.config import cost_modelling_controller File "/home/site/wwwroot/CostModelling/cost_modelling/config.py", line 1, in <module> from .controller import CostModellingController File "/home/site/wwwroot/CostModelling/cost_modelling/controller.py", line 3, in <module> import attr
```

Is it possible for a python function to be run by the incorrect worker runtime, since this seems to be what is causing us this problem.

**Comment by balag0** [comment]
Looking into this. Will update my investigation results soon.

**Comment by balag0** [comment]
Looks like the scale unit this particular app is in is struggling with capacity which sometimes leads to the app landing on wrong worker. We are taking steps to prevent this from happening and you should start seeing the improvements in the next couple of days. Apologize for the inconvienence.

**Comment by balag0** [comment]
This should be fixed now. Please open an issue if you are continuing to see this failure.
