### ISSUE TITLE
[Errno 30] Read-only file system when using azureml.core.dataset

### ISSUE THREAD

**Issue by bszewczyk** [Azure/azure-functions-python-worker#733]
Im trying to run this code in Azure Functions:

from azureml.core.dataset import Dataset

dataset= Dataset.Tabular.from_delimited_files(path=ds.path('mypath')) 

but getting error:

_[Errno 30] Read-only file system: '/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/dotnetcore2/bin/deps.lock'_

When I run it locally it works fine, only when published in azure functions.

**Comment by veyu** [comment]
@bszewczyk Do you use Linux consumption plan as well?

I am getting exactly the same error. I suspect it could be problem with using Linux consumption plan as it does not support editing functions in Azure portal - so this could be global *read-only constraint* on filesystem that also prevents `dotnetcore2` module from creating lock file.

I am using Linux consumption`Y1` plan, functions extension `~3` with `Python 3.6`.
Function is deployed using `func azure functionapp publish <dir>` command.

Executed code:
```python
# blob container is properly registered in datastore
blob_datastore = Datastore.get(ws, blob_datastore_name)
datastore_paths = [(blob_datastore, 'cf_2020-08-07/train_dataset.csv')]
train_dataset = Dataset.Tabular.from_delimited_files(path=datastore_paths)
```

Whole traceback:
```
Result: Failure
Exception: OSError: [Errno 30] Read-only file system: '/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/dotnetcore2/bin/deps.lock'
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 345, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 480, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/QueueTrigger/__init__.py", line 74, in main
    train_dataset = Dataset.Tabular.from_delimited_files(path=datastore_paths)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/data/_loggerfactory.py", line 126, in wrapper
    return func(*args, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/data/dataset_factory.py", line 311, in from_delimited_files
    quoting=support_multi_line)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/dataprep/api/readers.py", line 100, in read_csv
    df = Dataflow._path_to_get_files_block(path, archive_options)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/dataprep/api/dataflow.py", line 2407, in _path_to_get_files_block
    return datastore_to_dataflow(path)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/dataprep/api/_datastore_helper.py", line 41, in datastore_to_dataflow
    datastore, datastore_value = get_datastore_value(source)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/dataprep/api/_datastore_helper.py", line 83, in get_datastore_value
    _set_auth_type(workspace)
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/dataprep/api/_datastore_helper.py", line 134, in _set_auth_type
    get_engine_api().set_aml_auth(SetAmlAuthMessageArgument(AuthType.SERVICEPRINCIPAL, json.dumps(auth)))
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/api.py", line 18, in get_engine_api
    _engine_api = EngineAPI()
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/api.py", line 55, in __init__
    self._message_channel = launch_engine()
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/engine.py", line 300, in launch_engine
    dependencies_path = runtime.ensure_dependencies()
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/dotnetcore2/runtime.py", line 141, in ensure_dependencies
    with _FileLock(deps_lock_path, raise_on_timeout=timeout_exception):
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/dotnetcore2/runtime.py", line 113, in __enter__
    self.acquire()
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/dotnetcore2/runtime.py", line 72, in acquire
    self.lockfile = os.open(self.lockfile_path, os.O_CREAT | os.O_EXCL | os.O_RDWR)
```

In my case `requirements.txt` looks like:
```
azure-functions                                                                                                                             
azureml-core                                                                                                                                
azureml-dataprep                                                                                                                            
azureml-defaults                                                                                                                            
msrest  
```

**Comment by tot0** [comment]
Hi,
`dotnetcore2` requires write permission to the Python environment it's installed in *if* there are .NET Core 2.1 dependencies missing from the system. This is the case for Debian 10 by default (which is the Linux distro the Azure Functions Python Docker images are based on).
One way to work around this would be to install the missing dependencies in a Dockerfile based off of the one being use by Azure Functions, e.g.
```docker
FROM mcr.microsoft.com/azure-functions/python:3.0-python3.6
RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb & dpkg -i packages-microsoft-prod.deb
RUN sudo apt-get install -y dotnet-runtime-2.1
```
These command are taken from [this documentation](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-10-) regarding .NET Core usage on Linux systems.

After building the Dockerfile and publishing it to a public registry you should then be able to use it following the instructions [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-python#create-and-configure-a-function-app-on-azure-with-the-image).

**Comment by veyu** [comment]
@tot0 Thanks for answer. Does it mean that I would need to create dockerized functions (Docker image with my code inside) and then us it as Function App?
I am not sure if there is possibility to create custom Docker image like you described above and use it as runtime environment but have function's code deployed separately?

I found it rather upsetting that I cannot use official Azure ML library with compute possibilities which Azure Functions are providing.

**Comment by tot0** [comment]
@veyu Yea it really should work and I’m sorry it doesn’t. We are working on improvements to the dotnetcore2 package such that it would be able to install the dependencies itself in Azure Functions.
Could you explain to me how you currently deploy your code?

**Comment by bszewczyk** [comment]
I tried solution which @tot0 discribed but I don't understand what I should really do.

@veyu what do you mean by:

 "_I switched to creating Docker container - Dockerfile is based on file created by Azure Functions Core Tools with changes which you suggested_."

Should I use some ready dockerfile? How do I get it?

**Comment by tot0** [comment]
@veyu I have tested the `dotnetcore2` package after running the commands you ran and it doesn't find any missing dependencies, so I think the Debian 9 mentions are fine. Were you able to deploy your Azure Functions code on top of this image?

@bszewczyk This revised Dockerfile (revised from the one I posed above) will install .NET Core 2.1 runtime on top of the Azure Functions Python Worker base Docker image:
```dockerfile
FROM mcr.microsoft.com/azure-functions/python:3.0-python3.6
RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get install -y dotnet-runtime-2.1
```

**Comment by bszewczyk** [comment]
Hi, 

thank you for your help. I managed to create function app with Docker by using this tutorial:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-python

And to dockerfile I added lines you suggested. 

Is there any chance to improve azure functions to use auto ml without docker image? To use docker image I need to use premium plan and it costs at least 120 euro/month so it gets really expensive.

**Comment by bszewczyk** [comment]
But I think that is not end of my story

@veyu did your auto ml run wen fine by using docker? Do you use datastore to upload data for predictions?
On line
 training_data_set = Dataset.Tabular.from_delimited_files(path=ds.path('toplinedata/training_data.csv'))

I'm getting error:
Error message Engine process terminated. This is most likely due to system running out of memory. Please retry with increased memory. |session_id=dc17e670-a20f-4dd3-9012-615321367006

I tried to scale up my plan but it didn't help

**Comment by bszewczyk** [comment]
My files have 1 and 2 KB, so they are really small

**Comment by tot0** [comment]
@bszewczyk How large is `training_data.csv`? I'm not familiar with the resource constraints placed on Azure Functions Workers but I could see them being restrictive if the standard use use is to just execute some simple control plane logic.

If you are trying to create a TabularDataset for subsequent submission to an AutoML run you can try passing the `validate=False` parameter to `from_delimited_files`. By default most methods on `Dataset.Tabular` will 'verify' that the given path is valid and the data can be read. This check can be disabled with the `validate=False` flag.

**Comment by bszewczyk** [comment]
@tot0 I changed validate=False but it doesn't help. My file has only 4KB

**Comment by veyu** [comment]
@tot0 @bszewczyk Apologies for late replies - I was on vacation.

> @veyu what do you mean by:
> "_I switched to creating Docker container - Dockerfile is based on file created by Azure Functions Core Tools with changes which you suggested_."
> 
> Should I use some ready dockerfile? How do I get it?

You have probably figured it out already but I used Dockerfile generated by:
```
func init LocalFunctionsProject --worker-runtime python --docker
```

This is my Dockerfile:
```dockerfile
FROM mcr.microsoft.com/azure-functions/python:3.0-python3.6 

RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get install -y dotnet-runtime-2.1 

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \ 
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true 

COPY requirements.txt /
RUN pip install -r /requirements.txt
 
COPY . /home/site/wwwroot
```

@tot0 I am unable to run my code. When I try to run it I get the same error as @bszewczyk (https://github.com/Azure/azure-functions-python-worker/issues/733#issuecomment-680898148). I also use very small data - around 20kB file and I am using B1 plan (1.75 GB of memory) which should be enough.
```
Exception: MemoryError: Engine process terminated. This is most likely due to system running out of memory. Please retry with increased memory. |session_id=l_a85b87d9-c2c5-414e-9a45-61c6f0874478
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 345, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 480, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/QueueTrigger/__init__.py", line 75, in main
    train_dataset = Dataset.Tabular.from_delimited_files(path=datastore_paths, validate=False)
  File "/usr/local/lib/python3.6/site-packages/azureml/data/_loggerfactory.py", line 126, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azureml/data/dataset_factory.py", line 315, in from_delimited_files
    validate or infer_column_types or _is_inference_required(set_column_types))
  File "/usr/local/lib/python3.6/site-packages/azureml/data/dataset_factory.py", line 771, in _transform_and_validate
    _validate_has_data(dataflow, 'Cannot load any data from the specified path. '
  File "/usr/local/lib/python3.6/site-packages/azureml/data/dataset_error_handling.py", line 65, in _validate_has_data
    dataflow.verify_has_data()
  File "/usr/local/lib/python3.6/site-packages/azureml/dataprep/api/_loggerfactory.py", line 179, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azureml/dataprep/api/dataflow.py", line 804, in verify_has_data
    if len(self.take(1)._to_pyrecords()) == 0:
  File "/usr/local/lib/python3.6/site-packages/azureml/dataprep/api/dataflow.py", line 720, in _to_pyrecords
    self._raise_if_missing_secrets()
  File "/usr/local/lib/python3.6/site-packages/azureml/dataprep/api/dataflow.py", line 2460, in _raise_if_missing_secrets
    missing_secrets = set(self.get_missing_secrets())
  File "/usr/local/lib/python3.6/site-packages/azureml/dataprep/api/dataflow.py", line 2238, in get_missing_secrets
    secrets = self._engine_api.get_secrets(GetSecretsMessageArguments(steps_to_block_datas(self._steps)))
  File "/usr/local/lib/python3.6/site-packages/azureml/dataprep/api/_aml_helper.py", line 38, in wrapper
    return send_message_func(op_code, message, cancellation_token)
  File "/usr/local/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/api.py", line 170, in get_secrets
    response = self._message_channel.send_message('Engine.GetSecrets', message_args, cancellation_token)
  File "/usr/local/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/engine.py", line 180, in send_message
    response = self._read_response()
  File "/usr/local/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/engine.py", line 142, in _read_response
    raise error
```

**Comment by tot0** [comment]
@veyu @bszewczyk Apologies for not responding until now. The memory error you were seeing was due to a libssl issue with .NET Core 2.1 on Debian 9.
This issue has been fixed in `dotnetcore2==2.1.16` and installing this new version (along with using the Dockerfile that installs the .NET Core 2.1 runtime dependencies) shoudl enable Datasets usage.

**Comment by bszewczyk** [comment]
@tot0  could you tell me how I can add dotnetcore2==2.1.16 to my Dockerfile? 

My Dockerfile looks like:
```

FROM mcr.microsoft.com/azure-functions/python:3.0-python3.6

RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get install -y dotnet-runtime-2.1
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

RUN python -m pip install --upgrade pip

COPY requirements.txt /
RUN pip install -r /requirements.txt

COPY . /home/site/wwwroot
```

**Comment by tot0** [comment]
@bszewczyk I believe you will need to add `dotnetcore2>=2.1.16` to your requirements.txt which is being used on these lines:
```
COPY requirements.txt /
RUN pip install -r /requirements.txt
```

What does it look like right now?

Cheers,
Lucas

**Comment by bszewczyk** [comment]
I added 
`RUN apt-get update`
To my dockerfile and it worked

**Comment by tot0** [comment]
@bszewczyk That is likely because changing your Dockerfiles contents caused the image to rebuild and not use cached layers.
Re-installing `azureml-dataset-runtime` after `dotnetcore2==2.1.16` was released will have picked up this new version that has the fixes to avoid the OOM error.
Glad it's working!

**Comment by tot0** [comment]
@veyu Were you able to try building your container again?

**Comment by veyu** [comment]
@tot0 No, I didn't tried it. I was not sure how long solving this would take so I shifted my solution toward running AML related code in DevOps pipeline, which worked without any problems.
As I was able to mitigate this problem, I moved to another things. I won't have time to test it as reworking current solution is very low on my priority list - sorry.

**Comment by tot0** [comment]
Closing the loop here, `dotnetcore2==2.1.17` was released yesterday and adds support for Debian 10 as well as using a temp directory for downloading required dependencies.
This means that no special `apt` install instructions should be required for Azure Functions Docker images (as they are Debian 10 based) to have AzureML Datasets work as expected.

**Comment by Kapkan-Lesion** [comment]
@tot0 Thank you for the explanation, was wondering what are the steps I may need to do if I am attempting to deploy a similar AML azure function to Linux (plan can be consumption or premium)?

Is Docker necessary for this? Or should I just add dotnetcore2==2.1.17 to my requirements.txt and be done with it?

**Comment by Hazhzeng** [comment]
Hi @bszewczyk, the Linux Consumption plan is on a read-only file system and it does not allow you to change the content after it deploys. Your function app will be deployed as a .zip file and it will be mounted directly onto `/home/site/wwwroot`. Azure Functions assume customer's code is stateless, because we may create a new instance for you when your function is invoked.
Please refer to https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices#write-functions-to-be-stateless for more information.

I'm closing this issue now.

**Comment by balag0** [comment]
Just to add to @Hazhzeng other paths inside the container are writeable. Ex: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#temporary-files

But files under /home/site/wwwroot are readonly.

**Comment by joelwetzel** [comment]
> @tot0 Thank you for the explanation, was wondering what are the steps I may need to do (Post-fix) if I am attempting to deploy a similar AML azure function to Linux (plan can be consumption or premium)?
> 
> Is Docker necessary for this? Or should I just add dotnetcore2==2.1.17 to my requirements.txt and be done with it?

Did you ever figure out an answer to this?  Do we have to use docker?  Thanks!
