### ISSUE TITLE
[BUG] async functions are not being invoked in parallel

### ISSUE THREAD

**Issue by gohar94** [Azure/azure-functions-python-worker#734]
###### Please provide the following:

- Timestamp: 10:08 PM August 7, 2020 (UTC)
- Function App name: 
- Function name(s) (as appropriate):
- Core Tools version:

###### Provide the steps required to reproduce the problem:

Run two invocations of the HTTP triggered function provided below in parallel (at the same time.)

###### Provide a description of the expected behavior.

When I invoke the above function twice at the same time, I expect both invocations to finish at the same time.

###### Provide a description of the actual behavior observed.

The start and end times reported by the function show that the second invocation is being processed after the first one finished (i.e. after the sleep has finished and the first invocation has returned.)

```
azure-functions
azure-storage-blob==12.1.0
```

###### Provide any related information

* Links to source
* Bindings used

<!-- Uncomment this if you want to include your source (wrap it in details to make browsing easier)
<details>
<summary>Source</summary>

```
import asyncio
import json
import datetime
import logging
import time

import azure.functions as func
import azure.functions.blob as blob

async def test_read_write(req: func.HttpRequest) -> func.HttpResponse:
    start_now = str(datetime.datetime.now())
    logging.log(logging.DEBUG, "Running at " + start_now)

    await asyncio.sleep(10)

    end_now = str(datetime.datetime.now())
    logging.log(logging.DEBUG, "Done at " + end_now)

    response_dict = {
        'start': start_now,
        'end': end_now,
        'msg': 'Done'
    }

    response_body = json.dumps(response_dict, indent=2)

    return func.HttpResponse(
            body=response_body,
            mimetype="application/json",
            status_code=200,
        )
```

```txt
azure-functions==1.0.0a4
azure-functions-worker==1.0.0a4
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.11.0
```

</details>

**Comment by gohar94** [comment]
@Hazhzeng As we discussed, here is the issue. You can add more details if you want or let me know what other information I can provide that would be helpful. Thanks a lot.

**Comment by Hazhzeng** [comment]
Really appreciate Gohar looking into the Python dispatcher code and raising the issue to me.
This is a real issue as I discussed and did some experiments with Gohar.

Even when the function app is marked as async, the dispatcher is not picking up the next HTTP request when awaiting.

For example:
```python
import logging
import asyncio
from datetime import datetime
import azure.functions as func

# Async requests are never executed parallelly
async def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    start_time = f'Started At: {datetime.utcnow().isoformat()}'
    await asyncio.sleep(10)  # LONG SLEEP HERE
    end_time = f'Ended At: {datetime.utcnow().isoformat()}'

    return func.HttpResponse(
        f"{start_time} / {end_time}",
        status_code=200
    )
```
When invoking this HTTP trigger 3 times, the Http requests are still handled one after another, resulting 30 seconds of total execution time. What we suppose to see instead, is 3 HTTP requests executed in 10 seconds.

I think what Elvis said when he finishes the project, is to expose the async interface to our customers in `asyncio.get_event_loop()` and `await asyncio.wait()`. However, the dispatcher itself never executes async requests parallelly. (This explains why when Mark Russinovich tested our product, he uses his custom event loop to achieve parallel execution).

```python
import sys
import logging
import asyncio

from datetime import datetime
import azure.functions as func

async def parallelly_log_info():
    await asyncio.sleep(5)
    logging.info('parallelly_log_info at root logger')

async def parallelly_log_warning():
    await asyncio.sleep(5)
    logging.warning('parallelly_log_warning at root logger')

async def parallelly_log_error():
    await asyncio.sleep(5)
    logging.error('parallelly_log_error at root logger')

# Async interface for customer to use await asyncio.wait() for parallel execution inside 1 request
async def main(req: func.HttpRequest) -> func.HttpResponse:
    loop = asyncio.get_event_loop()

    # Create multiple tasks and schedule it into one asyncio.wait blocker
    task_info: asyncio.Task = loop.create_task(parallelly_log_info())
    task_warning: asyncio.Task = loop.create_task(parallelly_log_warning())
    task_error: asyncio.Task = loop.create_task(parallelly_log_error())

    # WaitAll
    await asyncio.wait([task_info, task_warning, task_error])

    return 'Async Parallel Execution Under One Http Call'
```
---
I need to investigate more into this to find out the bottleneck where it prevents running multiple async HTTP requests.
Meanwhile, to mitigate this issue, the customer can increase **FUNCTIONS_WORKER_PROCESS_COUNT** for spawning multiple Python processes.

**Comment by gohar94** [comment]
@Hazhzeng One more thing I noticed is that if you call *different* functions of the same app in parallel, that works fine. So in this case, if you copy the same function and put it as function with a different name and invoke them at the same time, they in fact do get processed in parallel. It's just that the *same* function is not being handled in parallel.

**Comment by Hazhzeng** [comment]
Yeah, I can repro that. If the customer duplicated the same functions into multiple different copies, the invocations between different async functions can go parallel. But as you said, if the request keeps hitting one async function, the requests are handled in sequence.

**Comment by gohar94** [comment]
@Hazhzeng Another interesting finding; if you run the same scenario without the browser (Chrome/Edge) and use `curl`, it works fine even for the *same* functions. 
I tried to do that and set a breakpoint in `HttpThrottleMidleware` [this line](https://github.com/Azure/azure-functions-host/blob/7d275117822cbef82d7ce386bade31beec69232f/src/WebJobs.Script.WebHost/Middleware/HttpThrottleMiddleware.cs#L38) (from `azure-functions-host`) and in the case where I'm invoking from the browser, it doesn't even hit the breakpoint for the second invocation until the first one is finished. But when doing from `curl` it gets hit as soon as the request is invoked and handled properly in parallel all the way through.

**Comment by gohar94** [comment]
@Hazhzeng Apparently this is a thing with Chromium as mentioned [here](https://stackoverflow.com/a/27514611/3132415).

**Comment by Hazhzeng** [comment]
Thanks @gohar94 for the investigation. I will close this issue for now. Please PM me if you have any follow ups.
