### ISSUE TITLE
Logging only works locally, not on portal

### ISSUE THREAD

**Issue by carmclarissa** [Azure/azure-functions-python-worker#736]
###### Please provide the following:

- Timestamp: 22:39 8/14/2020 UTC
- Function App name: caromechangefeed
- Function name(s) (as appropriate): changefeedtrigger
- Core Tools version:

###### Provide the steps required to reproduce the problem:

Test/Run of locally developed azure function on portal

###### Provide a description of the expected behavior.

Upon running on portal, the program should print out a few log statements. 

###### Provide a description of the actual behavior observed.

When running the azure function locally, the log statements are printed out. But, when trying to run the function on portal, the log statements are not printed.

###### Provide the requirements.txt file to help us find out module related issues.

```
azure-functions==1.3.0
azure-storage-blob-changefeed==12.0.0b1
```

###### Provide any related information

Have tried to set to logging.error instead of logging.info, and the portal will print out only the first logging.error statement. With logging.info nothing is printed.

**Comment by Hazhzeng** [comment]
Hi @carmclarissa,

Thanks for raising this issue. I saw your function app is running on Linux Consumption plan. This plan requires Application Insight to propagate the log into portal. Could you confirm if you have Application Insight configured properly? Thanks.

![image](https://user-images.githubusercontent.com/48038149/91889236-5b2e9e80-ec42-11ea-9e7a-bae8a6ad9279.png)

**Comment by carmclarissa** [comment]
Hi there,

Thank you for getting back to me on this issue! I have Application Insights linked to my Function App, but how do I know that it is configured properly?

Best,

Carmen

**Comment by Hazhzeng** [comment]
When making an invocation in your function app, inside the Application Insight -> Live Metrics, it should stream out the your functions logs.
![image](https://user-images.githubusercontent.com/48038149/92022661-75cf4900-ed10-11ea-840f-a2e7bf7395c8.png)
