### ISSUE TITLE
[BUG] Timer trigger with BytesIO initial run succeeds, further runs fail

### ISSUE THREAD

**Issue by Rik-de-Kort** [Azure/azure-functions-python-worker#738]
I have a function that reads a csv from an azure storage account and packs it into a BytesIO object to feed to pandas. Everything related to this runs fine the first time the function is triggered, but all subsequent times, the runtime complains the BytesIO object is empty. I import the BytesIO object from another file, where it is created from the data pulled from the azure storage account.

###### Please provide the following:
- Timestamp: 2020-08-19  08:42
- Function App name: fa-lre-etl-o
- Function name(s) (as appropriate): ETL_timed
- Core Tools version: 3.0.2798

###### Provide the steps required to reproduce the problem:
__init__.py and files.py are included below.
1. Make sure you have an Azure Storage account with a relevant fileshare, and a readable csv is there (I can't share mine due to company policy, unfortunately).
2. Make a timer triggered function, fill in the fileshare details. Put files.py in the top level directory, and replace the contents of __init__.py by the one given below.
3. Run the local environment. It will take a while, but the first run will succeed, and the second (and all subsequent runs) will fail.

###### Provide a description of the expected behavior.
I would expect the function to run the same way every time.

###### Provide a description of the actual behavior observed.
Second and subsequent runs of the function fail with the following error, which points to the BytesIO object being empty (i.e. already having been read).

```python
[19-8-2020 09:22:00] Executed 'Functions.test' (Failed, Id=0b5f2e6e-43c4-4a2e-a60a-0395be7656a3, Duration=65ms)
[19-8-2020 09:22:00] System.Private.CoreLib: Exception while executing function: Functions.test. System.Private.CoreLib: Result: Failure
Exception: EmptyDataError: No columns to parse from file
Stack:   File "C:\choco\lib\azure-functions-core-tools-3\tools\workers\python\3.7\WINDOWS\X64\azure_functions_worker\dispatcher.py", line 345, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "C:\Users\KORR\.conda\envs\lre\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\choco\lib\azure-functions-core-tools-3\tools\workers\python\3.7\WINDOWS\X64\azure_functions_worker\dispatcher.py", line 480, in __run_sync_func
    return func(**params)
  File "J:\af-bug-report\test\__init__.py", line 10, in main
    df = pd.read_csv(SCD, sep=";")
  File "C:\Users\KORR\.conda\envs\lre\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\KORR\.conda\envs\lre\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\KORR\.conda\envs\lre\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Users\KORR\.conda\envs\lre\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\KORR\.conda\envs\lre\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
````

###### Provide a description of any known workarounds.
You can inline obtaining the file. However, as I have six different files and would like to keep all that fileshare IO separate, I donj't think that's a good solution. Alternatively, you can put them in a closure (simply wrap them in lambda) and call it every time you need it. This will force a reload.

###### Provide the requirements.txt file to help us find out module related issues.
```txt
azure-functions
azure-storage-file
pandas
```
### Related information
<details>
<summary>Source</summary>

```python
# files.py
from azure.storage.file import FileService
from io import BytesIO
import os

fs = FileService(account_name="<storage_account_name>",
                 account_key=os.environ["storage_account_key"])


SCD = BytesIO(fs.get_file_to_bytes("<share>", "<folder>", "<file>.csv").content)
```

```python
# __init__.py
import logging

import azure.functions as func
import pandas as pd
from ..files import file


def main(mytimer: func.TimerRequest) -> None:
    logging.info("Trying to get the dataframe")
    df = pd.read_csv(file, sep=";")
    logging.info("Got the dataframe!")
````

```txt
azure-functions
azure-storage-file
pandas
```

</details>

**Comment by Hazhzeng** [comment]
Hi @Rik-de-Kort, thanks for raising the issue and providing the sample and source code.
I don't find file reference in **\_\_init\_\_.py* (`from ..files import file`).

Our Python worker has function_load step and function_invocation step.
The **files.py** will be executed in function_load step since **from ..files import file** is defined in **\_\_init\_\_.py**.

The first argument in pandas read_csv function expects [str, path object or file-like object](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html#pandas-read-csv). I would recommend you download the file to `/tmp/temp_file_name.csv` and use `pd.read_csv('/tmp/temp_file_name.csv')` to read the file and ensure its integrity.

Let me know if you have any questions.
