### ISSUE TITLE
Returning from a function without $return or "out" bindings

### ISSUE THREAD

**Issue by 1st1** [Azure/azure-functions-python-worker#74]
For a function with the following `function.json`:

```json
{
  "scriptFile": "main.py",
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    }
  ]
}
```

and the following implementation:

```python
def main(req):
    return 'OK'
```

The Web Host / Python worker currently return HTTP 204 No Content status. This is confusing, as a user would expect to see an HTTP 200 status with "OK" response.

I propose to raise an error in cases like this and return HTTP 500.

We've discussed an alternative solution of throwing a warning in cases like this before, but I'd really prefer this to be an error. Warnings are frequently ignored by Python users so it's possible that a lot of users will spent a lot of time trying to figure out why they get 204 messages.  Returning an error exposes the problem in a visible and an easily fixable way (and that's how we usually deal with situation like this in Python).

/cc @asavaritayal @christopheranderson @pragnagopa @elprans @brettcannon

**Comment by brettcannon** [comment]
["Errors should never pass silently"](https://www.python.org/dev/peps/pep-0020/) 😁

**Comment by 1st1** [comment]
Closing this one now.
