### ISSUE TITLE
How to post raw json body to the function app?

### ISSUE THREAD

**Issue by ness001** [Azure/azure-functions-python-worker#762]
#### Is your question related to a specific version? If so, please specify:
Found Python version 3.8.5 (python).
Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
Http
#### Question
The post body is like this
![image](https://user-images.githubusercontent.com/5109598/95888200-5cabc480-0db3-11eb-8959-c3b1e02ebf4c.png)
My code is like this:
![image](https://user-images.githubusercontent.com/5109598/95888285-78af6600-0db3-11eb-9e86-af0c2f1d8640.png)
```
def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    description = req.body
    # if not description:
    #     try:
    #         req_body = req.get_json()
    #     except ValueError:
    #         pass
    #     else:
    #         description = req_body.get('description')

    if description:
        return func.HttpResponse(test_availability(description))
    else:
        return func.HttpResponse(
             "This HTTP triggered function executed successfully. Pass a description in the query string or in the request body for a personalized response.",
             status_code=200
        )
```
**I'm really new to azure functions and read quite a bit of the official documentations but I still don't know how to write code that I could define a body key ( "description" here) ,and make my function read in the value of the "description" & pass to the variable description.**

ref:
https://docs.microsoft.com/en-us/python/api/azure-functions/azure.functions.httprequest?view=azure-python

Thank you very much!

**Comment by anthonychu** [comment]
@ness001  Since the body is JSON, you can get access to it as a dictionary by calling `req.get_json()`.

```python
def main(req: func.HttpRequest) -> func.HttpResponse:
    req_body = req.get_json()
    return func.HttpResponse(f"description is {req_body.get('description')}")
```

**Comment by ness001** [comment]
Thank you @anthonychu ! It really helped me to solve the problem. Just one more question. When should we use get_body() method?

**Comment by Hazhzeng** [comment]
@ness001, the **req.get_body()** method will ensure the return value is a python bytes object, if you want to fetch the json as a dictionary, use **req.get_json()** would be ideal.

https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/_http.py#L202-L206
```python
    def get_body(self) -> bytes:
        return self.__body_bytes

    def get_json(self) -> typing.Any:
        return json.loads(self.__body_bytes.decode('utf-8'))
```

**Comment by S-Tensor** [comment]
> @ness001 Since the body is JSON, you can get access to it as a dictionary by calling `req.get_json()`.
> 
> ```python
> def main(req: func.HttpRequest) -> func.HttpResponse:
>     req_body = req.get_json()
>     return func.HttpResponse(f"description is {req_body.get('description')}")
> ```

How to pass json data in local host url(http://localhost:7071/api/HttpTrigger1)????
