### ISSUE TITLE
How could I make printed message or a list variable to be my GET output messge?

### ISSUE THREAD

**Issue by ness001** [Azure/azure-functions-python-worker#768]
#### Is your question related to a specific version? If so, please specify:
python
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
http
#### Question
The test availability function is for testing all urls connection in a long string. Since I have a list of urls to test, so the result can be output either by print or be appened in a list.
Now, I have my result saved in 
```
        result = test_availability(d_json.get('description'))
        for res in result:
            res
```
How could I use `            return func.HttpResponse(res)` to show all my res?

OR,
Is there a way to let the function get all my print()s as output.
Now my function.json is
```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}

```
Thank you!

**Comment by anthonychu** [comment]
You'll need to serialize the result to a string and return it. Try something like this:

```python
    result = test_availability(d_json.get('description'))
    return func.HttpResponse(
        result,
        status_code=200,
        headers={
            'Content-type': 'application/json'
        }
    )
```
