### ISSUE TITLE
Azure cli return "pkg_resources.DistributionNotFound" error

### ISSUE THREAD

**Issue by irniaxsep** [Azure/azure-functions-python-worker#771]
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
python azure-cli

#### Question
I installed python azure-cli module, the python azure-cli module has the same name for the executable which is “az”. 
 when I ran “az -v”, it actually ran the executable of the python azure-cli module, and this error returned “pkg_resources.DistributionNotFound: The 'vsts' distribution was not found and is required by azure-functions-devops-build”.

How can I fix this issue?

$az -v
Traceback (most recent call last):
  File '/usr/local/bin/az', line 4, in module
    __import__('pkg_resources').run_script('azure-cli==2.13.0', 'az')
  File '/usr/lib/python3/dist-packages/pkg_resources/__init__.py', line 3088, in module
    @_call_aside
  File '/usr/lib/python3/dist-packages/pkg_resources/__init__.py', line 3072, in _call_aside
    f(*args, **kwargs)
  File '/usr/lib/python3/dist-packages/pkg_resources/__init__.py', line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File '/usr/lib/python3/dist-packages/pkg_resources/__init__.py', line 574, in _build_master
    ws.require(__requires__)
  File '/usr/lib/python3/dist-packages/pkg_resources/__init__.py', line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File '/usr/lib/python3/dist-packages/pkg_resources/__init__.py', line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vsts' distribution was not found and is required by azure-functions-devops-build

**Comment by Hazhzeng** [comment]
Hi @irniaxsep,

Unfortunately, the project azure-functions-devops-build is no longer maintained. If you're using the `devops` command to initialize the pipeline, we would highly recommend using our portal deployment center.
Sorry for the inconvenience.

![image](https://user-images.githubusercontent.com/48038149/107577897-e1fb8600-6ba7-11eb-87cb-f1c6d654fb4c.png)
