### ISSUE TITLE
os.system or subprocess.call() not working in azure function

### ISSUE THREAD

**Issue by gsaikoundinya** [Azure/azure-functions-python-worker#778]
Hi, I'm trying to run a .exe file with required dll's in same folder with os.system or subprocess.call(), which is woriking perfectly fine in local machine but after deployment even os.system('date') is resulting in 0. Is there anything I can do to solve this issue?

**Comment by Hazhzeng** [comment]
The Python Function App is running on a Debian Buster (Linux). https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#runtime-system-libraries
The Windows Executable is not supported on our runtime.

**Comment by gsaikoundinya** [comment]
Let's say we are developing our .exe's and dll's with .Net Core which is supposed to be class platform, Would that work?

Thanks

**Comment by Hazhzeng** [comment]
Hi @gsaikoundinya,

Sorry I'm not an expert on the .NET field and this is not a Python worker related issue. We do have dotnet runtime inside our Python images https://github.com/Azure/azure-functions-docker/blob/master/host/3.0/buster/amd64/python/python36/python36.Dockerfile#L3.
Would recommend doing more research on runtime identifiers in https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#runtimeidentifiers

**Comment by anthonychu** [comment]
Yes you should be able to build a self-contained .NET Core app and run it in the image. See [this line in the Dockerfile](https://github.com/Azure/azure-functions-docker/blob/4783af9c41b727a5d98443887795a1f0fb529e7d/host/3.0/buster/amd64/python/python36/python36.Dockerfile#L12) that @Hazhzeng linked to where we build the function host that is later copied into the final image. You should be able to do the same to build your app and include the published output in your application package.
