### ISSUE TITLE
[BUG] Python azure function returning 500 Internal Server Error

### ISSUE THREAD

**Issue by michmike** [Azure/azure-functions-python-worker#787]
hi there,

i created an azure function using python 3.7 and HTTP trigger in VS code and i keep getting "500 Internal Server Error" when i run it on the web. when i run it locally on VS code, all works.

## Investigative information
From the VS code venv for python, here's the output of
```
>python --version
3.7.3
```

```
>pip freeze
aiohttp==3.7.3
async-timeout==3.0.1
attrs==20.3.0
azure-functions==1.5.0
chardet==3.0.4
idna==2.10
multidict==5.0.2
python-engineio==3.14.1
python-socketio==4.6.1
pytz==2020.4
simplisafe-python==9.6.0
six==1.15.0
typing-extensions==3.7.4.3
voluptuous==0.12.0
websockets==8.1
yarl==1.6.3
```
###### Please provide the following:

- Timestamp: 5.36pm central timezone
- Function App name: SimplisafePythonFnHttpTrigger 
- Function name(s) (as appropriate): SimplisafePythonFnHttpTrigger 
- Core Tools version: 3.0.2996 (Windows 10 version 2004)

###### Provide the steps required to reproduce the problem:
1. create a new azure function in VS code
2. use the file outlined below for _init_.py
3. open terminal venv and run the following two commands
4. pip install aiohttp
5. pip install simplisafe-python
6. run it locally and make sure it works (you may not be able to run it since it requires creds to simplisafe)
7. upload to azure and observe that it fails with no logs, no output, and just error 500

###### Provide the requirements.txt file to help us find out module related issues.

```python
# __init__.py
import logging
import azure.functions as func
import asyncio
from aiohttp import ClientSession
import simplipy

async def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    simplisafeLatestEvent = None
    async with ClientSession() as session:
        simplisafe = await simplipy.API.login_via_credentials(
            "<username>",
            "<password>",
            client_id="<client ID>",
            session=session
        )

        # Get a dict of systems with the system ID as the key:
        systems = await simplisafe.get_systems()
        for system in systems.items():
            systemid = system[0]
            systemobj = system[1]
            events = await systemobj.get_latest_event()            
            for key, value in events.items():
                #print(key, ' : ', value)
                if key == "messageBody":
                    simplisafeLatestEvent = value

    if simplisafeLatestEvent:
        return func.HttpResponse(f"{simplisafeLatestEvent}")
    else:
        return func.HttpResponse(
             "Failed - This HTTP triggered function executed unsuccessfully",
             status_code=200
        )
```

**Comment by TroyWitthoeft** [comment]
Ran into something similar.  I think asyncio might already be in the python libraries?  Try removing the `import asyncio` and see if the function still works locally.  Then deploy and test again.

**Comment by michmike** [comment]
> Ran into something similar. I think asyncio might already be in the python libraries? I know it sounds odd, but try removing the `import asyncio` and see if the function still works locally. Then deploy and test again.

thanks @TroyWitthoeft , i removed the `import asyncio` and re-deployed, but i got the same error.

**Comment by TroyWitthoeft** [comment]
They way I solved a similar issue was to start with a basic "hello world" function, and then keep adding dependencies/imports until I found the culprit.  It's slightly tedious "black box" debugging but it WILL work. At some point you'll find which dependency is causing the 500.  Then, we can dive in and figure out why.

**Comment by Hazhzeng** [comment]
Hi @michmike, thanks for raising this issue.
I deployed your function app to Azure and it seems like it is an issue of invalid credentials from simplipy library.
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.HttpTrigger
 ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
Exception: InvalidCredentialsError: Invalid username/password
Stack:   File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 353, in _handle__invocation_request
    call_result = await fi.func(**args)
  File "/home/site/wwwroot/HttpTrigger/__init__.py", line 16, in main
    session=session
  File "/home/site/wwwroot/.python_packages/lib/site-packages/simplipy/api.py", line 136, in login_via_credentials
    "scope": "offline_access",
  File "/home/site/wwwroot/.python_packages/lib/site-packages/simplipy/api.py", line 168, in authenticate
    token_resp = await self.request("post", "api/token", json=payload)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/simplipy/api.py", line 314, in request
    raise InvalidCredentialsError("Invalid username/password") from None
```

Please ensure you have setup the app setting (environment variable) correclty. If you want to see the live log stream of your function, please head to **appinsight => live metrics**

**Comment by michmike** [comment]
thanks @Hazhzeng , how did you set up your app setting (environment variable) in the test you had?
the reason you failed is because i entered dummy creds above, but it seems the simplipy library worked for you.

**Comment by michmike** [comment]
thanks for the live metrics hint, i was looking for the logs. it is still looking for aiohttp even though i did install it and verified it with pip freeze...
```Exception while executing function: Functions.SimplisafePythonFnHttpTrigger <--- Result: Failure Exception: ModuleNotFoundError: No module named 'aiohttp'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 275, in _handle__function_load_request func_request.metadata.entry_point) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 34, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 32, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/loader.py", line 76, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/SimplisafePythonFnHttpTrigger/__init__.py", line 7, in <module> from aiohttp import ClientSession```

**Comment by michmike** [comment]
fixed the issue. i did not realize that the file requirements.txt had to be manually amended with the libraries. that's my fault.

**Comment by berndverst** [comment]
Just a thought: Maybe we could add a check to the function core tools that upon deploy compares `pip freeze` to requirements.txt and in case of mismatch gives the options to ignore, stop the deploy, or create a new requirements.txt from the `pip freeze` output. Could be helpful for these kinds of situations.

**Comment by tahsin-github** [comment]
I faced similar problem. I forgot to edit the "requirements.txt" file. Later after editing it by adding the necessary package names, which I added using pip install the problem is solved.

**Comment by rapha-etos** [comment]
Any updated on this?
I am getting a Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException error only for a specific timeframe (10pm-12pm), it works the rest of the day.
