### ISSUE TITLE
[FeatureRequest] Log custom properties to App Insights

### ISSUE THREAD

**Issue by szklany** [Azure/azure-functions-python-worker#788]
It would be good to have the ability to log custom properties to application insights, like with opencensus, i.e. by simply passing the extra parameter to the logger.
I have currently not found a good way to log custom-dimensions from a Function, since when using opencensus the logs are written twice to app insights.

properties = {'custom_dimensions': {'key_1': 'value_1', 'key_2': 'value_2'}}
logging.warning('With fixed span_context? extra', extra=properties)

**Comment by sebader** [comment]
I just opened the same question on [SO ](https://stackoverflow.com/questions/65307435/azure-functions-for-python-structured-logging-to-application-insights)before I found this here. Guess that means it's currently not supported?!

**Comment by Hazhzeng** [comment]
Hi @szklany and @sebader, This is actually doable.

Example code:
```python
# Change Instrumentation Key and Ingestion Endpoint before you run this function app

import logging

import azure.functions as func
from opencensus.ext.azure.log_exporter import AzureLogHandler

logger_opencensus = logging.getLogger('opencensus')
logger_opencensus.addHandler(
    AzureLogHandler(
        connection_string='InstrumentationKey=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee;IngestionEndpoint=https://eastus-6.in.applicationinsights.azure.com/'
    )
)

def main(req: func.HttpRequest) -> func.HttpResponse:
    properties = {
        'custom_dimensions': {
            'key_1': 'value_1',
            'key_2': 'value_2'
        }
    }

    logger_opencensus.info('logger_opencensus.info Custom Dimension', extra=properties)
    logger_opencensus.info('logger_opencensus.info Statement')
    return func.HttpResponse("OK")
```

And in your application insight, you can query custom-dimensions by
![image](https://user-images.githubusercontent.com/48038149/105536673-8ecb9d00-5ca5-11eb-9e14-50df22dac42b.png)

Here is the full function project example
[OpenCensusAzureFunctions.zip](https://github.com/Azure/azure-functions-python-worker/files/5858148/OpenCensusAzureFunctions.zip)

**Comment by sebader** [comment]
Thanks for that! Just to confirm, will those logs have the same correlation id as other logs from the function invocation (and the request itself)?

**Comment by Hazhzeng** [comment]
Hi @seabader
If I recall correctly, the correlation id will be in trace_context.
See the following example https://github.com/Azure/azure-functions-python-worker/blob/698c524db03b70b13fb42d17e7b986ea8f744b6d/tests/unittests/http_functions/return_context/main.py

**Comment by sebader** [comment]
Yes, but will the opencensus take this automatically into account? If not, could you please show how to manually add it? Thanks!

**Comment by sebader** [comment]
ok, I just tested this myself and indeed the correlation works like a charm :) All log entries get the same correlation ID from the request.

@Hazhzeng I would propose you add this sample to the[ python dev reference](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#logging), similar to what is available for [Node](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#log-custom-telemetry).

**Comment by pacorreia** [comment]
I wonder how is this going?

I tried almost everything to solve this, and in the end some functionality is always lost
