### ISSUE TITLE
[BUG] Azure Functions worker using outdated cygrpc/grpcio, python 3.6

### ISSUE THREAD

**Issue by asears** [Azure/azure-functions-python-worker#797]
###### Please provide the following:

- Timestamp:  12/17/2020
- Function App name: n/a, local
- Function name(s) (as appropriate): n/a
- Core Tools version: 3.0.3160

###### Provide the steps required to reproduce the problem:

```shell
pip install azure-functions-worker
```

### Expected behavior

Azure functions worker installs.

###### Provide a description of the actual behavior observed.

```plaintext
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cygrpc 1.0.4.post6 requires grpcio==1.23.0, but you have grpcio 1.33.2 which is incompatible.
cygrpc 1.0.4.post6 requires grpcio-tools==1.23.0, but you have grpcio-tools 1.33.2 which is incompatible.
Successfully installed azure-functions-worker-1.1.9 grpcio-1.33.2 grpcio-tools-1.33.2
```

```shell
func start --python
```

```shell
[2020-12-17T11:57:51.434Z]     import grpc
[2020-12-17T11:57:51.436Z]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools-3\tools\workers\python\3.6\WINDOWS\X64\grpc\__init__.py", line 23, in <module>
[2020-12-17T11:57:51.438Z]     from grpc._cython import cygrpc as _cygrpc
[2020-12-17T11:57:51.439Z] ImportError: cannot import name 'cygrpc' from 'grpc._cython' (C:\ProgramData\chocolatey\lib\azure-functions-core-tools-3\tools\workers\python\3.6\WINDOWS\X64\grpc\_cython\__init__.py)
```

###### Provide any related information

* Links to source
* Bindings used

Any ETA as to when local runtime of functions will support Python 3.7, 3.8, 3.9 64-bit running locally on Windows?  Documentation shows support for 3.8, however worker is at 3.6? 

https://github.com/Azure/azure-functions-python-worker/wiki/Contributor-Guide

Is there a reason for hard-coded dependency on 3.6?  Is feature to target python version within the worker runtime available yet?

## Relates

https://github.com/Azure/azure-functions-python-worker/issues/450

**Comment by anirudhgarg** [comment]
Hi @asears we already do support 3.7, 3.8 for local development on Windows as well.

**Comment by asears** [comment]
Thanks for fast reply.  I was running Conda-installed Python38 environment and received above error.  In current environment, the only python version which successfully ran the "func start --python" command without above error was python 3.6.  Also tested 3.7.

The bug detailed is mainly a note to update the cygrpc/gpio dependency, if it needs it?
I think there are some other issues around this dependency, based on reviewing frequent comments about it.

**Comment by asears** [comment]
The issue in my case appears to be due to lack of installing the grpc dependencies required for the function runtime worker, (which seems to hit a lot of devs and isn't done by default?) and me trying to install them via pip install cygrpc.  Cygrpc is a pip package maintained (or slightly maintained) but not related to the primary grpc package.  This is not the same as the internal import being called by the function python worker, though aliased names are same.  

It sounds like removing this package should solve my error with Python 3.7/3.8.

To make the experience better, would suggest some error handling & logging on the imports, or some way to avoid the various grpc / external dependency issues besides documenting them on AzureDocs.  Appreciate all the documentation around python dependency issues as I'm sure it's a pain point for many others.

https://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it

**Comment by Hazhzeng** [comment]
Hi @asears,

Thanks for your advice and we did heard quite a few feedbacks related to module import.

We recently released a new feature under the feature flag `PYTHON_ISOLATE_WORKER_DEPENDENCIES`. This will ensure the worker module search path will be different from customer's packages. Also we stop uploading pypi packages since the Python worker is heavily bound to Azure Functions service.

1. To use our latest worker in your own project, you can use the git link in pip
```
pip install git+https://github.com/Azure/azure-functions-python-worker@dev
```

2. To enable the isolation between worker packages and customer packages, please set your environment variable
```
export PYTHON_ISOLATE_WORKER_DEPENDENCIES='true'
```

Let us know if you have any other quesitons.
