### ISSUE TITLE
Entry point decorator

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#8]
In order to indicate an entry point in the script, the user can add an **@azure_functions.export** decorator. That is, it's perfectly fine to have a Python file with many helper functions none of which should be directly runnable:

```python
# main.py
import azure_functions

# Private helper function
def helper():
    return 42

# Directly runnable function
@azure_functions.export  # or @azure_functions.runnable
def main():
    return helper()
```
Since the behavior is redundant to specifying the "entry point" attribute in function.json, we'll consider this out of scope for now.

**Comment by Hazhzeng** [comment]
Since not too many customers are asking this feature. I will close the issue for now.
