### ISSUE TITLE
Isolation of user dependencies

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#80]
Currently, the Python worker implementation depends on the following libraries: 
```
grpcio
grpcio-tools
pytest
requests
mypy
flake8
```
On start up, `workerenv` is bootstrapped with the latest version of the above packages.

### Problem Statement
If the user attempts to install a different version of one or more of the pre-installed packages, the runtime will get conflicted. For e.g. if the Python worker needs `requests == 2.18.4` but the user wants to install `requests == 1.6` , `pip` will only resolve one of the requirements causing either the worker or the function to fail. 

Is there a way to isolate the worker dependencies from user defined dependencies?

**Comment by asavaritayal** [comment]
@elprans @1st1 
\cc @christopheranderson @pragnagopa

**Comment by elprans** [comment]
There is no way to isolate, since the function is executed directly in the worker process.  However, the only actual runtime dependency is `grpcio`, all the other are development dependencies.  We can pin the `grpcio` version by appending it to user's `requirements.txt` (and document this).

**Comment by asavaritayal** [comment]
Agreed, if `grpcio` is the only dependency. 

Marking this as out of scope for now - let's revisit if the list of runtime dependencies grows in the future.

**Comment by anirudhgarg** [comment]
This is a very old comment, I am not sure if this is even relevant anymore and we havent seen any customer angst around it. Closing this out.
