### ISSUE TITLE
Functions Integration Tests--Move Python language worker pipeline from Azure Functions Python to Azure Functions 

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-python-worker#806]
Functions Integration Tests--Move Python language worker pipeline from https://azfunc.visualstudio.com/Azure%20Functions%20Python to https://azfunc.visualstudio.com/Azure%20Functions

**Comment by Hazhzeng** [comment]
All python related pipelines are migrated to main **azfunc** repo
Python Worker Build: https://azfunc.visualstudio.com/Azure%20Functions/_build?definitionId=57&_a=summary
Python Durable Functions Build: https://azfunc.visualstudio.com/Azure%20Functions/_build?definitionId=58
Python Worker Release: https://azfunc.visualstudio.com/Azure%20Functions/_release?_a=releases&view=mine&definitionId=42
Python Library Release: https://azfunc.visualstudio.com/Azure%20Functions/_release?_a=releases&view=mine&definitionId=43

Release instructions are updated in azure-functions-python-worker and azure-functions-python-library.
