### ISSUE TITLE
Functions Integration Tests—Onboard Python worker 

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-python-worker#807]
Please follow the instructions in the OneNote to onboard your language worker.

**Comment by Hazhzeng** [comment]
E2E Core Tools successfully generated, next step: integrating core tools into E2E tests

**Comment by Francisco-Gamino** [comment]
Hi @Hazhzeng , I've sent you a meeting request for Friday at 12:30. Hopefully this time works for both of you. 

/cc: @vrdmr

**Comment by Hazhzeng** [comment]
Integration Test pipeline is added in https://azfunc.visualstudio.com/Azure%20Functions/_build?definitionId=59&_a=summary

**Comment by Francisco-Gamino** [comment]
Awesome, tanks @Hazhzeng!
