### ISSUE TITLE
Referencing modules

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#81]
Currently, any file / module references in `main.py` have to be with respect to the top level function app. 

For e.g. -

```
FunctionApp
    |__ HttpTrigger1
             |__ function.json
             |__ main.py
             |__ model.pkl
    |__ host.json
    |__ requirements.txt
```

```python
# main.py
import os
import azure.functions

def main(req: azure.functions.HttpRequest):

    # file reference wrt top level function app
    f = open('HttpTrigger1/model.pkl', 'rb')
   
```

Can we have relative paths instead? E.g.  - `f = open('model.pkl', 'rb')`

**Comment by elprans** [comment]
The issue is that the current working directory is a global per-process setting.  It's impossible to do a `chdir` without affecting other functions that may be executing concurrently.

**Comment by elprans** [comment]
The recommended way to reference local files in Python in general is to use `__file__`:

```python
import pathlib

open(pathlib.Path(__file__).parent / 'model.pkl', 'rb')

```

**Comment by asavaritayal** [comment]
Okay. Do you recommend the same for importing modules as well?

Here's the issue I'm running into:
```
FunctionApp
    |__ HttpTrigger1
             |__ function.json
             |__ main.py
             |__ example.py
```

```python
# main.py 

import example #fails
import HttpTrigger/example #also fails
```

**Comment by asavaritayal** [comment]
That works - thanks!

**Comment by paolosalvatori** [comment]
What about if the function uses packages like helpers in the below sample?

```
FunctionApp
    |__ HttpTrigger1
             |__ function.json
             |__ main.py
             |__ example.py
             |__ helpers
                         |__ jwt
                                     |__ __init__.py
```

Placing the package in the same folder of the python function is not enough. As a workaround, we had to explicitly add the current folder to the path as follows:

```python
from sys import path
from os.path import dirname, join
path.append(dirname(__file__))

import json
from helpers.jwt import JWT
...
```

**Comment by elprans** [comment]
Use `from .helpers import jwt`

**Comment by paolosalvatori** [comment]
Thanks @elprans

**Comment by anindya5** [comment]
Hi,

My issue is if I want to import a function say function1 in module1 of SharedCode, but for me the SharedCode is inside the API folder, like below

```
FunctionApp
|_ HttpTrigger1
     |_ __init__.py
     |_ function.json
     |_ SharedCode
        |_ module1.py
        |_ module2.py
|_ HttpTrigger2
     |_ __init__.py
     |_ function.json
```
The functions are defined inside module1 and module2

Usually I'd have done 
`from ShareCode.module1 import function1`

That does not work. 

`from .ShareCode.module1 import function1` also gives module not found error, shown below

>  Executed 'Functions.HtmBatchAzureFunc' (Failed, Id=d70ee3dc-dca2-4d89-b39c-5c902ed64b11)
[5/22/19 8:54:05 PM] System.Private.CoreLib: Exception while executing function: Functions.HtmBatchAzureFunc. System.Private.CoreLib: Result: Failure
[5/22/19 8:54:05 PM] Exception: ModuleNotFoundError: No module named 'htm_shared_src'
[5/22/19 8:54:05 PM] Stack:   File "/usr/local/Cellar/azure-functions-core-tools/2.7.1158/workers/python/deps/azure/functions_worker/dispatcher.py", line 229, in _handle__function_load_request


Can anyone help
