### ISSUE TITLE
Azure Function Python to access ML Workspace Computes 

### ISSUE THREAD

**Issue by anaberlin** [Azure/azure-functions-python-worker#810]
#### Is your question related to a specific version? If so, please specify:
I am using Python 3.7 and search for the correct requirements setup and Python sdk versions to be able to access azure ml workspace when having authenticated via msi.
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
Timer
#### Question
I need to access ml computes of ml workspaces for a given subscription.
It works fine from my vsc environment but throws an exception when trying to run the function in Azure.
Exception being thrown is:
`Result: Failure Exception: AttributeError: 'MSIAuthentication' object has no attribute 'get_token' Stack: File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 357, in _handle__invocation_request self.__run_sync_func, invocation_id, fi.func, args) File 
`
As requirements.txt I have:
`azure-functions
azure-identity
azureml
azureml-core
azure-mgmt-resource==15.0.0`

**Comment by vrdmr** [comment]
Sorry for responding late to the issue. If this is still happening, please let us know and we'll take a look. Most likely this looks like a transient issue with the correct module either not loaded, or an issue with the user code with the `get_token` not being present in `class MSIAuthentication` - need a confirmation.

If you are still facing an issue, please re-open the issue.
