### ISSUE TITLE
Add support for RetryContext

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#814]
cc @alrod @AnatoliB 

Issue:  https://github.com/Azure/azure-webjobs-sdk/issues/2595 added support to access retry context within execution context.

This tracking item to expose the same property in python functions. Currently blocked on https://github.com/Azure/azure-functions-host/issues/7048

**Comment by vrdmr** [comment]
Still needs investigating. :)

**Comment by vrdmr** [comment]
Fixed by #909
