### ISSUE TITLE
Python function app not triggered from service bus queue

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-python-worker#823]
This is raised from an internal CRI. Link to existing github issue is here (https://github.com/Azure/azure-functions-servicebus-extension/issues/127) 

Scenario:
Customer has durable C# function which enqueues message to service bus. It seems like the runtime picks it up but worker doesn't execute it for the first time . Upon enqueueing it for the second time, it does. The app is hosted on AKS. Confirmed with @alrod that there are no issues with service bus trigger.

**Comment by vrdmr** [comment]
Closing the issue as this is old and we don't have relevant logs.
