### ISSUE TITLE
Simple Deployment Steps for Python Function App

### ISSUE THREAD

**Issue by tamathew** [Azure/azure-functions-python-worker#826]
I wanted to deploy Python function app from Dev to QA environment through Azure CLI commands.  I tried the below command with a zip file created and it pushed the code to portal/function-app. But it did not work as expected because a build step is missing. I did not find a proper documentation stating the steps to build a python code and use Azure CLI to deploy.

az functionapp deployment source config-zip -g 'MyresourceGroup' -n 'MyappName' --src MyPythonAppScript.zip

Any help with steps ??

**Comment by tmathewlulu** [comment]
Thank you @davidmrdavid for providing me a quick solution which actually passed my initial testing. I will do more testing and post a final response here. 

Here is the command : 

az functionapp deployment source config-zip --src <local_file_path> --build-remote true --name <appn_ame> --resource-group <rg_name>
