### ISSUE TITLE
[Detector] Add a detector to display the Python worker version

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-python-worker#830]
Add a detector that displays the Python worker version. Anatoli added one for the PowerShell language worker. Please see below.

![image](https://user-images.githubusercontent.com/12720858/107720155-9d96e580-6c8e-11eb-9c7d-269a7e9fe652.png)

**Comment by stefanushinardi** [comment]
@Hazhzeng mentioned that this is done, so closing this
