### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'requests' when executing a TimerTrigger

### ISSUE THREAD

**Issue by rob-yerc** [Azure/azure-functions-python-worker#831]
###### Please provide the following:

- Timestamp: 2021-03-13 18:10:00.075
- Function App name: di-fa-test
- Function name(s) (as appropriate): TimerTrigger
- Core Tools version:  3.0.3388

###### Provide the steps required to reproduce the problem:

I created a TimerTrigger function using the TimerTrigger template.  I added an import statement for the requests module as follows.

import azure.functions as func
import requests

###### Provide a description of the expected behavior.

I am able to run/debug the function locally.  Here is the expected output:

[2021-03-13T18:28:00.013Z] Executing 'Functions.TimerTrigger' (Reason='Timer fired at 2021-03-13T11:28:00.0070864-07:00', Id=6d5a6fc3-f70e-4810-b5e3-fa91bc891e77)
[2021-03-13T18:28:00.047Z] Python timer trigger function ran at 2021-03-13T18:28:00.041343+00:00
[2021-03-13T18:28:00.055Z] Executed 'Functions.TimerTrigger' (Succeeded, Id=6d5a6fc3-f70e-4810-b5e3-fa91bc891e77, Duration=47ms)
[2021-03-13T18:30:00.006Z] Executing 'Functions.TimerTrigger' (Reason='Timer fired at 2021-03-13T11:30:00.0027658-07:00', Id=513765c5-9a27-4598-bebe-a8852ce24b2b)
[2021-03-13T18:30:00.036Z] Python timer trigger function ran at 2021-03-13T18:30:00.030067+00:00
[2021-03-13T18:30:00.045Z] Executed 'Functions.TimerTrigger' (Succeeded, Id=513765c5-9a27-4598-bebe-a8852ce24b2b, Duration=41ms)

###### Provide a description of the actual behavior observed.

The requests module is not installed even though it is specified in requirements.txt.  Here is the function log, viewed using Azure Portal:

Result: Failure Exception: ModuleNotFoundError: No module named 'requests'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 288, in _handle__function_load_request func_request.metadata.entry_point) File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 42, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/loader.py", line 76, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/TimerTrigger/__init__.py", line 5, in <module> import requests

###### Provide a description of any known workarounds.

Have not found any

###### Provide the requirements.txt file to help us find out module related issues.

azure-functions==1.6.0
requests==2.25.1

###### Provide any related information

* Links to source
* Bindings used

<details>
<summary>Source</summary>

# __init__.py

import datetime
import logging

import azure.functions as func
import requests

def main(mytimer: func.TimerRequest) -> None:
    utc_timestamp = datetime.datetime.utcnow().replace(tzinfo=datetime.timezone.utc).isoformat()

    if mytimer.past_due:
        logging.info('The timer is past due!')

    logging.info('Python timer trigger function ran at %s', utc_timestamp)

</details>

**Comment by rob-yerc** [comment]
I resolved the problem.  It was a problem with the function app definition -- some settings needed to be updated.

**Comment by igors-cognite** [comment]
> I resolved the problem. It was a problem with the function app definition -- some settings needed to be updated.

Rob-yerc, could you please share what was the issue with your app definition?

**Comment by saileshchauhan** [comment]
> I resolved the problem. It was a problem with the function app definition -- some settings needed to be updated.

rob-yerc could you please share what was the issue with your app definition ?

**Comment by rob-yerc** [comment]
Apologize for the slow response.  I don't recall which setting changes made the difference but here are the settings that worked (I am using pulumi to manage the definitions, hence the systax):

sku=appservice.PlanSkuArgs(
        tier="Dynamic",
        size="Y1",
        tier="Basic",
        size="B1",
    ))
app_settings = {
       "APPINSIGHTS_INSTRUMENTATIONKEY": insights.instrumentation_key,
       "APPLICATIONINSIGHTS_CONNECTION_STRING": insights.connection_string,
       "BUILD_FLAGS": "UseExpressBuild",
       "ENABLE_ORYX_BUILD": True,
       "FUNCTIONS_WORKER_RUNTIME": "python",
       "SCM_DO_BUILD_DURING_DEPLOYMENT": "1",
       "XDG_CACHE_HOME": "/tmp/.cache",
        }
