### ISSUE TITLE
Testing azure functions 

### ISSUE THREAD

**Issue by AnaSofia94** [Azure/azure-functions-python-worker#833]
I'm using python 3.7.2, and when I try to debug my azure function I keep having this error:  ImportError: cannot import name 'cygrpc' from 'grpc._cython'.
So I manually installed cygrpc with: pip install cygrpc,however I continue having this error. Can someone help me please?

**Comment by ericthomas1** [comment]
- Is `cygrpc` named in your `requirements.txt` file?
  - If not, add it
  - If so, did you run `pip install -r requirements.txt` **after** you activated the virtual env?
  - This can be done using `.venv\scripts\activate` on Windows **if** ".venv" is the name of your virtual env.

Sometime my venv gets out of sync because I forgot to activate the venv before running `pip`.

**Comment by AnaSofia94** [comment]
I have done all the steps that you mentioned, but I continue having this
problem:
ERROR: pip's dependency resolver does not currently take into account all
the packages that are installed. This behaviour is the source of the
following dependency conflicts.
azure-functions-worker 1.1.9 requires grpcio~=1.33.1, but you have grpcio
1.23.0 which is incompatible.
azure-functions-worker 1.1.9 requires grpcio-tools~=1.33.1, but you have
grpcio-tools 1.23.0 which is incompatible.
Successfully installed grpcio-1.23.0
How can I use azure functions without any problems?

ericthomas1 ***@***.***> escreveu no dia segunda, 22/03/2021
à(s) 20:18:

**Comment by ericthomas1** [comment]
Looks like you'll need to specify package versions. You can try adding `grpcio==1.33.1` and `grpcio-tools==1.33.1` to `requirements.txt`. Then run `pip install -r requirements`.

**Comment by Hazhzeng** [comment]
Hi @AnaSofia94,

Seems like this is a collision between your local development environment packages vs Python worker runtime dependencies.
Could you try turning on **PYTHON_ISOLATE_WORKER_DEPENDENCIES** feature flag by adding the follwing line into your `local.settings.json::Values` section:
```json
{
  "...": "...",
  "Values": {
    "PYTHON_ISOLATE_WORKER_DEPENDENCIES": "1",
     "...": "..."
  }
}
```
This is a preview feature so we haven't documented it yet.
If this doesn't work, could you follow the https://docs.microsoft.com/en-us/azure/azure-functions/recover-python-functions?tabs=vscode#troubleshoot-cannot-import-cygrpc and provide me with your Python platform architecture?
```bash
# On Windows in PowerShell:
py -c 'import platform; print(platform.architecture()[0])'

# On Unix-like shell:
python3 -c 'import platform; print(platform.architecture()[0])'
```
