### ISSUE TITLE
Python Unit Testing Clarity

### ISSUE THREAD

**Issue by ericthomas1** [Azure/azure-functions-python-worker#834]
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
- HTTP Request-trigger

#### Question
I'm fairly new to Python; just getting into unit testing. Hoping you can shed some light on the [Unit testing doc found here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#unit-testing). 

- Its tough for me to follow what is going on.
- Are there any other examples of Unit Testing an HTTP-triggered Python Function you could provide?
- Something without "shared code" and multiple functions in a project root folder. 
- Just a clear cut case of testing a single Function would be great

**Comment by stefanushinardi** [comment]
Hello @ericthomas1, here is my attempt to show the another example how to setup unit test: https://github.com/stefanushinardi/azure-functions-python-simple-unittest 

Also, if I may ask, what is the local development setup that you have currently? 

Thanks!

**Comment by ericthomas1** [comment]
Hi @stefanushinardi ,
Thank you. I will study this new example now

**RE: Local dev setup:**
- **Editor**: VS Code
- **CLI**: `func-tools`
- **Local testing:**
  - `func start --useHttps --cert .\cert.pfx --password <redacted>`
  - Use Postman with client-cert to send requests
  - Use extensive logging in Python function code to debug/etc.

**Comment by stefanushinardi** [comment]
Awesome! if you havent already, installing the [az functions vs code extentsion](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions) will make the local dev experience better. 

Also whenever you create the ```tests``` folder, don't forget to pick the test framework(in the example, it is unittest). One way to navigate to that setting is to press F1  and type "Python: Configure Tests".

**Comment by ericthomas1** [comment]
This is a very straightforward example. I believe this should be in the docs as opposed to the existing one (the naming conventions and folder structure is easier to follow, etc.). 

**So I have ~550 lines of code between the request and response that does all sorts of things:**
- Uses `AzureDefaultCredential` which provides multiple sources for identity based on host (`AzureCLI` in localhost, System-assigned Managed Identity in Azure)
- Creates clients for key vault, retrieves secrets, creates clients for blob storage, table service, etc.
  - Would I have a single http-trigger test case for each of these client-creation functions within `main`?
  - Would my test case actually use `AzureDefaultCredential` or is there a mock identity to somehow use?

**Example:**
- **Test case:** Ensure KeyVault client can be created
- **Inputs:** KeyVault name retrieved from `os.environ[KV_NAME]` and `AzureDefaultCredential`
- I can understand how to mock up the `KV_NAME` env variable, but how is `AzureDefaultCredential` mocked?
- What about the returned secret? Would my test actually go get the secret or would I have a "test_secret" in the Key Vault that is retrieved?

**Comment by stefanushinardi** [comment]
Thanks for the feedback regarding the sample!

Regarding the strategy to test your code, there are probably multiple ways to do it, based on people's preference.

I personally would not test anything that requires network calls (i.e. get identity, token, instantiate azure clients) in my **unit tests** as it might fail if the box I am test. I would most likely put those in integration tests, which might live in some type of CI pipeline. 

As for the unit test, my general rule of thumb is that I only test the logic I wrote. So the outline for a http trigger code, it would be like:
```python
def main(req: func.HttpRequest) -> func.HttpResponse:

    data_one, data_two = extract_data_from_http_request(req)
    client_one, client_two =  get_clients()

    # Potentially do some type of data validation as well 
    result_one= functions_to_use_client_one_with_data_one(client_one, data_one)
    result_two= functions_to_use_client_two_with_data_two(client_two, data_two)
  
    return func.HttpResponse([result_one, result_two], status_code=200)

```

and the test files would then test these helper functions:
```python
import unittest

import azure.functions as func
import extract_data_from_http_request

class TestExtractData(unittest.TestCase):
    def test_extract_data_from_http_request_happy_case(self):
        
       mock_req = func.HttpRequest(
            method='GET',
            body=None,
            url='/api/HttpTrigger',
            params={'data_one': data_one, 'data_two': data_two})

        data_one, data_two= extract_data_from_http_request(req)
        
        self.assertEqual(
            data_one,
            expected_data_one
        )

        self.assertEqual(
            data_two,
            expected_data_two
        )
       
```

But again, this is my preference(which might not be the most pythonic). Let me know if you have anymore thoughts!

**Comment by ericthomas1** [comment]
Very helpful. I will study this and work to apply it to my Functions. Thank you for sharing.
