### ISSUE TITLE
[FeatureRequest] Support container-level output binding for blob storage

### ISSUE THREAD

**Issue by shwars** [Azure/azure-functions-python-worker#838]
There are some scenarios when we need to output several files from Azure function into blob storage. In this case, it would be convenient to be able to bind to output blob container declaratively, and then write multiple files to it. Similar to the way multiple rows of table can we written when dealing with Azure tables output binding in C# using IWriter.
Related to #652.
/cc @stefanushinardi @dariagrigoriu

**Comment by leestott** [comment]
@eamonoreilly fyi

**Comment by anthonychu** [comment]
@cachai2 Let's see if we can make some progress on this next semester. This would help other bindings and languages too.

Related: #654

**Comment by hallvictoria** [comment]
This can be addressed by using SDK Type Bindings for Blob. For this particular situation, binding to a ContainerClient type would be useful. You can dynamically define the container through an HTTP trigger or other method and use the client type to upload multiple files to the container.

For more information on how to use SDK Type Bindings:
- [SDK type bindings for Azure Blob Storage](https://techcommunity.microsoft.com/t5/azure-compute-blog/azure-functions-sdk-type-bindings-for-azure-blob-storage-with/ba-p/4146744)
- [Python Developer Reference - SDK Type Bindings](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=get-started%2Casgi%2Capplication-level&pivots=python-mode-decorators#sdk-type-bindings-preview)
