### ISSUE TITLE
[BUG] Bug Title

### ISSUE THREAD

**Issue by pratimvengurlekar** [Azure/azure-functions-python-worker#842]
###### Please provide the following:

Hi, I'm trying to run a data build tool commands inside a cli, it is a commands delimited by “; “ os.system or subprocess.call(), which is woriking perfectly fine in local machine but after deployment it has stopped working since 12 Apr, before that it was working now stopped.
 Is there anything I can do to solve this issue?

- Timestamp: since 12 Apr
- Function App name:
- Function name(s) (as appropriate):
- Core Tools version: azure function docker

###### Provide any related information

* Links to source
* Bindings used

**Comment by stefanushinardi** [comment]
@pratimvengurlekar could you give us information on the app? please follow this instructions: https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately
