### ISSUE TITLE
Using python Azure functions I am trying to read a large JSON file ~913MB using http trigger. function is timing out after 10 minutes

### ISSUE THREAD

**Issue by achu-r-27** [Azure/azure-functions-python-worker#847]
Using python Azure functions I am trying to read a large JSON file ~913MB using http trigger. function is timing out after 10 minutes. Anyone else faced this issue? Any suggestions to solve this issue?Thankyou

**Comment by zhenyuan0502** [comment]
@achu-r-27 http trigger itself is not suitable for long running task, you may look at Durable Functions to improve it.

**Comment by stefanushinardi** [comment]
@achu-r-27 If youre using consumption plan, this might run out of memory. Please check our service limits: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits. Closing this, re-open if there are further questions
