### ISSUE TITLE
Azure Python functions http trigger

### ISSUE THREAD

**Issue by narendra5c0** [Azure/azure-functions-python-worker#849]
```
import logging

import azure.functions as func


def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    **name = req.params.get('name')
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get('name')**



    if name:
        return func.HttpResponse(f"Hello, {name}. This HTTP triggered function executed successfully.")
    else:
        return func.HttpResponse(
             "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.",
             status_code=200
        )

```

#############
what is req.get_json and from where request get json is getting that?and what is request doby
2) can someone explain code in deatils

**Comment by vrdmr** [comment]
@narendra5c0 This is an example code for the Http trigger.

The code is a sample function that has a function called `main`, which is run by the Functions worker, and when you do an HTTP call to a function, you can pass in query parameters and body to the HTTP function.

When you created this function in either VSCode or CoreTools and when you start the function locally (using `func host start`), you would see URL like the below:

```bash
Azure Functions Core Tools
Core Tools Version:       3.0.3388 Commit hash: fb42a4e0b7fdc85fbd0bcfc8d743ff7d509122ae 
Function Runtime Version: 3.0.15371.0


Functions:

        HttpTrigger1: [GET,POST] http://localhost:7071/api/HttpTrigger1

        HttpTrigger2: [GET,POST] http://localhost:7071/api/HttpTrigger2

For detailed output, run func with --verbose flag.
[2021-05-22T10:44:05.746Z] Worker process started and initialized.
```

You can then use either the browser or the CLI to hit the function.

Passing the query string. This would hit the `name = req.params.get('name')` code path.
```bash
➜ curl http://localhost:7071/api/HttpTrigger2\?name\=PythonFunctions

Hello, PythonFunctions. This HTTP triggered function executed successfully.
```

Passing the body string. As we don't pass the query string,
```bash
➜ curl -d '{"name": "PythonFunction"}'  http://localhost:7071/api/HttpTrigger2

Hello, PythonFunction. This HTTP triggered function executed successfully.
```

And the above hits the following code base. When doing the `get_json`, it returns the `{"name": "PythonFunction"}` which is passed as data.
```python
if not name:
    try:
        req_body = req.get_json()
    except ValueError:
        pass
    else:
        name = req_body.get('name')**
```

More information on Query Strings in available [here](https://en.wikipedia.org/wiki/Query_string) and for [Body](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#body_2).

For more reference, please refer to the [Quick Start Guide](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python) or the [Python-Dev Reference Guide](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python)

Let me know if you have more questions. Closing this issue.
