### ISSUE TITLE
Unable to test Azure Function in Python locally

### ISSUE THREAD

**Issue by disssid** [Azure/azure-functions-python-worker#851]
I have an Azure Function written in Python which was working fine with Visual Studio Code. I was able to run it locally, test and even deploy to Azure. I checked it on the portal and the function is running fine for quite some time now.But after updating the Azure Function core tools version to 3, I'm getting this message when I run it locally 
`Invalid Message: "noDebug" is not supported for attach` 
and gave me the options to "Open launch.json" or "Cancel". 

I did check my launch.json file and I didn't make any changes, here is the content of the file

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Python Functions",
            "type": "python",
            "request": "attach",
            "port": 9091,
            "preLaunchTask": "func: host start"
        }
    ]
}
```

EDIT: I downgraded Azure Function core tools to 2.0 and the issue still exists. Is it something related to VS Code?

I did try creating a fresh Azure Function project using VS Code and copied all the functions to the new project and it worked. But the old project still has the issue.

If someone wants to still take a shot at it, I'll be more than happy to provide any information

**Comment by ankku** [comment]
Is there any update here, same issue, functions runs fine but the error message keeps prompting. Using VS Code and Python v3.9

**Comment by andreso-connecterra** [comment]
Any update? Thanks

**Comment by HariKrishnaRajoli-MT** [comment]
Is there any update about this error Visual Studio Code - Invalid message no debug is supported for attach. I'm also getting same error.. did many times re-installing and also tried Vs Code System setup as well as user setup but no change in that error.

**Comment by zhenyuan0502** [comment]
I confirm that Azure Tool Core V4 still got this error as well, quite annoying when I press Ctrl F5 as usual behavior

**Comment by HariKrishnaRajoli-MT** [comment]
I observed the strange behavior which is, When I run the .Net Stack azure functions with any trigger, it works perfectly in VS Code with any version of azure function core tools whereas If I run the other stack like Python, Javascript azure functions, it shows the many errors at every time

**Comment by vrdmr** [comment]
Hi @zhenyuan0502, @HariKrishnaRajoli-MT - If you could share the repro-steps for the same?

Also, could you update the `host.json` and _Start with debugging_ and share the logs below, it'll help

```json
{
  "version": "2.0",
  "logging": {
    "logLevel": {"default": "Trace"}
  }, ...
}
```

I have not been able to repro it locally and would appreciate it if you have a live repro. Thanks.

/cc @gavin-aguiar @YunchuWang

**Comment by YunchuWang** [comment]
No new feedback from author

**Comment by HariKrishnaRajoli-MT** [comment]
![VSCodePythonDebugError](https://user-images.githubusercontent.com/88704316/179358573-bd05935a-3ea5-4cb9-b78e-c10f53577368.gif)

**Comment by psychomintra** [comment]
Help I'm still having the Launch.Json error but these instructions are a bit confusing in the comments, It's my first time using visual studio code and I have assignments due!!! 


![Screenshot (109)](https://github.com/Azure/azure-functions-python-worker/assets/159205706/34de1ab1-cbdc-44d9-ace0-906e54d718df)
