### ISSUE TITLE
[BUG] Missing fields in timer object

### ISSUE THREAD

**Issue by pacorreia** [Azure/azure-functions-python-worker#858]
###### Please provide the following:

- Timestamp: Irrelevant
- Function App name: local development
- Function name(s) (as appropriate): local development
- Core Tools version: 3.0.3442

###### Provide the steps required to reproduce the problem:

1. Create and ordinary timer triggered function
2. Declare entrypoint as usual:
   - def main(mytimer: func.TimerRequest) -> None: 
 

###### Provide a description of the expected behavior.

Content expect in mytimer object (sample):
```json
{
    "schedule":{
    },
    "scheduleStatus": {
        "last":"2016-10-04T10:15:00+00:00",
        "lastUpdated":"2016-10-04T10:16:00+00:00",
        "next":"2016-10-04T10:20:00+00:00"
    },
    "isPastDue":false
}
```

###### Provide a description of the actual behavior observed.

This the current behavior:
![image](https://user-images.githubusercontent.com/54323159/121035222-93e93e80-c7a5-11eb-95cc-22d5754a91c8.png)

Only the flag past_due is present

###### Provide a description of any known workarounds.

None

###### Provide the requirements.txt file to help us find out module related issues.

```
# Do not include azure-functions-worker as it may conflict with the Azure Functions platform

# Microsoft function app package
azure-functions

# AAD authetincation and blob storage packages
azure-identity
azure-storage-file-datalake

# Database access packages
sqlalchemy
pyodbc

# Packages for ETL
urllib3
pandas
fastparquet
xlrd

# Debug package
debugpy

# Logging
opencensus-ext-azure

```

###### Provide any related information

* Links to source: Can't provide, corporate content
* Bindings used
  *   ```json
      {
          "scriptFile": "__init__.py",
          "bindings": [
              {
                  "name": "functimer",
                  "authLevel": "function",
                  "direction": "in",
                  "type": "timerTrigger",
                  "schedule": "%COFFEE_STOCKS_SCHEDULE%",
                  "useMonitor": true
              }
          ]
      }
      ```

**Comment by vrdmr** [comment]
Verifying in TypeScript - It does have `scheduleStatus` field and we need to add this in the [timer's implementation](https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/timer.py).

![image](https://user-images.githubusercontent.com/1047040/124706010-747c2900-deab-11eb-9ae1-9c0af4a3cb69.png)
