### ISSUE TITLE
Cosmos DB Bindings

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#86]
Add support for Cosmos DB as a: 

- [x] Trigger

- [x] Input Binding

- [x] Output Binding

Goal is to enable the functionality and document the Python example here - [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb)

For now, we can add the docs and samples to the [developer reference](https://pythondeveloperguide.azurewebsites.net/).

**Comment by asavaritayal** [comment]
\cc @1st1 , @elprans

**Comment by elprans** [comment]
@asavaritayal @pragnagopa I'm having difficulty testing the CosmosDB bindings.

Locally, I have defined the following function (named `put_document`):

`function.json`:
```json
{
  "scriptFile": "__init__.py",
  "disabled": false,

  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "direction": "out",
      "name": "doc",
      "databaseName": "test",
      "collectionName": "items",
      "createIfNotExists": true,
      "connection": "CosmosDB_connection"
    },
    {
      "direction": "out",
      "name": "$return",
      "type": "http"
    }
  ]
}
```

`__init__.py`:
```python
import azure.functions as func

def main(req: func.HttpRequest, doc: func.Out[func.Document]):
    doc.set(func.Document.from_json(req.get_body()))

    return 'OK'

```

The host fails to load the function with the following error:
```
fail: Host.General[0]
      The following 1 functions are in error:
      put_document: Object reference not set to an instance of an object.
```

I have verified that "CosmosDB_connection" is set on the function app, and that both the database and the collection exist.

**Comment by elprans** [comment]
Also, I tried adding a JavaScript CosmosDB trigger in the portal and it fails with:
```
2018-03-26T17:37:48  Welcome, you are now connected to log-streaming service.

2018-03-26T17:37:51.683 [Info] Function started (Id=22892c79-d129-4ef9-a61a-93ac7948abc1)

2018-03-26T17:37:51.698 [Error] Exception while executing function: Functions.itemsTrigger. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'input'. Microsoft.Azure.WebJobs.Extensions.DocumentDB: Unable to convert trigger to CosmosDBTrigger.

2018-03-26T17:37:51.714 [Error] Function completed (Failure, Id=22892c79-d129-4ef9-a61a-93ac7948abc1, Duration=34ms)
```

**Comment by pragnagopa** [comment]
All the extensions defined in [extensions repo](https://github.com/Azure/azure-webjobs-sdk-extensions) except HTTP, need to be explicitly installed on the runtime.  Installing  [CosmosDB extension](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#local-development-azure-functions-core-tools) should work

**Comment by elprans** [comment]
@pragnagopa How do I do that on the portal?  I didn't get an install prompt as the docs say.

**Comment by pragnagopa** [comment]
@soninaren - Can you please send instructions on how to test this?

**Comment by elprans** [comment]
Initial support for CosmosDB bindings done in https://github.com/Azure/azure-functions-python-worker/pull/104
