### ISSUE TITLE
NATS.io as topic sender

### ISSUE THREAD

**Issue by JuniorZilles** [Azure/azure-functions-python-worker#863]
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
Topic Trigger

#### Question
So the deal is that I need to listen to topics from [NATS](https://github.com/nats-io) using Python.
I found this guy [krvarma](https://github.com/krvarma/azure-functions-nats-extension) that did it with C#, but I need it to be in Python and I don't know how to do it (just started learning about Azure Functions).

I used the bus topic trigger already, but sending message from the azure console, and not from nats, any help I would appreciate.

**Comment by stefanushinardi** [comment]
Hello @JuniorZilles, unfortunately we do not have a plan to support NATS in the near future. 

cc: @vrdmr for further information why it wouldn't work for Python as it does in .NET

**Comment by JuniorZilles** [comment]
Thank you @stefanushinardi!
@vrdmr can you explain why it wouldn't work?
