### ISSUE TITLE
Event Grid Bindings

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#87]
Add support for Event Grid as a: 

- [ ] Trigger

Goal is to enable the functionality and document the Python example here - [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid)

For now, we can add the docs and samples to the [developer reference](https://pythondeveloperguide.azurewebsites.net/).

We will also need a template per this issue - https://github.com/Azure/azure-functions-templates/issues/646

**Comment by asavaritayal** [comment]
\cc @1st1 @elprans

**Comment by elprans** [comment]
@asavaritayal I can't seem to be able to create an eventGridTrigger function in the portal, there's no option for the binding.

**Comment by asavaritayal** [comment]
Currently, there's no experience to test the EventGrid binding in the portal for v2. @soninaren @agruning  to confirm.

Please use a local build of the host to develop and test the sample.

**Comment by soninaren** [comment]
Event grid extension is not available for for v2 yet. Adding @watashiSHUN to comment on the status of EventGrid extension for V2.

**Comment by soninaren** [comment]
Event Grid trigger and template has been added to portal now.  Here is the template 
https://github.com/Azure/azure-functions-templates/tree/v2.x/Functions.Templates/Templates/EventGridTrigger-CSharp

**Comment by asavaritayal** [comment]
Updating milestone to sprint 5.

**Comment by asavaritayal** [comment]
https://github.com/Azure/azure-webjobs-sdk-extensions
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid

**Comment by elprans** [comment]
I'm blocked here.  
Followed the docs, here's my function:

*function.json*:

```json
{
  "scriptFile": "__init__.py",
  "disabled": false,

  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "eventGridTrigger",
      "direction": "in",
      "name": "event",
    },
    {
      "type": "blob",
      "direction": "out",
      "name": "$return",
      "connection": "AzureWebJobsStorage",
      "path": "python-worker-tests/test-eventgridtrigger-blob.txt"
    }
  ]
}
```

**__init__.py**:

```python
import json

import azure.functions as func


def main(event: func.GridEvent) -> str:
    result = json.dumps({
        'id': event.id,
        'data': event.get_json(),
    })

    return result
```

Downloaded and configured the "Microsoft.Azure.WebJobs.Extensions.EventGrid" extension.

Run the host:

```
$ python -m azure.worker.testutils tests/eventgrid_functions/
Hosting environment: Production
Content root path: /home/elvis/dev/clients/microsoft/azure-functions-python-worker/tests/eventgrid_functions
Now listening on: http://localhost:5000
info: Host.Startup[0]
      Reading host configuration file '/home/elvis/dev/clients/microsoft/azure-functions-python-worker/tests/eventgrid_functions/host.json'
info: Host.Startup[0]
      Host configuration file read:
      {}
info: Host.General[0]
      Starting Host (HostId=hammer-1927488498, InstanceId=444e5c8c-6a5d-45a3-8cf8-8610c8de2eda, Version=2.0.11737.0, ProcessId=11746, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
info: Host.Startup[0]
      Loading all the worker providers from the default workers directory: /home/elvis/dev/clients/microsoft/azure-functions-python-worker
info: Host.Startup[0]
      Found worker config: /home/elvis/dev/clients/microsoft/azure-functions-python-worker/python/worker.config.json
info: Host.Startup[0]
      Will load worker provider for language: python
info: Host.Startup[0]
      Loading custom extension 'EventGridExtensionConfig'
info: Host.Startup[0]
      Loaded custom extension: EventGridExtensionConfig from '/home/elvis/dev/clients/microsoft/azure-functions-python-worker/tests/eventgrid_functions/bin/Microsoft.Azure.WebJobs.Extensions.EventGrid.dll'
info: Host.Startup[0]
      Loading custom extension 'CosmosDBConfiguration'
info: Host.Startup[0]
      Loaded custom extension: CosmosDBConfiguration from '/home/elvis/dev/clients/microsoft/azure-functions-python-worker/tests/eventgrid_functions/bin/Microsoft.Azure.WebJobs.Extensions.CosmosDB.dll'
info: Worker.python.ea61ab11-2425-4ba5-8bd6-926e4f2ebebd[0]
      Start Process: python  "/home/elvis/dev/clients/microsoft/azure-functions-python-worker/python/worker.py" --host 127.0.0.1 --port 42803 --workerId ea61ab11-2425-4ba5-8bd6-926e4f2ebebd --requestId bc9bb9b0-a029-4dfa-9bd8-6b16efbfa603 --grpcMaxMessageLength 134217728
info: Host.Startup[0]
      Generating 2 job function(s)
info: Host.Startup[0]
      Found the following functions:
      Host.Functions.ping
      Host.Functions.eventgrid_trigger

info: Host.Startup[0]
      Host initialized (590ms)
info: Host.Startup[0]
      Host started (2143ms)
info: Host.Startup[0]
      Job host started
info: Host.General[0]
      Host lock lease acquired by instance ID '0000000000000000000000009CEDC434'.
```

As shown above, the host loaded the extension and found the "eventgrid_trigger" function.  However, I'm unable to invoke the function.  The docs specify:

> Post to the URL of your Event Grid trigger function, using the following pattern:
> http://localhost:5000/admin/extensions/EventGridExtensionConfig?functionName={functionname}

However, when I'm attempting to do so, I get 404:

```
$ curl --verbose -X POST --data-ascii '{"foo":"bar"}' 'http://127.0.0.1:5000/admin/extensions/EventGridExtensionConfig?functionName=eventgrid_trigger'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> POST /admin/extensions/EventGridExtensionConfig?functionName=eventgrid_trigger HTTP/1.1
> Host: 127.0.0.1:5000
> User-Agent: curl/7.60.0
> Accept: */*
> Content-Length: 13
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 13 out of 13 bytes
< HTTP/1.1 404 Not Found
< Date: Wed, 30 May 2018 23:56:30 GMT
< Server: Kestrel
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact
```

I need help to figure out how to test EventGrid on a local Host.

**Comment by elprans** [comment]
For reference, the WIP PR is #134

\cc @watashiSHUN

**Comment by pragnagopa** [comment]
There is a mistake in the documentation to test locally.  Here is the documentation I followed: [local-testing-with-ngrok](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid#local-testing-with-ngrok)
Correction in the URL:
https://{subdomain}.ngrok.io/runtime/webhooks/EventGridExtensionConfig?functionName=FunctionName

I will open issue to fix the documentation.

**Comment by elprans** [comment]
@pragnagopa ngrok is only there to expose the local host to the internet, it simply forwards requests to the local host.  The documentation elsewhere says

> Manually post the request to the localhost URL of your Event Grid trigger function.

What is that localhost URL? Neither `/api/{function_name}`, nor `/admin/extensions/EventGridExtensionConfig?functionName={functionname}` work,

**Comment by pragnagopa** [comment]
Yes. I think it is the same issue. Url has typo. Can you try replacing admin/extensions with /runtime/webhooks?

**Comment by elprans** [comment]
With `runtime/webhooks` I get a 401 instead of 404 and no log output.

**Comment by pragnagopa** [comment]
Following works with the CLI:

URL: 
```
 http://localhost:7071/runtime/webhooks/EventGridExtensionConfig?functionName=EventGridTriggerCSharp2
```

Headers:
```
Content-Type: application/json
aeg-event-type: Notification
```

Sample Post data from [sample.dat](https://raw.githubusercontent.com/Azure/azure-functions-templates/dev/Functions.Templates/Templates/EventGridTrigger-CSharp/sample.dat)
Note: Input is Json Array
```
[
{
  'topic': '/subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/test/providers/Microsoft.EventHub/namespaces/test',
  'subject': 'eventhubs/test',
  'eventType': 'captureFileCreated',
  'eventTime': '2017-07-14T23:10:27.7689666Z',
  'id': '7b11c4ce-1c34-4416-848b-1730e766f126',
  'data': {
    'fileUrl': 'https://test.blob.core.windows.net/debugging/testblob.txt',
    'fileType': 'AzureBlockBlob',
    'partitionId': '1',
    'sizeInBytes': 0,
    'eventCount': 0,
    'firstSequenceNumber': -1,
    'lastSequenceNumber': -1,
    'firstEnqueueTime': '0001-01-01T00:00:00',
    'lastEnqueueTime': '0001-01-01T00:00:00'
  },
  "dataVersion": "",
  "metadataVersion": "1" 
}
]
```

**Comment by elprans** [comment]
@pragnagopa Which version of host does that use?

**Comment by pragnagopa** [comment]
Did some more investigation. Invoking the API on the functions host, needs a system level key. In CLI this is taken care before starting the webhost. For now, please test E2E with a deployed Azure Function.  I need to look into this further to provide instructions on setting up SystemLevel key for testing via localhost.

**Comment by watashiSHUN** [comment]
I don't have access to a laptop right now but in the past when I was working on eventgrid I did come across an issue https://github.com/Azure/azure-functions-host/issues/2360 @pragnagopa this might be helpful?

**Comment by pragnagopa** [comment]
Addressed: https://github.com/Azure/azure-functions-python-worker/commit/0800b4deb7641157ca8fd62563351ca54e20f552
