### ISSUE TITLE
[BUG] python exited with code 137 

### ISSUE THREAD

**Issue by juicyscoop** [Azure/azure-functions-python-worker#871]
###### Please provide the following:

- Timestamp: 2021-07-06 12:35:51.836
- Function App name: muziker-dashboard-update
- Function name(s) (as appropriate): TimerTriggerEyerimDaily
- Core Tools version: 1.14

###### Provide the steps required to reproduce the problem:
Trigger the function (its set to a http trigger currently), after about 3 hours, it exits with "python exited with code 137 "

###### Provide a description of the expected behavior.
It should run until the end of the script, not get stuck withing the main for loop.
After I trigger the function, it should read, process, write data within main for loop, then aggregate data, write results, write logs. (All is supposed to be written into blob storage)

###### Provide a description of the actual behavior observed.
After I trigger the function -> works for about 60 iterations of for loop, then exits with "python exited with code 137"
 After I trigger the function -> works for about 60 iterations of for loop, then exits with "python exited with code 137"

###### Provide the requirements.txt file to help us find out module related issues.

azure-core==1.14.0
azure-functions==1.7.0
azure-storage-blob==12.8.1
azure-storage-file-share==12.4.2
backcall==0.2.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
colorama==0.4.4
cryptography==3.4.7
decorator==5.0.9
idna==2.10
isodate==0.6.0
jedi==0.18.0
msrest==0.6.21
numpy==1.20.3
oauthlib==3.1.0
pandas==1.2.4
parso==0.8.2
pickleshare==0.7.5
prompt-toolkit==3.0.18
pycparser==2.20
Pygments==2.9.0
python-dateutil==2.8.1
requests==2.25.1
requests-oauthlib==1.3.0
six==1.16.0
tornado==6.1
traitlets==5.0.5
urllib3==1.26.4
wcwidth==0.2.5
pandas-read-xml

###### Provide any related information

* Links to source
* Bindings used

**Comment by stefanushinardi** [comment]
Hello, please check this [troubleshooting guide](https://docs.microsoft.com/en-us/azure/azure-functions/recover-python-functions?tabs=vscode#troubleshoot-python-exited-with-code-137). Re open if the issue still persists. Thanks!
