### ISSUE TITLE
Blob Storage Bindings

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#88]
Add support for Azure Blob storage as a: 

- [x] Trigger

- [x] Input Binding

- [x] Output Binding

Goal is to enable the functionality and document the Python example here - [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob)

For now, we can add the docs and samples to the [developer reference](https://pythondeveloperguide.azurewebsites.net/).

**Comment by elprans** [comment]
@asavaritayal We already have support for input/output bindings as well.
