### ISSUE TITLE
[BUG] When using Azure functions with WSGI/Flask, errors are not bubbled up properly

### ISSUE THREAD

**Issue by eelwk** [Azure/azure-functions-python-worker#881]
###### Please provide the following:

- Timestamp: 8/2/2021 3:31
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Core Tools version: 3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit)

###### Provide the steps required to reproduce the problem:

1. Create python function using WGSI and flask as described in #165 
2. In flask app, force error to happen, i.e.:
```
@application.route("/api/function-flask-bad-error")
def home():
    x = "hello"

    if not type(x) is int:
        raise TypeError("Only integers are allowed")
    return x
```
3. Run function app and call /api/function-flask-bad-error

###### Provide a description of the expected behavior.

After step 3, I expect to see the Type error "Only integers are allowed" displayed in the console log. 

###### Provide a description of the actual behavior observed.

Instead of the actual error, the error (and location of the error) that comes up is ambiguous and doesn't help with debugging.

![functions-bad-error](https://user-images.githubusercontent.com/43866344/127932950-7883a3ab-97ba-4647-a298-07db5504a127.PNG)

###### Provide a description of any known workarounds.

The only workaround we found was to remove Azure functions and use Flask with gunicorn.

###### Provide the requirements.txt file to help us find out module related issues.

```
azure-functions==1.7.2
click==8.0.1
Flask==0.12.4
itsdangerous==2.0.1
Jinja2==3.0.1
MarkupSafe==2.0.1
Werkzeug==2.0.1
```
 ##
###### Provide any related information

* Links to source
* Bindings used

<details>
<summary>Source</summary>

```python
# __init__.py

def main(req: func.HttpRequest, context: func.Context) -> func.HttpResponse:
    return func.WsgiMiddleware(application).handle(req, context)
```

```python
# app.py
from flask import Flask

application = Flask(__name__)

@application.route("/api/function-flask-bad-error")
def home():
    x = "hello"

    if not type(x) is int:
        raise TypeError("Only integers are allowed")
    return x
```

</details>

**Comment by YunchuWang** [comment]
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/12449837/213824722-22e3fbb5-42d0-40cd-85b2-a7c1fbd05f2d.png">
Cant repro with core-tool version 4.0.4915, python 3.9
