### ISSUE TITLE
[BUG] Azure Queue Trigger parameters not available for CosmosDB input Binding

### ISSUE THREAD

**Issue by SashiDareddy** [Azure/azure-functions-python-worker#885]
I created an Azure Function that is triggered by Azure Queue Storage.

This function has a few output bindings - mainly writing to blob storage and updating a document in CosmosDB. The name of the blobs is built using one of the parameters in the messages sent to the Azure Queue Storage.

A sample message is below:

```json
{
  "meta": {
    "user_id": "abc.def@xyz.org",
    "runId": "63a66f32-9080-4ea4-a03e-32166e63c1a8"
  },
  "config": {
    "Params": {
      "filepath": "./xxxx/lxxxx.csv",
      "size": 10.0
    }
  }
}
```

Here's my `function.json`:

Notice  how I'm using the `{meta.runId}` as binding pattern in the `function.json` - the `runId` which is a guid is part of the message sent to the Azure Queue - 
```json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "msg",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "my-queue",
      "connection": "xxxxxx_STORAGE"
    },
    {
      "type": "cosmosDB",
      "direction": "out",
      "name": "outputDoc",
      "databaseName": "xxxxxDB",
      "collectionName": "Simulations",
      "createIfNotExists": false,
      "connectionStringSetting": "xxxxxx_DOCUMENTDB"
    },
    {
      "type": "blob",
      "direction": "out",
      "name": "outputBlob",
      "path": "xxxxxx-yyyyy/runs/{meta.runId}.json.zip",
      "connection": "xxxxxx_STORAGE"
    },
    {
      "type": "blob",
      "direction": "out",
      "name": "outputBlobCsv",
      "path": "xxxxxx-yyyyy/runs/{meta.runId}.csv.zip",
      "connection": "xxxxxx_STORAGE"
    },
    {
      "type": "cosmosDB",
      "direction": "out",
      "name": "outputStatus",
      "databaseName": "xxxxxDB",
      "collectionName": "Status",
      "createIfNotExists": false,
      "connectionStringSetting": "xxxxxx_DOCUMENTDB",
      "partitionKey": "/runId"
    },
    {
      "type": "cosmosDB",
      "direction": "in",
      "name": "statusDocument",
      "databaseName": "xxxxxDB",
      "collectionName": "Status",
      "connectionStringSetting": "xxxxxx_DOCUMENTDB",
      "sqlQuery": "select * from c where c.id = {meta.runId}"
    }
  ]
}

```

When I run my function - the blob storage output bindings correctly create the output files with the expected names after parsing `{meta.runId}` - so a path like:  `"xxxxxx-yyyyy/runs/{meta.runId}.json.zip"` with runId given as `"63a66f32-9080-4ea4-a03e-32166e63c1a8"` creates a blob at `xxxxxx-yyyyy/runs/63a66f32-9080-4ea4-a03e-32166e63c1a8.json.zip`.

However, the CosmodDB binding doesn't seem to pick up the runId like the blob bindings are able to do. According to the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-input?tabs=python#queue-trigger-get-multiple-docs-using-sqlquery-3) I believe what I'm trying to do should be possible but I get an error message saying:

```shell
[2021-08-17T14:32:53.175Z] System.Private.CoreLib: Exception while executing function: Functions.xxxxx. Microsoft.Azure.WebJobs.Host: Error while accessing 'runId': property doesn't exist.
```

Now- if change the sqlQuery in the input CosmosDB binding to ` "sqlQuery": "select * from c where c.id = \"63a66f32-9080-4ea4-a03e-32166e63c1a8\""` by hard coding the runId - it works as expected.

I also tried without the sqlQuery - by using `Id` & `"partitionKey": "/runId"` - this did not work:
```json
    {
      "type": "cosmosDB",
      "direction": "in",
      "name": "statusDocument",
      "databaseName": "xxxxxDB",
      "collectionName": "Status",
      "connectionStringSetting": "xxxxxx_DOCUMENTDB",
      "Id": "{meta.runId}",
      "partitionKey": "/runId"

    }
```

A sample document in CosmosDB I'm trying to update when my Azure Function is executed:
```json
{
    "id": "63a66f32-9080-4ea4-a03e-32166e63c1a8",
    "runId": "63a66f32-9080-4ea4-a03e-32166e63c1a8",
    "status": "ACCEPTED",
    "updateTime": "2021-08-17 10:29:17",
    "_rid": "OcQyAI0H3wEDAAAAAAAAAA==",
    "_self": "dbs/OcQyAA==/colls/OcQyAI0H3wE=/docs/OcQyAI0H3wEDAAAAAAAAAA==/",
    "_etag": "\"100067e0-0000-0c00-0000-611b955d0000\"",
    "_attachments": "attachments/",
    "_ts": 1629197661
}
```

###### Please provide the following:

- Timestamp:
- Function App name:
- Function name(s) (as appropriate):
- Core Tools version: 3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit)
- Function Runtime Version: 3.0.15828.0

###### Provide a description of the expected behavior.
As per the document  the binding pattern should work for CosmosDB - just like it is working for Blob

###### Provide a description of the actual behavior observed.
CosmosDB does not pick up the binding pattern from Queue trigger

**Comment by arroyc** [comment]
@SashiDareddy apology for delayed response, are you still facing this issue? can you tell which region are you deploying this?
