### ISSUE TITLE
[BUG] Local Debugging Fails With "KeyError: '__main__'"

### ISSUE THREAD

**Issue by tyler555g** [Azure/azure-functions-python-worker#887]
###### Please provide the following:

- Timestamp: 2021-08-30T14:04:57.007Z
- Function App name: n/a local debug
- Function name(s) (as appropriate): n/a local debug
- Core Tools version: 3.0.5368 
- Function Runtime Version: 3.0.15828.0

###### Provide the steps required to reproduce the problem:

1. Download repo
2. Initialize .venv with python 3.9.6
3. Initialize debugging session in vscode with F5
4. Get error
>[2021-08-30T14:16:09.495Z] Worker failed to function id 5cfd6c05-6b2d-46e8-b09f-6c5c8a0ac887.
[2021-08-30T14:16:09.496Z] Result: Failure
Exception: KeyError: '__main__'
Stack:   File "C:\Users\tyler\AppData\Roaming\nvm\v16.8.0\node_modules\azure-functions-core-tools\bin\workers\python\3.9/WINDOWS/X64\azure_functions_worker\dispatcher.py", line 301, in _handle__function_load_request
>
###### Provide a description of the expected behavior.

Expect debugging to continue successfully.

###### Provide a description of the actual behavior observed.

Does not work.

###### Provide a description of any known workarounds.

Works on my other machine. Have not tried a fresh install yet.

###### Provide the requirements.txt file to help us find out module related issues.

```
azure-functions
azure-functions-durable
usaddress-scourgify
```

###### Provide any related information

https://github.com/tyler555g/AzureDurableFunctionsExample

**Comment by tyler555g** [comment]
Anyone get a chance to look at this?
@Hazhzeng @microsoftopensource

**Comment by tyler555g** [comment]
https://github.com/pallets/click/issues/2066#event-5292960349

click says this is a Python Worker issue. Please assist...

**Comment by niekvleeuwen** [comment]
Updating to [Azure Functions Core Tools 4.0](https://github.com/Azure/azure-functions-core-tools) fixed the exact same issue for me.

**Comment by wangbill1993** [comment]
@tyler555g Hello I wonder is the issue fixed for you now?

**Comment by YunchuWang** [comment]
Tried with core-tool 4.0 and issue no longer occurs.

**Comment by bmeredyk** [comment]
I know this is old, but if anybody happens to run into it like I just did, the version of click installed does seem to matter. click 8.0.4 will cause problems but ^8.1.3 seems to work.  This is under Core Tools v4.0.5455 & Function Runtime v4.27.5.21554. (Didn't have problems with click 8.0.4 under Core Tools v4.0.4915 Function runtime 4.14.0.19631 though )
