### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#89]
Currently, we see the following output if a function fails to load - 
![image](https://user-images.githubusercontent.com/8435148/37806473-65a0f86e-2dfd-11e8-8ce9-53f0b4ddef2f.png)

It's hard to tell from the GUID which function failed. Can we print the function name instead? 

Additionally, there are no logs for the failure. How do I see errors from the Python runtime?

**Comment by 1st1** [comment]
We have no control over how this message is rendered, it's up to WebHost. I suggest to open an issue there.

**Comment by pragnagopa** [comment]
I will look into it. If host needs to parse the function name, i will move the bug to [runtime issues](https://github.com/Azure/azure-functions-host/issues)

**Comment by asavaritayal** [comment]
Closing the issue in favor of https://github.com/Azure/azure-functions-host/issues/2588
