### ISSUE TITLE
Set multiple cookies in response headers in Python

### ISSUE THREAD

**Issue by KarFan-FS** [Azure/azure-functions-python-worker#892]
Hello. I'll be brief as my problem is already exaplined in detail here:
https://github.com/Azure/azure-functions-host/issues/2737

In short, I want to be able to add multiple "Set-Cookie" headers to the HttpResponse object in Python.
Could you please provide the same "cookies" attribute you did in Javascript to Python?

If not, how can I dynamically create cookies in the meantime? The proxy solution given in the link only allows for hard-coded cookies, correct? I need to be able to generate cookie values based on my logic.

**Comment by vrdmr** [comment]
Closing this issue in favor of #944 - we are investigating and will get the fix out soon.
