### ISSUE TITLE
[BUG] Empty query params are discarded

### ISSUE THREAD

**Issue by nathanhi** [Azure/azure-functions-python-worker#894]
### Investigative information

- Timestamp: 1632902318
- Function App name:
- Function name(s) (as appropriate):
- Core Tools version: 3.2.0-0 Commit hash: 5ffe001695be89a9b33cb569c875aef15938830b

###### Provide the steps required to reproduce the problem:

1. Create simple function:
   __\_\_init\_\_.py__
    ```python
    import azure.functions

    def main(req: azure.functions.HttpRequest):
        return str(req.params)
    ```
    __function.json__
    ```json
    {
        "scriptFile": "__init__.py",
        "bindings": [
            {
                "authLevel": "anonymous",
                "type": "httpTrigger",
                "direction": "in",
                "name": "req",
                "methods": [
                    "get",
                    "post"
                ]
            },
            {
                "type": "http",
                "direction": "out",
                "name": "$return"
            }
        ]
    }
    ```
2. Access function URL with query params `?paramwithvalue=foo&paramwithoutvalue`
3. `{"paramwithvalue": "foo"}` is returned
### Expected behavior

I would expect the `HttpRequest.params` to contain all query params, defaulting to either a value of `None` or an empty string:

```json
{
    "paramwithvalue": "foo",
    "paramwithoutvalue": ""
}
```

### Actual behavior

The query parameter is silently discarded:

```json
{
    "paramwithvalue": "foo"
}
```

### Known workarounds

The query param can be retrieved via `urllib.parse.parse_qs` from the `HttpRequest.url`object:

__\_\_init\_\_.py__
```python
from urllib.parse import parse_qs, urlparse

import azure.functions

def main(req: azure.functions.HttpRequest):
    return str(parse_qs(urlparse(req.url).query, keep_blank_values=True))
```

This will return the full set of params:

```
"{'paramwithvalue': ['foo'], 'paramwithoutvalue': ['']}"
```

### Contents of the requirements.txt file:

```
azure-functions==1.7.2
```

### Related information
This seems to be an underlying issue in the protobuf implementation and was already fixed in https://github.com/Azure/azure-functions-language-worker-protobuf/issues/49

* https://github.com/Azure/azure-functions-language-worker-protobuf/issues/49
* https://github.com/Azure/azure-functions-nodejs-worker/pull/326
* https://github.com/Azure/azure-functions-nodejs-worker/issues/253

**Comment by shreyabatra4** [comment]
Hi @nathanhi, are you still facing this issue?

**Comment by lucyzhang929** [comment]
Hello, I am still seeing this issue. Are there plans to fix this? There is a fix using `UseNullableValueDictionaryForHttp` mentioned in the PowerShell worker regarding the same issue https://github.com/Azure/azure-functions-powershell-worker/issues/895.
