### ISSUE TITLE
How do I handle a file sent via HTTP requests on Azure Functions?

### ISSUE THREAD

**Issue by sshojiro** [Azure/azure-functions-python-worker#895]
#### Is your question related to a specific version? If so, please specify:
N/A

#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 

Behaviour of Basic HttpTrigger for Python. I created an HttpTrigger that is expected to receive a PDF file via HTTP requests, save it temporarily, and delete it when the entire process for a request finishes.

#### Question

I wrote the following code and would like to have Functions App receive a PDF file from HTTP requests in their form. `req.files`, where `req` is an instance of `func.Httprequest`, shall have the field "filedata" corresponding to a PDF file when I locally run `curl -X POST -H 'Content-Type:application/json' -H 'x-functions-key:brabra==' -F filedata=@path/to/file.pdf`. This passed when I developed and tested with a local Docker container. However, the app on the remote container never receives the field and `req.files`'s keys are always `[]`, a blank array. It'd be helpful if anyone gives me any advices.

```python
import logging
import json
from mylib import extract_data # in-house library
import azure.functions as func
SUPPORTED_CONTENT_TYPES = ['application/pdf']

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    logging.info('Start solving a HTTP(S) request')

    name = req.params.get('name')
    body = req.get_body()

    ret = None # initialize
    """Note:
    When you run `curl -X POST -F filedata=path/to/file.pdf` or so,
    then you have req.form['filedata'] field.
    On the contrary, `curl -X POST -F filedata=@path/to/file.pdf`
    triggers req.files['filedata'] and leaves req.form['filedata']
    empty.
    """

    imaginary_file = '/tmp/fed.pdf'
    logging.info('{}'.format(list(req.files.keys())))
    if 'filedata' in req.files:
        # dtype='{}'.format(type(req.files['filedata']))
        # logging.info('log=> dtype: '+dtype)
        # dtype: <class 'azure.functions._thirdparty.werkzeug.datastructures.FileStorage'>
        with open(imaginary_file, 'wb') as out:
            out.write(req.files['filedata'].read())
        ret = extract_data(imaginary_file)
        if ret is not None:
        logging.info('='*10+'\n We got the expected return')
        return func.HttpResponse(
            body=json.dumps(ret),
            status_code=200,
            mimetype='application/json'
        )
    else:
        logging.info('='*10+'>')
        if name!="":
            return func.HttpResponse(
                f"Health check for {name} in Azure Functions.\n Bye.",
                status_code=200
            )
        else:
            return func.HttpResponse(
                "Azure Functions is successfully turned on.",
                status_code=200
            )
```

If here is not an appropriate forum, please suggest me an alternative.

Thanks,
S

**Comment by balag0** [comment]
@vrdmr Do you know if the request content gets passed to the language workers?

**Comment by sshojiro** [comment]
From a local environment, cURL should have an HTTP request whose header shall indicate 'Content-Type:multipart/form-data', which was not an issue when I tested the Function app running on a local Docker image based on Azure Functions app Docker image.

Once I corrected Content-Type in the header, the app received the req.files variable, where req is an instance of azure.functions.HttpRequest class.
Thanks,
S
