### ISSUE TITLE
[FEATURE] Add support for Python 3.10

### ISSUE THREAD

**Issue by JohnCarmichael3000** [Azure/azure-functions-python-worker#899]
While using Func Core Tools v3.0.3785 received message:

Python version "3.10.0" does not match supported versions: "3.6.x", "3.7.x", "3.8.x", "3.9.x"

3.10 just came out on October 4th, 2021. For reference func supported 3.9 came out October 2020.

**Comment by loganmc10** [comment]
Is 3.9 out of preview? I think on the Azure Portal when you select it, it no longer has the preview tag, but the readme for this repo still lists it as preview

**Comment by anthonychu** [comment]
Yes it’s [generally available](https://azure.microsoft.com/en-us/updates/azure-functions-python-39-support-is-now-generally-available/). @stefanushinardi @vrdmr to update readme

**Comment by jaymegordo** [comment]
@anirudhgarg out of curiosity, what type of things does the azure functions team need to do to make 3.10 available? Are there specific changes that need to be made, or more just that you need the time to test and validate everything?

Personally I'm really looking forward to using 3.10, but most of my projects are on azure functions, so have to wait for now. Thanks!

**Comment by m10d** [comment]
> This is on our backlog. Current plan is to have this available early next year.

at halfway through Q2 of "next year" - what's the ETA for this support?  Thank you.

**Comment by tintin10q** [comment]
I would really like to start using the new match keyword.

**Comment by vrdmr** [comment]
We are doing the final bit of testing and setting up the infrastructure. You will see this out soon. Apologies for the wait.

**Comment by YunchuWang** [comment]
Dedicated
1. Create and publish a python 3.7, 3.8 or 3.9 dedicated/elasticpremium V4 function app containing a http trigger function using vscode extension or cli.
2. [Optional] Open console, enter command to show your published function app settings: az functionapp config show --name <function-app-name> --resource-group <resource-group>
3. Enter command in console to set the python version: az functionapp config set --name <function-app-name> --resource-group <resource-group> --linux-fx-version "python|3.10"  (ref to https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal)

**Comment by tintin10q** [comment]
The func cli tool does not work with 3.10 yet.

**Comment by DCMattyG** [comment]
Checking on Func CLI support for Python 3.10. Any ETA on that? Thank you!

**Comment by BartoszCki** [comment]
Still not available...

**Comment by erik-citterberg** [comment]
It is not available yet the issue is closed.

**Comment by hjlarrea** [comment]
Check this out @tintin10q @DCMattyG @BartoszCki @erik-citterberg, seems they are planning the release for the end of this month: https://github.com/Azure/azure-functions-python-worker/issues/915#issuecomment-1205832739 🤞

**Comment by CaishenNefri** [comment]
Not yet releases as far as I know :/

**Comment by dkmiller** [comment]
I believe this is in public preview now:

https://azure.microsoft.com/en-us/updates/public-preview-azure-functions-support-for-python-310-2/
