### ISSUE TITLE
Python Function fails to import numpy when deploying Python 3.6 Functions with Azure Pipelines

### ISSUE THREAD

**Issue by lehmus** [Azure/azure-functions-python-worker#904]
The Python Functions are not able to import the numpy dependency anymore, if using Python 3.6. From the function host logs, the following error message can be found:

```
Result: Failure
Exception: ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

 https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

* The Python version is: Python3.6 from "/usr/local/bin/python"
* The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
. Troubleshooting Guide: https://aka.ms/functions-modulenotfound
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 275, in _handle__function_load_request
 func_request.metadata.entry_point)
File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 34, in call
 raise extend_exception_message(e, message)
File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 32, in call
 return func(*args, **kwargs)
File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/loader.py", line 76, in load_function
 mod = importlib.import_module(fullmodname)
File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
 return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/home/site/wwwroot/MyFuncName/__init__.py", line 5, in <module>
 from mycustommodule import mycustomsubmodule
File "/home/site/wwwroot/mycustommodule/mycustomsubmodule.py", line 6, in <module>
 from .anothersubmodule import module_xyz
File "/home/site/wwwroot/mycustommodule/module_xyz.py", line 7, in <module>
 from numpy import isnan
File "/home/site/wwwroot/.python_packages/lib/site-packages/numpy/__init__.py", line 140, in <module>
 from . import core
File "/home/site/wwwroot/.python_packages/lib/site-packages/numpy/core/__init__.py", line 48, in <module>
 raise ImportError(msg)
```

This error appeared last week. The errors started to appear after the runtime virtual environment was updated to Ubuntu 20.04 (I can see this change from Azure DevOps deployment pipeline logs).

It seems that the issue is related to Python 3.6 version. The root error is caused by the module `numpy.core._multiarray_umath`. When I open the Function files in VS Code, I can see that `.python_packages/lib/site-packages/numpy/core` contains file `_multiarray_umath.cpython-37m-x86_64-linux-gnu.so`, which seems to refer to the wrong Python version (3.7).

The full requirements file:

```
azure-functions==1.6.0
azure-identity==1.5.0
azure-keyvault-secrets==4.2.0
opencensus-ext-azure==1.0.7
ortools==8.2.8710
numpy==1.19.5
pandas==1.1.5
pyodbc==4.0.30
sqlalchemy==1.3.23
```

Numpy version 1.19.5 is compatible with Python 3.6, so it shouldn't be an issue.

I need to use Python 3.6 because the SQL ODBC drivers depend on it. This is a critical issue, since numpy is one of the most popular packages. It is also very critical to us, since our customer's production environment is now broken because of this.

**Comment by adam-luck** [comment]
I was receiving the same error: No module named 'numpy.core._multiarray_umath', and I managed to solve the problem by bumping the versionSpec. We are using Python 3.9, but the versionSpec was set to 3.7. That meant _multiarray_umath.cpython-37m-x86_64-linux-gnu.so was added under .python_packages\lib\site-packages\numpy\core in the zip file. When doing a VS Code build (which was working for me), I noticed _multiarray_umath.cpython-39-x86_64-linux-gnu.so was added.

Changing versionSpec to 3.9 solved the problem for me using vmImageName: ubuntu-latest. See my yml below.

```
# Python Function App to Linux on Azure
# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'your-subscription-id-here'

  # Function app name
  functionAppName: 'your-function-name-here'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
        fi
      workingDirectory: $(workingDirectory)
      displayName: 'Build extensions'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.9'
      inputs:
        versionSpec: 3.9 # Functions V2 supports Python 3.6 as of today

    - bash: |
        pip install --upgrade pip
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
```

**Comment by shreyabatra4** [comment]
This is an issue with the VM and is not Python specific. The recommendation is to use the latest Ubuntu spec and ensure that the correct library is used.

**Comment by pievalentin** [comment]
Hello I am running into the same issue with python 3.8 and function v4
As suggested here, I used the ubuntu vm to publish my .zip to azure functions. But I still run into that issue. I detailed my [issue here](https://github.com/Azure/azure-functions-host/issues/8663)

Beside using ubuntu in the build steps, what was the solution?

**Comment by rajanikanthr** [comment]
> I was receiving the same error: No module named 'numpy.core._multiarray_umath', and I managed to solve the problem by bumping the versionSpec. We are using Python 3.9, but the versionSpec was set to 3.7. That meant _multiarray_umath.cpython-37m-x86_64-linux-gnu.so was added under .python_packages\lib\site-packages\numpy\core in the zip file. When doing a VS Code build (which was working for me), I noticed _multiarray_umath.cpython-39-x86_64-linux-gnu.so was added.
> 
> Changing versionSpec to 3.9 solved the problem for me using vmImageName: ubuntu-latest. See my yml below.
> 
> ```
> # Python Function App to Linux on Azure
> # Build a Python function app and deploy it to Azure as a Linux function app.
> # Add steps that analyze code, save build artifacts, deploy, and more:
> # https://docs.microsoft.com/azure/devops/pipelines/languages/python
> 
> trigger:
> - master
> 
> variables:
>   # Azure Resource Manager connection created during pipeline creation
>   azureSubscription: 'your-subscription-id-here'
> 
>   # Function app name
>   functionAppName: 'your-function-name-here'
> 
>   # Agent VM image name
>   vmImageName: 'ubuntu-latest'
> 
>   # Working Directory
>   workingDirectory: '$(System.DefaultWorkingDirectory)/'
> 
> stages:
> - stage: Build
>   displayName: Build stage
> 
>   jobs:
>   - job: Build
>     displayName: Build
>     pool:
>       vmImage: $(vmImageName)
> 
>     steps:
>     - bash: |
>         if [ -f extensions.csproj ]
>         then
>             dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
>         fi
>       workingDirectory: $(workingDirectory)
>       displayName: 'Build extensions'
> 
>     - task: UsePythonVersion@0
>       displayName: 'Use Python 3.9'
>       inputs:
>         versionSpec: 3.9 # Functions V2 supports Python 3.6 as of today
> 
>     - bash: |
>         pip install --upgrade pip
>         pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
>       workingDirectory: $(workingDirectory)
>       displayName: 'Install application dependencies'
> 
>     - task: ArchiveFiles@2
>       displayName: 'Archive files'
>       inputs:
>         rootFolderOrFile: '$(workingDirectory)'
>         includeRootFolder: false
>         archiveType: zip
>         archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
>         replaceExistingArchive: true
> 
>     - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
>       artifact: drop
> 
> - stage: Deploy
>   displayName: Deploy stage
>   dependsOn: Build
>   condition: succeeded()
> 
>   jobs:
>   - deployment: Deploy
>     displayName: Deploy
>     environment: 'development'
>     pool:
>       vmImage: $(vmImageName)
> 
>     strategy:
>       runOnce:
>         deploy:
> 
>           steps:
>           - task: AzureFunctionApp@1
>             displayName: 'Azure functions app deploy'
>             inputs:
>               azureSubscription: '$(azureSubscription)'
>               appType: functionAppLinux
>               appName: $(functionAppName)
>               package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
> ```

Worked great!!
To anyone who is trying to deploy using Azure Devops and the function code is inside a sub folder rather than at root level in the repo, add a CopyFiles@2 task to copy function contents to root and DeleteFiles@1 task to delete all other unneeded folders **especially when functions are not showing up after deployment**. The drop zip file should essentially contain .python_packages and all the function code.
