### ISSUE TITLE
'func host start' does not use workspace python interpreter

### ISSUE THREAD

**Issue by sweco-benebw** [Azure/azure-functions-python-worker#905]
I am experiencing exactly the same issue as discribed in Azure/azure-functions-core-tools#2329. However, I cannot resolve it by reinstalling python as suggested in the referenced issue.

The problem is that when I run 'func host start' within an activated python environment the python interpreter gets picked up by core tools is not the one of the activated environment by the global python interpreter that is on the system PATH.

The issue appears in Windows using the python distribution from Microsoft Store. I have tried different python versions available in the Store but none solves the issue. I also tried it with core tools v3 and v4-preview, which also doesn't have any influence.

I also tried running the same code in Ubuntu via WSL2 where it works without a problem. Also when replacing virtualenv for an Anaconda environment it also works fine.

![Screenshot 2021-09-19 123233](https://user-images.githubusercontent.com/49614740/133924402-858381ca-6d91-4291-83ad-b6923d74ffc1.jpg)

**Comment by zhenyuan0502** [comment]
I am facing this problem too

![image](https://user-images.githubusercontent.com/16673159/151540827-8dc984b1-a054-4041-9d01-f1d608fcc874.png)
![image](https://user-images.githubusercontent.com/16673159/151540924-6ace0fdb-20e1-4f9e-b104-3558503c8a27.png)

The core tools always pick the default microsoft store environment instead the .venv

**Comment by gavin-aguiar** [comment]
@sweco-benebw are you still getting this error? I tried to reproduce it but didn't get any error. I installed multiple versions either from the microsoft store or directly from python.org. func host start was always picking the activated python version.
Did you have any aliases set before running func host start?

**Comment by pkreissel** [comment]
Issue still exists
