### ISSUE TITLE
Dynamic filename generation for blob out bindings - Python

### ISSUE THREAD

**Issue by enpuig** [Azure/azure-functions-python-worker#910]
I am facing issues when trying to write outputs into a blob storage account file with a dynamic name based on the azure function code (using python).

What I have:
Http trigger - with some key parameters
Blob out binding

![image](https://user-images.githubusercontent.com/18518436/73439259-a2248080-434f-11ea-90b1-07b34b4ae2c5.png)

Now what I want to do is based on my function logic provide a name dynamically to the output. Is that possible? is there any better way to do it?

Many thanks in advanced.

**Comment by arundeep78** [comment]
Any news on this feature? Or as asked originally, what is the alternative way to do it ? 
[An example here only](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-output?tabs=python#example) provides help when the variable is available through another input binding; in this case queueTrigger.

I have a situation where I want to use timeTrigger and write files to blob storage with pattern like /container/fixedpart-{dynamic-part}.{extension}. if not through OUT binding pattern, any alternative way to do it ?

**Comment by stefanushinardi** [comment]
@arundeep78 The alternative is to use Azure SDK to have more flexibility

**Comment by vrdmr** [comment]
Can be resolved - 
1. not supported in existing bindings
2. Deferred Bindings supports this - https://azure.microsoft.com/en-us/updates/public-preview-sdk-type-bindings-for-azure-blog-storage-with-azure-functions-in-python/
