### ISSUE TITLE
pylance support for azure-functions package

### ISSUE THREAD

**Issue by janusch** [Azure/azure-functions-python-worker#916]
#### Is your question related to a specific version? If so, please specify:
azure-functions          1.8.0
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
HTTP Trigger
#### Question
![image](https://user-images.githubusercontent.com/4488824/142898178-6069a1bb-29df-435c-9f54-2cb63a6ed26d.png)

I was wondering if there is a way to get rid of the red squiggly lines in the Vscode editor as shown above when using the Pylance editor?

Do you experience the same problem?

The error or HttpResponse states: "Function with declared type of "HttpResponse" must return value
  Type "None" cannot be assigned to type "HttpResponse"PylancereportGeneralTypeIssues"

And the second and third are as follows: Cannot assign member "mimetype" for type "Type[HttpResponse]"
  Property "mimetype" has no defined setterPylancereportGeneralTypeIssues"

I was just following the python function examples.

Looking forward hearing from you!

**Comment by Ved2806** [comment]
Thank you for the feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @janusch 
1. You have declared a function for which a return type is HttpResponse. You must return a data member of HttpResponse type before closing the function body.
2. Second error is of type conversion. You must assign a value of HttpResponse type.
