### ISSUE TITLE
getting   from .cv2 import  ImportError: libGL.so.1: cannot open shared object file: No such file or directory 2[BUG] Bug Title

### ISSUE THREAD

**Issue by swiftinitdotcom** [Azure/azure-functions-python-worker#924]
We have azure app service linux plan and when we install python script it works but as soon as we want opencv functions and import opencv2 it fails.

getting   from .cv2 import  ImportError: libGL.so.1: cannot open shared object file: No such file or directory 2[BUG] Bug Title.
How to fix this?

**Comment by YunchuWang** [comment]
@swiftinitdotcom not enough details provided. Please create a new issue following the bug report template https://github.com/Azure/azure-functions-python-worker/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md.
