### ISSUE TITLE
Analyze cold start impact of handling FunctionEnvironmentReloadRequest 

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-python-worker#928]
During cold start, when handling FunctionEnvironmentReloadRequest in _handle__function_environment_reload_request,
sometimes there is a delay of ~400ms between the log lines
Received FunctionEnvironmentReloadRequest
and
Reloading {p} module

Needs investigation to identify the expensive operation here and see if it can be moved outside the critical path.

**Comment by vrdmr** [comment]
Closing this as we are tracking this internally and will update on any improvements we find and put it in the worker PR (if any).
