### ISSUE TITLE
[FeatureRequest] Add support for generator output

### ISSUE THREAD

**Issue by mockodin** [Azure/azure-functions-python-worker#929]
azure.functions.HttpResponse currently supports only str/bytes content (body). This has a high memory overhead for delivery of large returns. Adding support for a generator would be ideally to support larger returns without the high memory consumption. This is commonly supported on other Response objects such as flask.Response

```
import azure.functions as func
from pathlib import Path

def main(req: func.HttpRequest, context: func.Context) -> func.HttpResponse:
    def get_file(file):
        with io.open(file, 'rb') as file_hdl:
            chunk = file_hdl.read(1024)
            while chunk:
                yield chunk
                chunk = file_hdl.read(1024)
            if Path(file).exists():
                Path(file).unlink()
    for input_file in req.files.values():
        with tempfile.NamedTemporaryFile(mode='wb', suffix=Path(input_file.filename).suffix) as in_file:
            input_file.save(in_file)
            with tempfile.NamedTemporaryFile(mode='rb', suffix=Path(input_file.filename).suffix) as out_file:
                # manipulate file somehow
                return func.HttpResponse(body=get_file(out_file.name), mimetype='video/mp4', headers={"Content-Type":"video/mp4", "Content-Disposition":"inline", "Content-Transfer-Enconding":"binary", "Content-Length":Path(out_file.name).stat().st_size})

```

**Comment by v-bbalaiagar** [comment]
Hi @mockodin , Thank you for your feedback! Adding this issue as a feature request to consider this in future implementations.

**Comment by sudoPete** [comment]
Has there been any progress on this? I am trying to use Fast API and Starlette to return large files via an HTTP trigger on functions, but the lack of ability to use streaming severely limits the usefulness of functions for such a task.

**Comment by ligonliu** [comment]
I also want this functionality.  Based on the current code structure, maybe the easiest way to implement this is to update downstream code handling func.HttpResponse to accept iterators that yield str/bytes.

For the OP's specific use case, there is an easier implementation that requires very small change of code: mmap the video file as read only, and pass the mmap object to func.HttpResponse  which is a bytearray-like object. 

@YunchuWang Can you please point me to the code of serving the response body to HTTP server? I might be able to submit a patch, beginning from: 

`    
# 
class HttpResponse(_abc.HttpResponse):
......
def __set_body(self, body):
        if isinstance(body, str):
            body = body.encode(self.__charset)

        if not isinstance(body, (bytes, bytearray)):   ----> add type memoryview, memoryview object can be constructed from mmap object
            raise TypeError(
                f'response is expected to be either of '
                f'str, bytes, or bytearray, got {type(body).__name__}')

        self.__body = bytes(body)
`

**Comment by YunchuWang** [comment]
sorry for late followup! thanks for all feedback. Recently function host started http streaming and we have been working on supporting http streaming going to release early next year(jan-feb). Will post update once thats released, stay tuned!

**Comment by hallvictoria** [comment]
Addressed by HTTP Streaming. Please see this documentation for more information:
- [Python Developer Reference - HTTP streams](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=get-started%2Casgi%2Capplication-level&pivots=python-mode-decorators#http-streams-preview)
- [Support for HTTP Streams](https://techcommunity.microsoft.com/t5/azure-compute-blog/azure-functions-support-for-http-streams-in-python-is-now-in/ba-p/4146697)
