### ISSUE TITLE
JWT Module Not Found

### ISSUE THREAD

**Issue by tsheoran-anacap** [Azure/azure-functions-python-worker#932]
#### Is your question related to a specific version? If so, please specify:
Python version: 3.9
Azure Function version: 4

#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc)
HTTP Trigger 

#### Question
I am working on a HTTP Trigger Azure Function. When deployed manually through VSCode, the azure function works fine. But when deployed through CI/CD from Azure, JWT library/module is not found by the code, even though it is present there in requirements.txt and I have checked the logs during deployment, pyjwt is installed at that moment

**Comment by v-bbalaiagar** [comment]
Hi @tsheoran-anacap , Thank you for your feedback! We will investigate this further and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @tsheoran-anacap , Can we know the repro steps, so that we can repro it from our end.

**Comment by YunchuWang** [comment]
@tsheoran-anacap thanks for raising the issue! please follow https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops?tabs=java%2Cyaml%2Ccsharp and use build+deploy task in classic pipeline to deploy your function app. 
(more detail on Azure Function App task at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops). If you have further questions, please let us know by posting a new issue with detailed repro steps
