### ISSUE TITLE
Http response sometimes ignores content-header

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-python-worker#98]
An HTTP response created in code will not always return as the correct content-type. This can result in output being formatted incorrectly or a 406. Root cause: https://github.com/Azure/azure-functions-host/issues/2552

The issue is currently being addressed in azure-functions-host, and the workaround is to add the following property to the response: `isRaw: true`

**Comment by 1st1** [comment]
It looks like we already do that:

https://github.com/Azure/azure-functions-python-worker/blob/0e7acf09193e7ad94586180a92b389141f464117/azure/worker/bindings/http.py#L96-L101

**Comment by mhoeger** [comment]
Awesome!! :) We'll be making a change soon to get rid of the "is_raw" flag and default it to true on the functions-host side.

I'll submit a PR for corresponding changes when the time comes, but wanted to file this issue in the meantime, since java and javascript have this issue.
